In [1]:
import os
import json
import sys
import argparse
import datetime
import pandas as pd
from kp_info_loader_core import InitCore
# from exchange_plugin.common_info import InitCommonInfo
# from monitor_engine.kimp_core_monitor import InitKimpCoreMonitor
from etc.db_handler.create_schema_tables import InitDBClient
# from trigger_engine.snatcher import InitSnatcher
from etc.register_monitor_msg import RegisterMonitorMsg

# for jupyter notebook
import nest_asyncio
nest_asyncio.apply()

[WARNING] upbit-client is currently a newer version: 1.3.4.1
Please update to the latest version using the pip command:`pip install --upgrade upbit-client`

In [2]:
logging_dir = "/home/kp_info_loader/"
with open("/home/kp_info_loader/kp_info_loader_config.json") as f:
    config = json.load(f)
proc_n = 3
# node = config['node']
node = 'kp_info_loader'
monitor_bot_name = config['monitor_setting']['monitor_bot']
monitor_bot_token = config['telegram_bot_setting'][monitor_bot_name]
monitor_bot_api_url = config['monitor_setting']['monitor_bot_api_url']
admin_id = config['telegram_admin_id']['charlie1155']

register_monitor_msg = RegisterMonitorMsg(monitor_bot_token, monitor_bot_api_url, admin_id)
# Read api keys
exchange_api_key_dict = config['exchange_api_key']
# Exchange market settings
enabled_markets_dict = config['enabled_markets']

my_okx_demo_api_key = "bbb8a09a-6ea2-4686-add5-1095c918b7f4"
my_okx_demo_secret_key = "FBEAD86057449BAEC3FFA8A80CE76E4F"
my_okx_demo_passphrase = "121431Rn!!"

In [3]:
core = InitCore(logging_dir, proc_n, node, admin_id, register_monitor_msg, exchange_api_key_dict, enabled_markets_dict)

2023-09-06 16:51:49,035 - kimp_bot_core - INFO - InitCore|InitCore initiated with proc_n=8
[INFO] InitCore|InitCore initiated with proc_n=8
2023-09-06 16:51:49,158 - okx_plug - INFO - okx_plug_logger started.
[INFO] okx_plug_logger started.
2023-09-06 16:51:50,020 - upbit_plug - INFO - upbit_plug_logger started.
[INFO] upbit_plug_logger started.
2023-09-06 16:51:50,227 - binance_plug - INFO - binance_plug_logger started.
[INFO] binance_plug_logger started.
2023-09-06 16:51:50,230 - kimp_bot_core - INFO - InitCore|update_upbit_spot_ticker_df thread has started.
[INFO] InitCore|update_upbit_spot_ticker_df thread has started.
2023-09-06 16:51:50,235 - kimp_bot_core - INFO - InitCore|update_upbit_wallet_status_df thread has started.
[INFO] InitCore|update_upbit_wallet_status_df thread has started.
2023-09-06 16:51:50,239 - kimp_bot_core - INFO - InitCore|update_binance_spot_ticker_df thread has started.
[INFO] InitCore|update_binance_spot_ticker_df thread has started.
2023-09-06 16:51:50,244 - kimp_bot_core - INFO - InitCore|update_binance_spot_info_df thread has started.
[INFO] InitCore|update_binance_spot_info_df thread has started.
2023-09-06 16:51:50,247 - kimp_bot_core - INFO - InitCore|update_binance_usd_m_ticker_df thread has started.
[INFO] InitCore|update_binance_usd_m_ticker_df thread has started.
2023-09-06 16:51:50,251 - kimp_bot_core - INFO - InitCore|update_binance_usd_m_info_df thread has started.
[INFO] InitCore|update_binance_usd_m_info_df thread has started.
2023-09-06 16:51:50,255 - kimp_bot_core - INFO - InitCore|update_binance_coin_m_ticker_df thread has started.
[INFO] InitCore|update_binance_coin_m_ticker_df thread has started.
2023-09-06 16:51:50,260 - kimp_bot_core - INFO - InitCore|update_binance_coin_m_info_df thread has started.
[INFO] InitCore|update_binance_coin_m_info_df thread has started.
2023-09-06 16:51:50,264 - kimp_bot_core - INFO - InitCore|Waiting for all info to be updated.
[INFO] InitCore|Waiting for all info to be updated.
2023-09-06 16:51:51,224 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 16:51:52,168 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_ticker_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_ticker_df') is None, Fetched from API
2023-09-06 16:51:52,272 - kimp_bot_core - INFO - InitCore|All info df has been updated.
[INFO] InitCore|All info df has been updated.
2023-09-06 16:51:52,422 - upbit_websocket - INFO - 1th Upbit ticker websocket does not exist. starting..
[INFO] 1th Upbit ticker websocket does not exist. starting..
2023-09-06 16:51:52,423 - upbit_websocket - INFO - [UPBIT SPOT]started monitor_shared_symbol_change..
[INFO] [UPBIT SPOT]started monitor_shared_symbol_change..
2023-09-06 16:51:52,443 - upbit_websocket - INFO - upbit_orderbook_ticker_websocket|1th upbit_ticker_proc started.
[INFO] upbit_orderbook_ticker_websocket|1th upbit_ticker_proc started.
2023-09-06 16:51:52,531 - upbit_websocket - INFO - upbit_websocket|upbit_websocket started
[INFO] upbit_websocket|upbit_websocket started
2023-09-06 16:51:52,697 - upbit_websocket - INFO - 1th Upbit orderbook websocket does not exist. starting..
[INFO] 1th Upbit orderbook websocket does not exist. starting..
2023-09-06 16:51:52,710 - upbit_websocket - INFO - upbit_orderbook_ticker_websocket|1th upbit_orderbook_proc started.
[INFO] upbit_orderbook_ticker_websocket|1th upbit_orderbook_proc started.
2023-09-06 16:51:52,793 - upbit_websocket - INFO - upbit_websocket|upbit_websocket started
[INFO] upbit_websocket|upbit_websocket started
2023-09-06 16:51:52,984 - binance_websocket - INFO - [BINANCE SPOT]1th_price_proc is not in self.websocket_proc_dict. starting..
2023-09-06 16:51:52,986 - binance_websocket - INFO - [BINANCE SPOT]started monitor_shared_symbol_change..
[INFO] [BINANCE SPOT]1th_price_proc is not in self.websocket_proc_dict. starting..
[INFO] [BINANCE SPOT]started monitor_shared_symbol_change..
2023-09-06 16:51:52,997 - binance_websocket - INFO - [BINANCE SPOT]started 1th_price_proc websocket proc..
[INFO] [BINANCE SPOT]started 1th_price_proc websocket proc..
2023-09-06 16:51:53,070 - upbit_websocket - INFO - 2th Upbit ticker websocket does not exist. starting..
[INFO] 2th Upbit ticker websocket does not exist. starting..
2023-09-06 16:51:53,087 - upbit_websocket - INFO - upbit_orderbook_ticker_websocket|2th upbit_ticker_proc started.
[INFO] upbit_orderbook_ticker_websocket|2th upbit_ticker_proc started.
2023-09-06 16:51:53,153 - binance_websocket - INFO - [BINANCE SPOT]2th_price_proc is not in self.websocket_proc_dict. starting..
[INFO] [BINANCE SPOT]2th_price_proc is not in self.websocket_proc_dict. starting..
2023-09-06 16:51:53,181 - binance_websocket - INFO - [BINANCE SPOT]started 2th_price_proc websocket proc..
[INFO] [BINANCE SPOT]started 2th_price_proc websocket proc..
2023-09-06 16:51:53,184 - upbit_websocket - INFO - upbit_websocket|upbit_websocket started
[INFO] upbit_websocket|upbit_websocket started
2023-09-06 16:51:53,316 - binance_usdm_websocket - INFO - [BINANCE USD-M]1th_price_proc is not in self.websocket_proc_dict. starting..
2023-09-06 16:51:53,317 - binance_usdm_websocket - INFO - [BINANCE USD-M]started monitor_shared_symbol_change..
[INFO] [BINANCE USD-M]1th_price_proc is not in self.websocket_proc_dict. starting..
[INFO] [BINANCE USD-M]started monitor_shared_symbol_change..
2023-09-06 16:51:53,338 - binance_websocket - INFO - [BINANCE SPOT]3th_price_proc is not in self.websocket_proc_dict. starting..
2023-09-06 16:51:53,338 - binance_usdm_websocket - INFO - [BINANCE USD-M]started 1th_price_proc websocket..
[INFO] [BINANCE SPOT]3th_price_proc is not in self.websocket_proc_dict. starting..
[INFO] [BINANCE USD-M]started 1th_price_proc websocket..
2023-09-06 16:51:53,352 - binance_websocket - INFO - [BINANCE SPOT]started 3th_price_proc websocket proc..
2023-09-06 16:51:53,353 - upbit_websocket - INFO - 2th Upbit orderbook websocket does not exist. starting..
[INFO] [BINANCE SPOT]started 3th_price_proc websocket proc..
[INFO] 2th Upbit orderbook websocket does not exist. starting..
2023-09-06 16:51:53,366 - upbit_websocket - INFO - upbit_orderbook_ticker_websocket|2th upbit_orderbook_proc started.
[INFO] upbit_orderbook_ticker_websocket|2th upbit_orderbook_proc started.
2023-09-06 16:51:53,450 - upbit_websocket - INFO - upbit_websocket|upbit_websocket started
[INFO] upbit_websocket|upbit_websocket started
2023-09-06 16:51:53,494 - binance_usdm_websocket - INFO - [BINANCE USD-M]2th_price_proc is not in self.websocket_proc_dict. starting..
[INFO] [BINANCE USD-M]2th_price_proc is not in self.websocket_proc_dict. starting..
2023-09-06 16:51:53,511 - binance_websocket - INFO - [BINANCE SPOT]4th_price_proc is not in self.websocket_proc_dict. starting..
[INFO] [BINANCE SPOT]4th_price_proc is not in self.websocket_proc_dict. starting..
2023-09-06 16:51:53,531 - binance_usdm_websocket - INFO - [BINANCE USD-M]started 2th_price_proc websocket..
[INFO] [BINANCE USD-M]started 2th_price_proc websocket..
2023-09-06 16:51:53,546 - binance_websocket - INFO - [BINANCE SPOT]started 4th_price_proc websocket proc..
2023-09-06 16:51:53,547 - binance_coinm_websocket - INFO - [BINANCE COIN-M]1th_price_proc is not in self.websocket_proc_dict. starting..
2023-09-06 16:51:53,548 - binance_coinm_websocket - INFO - [BINANCE COIN-M]started monitor_shared_symbol_change..
[INFO] [BINANCE COIN-M]1th_price_proc is not in self.websocket_proc_dict. starting..
[INFO] [BINANCE SPOT]started 4th_price_proc websocket proc..
[INFO] [BINANCE COIN-M]started monitor_shared_symbol_change..
2023-09-06 16:51:53,563 - binance_coinm_websocket - INFO - [BINANCE COIN-M]started 1th_price_proc websocket proc..
[INFO] [BINANCE COIN-M]started 1th_price_proc websocket proc..
2023-09-06 16:51:53,686 - binance_usdm_websocket - INFO - [BINANCE USD-M]3th_price_proc is not in self.websocket_proc_dict. starting..
[INFO] [BINANCE USD-M]3th_price_proc is not in self.websocket_proc_dict. starting..
2023-09-06 16:51:53,698 - binance_usdm_websocket - INFO - [BINANCE USD-M]started 3th_price_proc websocket..
[INFO] [BINANCE USD-M]started 3th_price_proc websocket..
2023-09-06 16:51:53,703 - binance_websocket - INFO - [BINANCE SPOT]5th_price_proc is not in self.websocket_proc_dict. starting..
[INFO] [BINANCE SPOT]5th_price_proc is not in self.websocket_proc_dict. starting..
2023-09-06 16:51:53,717 - binance_coinm_websocket - INFO - [BINANCE COIN-M]2th_price_proc is not in self.websocket_proc_dict. starting..
2023-09-06 16:51:53,719 - binance_websocket - INFO - [BINANCE SPOT]started 5th_price_proc websocket proc..
2023-09-06 16:51:53,720 - upbit_websocket - INFO - 3th Upbit ticker websocket does not exist. starting..
[INFO] [BINANCE SPOT]started 5th_price_proc websocket proc..
[INFO] [BINANCE COIN-M]2th_price_proc is not in self.websocket_proc_dict. starting..
[INFO] 3th Upbit ticker websocket does not exist. starting..
2023-09-06 16:51:53,735 - upbit_websocket - INFO - upbit_orderbook_ticker_websocket|3th upbit_ticker_proc started.
2023-09-06 16:51:53,747 - binance_coinm_websocket - INFO - [BINANCE COIN-M]started 2th_price_proc websocket proc..
[INFO] [BINANCE COIN-M]started 2th_price_proc websocket proc..
[INFO] upbit_orderbook_ticker_websocket|3th upbit_ticker_proc started.
2023-09-06 16:51:53,835 - upbit_websocket - INFO - upbit_websocket|upbit_websocket started
[INFO] upbit_websocket|upbit_websocket started
2023-09-06 16:51:53,852 - binance_usdm_websocket - INFO - [BINANCE USD-M]4th_price_proc is not in self.websocket_proc_dict. starting..
[INFO] [BINANCE USD-M]4th_price_proc is not in self.websocket_proc_dict. starting..
2023-09-06 16:51:53,863 - binance_usdm_websocket - INFO - [BINANCE USD-M]started 4th_price_proc websocket..
[INFO] [BINANCE USD-M]started 4th_price_proc websocket..
2023-09-06 16:51:53,873 - binance_websocket - INFO - [BINANCE SPOT]6th_price_proc is not in self.websocket_proc_dict. starting..
[INFO] [BINANCE SPOT]6th_price_proc is not in self.websocket_proc_dict. starting..
2023-09-06 16:51:53,884 - binance_websocket - INFO - [BINANCE SPOT]started 6th_price_proc websocket proc..
[INFO] [BINANCE SPOT]started 6th_price_proc websocket proc..
2023-09-06 16:51:53,900 - binance_coinm_websocket - INFO - [BINANCE COIN-M]3th_price_proc is not in self.websocket_proc_dict. starting..
[INFO] [BINANCE COIN-M]3th_price_proc is not in self.websocket_proc_dict. starting..
2023-09-06 16:51:53,911 - binance_coinm_websocket - INFO - [BINANCE COIN-M]started 3th_price_proc websocket proc..
[INFO] [BINANCE COIN-M]started 3th_price_proc websocket proc..
2023-09-06 16:51:54,001 - upbit_websocket - INFO - 3th Upbit orderbook websocket does not exist. starting..
[INFO] 3th Upbit orderbook websocket does not exist. starting..
2023-09-06 16:51:54,012 - upbit_websocket - INFO - upbit_orderbook_ticker_websocket|3th upbit_orderbook_proc started.
[INFO] upbit_orderbook_ticker_websocket|3th upbit_orderbook_proc started.
2023-09-06 16:51:54,017 - binance_usdm_websocket - INFO - [BINANCE USD-M]5th_price_proc is not in self.websocket_proc_dict. starting..
[INFO] [BINANCE USD-M]5th_price_proc is not in self.websocket_proc_dict. starting..
2023-09-06 16:51:54,037 - binance_websocket - INFO - [BINANCE SPOT]7th_price_proc is not in self.websocket_proc_dict. starting..
[INFO] [BINANCE SPOT]7th_price_proc is not in self.websocket_proc_dict. starting..
2023-09-06 16:51:54,070 - binance_coinm_websocket - INFO - [BINANCE COIN-M]4th_price_proc is not in self.websocket_proc_dict. starting..
2023-09-06 16:51:54,070 - binance_usdm_websocket - INFO - [BINANCE USD-M]started 5th_price_proc websocket..
[INFO] [BINANCE USD-M]started 5th_price_proc websocket..
[INFO] [BINANCE COIN-M]4th_price_proc is not in self.websocket_proc_dict. starting..
2023-09-06 16:51:54,090 - binance_websocket - INFO - [BINANCE SPOT]started 7th_price_proc websocket proc..
2023-09-06 16:51:54,102 - binance_coinm_websocket - INFO - [BINANCE COIN-M]started 4th_price_proc websocket proc..
[INFO] [BINANCE SPOT]started 7th_price_proc websocket proc..
[INFO] [BINANCE COIN-M]started 4th_price_proc websocket proc..
2023-09-06 16:51:54,110 - upbit_websocket - INFO - upbit_websocket|upbit_websocket started
[INFO] upbit_websocket|upbit_websocket started
2023-09-06 16:51:54,225 - binance_usdm_websocket - INFO - [BINANCE USD-M]6th_price_proc is not in self.websocket_proc_dict. starting..
[INFO] [BINANCE USD-M]6th_price_proc is not in self.websocket_proc_dict. starting..
2023-09-06 16:51:54,239 - binance_usdm_websocket - INFO - [BINANCE USD-M]started 6th_price_proc websocket..
[INFO] [BINANCE USD-M]started 6th_price_proc websocket..
2023-09-06 16:51:54,255 - binance_websocket - INFO - [BINANCE SPOT]8th_price_proc is not in self.websocket_proc_dict. starting..
[INFO] [BINANCE SPOT]8th_price_proc is not in self.websocket_proc_dict. starting..
2023-09-06 16:51:54,257 - binance_coinm_websocket - INFO - [BINANCE COIN-M]5th_price_proc is not in self.websocket_proc_dict. starting..
[INFO] [BINANCE COIN-M]5th_price_proc is not in self.websocket_proc_dict. starting..
2023-09-06 16:51:54,271 - binance_coinm_websocket - INFO - [BINANCE COIN-M]started 5th_price_proc websocket proc..
2023-09-06 16:51:54,283 - binance_websocket - INFO - [BINANCE SPOT]started 8th_price_proc websocket proc..
[INFO] [BINANCE COIN-M]started 5th_price_proc websocket proc..
[INFO] [BINANCE SPOT]started 8th_price_proc websocket proc..
2023-09-06 16:51:54,366 - upbit_websocket - INFO - 4th Upbit ticker websocket does not exist. starting..
[INFO] 4th Upbit ticker websocket does not exist. starting..
2023-09-06 16:51:54,377 - upbit_websocket - INFO - upbit_orderbook_ticker_websocket|4th upbit_ticker_proc started.
[INFO] upbit_orderbook_ticker_websocket|4th upbit_ticker_proc started.
2023-09-06 16:51:54,393 - binance_usdm_websocket - INFO - [BINANCE USD-M]7th_price_proc is not in self.websocket_proc_dict. starting..
[INFO] [BINANCE USD-M]7th_price_proc is not in self.websocket_proc_dict. starting..
2023-09-06 16:51:54,405 - binance_usdm_websocket - INFO - [BINANCE USD-M]started 7th_price_proc websocket..
[INFO] [BINANCE USD-M]started 7th_price_proc websocket..
2023-09-06 16:51:54,435 - binance_coinm_websocket - INFO - [BINANCE COIN-M]6th_price_proc is not in self.websocket_proc_dict. starting..
[INFO] [BINANCE COIN-M]6th_price_proc is not in self.websocket_proc_dict. starting..
2023-09-06 16:51:54,448 - binance_coinm_websocket - INFO - [BINANCE COIN-M]started 6th_price_proc websocket proc..
[INFO] [BINANCE COIN-M]started 6th_price_proc websocket proc..
2023-09-06 16:51:54,545 - update_dollar - INFO - fetch_dollar|Dollar price (1332.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1332.5 KRW) has been updated.
2023-09-06 16:51:54,558 - binance_usdm_websocket - INFO - [BINANCE USD-M]8th_price_proc is not in self.websocket_proc_dict. starting..
[INFO] [BINANCE USD-M]8th_price_proc is not in self.websocket_proc_dict. starting..
2023-09-06 16:51:54,572 - binance_usdm_websocket - INFO - [BINANCE USD-M]started 8th_price_proc websocket..
[INFO] [BINANCE USD-M]started 8th_price_proc websocket..
2023-09-06 16:51:54,601 - binance_coinm_websocket - INFO - [BINANCE COIN-M]7th_price_proc is not in self.websocket_proc_dict. starting..
[INFO] [BINANCE COIN-M]7th_price_proc is not in self.websocket_proc_dict. starting..
2023-09-06 16:51:54,614 - binance_coinm_websocket - INFO - [BINANCE COIN-M]started 7th_price_proc websocket proc..
[INFO] [BINANCE COIN-M]started 7th_price_proc websocket proc..
2023-09-06 16:51:54,631 - upbit_websocket - INFO - 4th Upbit orderbook websocket does not exist. starting..
[INFO] 4th Upbit orderbook websocket does not exist. starting..
2023-09-06 16:51:54,642 - upbit_websocket - INFO - upbit_orderbook_ticker_websocket|4th upbit_orderbook_proc started.
[INFO] upbit_orderbook_ticker_websocket|4th upbit_orderbook_proc started.
2023-09-06 16:51:54,651 - upbit_websocket - INFO - upbit_websocket|upbit_websocket started
[INFO] upbit_websocket|upbit_websocket started
2023-09-06 16:51:54,725 - binance_usdm_websocket - INFO - [BINANCE USD-M]liquidation_proc is not in self.websocket_proc_dict. starting..
[INFO] [BINANCE USD-M]liquidation_proc is not in self.websocket_proc_dict. starting..
2023-09-06 16:51:54,737 - binance_usdm_websocket - INFO - [BINANCE USD-M]started liquidation_proc websocket proc..
[INFO] [BINANCE USD-M]started liquidation_proc websocket proc..
2023-09-06 16:51:54,756 - binance_usdm_websocket - INFO - started liquidation_websocket for USD-M..
[INFO] started liquidation_websocket for USD-M..
2023-09-06 16:51:54,768 - binance_coinm_websocket - INFO - [BINANCE COIN-M]8th_price_proc is not in self.websocket_proc_dict. starting..
[INFO] [BINANCE COIN-M]8th_price_proc is not in self.websocket_proc_dict. starting..
2023-09-06 16:51:54,782 - binance_coinm_websocket - INFO - [BINANCE COIN-M]started 8th_price_proc websocket proc..
[INFO] [BINANCE COIN-M]started 8th_price_proc websocket proc..
2023-09-06 16:51:54,924 - upbit_websocket - INFO - upbit_websocket|upbit_websocket started
[INFO] upbit_websocket|upbit_websocket started
2023-09-06 16:51:54,935 - binance_coinm_websocket - INFO - [BINANCE COIN-M]liquidation_proc is not in self.websocket_proc_dict. starting..
[INFO] [BINANCE COIN-M]liquidation_proc is not in self.websocket_proc_dict. starting..
2023-09-06 16:51:54,948 - binance_coinm_websocket - INFO - [BINANCE COIN-M]started liquidation_proc websocket proc..
[INFO] [BINANCE COIN-M]started liquidation_proc websocket proc..
2023-09-06 16:51:54,967 - binance_coinm_websocket - INFO - started liquidation_websocket for COIN-M..
[INFO] started liquidation_websocket for COIN-M..
2023-09-06 16:51:54,996 - upbit_websocket - INFO - 5th Upbit ticker websocket does not exist. starting..
[INFO] 5th Upbit ticker websocket does not exist. starting..
2023-09-06 16:51:55,008 - upbit_websocket - INFO - upbit_orderbook_ticker_websocket|5th upbit_ticker_proc started.
[INFO] upbit_orderbook_ticker_websocket|5th upbit_ticker_proc started.
2023-09-06 16:51:55,261 - upbit_websocket - INFO - 5th Upbit orderbook websocket does not exist. starting..
[INFO] 5th Upbit orderbook websocket does not exist. starting..
2023-09-06 16:51:55,272 - upbit_websocket - INFO - upbit_orderbook_ticker_websocket|5th upbit_orderbook_proc started.
[INFO] upbit_orderbook_ticker_websocket|5th upbit_orderbook_proc started.
2023-09-06 16:51:55,307 - upbit_websocket - INFO - upbit_websocket|upbit_websocket started
[INFO] upbit_websocket|upbit_websocket started

2023-09-06 16:51:55,570 - upbit_websocket - INFO - upbit_websocket|upbit_websocket started
[INFO] upbit_websocket|upbit_websocket started
2023-09-06 16:51:55,626 - upbit_websocket - INFO - 6th Upbit ticker websocket does not exist. starting..
[INFO] 6th Upbit ticker websocket does not exist. starting..
2023-09-06 16:51:55,638 - upbit_websocket - INFO - upbit_orderbook_ticker_websocket|6th upbit_ticker_proc started.
[INFO] upbit_orderbook_ticker_websocket|6th upbit_ticker_proc started.
2023-09-06 16:51:55,894 - upbit_websocket - INFO - 6th Upbit orderbook websocket does not exist. starting..
[INFO] 6th Upbit orderbook websocket does not exist. starting..
2023-09-06 16:51:55,906 - upbit_websocket - INFO - upbit_orderbook_ticker_websocket|6th upbit_orderbook_proc started.
[INFO] upbit_orderbook_ticker_websocket|6th upbit_orderbook_proc started.
2023-09-06 16:51:55,938 - upbit_websocket - INFO - upbit_websocket|upbit_websocket started
[INFO] upbit_websocket|upbit_websocket started
2023-09-06 16:51:56,220 - upbit_websocket - INFO - upbit_websocket|upbit_websocket started
[INFO] upbit_websocket|upbit_websocket started
2023-09-06 16:51:56,259 - upbit_websocket - INFO - 7th Upbit ticker websocket does not exist. starting..
[INFO] 7th Upbit ticker websocket does not exist. starting..
2023-09-06 16:51:56,274 - upbit_websocket - INFO - upbit_orderbook_ticker_websocket|7th upbit_ticker_proc started.
[INFO] upbit_orderbook_ticker_websocket|7th upbit_ticker_proc started.
2023-09-06 16:51:56,529 - upbit_websocket - INFO - 7th Upbit orderbook websocket does not exist. starting..
[INFO] 7th Upbit orderbook websocket does not exist. starting..
2023-09-06 16:51:56,540 - upbit_websocket - INFO - upbit_orderbook_ticker_websocket|7th upbit_orderbook_proc started.
[INFO] upbit_orderbook_ticker_websocket|7th upbit_orderbook_proc started.
2023-09-06 16:51:56,588 - upbit_websocket - INFO - upbit_websocket|upbit_websocket started
[INFO] upbit_websocket|upbit_websocket started
2023-09-06 16:51:56,784 - upbit_websocket - INFO - upbit_websocket|upbit_websocket started
[INFO] upbit_websocket|upbit_websocket started
2023-09-06 16:51:56,895 - upbit_websocket - INFO - 8th Upbit ticker websocket does not exist. starting..
[INFO] 8th Upbit ticker websocket does not exist. starting..
2023-09-06 16:51:56,907 - upbit_websocket - INFO - upbit_orderbook_ticker_websocket|8th upbit_ticker_proc started.
[INFO] upbit_orderbook_ticker_websocket|8th upbit_ticker_proc started.
2023-09-06 16:51:57,161 - upbit_websocket - INFO - 8th Upbit orderbook websocket does not exist. starting..
[INFO] 8th Upbit orderbook websocket does not exist. starting..
2023-09-06 16:51:57,169 - upbit_websocket - INFO - upbit_websocket|upbit_websocket started
[INFO] upbit_websocket|upbit_websocket started
2023-09-06 16:51:57,172 - upbit_websocket - INFO - upbit_orderbook_ticker_websocket|8th upbit_orderbook_proc started.
[INFO] upbit_orderbook_ticker_websocket|8th upbit_orderbook_proc started.
2023-09-06 16:51:57,448 - upbit_websocket - INFO - upbit_websocket|upbit_websocket started
[INFO] upbit_websocket|upbit_websocket started
2023-09-06 16:52:07,865 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-07 02:05:20,452 - binance_websocket - ERROR - handle_spot_bookticker_streams|Traceback (most recent call last):
  File "/home/kp_info_loader/exchange_websocket/binance_websocket.py", line 52, in handle_spot_bookticker_streams
    bookticker_dict[msg['data']['s']] = msg['data']
KeyError: 'data'
, msg:{'e': 'error', 'm': 'Queue overflow. Message not filled'}
[ERROR] handle_spot_bookticker_streams|Traceback (most recent call last):
  File "/home/kp_info_loader/exchange_websocket/binance_websocket.py", line 52, in handle_spot_bookticker_streams
    bookticker_dict[msg['data']['s']] = msg['data']
KeyError: 'data'
, msg:{'e': 'error', 'm': 'Queue overflow. Message not filled'}
2023-09-07 02:05:22,053 - binance_websocket - ERROR - handle_spot_bookticker_streams|Traceback (most recent call last):
  File "/home/kp_info_loader/exchange_websocket/binance_websocket.py", line 52, in handle_spot_bookticker_streams
    bookticker_dict[msg['data']['s']] = msg['data']
KeyError: 'data'
, msg:{'e': 'error', 'm': 'Queue overflow. Message not filled'}
[ERROR] handle_spot_bookticker_streams|Traceback (most recent call last):
  File "/home/kp_info_loader/exchange_websocket/binance_websocket.py", line 52, in handle_spot_bookticker_streams
    bookticker_dict[msg['data']['s']] = msg['data']
KeyError: 'data'
, msg:{'e': 'error', 'm': 'Queue overflow. Message not filled'}
2023-09-06 16:51:54,271 - binance_coinm_websocket - INFO - [BINANCE COIN-M]started 5th_price_proc websocket proc..
2023-09-07 02:05:27,860 - binance_websocket - ERROR - handle_spot_bookticker_streams|Traceback (most recent call last):
  File "/home/kp_info_loader/exchange_websocket/binance_websocket.py", line 52, in handle_spot_bookticker_streams
    bookticker_dict[msg['data']['s']] = msg['data']
KeyError: 'data'
, msg:{'e': 'error', 'm': 'Queue overflow. Message not filled'}
[ERROR] handle_spot_bookticker_streams|Traceback (most recent call last):
  File "/home/kp_info_loader/exchange_websocket/binance_websocket.py", line 52, in handle_spot_bookticker_streams
    bookticker_dict[msg['data']['s']] = msg['data']
KeyError: 'data'
, msg:{'e': 'error', 'm': 'Queue overflow. Message not filled'}
2023-09-07 02:05:32,634 - binance_usdm_websocket - ERROR - handle_usdm_bookticker_streams|Traceback (most recent call last):
  File "/home/kp_info_loader/exchange_websocket/binance_websocket.py", line 232, in handle_usdm_bookticker_streams
    bookticker_dict[msg['data']['s']] = msg['data']
KeyError: 'data'
, msg:{'e': 'error', 'm': 'Queue overflow. Message not filled'}
[ERROR] handle_usdm_bookticker_streams|Traceback (most recent call last):
  File "/home/kp_info_loader/exchange_websocket/binance_websocket.py", line 232, in handle_usdm_bookticker_streams
    bookticker_dict[msg['data']['s']] = msg['data']
KeyError: 'data'
, msg:{'e': 'error', 'm': 'Queue overflow. Message not filled'}
2023-09-07 02:05:34,695 - binance_usdm_websocket - ERROR - handle_usdm_bookticker_streams|Traceback (most recent call last):
  File "/home/kp_info_loader/exchange_websocket/binance_websocket.py", line 232, in handle_usdm_bookticker_streams
    bookticker_dict[msg['data']['s']] = msg['data']
KeyError: 'data'
, msg:{'e': 'error', 'm': 'Queue overflow. Message not filled'}
[ERROR] handle_usdm_bookticker_streams|Traceback (most recent call last):
  File "/home/kp_info_loader/exchange_websocket/binance_websocket.py", line 232, in handle_usdm_bookticker_streams
    bookticker_dict[msg['data']['s']] = msg['data']
KeyError: 'data'
, msg:{'e': 'error', 'm': 'Queue overflow. Message not filled'}
2023-09-07 02:05:35,031 - binance_usdm_websocket - ERROR - handle_usdm_bookticker_streams|Traceback (most recent call last):
  File "/home/kp_info_loader/exchange_websocket/binance_websocket.py", line 232, in handle_usdm_bookticker_streams
    bookticker_dict[msg['data']['s']] = msg['data']
KeyError: 'data'
, msg:{'e': 'error', 'm': 'Queue overflow. Message not filled'}
[ERROR] handle_usdm_bookticker_streams|Traceback (most recent call last):
  File "/home/kp_info_loader/exchange_websocket/binance_websocket.py", line 232, in handle_usdm_bookticker_streams
    bookticker_dict[msg['data']['s']] = msg['data']
KeyError: 'data'
, msg:{'e': 'error', 'm': 'Queue overflow. Message not filled'}
2023-09-07 02:05:35,356 - binance_usdm_websocket - ERROR - handle_usdm_bookticker_streams|Traceback (most recent call last):
  File "/home/kp_info_loader/exchange_websocket/binance_websocket.py", line 232, in handle_usdm_bookticker_streams
    bookticker_dict[msg['data']['s']] = msg['data']
KeyError: 'data'
, msg:{'e': 'error', 'm': 'Queue overflow. Message not filled'}
[ERROR] handle_usdm_bookticker_streams|Traceback (most recent call last):
  File "/home/kp_info_loader/exchange_websocket/binance_websocket.py", line 232, in handle_usdm_bookticker_streams
    bookticker_dict[msg['data']['s']] = msg['data']
KeyError: 'data'
, msg:{'e': 'error', 'm': 'Queue overflow. Message not filled'}
2023-09-07 02:06:21,259 - binance_usdm_websocket - ERROR - handle_usdm_bookticker_streams|Traceback (most recent call last):
  File "/home/kp_info_loader/exchange_websocket/binance_websocket.py", line 232, in handle_usdm_bookticker_streams
    bookticker_dict[msg['data']['s']] = msg['data']
KeyError: 'data'
, msg:{'e': 'error', 'm': 'Queue overflow. Message not filled'}
[ERROR] handle_usdm_bookticker_streams|Traceback (most recent call last):
  File "/home/kp_info_loader/exchange_websocket/binance_websocket.py", line 232, in handle_usdm_bookticker_streams
    bookticker_dict[msg['data']['s']] = msg['data']
KeyError: 'data'
, msg:{'e': 'error', 'm': 'Queue overflow. Message not filled'}
2023-09-07 02:56:33,577 - binance_usdm_websocket - ERROR - handle_usdm_bookticker_streams|Traceback (most recent call last):
  File "/home/kp_info_loader/exchange_websocket/binance_websocket.py", line 232, in handle_usdm_bookticker_streams
    bookticker_dict[msg['data']['s']] = msg['data']
KeyError: 'data'
, msg:{'e': 'error', 'm': 'Queue overflow. Message not filled'}
[ERROR] handle_usdm_bookticker_streams|Traceback (most recent call last):
  File "/home/kp_info_loader/exchange_websocket/binance_websocket.py", line 232, in handle_usdm_bookticker_streams
    bookticker_dict[msg['data']['s']] = msg['data']
KeyError: 'data'
, msg:{'e': 'error', 'm': 'Queue overflow. Message not filled'}

In [4]:
print(core.check_status(include_text=True, print_result=False)[0])

True

In [5]:
core.exchange_websocket_dict['UPBIT_SPOT'].check_status(print_result=True)

[UPBIT SPOT]1th_ticker_proc status: True
[UPBIT SPOT]1th_orderbook_proc status: True
[UPBIT SPOT]2th_ticker_proc status: True
[UPBIT SPOT]2th_orderbook_proc status: True
[UPBIT SPOT]3th_ticker_proc status: True
[UPBIT SPOT]3th_orderbook_proc status: True
[UPBIT SPOT]4th_ticker_proc status: True
[UPBIT SPOT]4th_orderbook_proc status: True
[UPBIT SPOT]5th_ticker_proc status: True
[UPBIT SPOT]5th_orderbook_proc status: True

True

2023-09-05 19:35:14,332 - upbit_websocket - INFO - upbit_websocket|upbit_websocket started
[INFO] upbit_websocket|upbit_websocket started
2023-09-06 01:00:35,110 - binance_usdm_websocket - ERROR - handle_usdm_bookticker_streams|Traceback (most recent call last):
  File "/home/kp_info_loader/exchange_websocket/binance_websocket.py", line 232, in handle_usdm_bookticker_streams
    bookticker_dict[msg['data']['s']] = msg['data']
KeyError: 'data'
, msg:{'e': 'error', 'm': 'Queue overflow. Message not filled'}
[ERROR] handle_usdm_bookticker_streams|Traceback (most recent call last):
  File "/home/kp_info_loader/exchange_websocket/binance_websocket.py", line 232, in handle_usdm_bookticker_streams
    bookticker_dict[msg['data']['s']] = msg['data']
KeyError: 'data'
, msg:{'e': 'error', 'm': 'Queue overflow. Message not filled'}

In [6]:
core.exchange_websocket_dict['BINANCE_SPOT'].check_status(print_result=True)

[BINANCE SPOT]1th_price_proc status: True
[BINANCE SPOT]2th_price_proc status: True
[BINANCE SPOT]3th_price_proc status: True
[BINANCE SPOT]4th_price_proc status: True
[BINANCE SPOT]5th_price_proc status: True
[BINANCE SPOT]6th_price_proc status: True
[BINANCE SPOT]7th_price_proc status: True
[BINANCE SPOT]8th_price_proc status: True

True

2023-09-05 19:35:14,580 - upbit_websocket - INFO - 6th Upbit ticker websocket does not exist. starting..
[INFO] 6th Upbit ticker websocket does not exist. starting..
2023-09-05 19:35:14,598 - upbit_websocket - INFO - upbit_orderbook_ticker_websocket|6th upbit_ticker_proc started.
[INFO] upbit_orderbook_ticker_websocket|6th upbit_ticker_proc started.
2023-09-05 19:35:14,709 - upbit_websocket - INFO - upbit_websocket|upbit_websocket started
[INFO] upbit_websocket|upbit_websocket started
2023-09-05 19:35:14,851 - upbit_websocket - INFO - 6th Upbit orderbook websocket does not exist. starting..
[INFO] 6th Upbit orderbook websocket does not exist. starting..
2023-09-05 19:35:14,865 - upbit_websocket - INFO - upbit_orderbook_ticker_websocket|6th upbit_orderbook_proc started.
[INFO] upbit_orderbook_ticker_websocket|6th upbit_orderbook_proc started.
2023-09-05 19:35:14,972 - upbit_websocket - INFO - upbit_websocket|upbit_websocket started
[INFO] upbit_websocket|upbit_websocket started
2023-09-05 19:35:15,219 - upbit_websocket - INFO - 7th Upbit ticker websocket does not exist. starting..
[INFO] 7th Upbit ticker websocket does not exist. starting..
2023-09-05 19:35:15,233 - upbit_websocket - INFO - upbit_orderbook_ticker_websocket|7th upbit_ticker_proc started.
[INFO] upbit_orderbook_ticker_websocket|7th upbit_ticker_proc started.
2023-09-05 19:35:15,323 - upbit_websocket - INFO - upbit_websocket|upbit_websocket started
[INFO] upbit_websocket|upbit_websocket started
2023-09-05 19:35:15,486 - upbit_websocket - INFO - 7th Upbit orderbook websocket does not exist. starting..
[INFO] 7th Upbit orderbook websocket does not exist. starting..
2023-09-05 19:35:15,501 - upbit_websocket - INFO - upbit_orderbook_ticker_websocket|7th upbit_orderbook_proc started.
[INFO] upbit_orderbook_ticker_websocket|7th upbit_orderbook_proc started.
2023-09-05 19:35:15,601 - upbit_websocket - INFO - upbit_websocket|upbit_websocket started
[INFO] upbit_websocket|upbit_websocket started
2023-09-05 19:35:15,854 - upbit_websocket - INFO - 8th Upbit ticker websocket does not exist. starting..
[INFO] 8th Upbit ticker websocket does not exist. starting..
2023-09-05 19:35:15,870 - upbit_websocket - INFO - upbit_orderbook_ticker_websocket|8th upbit_ticker_proc started.
[INFO] upbit_orderbook_ticker_websocket|8th upbit_ticker_proc started.
2023-09-05 19:35:15,971 - upbit_websocket - INFO - upbit_websocket|upbit_websocket started
[INFO] upbit_websocket|upbit_websocket started
2023-09-05 19:35:16,124 - upbit_websocket - INFO - 8th Upbit orderbook websocket does not exist. starting..
[INFO] 8th Upbit orderbook websocket does not exist. starting..
2023-09-05 19:35:16,137 - upbit_websocket - INFO - upbit_orderbook_ticker_websocket|8th upbit_orderbook_proc started.
[INFO] upbit_orderbook_ticker_websocket|8th upbit_orderbook_proc started.
2023-09-05 19:35:16,240 - upbit_websocket - INFO - upbit_websocket|upbit_websocket started
[INFO] upbit_websocket|upbit_websocket started

In [7]:
core.exchange_websocket_dict['BINANCE_USD_M'].get_price_df()

,scr,tp,v,atp24h,bp,ap,base_asset,quote_asset
0,1.707,0.5781,17017744,9624703.0828,0.5779,0.578,PHB,USDT
1,1.259,1.0934,18668800.0,19981512.7525,1.0931,1.0934,RLC,USDT
2,1.943,1.207,10367380.9,12302952.7821,1.207,1.208,HIGH,USDT
3,-4.234,0.01606,11673814123,186270694.34103,0.01606,0.01607,GALA,USDT
4,-1.444,0.12692,1473235208,189156636.04626,0.12693,0.12694,BLZ,USDT
...,...,...,...,...,...,...,...,...
142,0.966,0.03032,244576579,7270160.94924,0.03032,0.03033,TRU,USDT
143,0.661,0.08828,308048488,27598389.90758,0.08826,0.08827,NKN,USDT
144,-1.608,63.01,2429458.745,153924932.52,63.0,63.01,LTC,USDT
145,-0.77,1.4826,9723500.5,14362892.5046,1.4824,1.4825,WAVES,USDT
146,-0.21,0.07594,81847208,6139412.28338,0.07593,0.07594,ALPHA,USDT

In [158]:
temp = core.exchange_websocket_dict['BINANCE_USD_M'].get_price_df()
temp[temp['base_asset']=='STX']

,scr,tp,v,atp24h,bp,ap,base_asset,quote_asset
63,1.995,0.4653,117239140,55349272.5878,0.4652,0.4653,STX,USDT

In [172]:
temp = core.exchange_websocket_dict['UPBIT_SPOT'].get_price_df()
temp[temp['base_asset']=='STX']

,tp,scr,atp24h,h52wp,l52wp,ms,mw,tms_x,cd,tms_y,ap,bp,base_asset,quote_asset
1,634.0,-2.009274,42756530364.337883,1725.0,257.0,ACTIVE,NONE,1693972968582,KRW-STX,1693972968701,634.000000,633.000000,STX,KRW
105,0.000018,-1.72973,1.359351,0.000047,0.000012,ACTIVE,NONE,1693971360374,BTC-STX,1693972966574,0.000019,0.000018,STX,BTC

2023-09-06 13:02:58,613 - update_dollar - INFO - fetch_dollar|Dollar price (1331.7 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1331.7 KRW) has been updated.
2023-09-06 13:03:00,359 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 13:03:15,609 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 13:03:29,397 - update_dollar - INFO - fetch_dollar|Dollar price (1331.7 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1331.7 KRW) has been updated.
2023-09-06 13:03:30,854 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 13:03:46,395 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 13:04:00,267 - update_dollar - INFO - fetch_dollar|Dollar price (1331.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1331.5 KRW) has been updated.
2023-09-06 13:04:01,647 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 13:04:17,157 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 13:04:31,144 - update_dollar - INFO - fetch_dollar|Dollar price (1331.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1331.5 KRW) has been updated.
2023-09-06 13:04:32,403 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 13:04:47,659 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 13:05:02,030 - update_dollar - INFO - fetch_dollar|Dollar price (1331.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1331.5 KRW) has been updated.
2023-09-06 13:05:02,903 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 13:05:18,145 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 13:05:32,884 - update_dollar - INFO - fetch_dollar|Dollar price (1331.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1331.5 KRW) has been updated.
2023-09-06 13:05:33,387 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 13:05:48,633 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 13:06:03,683 - update_dollar - INFO - fetch_dollar|Dollar price (1331.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1331.5 KRW) has been updated.
2023-09-06 13:06:03,871 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 13:06:19,111 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 13:06:34,483 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 13:06:34,578 - update_dollar - INFO - fetch_dollar|Dollar price (1331.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1331.5 KRW) has been updated.
2023-09-06 13:06:49,718 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 13:07:04,963 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 13:07:05,528 - update_dollar - INFO - fetch_dollar|Dollar price (1331.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1331.5 KRW) has been updated.
2023-09-06 13:07:20,442 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 13:07:35,945 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 13:07:36,654 - update_dollar - INFO - fetch_dollar|Dollar price (1331.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1331.5 KRW) has been updated.
2023-09-06 13:07:51,687 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 13:08:07,396 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 13:08:07,994 - update_dollar - INFO - fetch_dollar|Dollar price (1331.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1331.5 KRW) has been updated.
2023-09-06 13:08:22,716 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 13:08:37,959 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 13:08:39,300 - update_dollar - INFO - fetch_dollar|Dollar price (1331.6 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1331.6 KRW) has been updated.
2023-09-06 13:08:53,209 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 13:09:09,581 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 13:09:10,598 - update_dollar - INFO - fetch_dollar|Dollar price (1331.6 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1331.6 KRW) has been updated.
2023-09-06 13:09:24,842 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 13:09:40,342 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 13:09:41,360 - update_dollar - INFO - fetch_dollar|Dollar price (1331.6 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1331.6 KRW) has been updated.
2023-09-06 13:09:55,602 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 13:10:10,844 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 13:10:12,132 - update_dollar - INFO - fetch_dollar|Dollar price (1331.6 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1331.6 KRW) has been updated.
2023-09-06 13:10:26,126 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API

In [55]:
core.info_dict['binance_spot_ticker_df']['symbol']

0          ETHBTC
1          LTCBTC
2          BNBBTC
3          NEOBTC
4         QTUMETH
          ...
2285    CYBERUSDT
2286    CYBERTUSD
2287      SEITUSD
2288       LPTTRY
2289       UNITRY
Name: symbol, Length: 2290, dtype: object

In [49]:
len(core.get_binance_spot_symbol_list())

693

2023-09-05 17:24:44,290 - update_dollar - INFO - fetch_dollar|Dollar price (1333.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1333.5 KRW) has been updated.

In [27]:
core.info_dict['upbit_spot_ticker_df']

,market,trade_date,trade_time,trade_date_kst,trade_time_kst,trade_timestamp,opening_price,high_price,low_price,lastPrice,...,acc_trade_volume,acc_trade_volume_24h,highest_52_week_price,highest_52_week_date,lowest_52_week_price,lowest_52_week_date,timestamp,base_asset,quote_asset,acc_trade_price_24h_krw
0,KRW-BTC,20230905,115738,20230905,205738,1693915058490,3.503500e+07,3.513500e+07,3.479100e+07,3.509900e+07,...,1.984244e+03,3.558157e+03,4.156900e+07,2023-06-30,2.070000e+07,2022-12-30,1693915058509,BTC,KRW,1.245534e+11
1,KRW-ETH,20230905,115730,20230905,205730,1693915050894,2.212000e+06,2.228000e+06,2.190000e+06,2.226000e+06,...,3.887300e+03,7.046033e+03,2.795000e+06,2023-04-16,1.500000e+06,2022-12-30,1693915050923,ETH,KRW,1.554396e+10
2,BTC-ETH,20230905,114427,20230905,204427,1693914267851,6.349140e-02,6.349140e-02,6.258397e-02,6.345668e-02,...,1.619735e+00,2.088688e+00,8.530000e-02,2022-09-07,6.055800e-02,2023-06-29,1693914300057,ETH,BTC,4.613115e+06
3,BTC-XRP,20230905,111530,20230905,201530,1693912530959,1.968000e-05,1.979000e-05,1.951000e-05,1.965000e-05,...,1.712794e+04,5.033406e+04,2.888000e-05,2023-07-19,1.273000e-05,2023-05-16,1693914000056,XRP,BTC,3.449374e+07
4,BTC-ETC,20230905,64519,20230905,154519,1693896319420,5.910000e-04,5.920000e-04,5.899500e-04,5.899500e-04,...,4.343945e+02,4.408115e+02,1.991730e-03,2022-09-14,5.377000e-04,2023-06-10,1693914000056,ETC,BTC,9.135582e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299,KRW-IMX,20230905,115558,20230905,205558,1693914958158,7.490000e+02,7.830000e+02,7.300000e+02,7.490000e+02,...,3.833009e+06,4.434160e+06,1.255000e+03,2023-07-28,7.250000e+02,2023-09-03,1693914960637,IMX,KRW,3.340465e+09
300,BTC-STG,20230905,115329,20230905,205329,1693914809623,1.987000e-05,2.052000e-05,1.985000e-05,2.052000e-05,...,9.424390e+04,1.542215e+05,2.415000e-05,2023-08-10,1.627000e-05,2023-08-17,1693914900401,STG,BTC,1.097111e+08
301,BTC-SEI,20230905,52806,20230905,142806,1693891686032,4.820000e-06,4.820000e-06,4.780000e-06,4.780000e-06,...,1.513106e+05,1.682285e+05,2.187000e-05,2023-08-16,4.590000e-06,2023-08-29,1693913100445,SEI,BTC,2.835580e+07
302,KRW-SEI,20230905,115742,20230905,205742,1693915062828,1.720000e+02,1.720000e+02,1.650000e+02,1.700000e+02,...,6.830212e+07,1.410523e+08,8.560000e+02,2023-08-16,1.630000e+02,2023-08-29,1693915062846,SEI,KRW,2.382689e+10
303,BTC-CYBER,20230905,115741,20230905,205741,1693915061602,2.402900e-04,2.402900e-04,2.212500e-04,2.260000e-04,...,2.489622e+05,5.688539e+05,1.393730e-03,2023-09-02,1.356500e-04,2023-08-26,1693915061633,CYBER,BTC,4.786634e+09

2023-09-05 20:57:53,056 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-05 20:58:08,403 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-05 20:58:19,817 - update_dollar - INFO - fetch_dollar|Dollar price (1334.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1334.5 KRW) has been updated.
2023-09-05 20:58:23,740 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-05 20:58:39,035 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-05 20:58:50,916 - update_dollar - INFO - fetch_dollar|Dollar price (1334.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1334.5 KRW) has been updated.
2023-09-05 20:58:54,358 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API

In [144]:
def convert_asset_rate(origin_market, origin_quote_asset, target_market, target_quote_asset):
    if origin_quote_asset == "USD":
        origin_quote_asset = "USDT"
    if target_quote_asset == "USD":
        target_quote_asset = "USDT"
    if origin_quote_asset == target_quote_asset:
        return 1
    origin_market_spot_info_df = core.info_dict[f"{origin_market.lower().split('_')[0]}_spot_ticker_df"]
    # First try to find the rate from the info_dict

    def convert_between_coins(origin_market_spot_info_df, origin_quote_asset, target_quote_asset):
        df = origin_market_spot_info_df[(origin_market_spot_info_df['base_asset']==origin_quote_asset)&(origin_market_spot_info_df['quote_asset']==target_quote_asset)]
        reverse_df = origin_market_spot_info_df[(origin_market_spot_info_df['quote_asset']==origin_quote_asset)&(origin_market_spot_info_df['base_asset']==target_quote_asset)]
        if len(df) == 1:
            convert_rate = df['lastPrice'].values[0]
        elif len(reverse_df) == 1:
            convert_rate = 1 / reverse_df['lastPrice'].values[0]
        else:
            convert_rate = None
        return convert_rate
    convert_rate = convert_between_coins(origin_market_spot_info_df, origin_quote_asset, target_quote_asset)
    if convert_rate is None: # not between coins
        # print("1st convert_rate is None, Not between coins")
        if target_quote_asset == "KRW" and origin_quote_asset == "USDT":
            convert_rate = core.update_dollar_return_dict['price']
        elif target_quote_asset == "USDT" and origin_quote_asset == "KRW":
            convert_rate = 1 / core.update_dollar_return_dict['price']
        elif target_quote_asset == "KRW":
            convert_rate = convert_between_coins(origin_market_spot_info_df, origin_quote_asset, "USDT") * core.update_dollar_return_dict['price']
        elif origin_quote_asset == "KRW":
            temp_convert_rate = convert_asset_rate(target_market, target_quote_asset, origin_market, origin_quote_asset)
            if temp_convert_rate is not None:
                convert_rate = 1 / temp_convert_rate
            else:
                title = f"target_quote_asset: {target_quote_asset}, origin_quote_asset: {origin_quote_asset}"
                raise Exception(f"Cannot find the convert rate for {title}")
        else:
            title = f"target_quote_asset: {target_quote_asset}, origin_quote_asset: {origin_quote_asset}"
            raise Exception(f"Cannot find the convert rate for {title}")
    return convert_rate

In [1]:
exchange_origin = 'BINANCE_USD_M/USDT'
exchange_target = 'UPBIT_SPOT/BTC'
def get_premium_df(self, target_exchange_code, origin_exchange_code):
    # POSSIBLE quote_assets: USDT, BUSD, BTC, KRW
    origin_market = exchange_origin.split('/')[0]
    quote_asset_one = exchange_origin.split('/')[1]
    target_market = exchange_target.split('/')[0]
    quote_asset_two = exchange_target.split('/')[1]

    origin_market_df = self.exchange_websocket_dict[origin_market].get_price_df()
    origin_market_df = origin_market_df[origin_market_df['quote_asset'] == quote_asset_one]
    target_market_df = self.exchange_websocket_dict[target_market].get_price_df()
    target_market_df = target_market_df[target_market_df['quote_asset'] == quote_asset_two]

    shared_bass_asset_list = list(set(origin_market_df['base_asset'].values).intersection(set(target_market_df['base_asset'].values)))
    origin_market_df = origin_market_df[origin_market_df['base_asset'].isin(shared_bass_asset_list)].sort_values('base_asset').reset_index(drop=True)
    target_market_df = target_market_df[target_market_df['base_asset'].isin(shared_bass_asset_list)].sort_values('base_asset').reset_index(drop=True)

    convert_rate = convert_asset_rate(origin_market, quote_asset_one, target_market, quote_asset_two)
    origin_market_df[['converted_tp','converted_ap','converted_bp']] = origin_market_df[['tp','ap','bp']] * convert_rate
    # target_market_df[['converted_tp','converted_ap','converted_bp']] = target_market_df[['tp','ap','bp']]

    # divide by target_market_df[['tp','ap','bp']]
    premium_df = pd.DataFrame((target_market_df[['tp','ap','bp']].values - origin_market_df[['converted_tp','converted_bp','converted_ap']].values)/
                            origin_market_df[['converted_tp','converted_bp','converted_ap']].values, columns=['tp_premium','LS_premium','SL_premium'])
    premium_df['LS_SL_spread'] = premium_df['LS_premium'] - premium_df['SL_premium']
    premium_df[['base_asset','quote_asset','tp','ap','bp','atp24h']] = target_market_df[['base_asset','quote_asset','tp','ap','bp','atp24h']]
    premium_df[['converted_tp','converted_ap','converted_bp']] = origin_market_df[['converted_tp','converted_ap', 'converted_bp']]
    premium_df.loc[:, ['tp_premium','LS_premium','SL_premium','LS_SL_spread']] = premium_df[['tp_premium','LS_premium','SL_premium','LS_SL_spread']] * 100
    return premium_df

In [170]:
# POSSIBLE quote_assets: USDT, BUSD, BTC, KRW

exchange_origin = 'BINANCE_USD_M/USDT'
exchange_target = 'UPBIT_SPOT/BTC'

origin_market = exchange_origin.split('/')[0]
quote_asset_one = exchange_origin.split('/')[1]
target_market = exchange_target.split('/')[0]
quote_asset_two = exchange_target.split('/')[1]


origin_market_df = core.exchange_websocket_dict[origin_market].get_price_df()
origin_market_df = origin_market_df[origin_market_df['quote_asset'] == quote_asset_one]
target_market_df = core.exchange_websocket_dict[target_market].get_price_df()
target_market_df = target_market_df[target_market_df['quote_asset'] == quote_asset_two]

shared_bass_asset_list = list(set(origin_market_df['base_asset'].values).intersection(set(target_market_df['base_asset'].values)))
origin_market_df = origin_market_df[origin_market_df['base_asset'].isin(shared_bass_asset_list)].sort_values('base_asset').reset_index(drop=True)
# origin_market_df = origin_market_df[origin_market_df['base_asset'].isin(shared_bass_asset_list)].set_index('base_asset')
target_market_df = target_market_df[target_market_df['base_asset'].isin(shared_bass_asset_list)].sort_values('base_asset').reset_index(drop=True)
# target_market_df = target_market_df[target_market_df['base_asset'].isin(shared_bass_asset_list)].set_index('base_asset')

convert_rate = convert_asset_rate(origin_market, quote_asset_one, target_market, quote_asset_two)

origin_market_df[['converted_tp','converted_ap','converted_bp']] = origin_market_df[['tp','ap','bp']] * convert_rate
# target_market_df[['converted_tp','converted_ap','converted_bp']] = target_market_df[['tp','ap','bp']]

# divide by target_market_df[['tp','ap','bp']]
premium_df = pd.DataFrame((target_market_df[['tp','ap','bp']].values - origin_market_df[['converted_tp','converted_bp','converted_ap']].values)/
                          origin_market_df[['converted_tp','converted_bp','converted_ap']].values, columns=['tp_premium','LS_premium','SL_premium'])
premium_df['LS_SL_spread'] = premium_df['LS_premium'] - premium_df['SL_premium']
premium_df[['base_asset','quote_asset','tp','ap','bp','atp24h']] = target_market_df[['base_asset','quote_asset','tp','ap','bp','atp24h']]
premium_df[['converted_tp','converted_ap','converted_bp']] = origin_market_df[['converted_tp','converted_ap', 'converted_bp']]
premium_df.loc[:, ['tp_premium','LS_premium','SL_premium','LS_SL_spread']] = premium_df[['tp_premium','LS_premium','SL_premium','LS_SL_spread']] * 100
premium_df.sort_values('atp24h', ascending=False).reset_index(drop=True).head(10)

,tp_premium,LS_premium,SL_premium,LS_SL_spread,base_asset,quote_asset,tp,ap,bp,atp24h,converted_tp,converted_ap,converted_bp
0,-0.007192,-0.007192,-0.559324,0.552131,NMR,BTC,0.000555,0.000555,0.000553,304.797912,0.000555,0.000556,0.000555
1,-0.101874,0.499651,-0.084801,0.584452,CYBER,BTC,0.000227,0.000228,0.000227,292.916129,0.000227,0.000227,0.000227
2,-0.351824,-0.25277,-0.607332,0.354562,GTC,BTC,0.000039,0.000039,0.000039,154.273882,0.000039,0.000039,0.000039
3,0.755072,1.292792,0.755072,0.537721,SNX,BTC,0.000099,0.000100,0.000099,77.203321,0.000098,0.000098,0.000098
4,-1.441102,-0.839,-1.719908,0.880908,NKN,BTC,0.000003,0.000003,0.000003,55.92468,0.000003,0.000003,0.000003
5,-0.328891,0.600182,-0.304155,0.904337,LPT,BTC,0.000282,0.000285,0.000282,55.566992,0.000283,0.000283,0.000283
6,0.579619,0.579619,-0.027867,0.607486,ARPA,BTC,0.000002,0.000002,0.000002,53.702797,0.000002,0.000002,0.000002
7,-0.30787,-0.29184,-1.16697,0.87513,OXT,BTC,0.000002,0.000002,0.000002,53.145974,0.000002,0.000002,0.000002
8,-0.457083,0.459776,-0.493247,0.953023,AGLD,BTC,0.000021,0.000021,0.000021,22.66042,0.000021,0.000021,0.000021
9,0.113863,0.448197,0.122665,0.325532,API3,BTC,0.000044,0.000044,0.000044,15.886144,0.000044,0.000044,0.000044

2023-09-06 19:56:02,516 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 19:56:18,328 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 19:56:18,506 - update_dollar - INFO - fetch_dollar|Dollar price (1331.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1331.5 KRW) has been updated.
2023-09-06 19:56:33,641 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 19:56:48,957 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 19:56:49,522 - update_dollar - INFO - fetch_dollar|Dollar price (1331.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1331.5 KRW) has been updated.
2023-09-06 19:57:04,268 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 19:57:20,082 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 19:57:20,482 - update_dollar - INFO - fetch_dollar|Dollar price (1331.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1331.5 KRW) has been updated.
2023-09-06 19:57:35,375 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 19:57:50,665 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 19:57:51,396 - update_dollar - INFO - fetch_dollar|Dollar price (1331.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1331.5 KRW) has been updated.
2023-09-06 19:58:05,970 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 19:58:21,523 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 19:58:22,340 - update_dollar - INFO - fetch_dollar|Dollar price (1331.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1331.5 KRW) has been updated.
2023-09-06 19:58:36,757 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 19:58:52,063 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 19:58:53,361 - update_dollar - INFO - fetch_dollar|Dollar price (1331.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1331.5 KRW) has been updated.
2023-09-06 19:59:07,310 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 19:59:22,628 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 19:59:24,325 - update_dollar - INFO - fetch_dollar|Dollar price (1331.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1331.5 KRW) has been updated.
2023-09-06 19:59:37,950 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 19:59:53,202 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 19:59:55,308 - update_dollar - INFO - fetch_dollar|Dollar price (1331.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1331.5 KRW) has been updated.
2023-09-06 20:00:08,537 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 20:00:23,844 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 20:00:26,305 - update_dollar - INFO - fetch_dollar|Dollar price (1331.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1331.5 KRW) has been updated.
2023-09-06 20:00:39,127 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 20:00:54,659 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 20:00:57,374 - update_dollar - INFO - fetch_dollar|Dollar price (1331.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1331.5 KRW) has been updated.
2023-09-06 20:01:10,179 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 20:01:25,820 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 20:01:28,338 - update_dollar - INFO - fetch_dollar|Dollar price (1331.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1331.5 KRW) has been updated.
2023-09-06 20:01:41,304 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 20:01:56,856 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 20:01:59,228 - update_dollar - INFO - fetch_dollar|Dollar price (1331.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1331.5 KRW) has been updated.
2023-09-06 20:02:12,163 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 20:02:27,437 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 20:02:30,167 - update_dollar - INFO - fetch_dollar|Dollar price (1332.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1332.0 KRW) has been updated.
2023-09-06 20:02:42,704 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 20:02:58,015 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 20:03:01,119 - update_dollar - INFO - fetch_dollar|Dollar price (1332.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1332.0 KRW) has been updated.
2023-09-06 20:03:13,309 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 20:03:28,544 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 20:03:32,007 - update_dollar - INFO - fetch_dollar|Dollar price (1332.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1332.0 KRW) has been updated.
2023-09-06 20:03:43,836 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 20:03:59,141 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 20:04:02,941 - update_dollar - INFO - fetch_dollar|Dollar price (1332.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1332.0 KRW) has been updated.
2023-09-06 20:04:14,424 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 20:04:29,733 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 20:04:33,976 - update_dollar - INFO - fetch_dollar|Dollar price (1332.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1332.0 KRW) has been updated.
2023-09-06 20:04:45,026 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 20:05:00,304 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 20:05:05,146 - update_dollar - INFO - fetch_dollar|Dollar price (1332.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1332.0 KRW) has been updated.
2023-09-06 20:05:15,608 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 20:05:30,885 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 20:05:36,444 - update_dollar - INFO - fetch_dollar|Dollar price (1332.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1332.0 KRW) has been updated.
2023-09-06 20:05:46,166 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 20:06:01,467 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 20:06:07,730 - update_dollar - INFO - fetch_dollar|Dollar price (1332.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1332.0 KRW) has been updated.
2023-09-06 20:06:16,732 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 20:06:31,996 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 20:06:39,147 - update_dollar - INFO - fetch_dollar|Dollar price (1332.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1332.0 KRW) has been updated.
2023-09-06 20:06:47,285 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 20:07:02,526 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 20:07:10,418 - update_dollar - INFO - fetch_dollar|Dollar price (1332.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1332.0 KRW) has been updated.
2023-09-06 20:07:17,802 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 20:07:33,112 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 20:07:41,772 - update_dollar - INFO - fetch_dollar|Dollar price (1332.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1332.0 KRW) has been updated.
2023-09-06 20:07:48,383 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 20:08:03,940 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 20:08:13,363 - update_dollar - INFO - fetch_dollar|Dollar price (1332.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1332.0 KRW) has been updated.
2023-09-06 20:08:19,254 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 20:08:34,499 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 20:08:44,251 - update_dollar - INFO - fetch_dollar|Dollar price (1332.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1332.0 KRW) has been updated.
2023-09-06 20:08:49,846 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 20:09:05,107 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 20:09:15,267 - update_dollar - INFO - fetch_dollar|Dollar price (1332.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1332.0 KRW) has been updated.
2023-09-06 20:09:20,359 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 20:09:35,691 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 20:09:46,341 - update_dollar - INFO - fetch_dollar|Dollar price (1332.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1332.0 KRW) has been updated.
2023-09-06 20:09:50,938 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 20:10:06,187 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 20:10:17,316 - update_dollar - INFO - fetch_dollar|Dollar price (1332.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1332.0 KRW) has been updated.
2023-09-06 20:10:21,503 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 20:10:36,781 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 20:10:48,194 - update_dollar - INFO - fetch_dollar|Dollar price (1332.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1332.0 KRW) has been updated.
2023-09-06 20:10:52,090 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 20:11:07,407 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 20:11:19,070 - update_dollar - INFO - fetch_dollar|Dollar price (1332.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1332.0 KRW) has been updated.
2023-09-06 20:11:23,052 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API

In [139]:
origin_market_df = core.exchange_websocket_dict[origin_market].get_price_df()
origin_market_df = origin_market_df[origin_market_df['quote_asset'] == quote_asset_one]
target_market_df = core.exchange_websocket_dict[target_market].get_price_df()
target_market_df = target_market_df[target_market_df['quote_asset'] == quote_asset_two]

In [140]:
origin_market_df

,scr,tp,v,atp24h,bp,ap,base_asset,quote_asset
0,2.225,1.516,47113119,70676291.818,1.515,1.516,RUNE,USDT
1,2.407,0.234,44207629,10228710.0245,0.2339,0.234,STORJ,USDT
2,1.957,0.5939,67820833,39944814.9075,0.5939,0.594,SFP,USDT
3,0.393,7.671,932628.4,7176575.976,7.67,7.672,ENS,USDT
5,7.429,0.1663,394587082.7,65020971.5355,0.1663,0.1664,ONT,USDT
...,...,...,...,...,...,...,...,...
187,1.914,0.0852,120014293.9,10303972.4557,0.0852,0.0853,DAR,USDT
188,0.99,0.000612,6450009809,3937095.065372,0.000611,0.000612,DENT,USDT
189,1.176,0.43,46936878.5,20146218.818,0.429,0.43,CELO,USDT
190,3.071,0.772,17720118.8,13680829.2,0.772,0.773,ALICE,USDT
191,0.005,1.00021,575675,575736.84373,1.0002,1.00021,USDC,USDT

In [142]:
core.exchange_websocket_dict[target_market].get_price_df()

,scr,tp,v,atp24h,bp,ap,base_asset,quote_asset
0,1.644,19.781,3426352,1709527.517567,19.783,19.784,SOL,USD
1,-0.283,214.8,1355786,63091.489513,214.79,214.8,BNB,USD
2,-0.752,0.5545,602583,10763716.218979,0.5545,0.5546,MATIC,USD
3,-0.885,138.89,113221,8157.603131,138.88,138.89,XMR,USD
4,-0.635,0.5007,2481365,49413485.925364,0.5007,0.5008,XRP,USD
5,1.794,0.624,51779,827757.607978,0.624,0.625,THETA,USD
6,-0.087,25729.7,5546147,21549.151761,25729.6,25729.7,BTC,USD
7,-5.208,0.1203,376279,30654518.178722,0.12032,0.12033,XLM,USD
8,0.009,1630.51,29722786,181959.665645,1630.5,1630.51,ETH,USD
9,1.154,0.5349,84009,1561689.067684,0.5349,0.535,KNC,USD
10,-0.195,0.256,702661,27333648.506097,0.2559,0.256,ADA,USD
11,-0.19,62.89,1381515,219294.176676,62.89,62.9,LTC,USD
12,-0.109,0.06397,1321936,206595097.443229,0.06397,0.06398,DOGE,USD
13,0.597,1.347,95093,708351.182834,1.347,1.348,APE,USD
14,1.08,15.441,428236,279250.297901,15.44,15.441,ETC,USD
15,-0.09,55.23,60452,10926.376408,55.23,55.24,AAVE,USD
16,-0.727,4.236,414706,975954.336557,4.235,4.236,DOT,USD
17,-0.297,0.2017,83849,4147320.756983,0.2017,0.2018,FTM,USD
18,1.35,0.3079,102182,3323849.526245,0.3079,0.308,SAND,USD
19,0.499,1.3284,374211,2801309.706287,1.3289,1.329,OP,USD
20,1.247,3.248,764802,2366186.385301,3.247,3.248,FIL,USD
21,-0.74,24.683,140914,56565.791583,24.693,24.694,EGLD,USD
22,1.853,4.397,185417,425622.812891,4.398,4.399,UNI,USD
23,1.56,6.12,1335036,2171544.510998,6.119,6.12,LINK,USD
24,-0.093,192.84,899026,46793.48637,192.86,192.87,BCH,USD
25,0.0,4.536,77187,169820.283732,4.536,4.537,AXS,USD
26,0.542,0.07788,112979,14585000.066215,0.07788,0.07789,TRX,USD
27,0.075,0.04005,35229,8708901.874209,0.04003,0.04005,ROSE,USD
28,1.466,0.1592,69526,4416799.028788,0.159,0.1591,GMT,USD
29,2.159,1.514,58667,391345.367762,1.513,1.514,RUNE,USD
30,0.814,9.91,111932,113262.471397,9.91,9.92,AVAX,USD
31,-0.256,5.464,126926,231209.42891,5.464,5.465,APT,USD
32,0.205,0.2936,120415,4103520.902976,0.2935,0.2936,MANA,USD
33,0.0,0.0936,20121,2148736.140498,0.0936,0.0937,ALGO,USD
34,0.275,7.668,68525,89283.062855,7.667,7.671,ENS,USD
35,1.143,6.811,119466,175903.365377,6.81,6.811,ATOM,USD
36,-0.266,1.123,154664,1370318.130924,1.123,1.124,NEAR,USD
37,-0.446,0.6922,14211,203867.028873,0.6922,0.6924,XTZ,USD
38,0.169,0.0593,15978,2686796.771966,0.0593,0.0594,CHZ,USD
39,2.122,0.1636,16309,1004652.972663,0.1635,0.1636,ICX,USD
40,1.377,0.589,254956,4347223.510082,0.589,0.59,EOS,USD

2023-09-06 18:47:21,784 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API

In [53]:
target_market_df.head()[['base_asset','tp','ap','bp']]

   base_asset       tp       ap       bp
58      1INCH    331.0    332.0    331.0
19       AAVE  75100.0  75100.0  75070.0
36        ADA    348.0    348.0    347.0
4        ALGO    128.0    128.0    127.0
28       ANKR     25.0     25.1     25.0

In [54]:
origin_market_df.head()[['base_asset','tp','ap','bp']]

   base_asset       tp      ap       bp
41      1INCH   0.2432  0.2433   0.2432
44       AAVE    55.16   55.17    55.16
15        ADA   0.2555  0.2555   0.2554
55       ALGO   0.0932  0.0933   0.0932
54       ANKR  0.01839  0.0184  0.01839

2023-09-06 17:19:48,528 - update_dollar - INFO - fetch_dollar|Dollar price (1333.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1333.0 KRW) has been updated.
2023-09-06 17:19:48,888 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 17:20:04,158 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 17:20:19,504 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 17:20:19,605 - update_dollar - INFO - fetch_dollar|Dollar price (1333.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1333.0 KRW) has been updated.
2023-09-06 17:20:34,752 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 17:20:50,255 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 17:20:50,632 - update_dollar - INFO - fetch_dollar|Dollar price (1333.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1333.0 KRW) has been updated.
2023-09-06 17:21:05,738 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API

In [124]:
origin_market_df.head()

2023-09-06 12:46:55,403 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API

,tp,scr,atp24h,h52wp,l52wp,ms,mw,tms_x,cd,tms_y,ap,bp,base_asset,quote_asset,converted_tp,converted_ap,converted_bp
0,35075000.0,0.054199,96615874776.293121,41569000.0,20700000.0,ACTIVE,NONE,1693972012477,KRW-BTC,1693972013291,35075000.0,35074000.0,BTC,KRW,26326.653156,26326.653156,26325.902574
1,634.0,-2.009274,42693830377.089645,1725.0,257.0,ACTIVE,NONE,1693972011977,KRW-STX,1693972014161,634.0,633.0,STX,KRW,0.475869,0.475869,0.475118
2,239.0,-1.239669,3580995722.840689,512.0,184.0,ACTIVE,NONE,1693972001024,KRW-ZRX,1693972010117,240.0,239.0,ZRX,KRW,0.179389,0.180140,0.179389
3,889.0,-0.447928,3348999523.535093,3200.0,857.0,ACTIVE,NONE,1693971990520,KRW-KAVA,1693972014054,890.0,888.0,KAVA,KRW,0.667267,0.668018,0.666517
4,747.0,-0.267023,1138264715.74378,1255.0,725.0,ACTIVE,NONE,1693971900688,KRW-IMX,1693972012889,749.0,747.0,IMX,KRW,0.560685,0.562186,0.560685

2023-09-06 12:47:10,656 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 12:47:17,765 - update_dollar - INFO - fetch_dollar|Dollar price (1332.3 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1332.3 KRW) has been updated.
2023-09-06 12:47:25,935 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API

In [106]:
convert_asset_rate(origin_market="BINANCE_SPOT", origin_quote_asset='BUSD', target_market="UPBIT_SPOT", target_quote_asset='KRW')

1st convert_rate is None, Not between coins

1332.2995700000001

2023-09-06 12:29:46,729 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-06 12:29:58,713 - update_dollar - INFO - fetch_dollar|Dollar price (1331.9 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1331.9 KRW) has been updated.

In [106]:
core.update_dollar_return_dict['price']

1332.0

2023-09-05 17:00:49,639 - update_dollar - INFO - fetch_dollar|Dollar price (1332.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1332.0 KRW) has been updated.
2023-09-05 17:01:20,529 - update_dollar - INFO - fetch_dollar|Dollar price (1332.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1332.0 KRW) has been updated.
2023-09-05 17:01:51,648 - update_dollar - INFO - fetch_dollar|Dollar price (1332.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1332.0 KRW) has been updated.
2023-09-05 17:02:22,579 - update_dollar - INFO - fetch_dollar|Dollar price (1332.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1332.5 KRW) has been updated.
2023-09-05 17:02:54,723 - update_dollar - INFO - fetch_dollar|Dollar price (1332.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1332.5 KRW) has been updated.

In [84]:
upbit_ticker_df = pd.DataFrame(dict(core.exchange_websocket_dict['UPBIT'].upbit_ticker_dict)).T.reset_index()[['index','tp','scr','atp24h','h52wp','l52wp','ms','mw','tms']]
upbit_orderbook_df = pd.DataFrame(dict(core.exchange_websocket_dict['UPBIT'].upbit_orderbook_dict)).T.reset_index(drop=True)[['cd','tms','obu']]
upbit_orderbook_df['ap'] = upbit_orderbook_df['obu'].apply(lambda x: x[0]['ap'])
upbit_orderbook_df['bp'] = upbit_orderbook_df['obu'].apply(lambda x: x[0]['bp'])
upbit_orderbook_df.drop('obu', axis=1, inplace=True)
upbit_merged_df = pd.merge(upbit_ticker_df, upbit_orderbook_df, left_on='index', right_on='cd', how='inner')
upbit_merged_df['base_asset'] = upbit_merged_df['index'].apply(lambda x: x.split('-')[1])
upbit_merged_df['quote_asset'] = upbit_merged_df['index'].apply(lambda x: x.split('-')[0])
upbit_merged_df.drop('index', axis=1, inplace=True)
upbit_merged_df.loc[:, ['scr','atp24h','h52wp','l52wp','ap','bp']] = upbit_merged_df.loc[:, ['scr','atp24h','h52wp','l52wp','ap','bp']].astype(float)
upbit_merged_df.loc[:, 'scr'] = upbit_merged_df['scr'] * 100
upbit_merged_df.head()

,tp,scr,atp24h,h52wp,l52wp,ms,mw,tms_x,cd,tms_y,ap,bp,base_asset,quote_asset
0,681.0,-4.488079,60549576212.024315,1050.0,324.0,ACTIVE,NONE,1693888666296,KRW-HIFI,1693888666356,6.820000e+02,6.810000e+02,HIFI,KRW
1,261250.0,-0.533029,13577217439.571684,436000.0,120450.0,ACTIVE,NONE,1693888664702,KRW-BCH,1693888667154,2.612500e+05,2.611000e+05,BCH,KRW
2,2199000.0,-0.542741,14606365395.293249,2795000.0,1500000.0,ACTIVE,NONE,1693888662364,KRW-ETH,1693888665247,2.200000e+06,2.199000e+06,ETH,KRW
3,20700.0,-0.6241,5668367806.45153,55490.0,18490.0,ACTIVE,NONE,1693888665826,KRW-ETC,1693888667694,2.070000e+04,2.069000e+04,ETC,KRW
4,0.000001,0.0,41.049127,0.000002,0.000001,ACTIVE,NONE,1693888534181,BTC-REI,1693888643805,9.100000e-07,9.000000e-07,REI,BTC

In [105]:
upbit_merged_df.head()

,tp,scr,atp24h,h52wp,l52wp,ms,mw,tms_x,cd,tms_y,ap,bp,base_asset,quote_asset
0,681.0,-4.488079,60549576212.024315,1050.0,324.0,ACTIVE,NONE,1693888666296,KRW-HIFI,1693888666356,6.820000e+02,6.810000e+02,HIFI,KRW
1,261250.0,-0.533029,13577217439.571684,436000.0,120450.0,ACTIVE,NONE,1693888664702,KRW-BCH,1693888667154,2.612500e+05,2.611000e+05,BCH,KRW
2,2199000.0,-0.542741,14606365395.293249,2795000.0,1500000.0,ACTIVE,NONE,1693888662364,KRW-ETH,1693888665247,2.200000e+06,2.199000e+06,ETH,KRW
3,20700.0,-0.6241,5668367806.45153,55490.0,18490.0,ACTIVE,NONE,1693888665826,KRW-ETC,1693888667694,2.070000e+04,2.069000e+04,ETC,KRW
4,0.000001,0.0,41.049127,0.000002,0.000001,ACTIVE,NONE,1693888534181,BTC-REI,1693888643805,9.100000e-07,9.000000e-07,REI,BTC

2023-09-05 16:47:25,872 - update_dollar - INFO - fetch_dollar|Dollar price (1332.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1332.0 KRW) has been updated.
2023-09-05 16:47:56,747 - update_dollar - INFO - fetch_dollar|Dollar price (1332.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1332.0 KRW) has been updated.
2023-09-05 16:48:27,620 - update_dollar - INFO - fetch_dollar|Dollar price (1332.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1332.0 KRW) has been updated.
2023-09-05 16:48:58,748 - update_dollar - INFO - fetch_dollar|Dollar price (1332.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1332.0 KRW) has been updated.
2023-09-05 16:49:29,554 - update_dollar - INFO - fetch_dollar|Dollar price (1331.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1331.5 KRW) has been updated.
2023-09-05 16:50:00,549 - update_dollar - INFO - fetch_dollar|Dollar price (1331.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1331.5 KRW) has been updated.
2023-09-05 16:50:31,311 - update_dollar - INFO - fetch_dollar|Dollar price (1331.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1331.5 KRW) has been updated.
2023-09-05 16:51:02,192 - update_dollar - INFO - fetch_dollar|Dollar price (1331.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1331.5 KRW) has been updated.
2023-09-05 16:51:33,130 - update_dollar - INFO - fetch_dollar|Dollar price (1331.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1331.5 KRW) has been updated.
2023-09-05 16:52:03,926 - update_dollar - INFO - fetch_dollar|Dollar price (1331.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1331.5 KRW) has been updated.
2023-09-05 16:52:34,802 - update_dollar - INFO - fetch_dollar|Dollar price (1331.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1331.5 KRW) has been updated.
2023-09-05 16:53:05,708 - update_dollar - INFO - fetch_dollar|Dollar price (1331.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1331.5 KRW) has been updated.
2023-09-05 16:53:36,494 - update_dollar - INFO - fetch_dollar|Dollar price (1331.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1331.5 KRW) has been updated.
2023-09-05 16:54:07,602 - update_dollar - INFO - fetch_dollar|Dollar price (1331.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1331.5 KRW) has been updated.
2023-09-05 16:54:38,535 - update_dollar - INFO - fetch_dollar|Dollar price (1332.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1332.0 KRW) has been updated.
2023-09-05 16:55:09,347 - update_dollar - INFO - fetch_dollar|Dollar price (1332.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1332.0 KRW) has been updated.
2023-09-05 16:55:40,349 - update_dollar - INFO - fetch_dollar|Dollar price (1332.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1332.0 KRW) has been updated.
2023-09-05 16:56:11,237 - update_dollar - INFO - fetch_dollar|Dollar price (1332.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1332.0 KRW) has been updated.
2023-09-05 16:56:42,110 - update_dollar - INFO - fetch_dollar|Dollar price (1332.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1332.0 KRW) has been updated.
2023-09-05 16:57:12,985 - update_dollar - INFO - fetch_dollar|Dollar price (1332.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1332.0 KRW) has been updated.
2023-09-05 16:57:44,138 - update_dollar - INFO - fetch_dollar|Dollar price (1332.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1332.0 KRW) has been updated.
2023-09-05 16:58:15,055 - update_dollar - INFO - fetch_dollar|Dollar price (1332.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1332.0 KRW) has been updated.
2023-09-05 16:58:45,870 - update_dollar - INFO - fetch_dollar|Dollar price (1332.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1332.0 KRW) has been updated.
2023-09-05 16:59:16,845 - update_dollar - INFO - fetch_dollar|Dollar price (1332.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1332.0 KRW) has been updated.
2023-09-05 16:59:47,603 - update_dollar - INFO - fetch_dollar|Dollar price (1332.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1332.0 KRW) has been updated.
2023-09-05 17:00:18,824 - update_dollar - INFO - fetch_dollar|Dollar price (1332.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1332.0 KRW) has been updated.

In [89]:
core.info_dict['binance_spot_info_df'][['symbol','baseAsset','quoteAsset']].head()

    symbol baseAsset quoteAsset
0   ETHBTC       ETH        BTC
1   LTCBTC       LTC        BTC
2   BNBBTC       BNB        BTC
3   NEOBTC       NEO        BTC
4  QTUMETH      QTUM        ETH

In [101]:
binance_ticker_df = pd.DataFrame(dict(core.exchange_websocket_dict['BINANCE_SPOT'].ticker_dict)).T.reset_index(drop=True)[['s','P','c','v','q']]
binance_ticker_df.rename(columns={"q": "atp24h", 'P': 'scr', 'c': 'tp'}, inplace=True)
binance_bookticker_df = pd.DataFrame(dict(core.exchange_websocket_dict['BINANCE_SPOT'].bookticker_dict)).T.reset_index(drop=True)[['s','b','a']]
binance_bookticker_df.rename(columns={"b": "bp", "a": "ap"}, inplace=True)
binance_merged_df = pd.merge(binance_ticker_df, binance_bookticker_df, on='s', how='inner')
binance_merged_df.loc[:, ['scr','tp','atp24h','ap','bp']] = binance_merged_df[['scr','tp','atp24h','ap','bp']].astype(float)
binance_merged_df = binance_merged_df.merge(core.info_dict['binance_spot_info_df'][['symbol','baseAsset','quoteAsset']], left_on='s', right_on='symbol', how='inner')
binance_merged_df.drop(['symbol', 's'], axis=1, inplace=True)
binance_merged_df.rename(columns={'baseAsset':"base_asset", 'quoteAsset':"quote_asset"}, inplace=True)
binance_merged_df

,scr,tp,v,atp24h,bp,ap,base_asset,quote_asset
0,0.0,2.093,6477595.93000000,13453687.07257,2.092,2.093,DYDX,USDT
1,1.397,0.1234,14689380.00000000,1836390.77,0.1234,0.1235,CFX,BUSD
2,2.078,0.2604,3544139.00000000,927170.077,0.2604,0.2606,FET,BUSD
3,-2.33,0.000044,67598.26000000,2.986275,0.000044,0.000044,API3,BTC
4,-2.945,4.317,1240161.63000000,5463164.30196,4.316,4.317,UNI,USDT
...,...,...,...,...,...,...,...,...
591,0.075,0.000027,79798.20000000,2.147748,0.000027,0.000027,XTZ,BTC
592,-2.011,0.0877,402568.00000000,35377.4305,0.0875,0.0877,CHR,BUSD
593,0.0,1.0,1077308.00000000,1077484.6243,1.0,1.0001,USDP,USDT
594,-1.368,0.02308,4842249.40000000,113263.58121,0.02304,0.02312,REI,BUSD
595,-2.358,0.001035,20437320.90000000,21133.951011,0.001034,0.001036,HOT,BUSD

In [102]:
binance_merged_df['quote_asset'].unique()

array(['USDT', 'BUSD', 'BTC'], dtype=object)

2023-09-05 14:12:19,312 - update_dollar - INFO - fetch_dollar|Dollar price (1324.4 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.4 KRW) has been updated.
2023-09-05 14:12:50,686 - update_dollar - INFO - fetch_dollar|Dollar price (1324.4 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.4 KRW) has been updated.
2023-09-05 14:13:21,607 - update_dollar - INFO - fetch_dollar|Dollar price (1324.4 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.4 KRW) has been updated.
2023-09-05 14:13:52,565 - update_dollar - INFO - fetch_dollar|Dollar price (1324.4 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.4 KRW) has been updated.
2023-09-05 14:14:23,628 - update_dollar - INFO - fetch_dollar|Dollar price (1324.6 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.6 KRW) has been updated.
2023-09-05 14:14:54,691 - update_dollar - INFO - fetch_dollar|Dollar price (1324.6 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.6 KRW) has been updated.
2023-09-05 14:15:26,311 - update_dollar - INFO - fetch_dollar|Dollar price (1324.6 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.6 KRW) has been updated.
2023-09-05 14:15:57,437 - update_dollar - INFO - fetch_dollar|Dollar price (1324.6 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.6 KRW) has been updated.
2023-09-05 14:16:28,482 - update_dollar - INFO - fetch_dollar|Dollar price (1324.8 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.8 KRW) has been updated.
2023-09-05 14:16:59,854 - update_dollar - INFO - fetch_dollar|Dollar price (1324.8 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.8 KRW) has been updated.
2023-09-05 14:17:31,099 - update_dollar - INFO - fetch_dollar|Dollar price (1325.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1325.0 KRW) has been updated.
2023-09-05 14:18:02,190 - update_dollar - INFO - fetch_dollar|Dollar price (1325.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1325.0 KRW) has been updated.
2023-09-05 14:18:33,464 - update_dollar - INFO - fetch_dollar|Dollar price (1324.7 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.7 KRW) has been updated.
2023-09-05 14:19:04,486 - update_dollar - INFO - fetch_dollar|Dollar price (1324.7 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.7 KRW) has been updated.
2023-09-05 14:19:36,094 - update_dollar - INFO - fetch_dollar|Dollar price (1324.7 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.7 KRW) has been updated.
2023-09-05 14:20:07,183 - update_dollar - INFO - fetch_dollar|Dollar price (1324.7 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.7 KRW) has been updated.
2023-09-05 14:20:38,367 - update_dollar - INFO - fetch_dollar|Dollar price (1324.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.5 KRW) has been updated.
2023-09-05 14:21:09,268 - update_dollar - INFO - fetch_dollar|Dollar price (1324.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.5 KRW) has been updated.
2023-09-05 14:21:40,168 - update_dollar - INFO - fetch_dollar|Dollar price (1324.3 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.3 KRW) has been updated.
2023-09-05 14:22:11,326 - update_dollar - INFO - fetch_dollar|Dollar price (1324.3 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.3 KRW) has been updated.
2023-09-05 14:22:42,486 - update_dollar - INFO - fetch_dollar|Dollar price (1324.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.5 KRW) has been updated.
2023-09-05 14:23:13,270 - update_dollar - INFO - fetch_dollar|Dollar price (1324.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.5 KRW) has been updated.
2023-09-05 14:23:44,158 - update_dollar - INFO - fetch_dollar|Dollar price (1324.7 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.7 KRW) has been updated.
2023-09-05 14:24:15,246 - update_dollar - INFO - fetch_dollar|Dollar price (1324.9 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.9 KRW) has been updated.
2023-09-05 14:24:46,274 - update_dollar - INFO - fetch_dollar|Dollar price (1324.9 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.9 KRW) has been updated.
2023-09-05 14:25:17,207 - update_dollar - INFO - fetch_dollar|Dollar price (1325.1 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1325.1 KRW) has been updated.
2023-09-05 14:25:48,270 - update_dollar - INFO - fetch_dollar|Dollar price (1325.1 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1325.1 KRW) has been updated.
2023-09-05 14:26:19,379 - update_dollar - INFO - fetch_dollar|Dollar price (1325.3 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1325.3 KRW) has been updated.
2023-09-05 14:26:50,364 - update_dollar - INFO - fetch_dollar|Dollar price (1325.3 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1325.3 KRW) has been updated.
2023-09-05 14:27:21,304 - update_dollar - INFO - fetch_dollar|Dollar price (1325.3 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1325.3 KRW) has been updated.
2023-09-05 14:27:52,188 - update_dollar - INFO - fetch_dollar|Dollar price (1325.1 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1325.1 KRW) has been updated.
2023-09-05 14:28:23,287 - update_dollar - INFO - fetch_dollar|Dollar price (1324.9 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.9 KRW) has been updated.
2023-09-05 14:28:54,377 - update_dollar - INFO - fetch_dollar|Dollar price (1324.9 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.9 KRW) has been updated.
2023-09-05 14:29:25,326 - update_dollar - INFO - fetch_dollar|Dollar price (1325.1 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1325.1 KRW) has been updated.
2023-09-05 14:29:56,110 - update_dollar - INFO - fetch_dollar|Dollar price (1324.9 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.9 KRW) has been updated.
2023-09-05 14:30:27,039 - update_dollar - INFO - fetch_dollar|Dollar price (1325.1 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1325.1 KRW) has been updated.
2023-09-05 14:30:58,134 - update_dollar - INFO - fetch_dollar|Dollar price (1324.9 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.9 KRW) has been updated.
2023-09-05 14:31:29,344 - update_dollar - INFO - fetch_dollar|Dollar price (1324.9 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.9 KRW) has been updated.
2023-09-05 14:32:00,263 - update_dollar - INFO - fetch_dollar|Dollar price (1324.9 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.9 KRW) has been updated.
2023-09-05 14:32:31,197 - update_dollar - INFO - fetch_dollar|Dollar price (1325.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1325.5 KRW) has been updated.
2023-09-05 14:33:02,196 - update_dollar - INFO - fetch_dollar|Dollar price (1325.3 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1325.3 KRW) has been updated.
2023-09-05 14:33:33,078 - update_dollar - INFO - fetch_dollar|Dollar price (1325.3 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1325.3 KRW) has been updated.
2023-09-05 14:34:04,255 - update_dollar - INFO - fetch_dollar|Dollar price (1325.3 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1325.3 KRW) has been updated.
2023-09-05 14:34:35,401 - update_dollar - INFO - fetch_dollar|Dollar price (1325.3 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1325.3 KRW) has been updated.
2023-09-05 14:35:06,469 - update_dollar - INFO - fetch_dollar|Dollar price (1325.1 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1325.1 KRW) has been updated.
2023-09-05 14:35:37,715 - update_dollar - INFO - fetch_dollar|Dollar price (1324.9 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.9 KRW) has been updated.
2023-09-05 14:36:08,630 - update_dollar - INFO - fetch_dollar|Dollar price (1324.9 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.9 KRW) has been updated.
2023-09-05 14:36:39,589 - update_dollar - INFO - fetch_dollar|Dollar price (1324.7 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.7 KRW) has been updated.
2023-09-05 14:37:10,648 - update_dollar - INFO - fetch_dollar|Dollar price (1324.7 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.7 KRW) has been updated.
2023-09-05 14:37:41,506 - update_dollar - INFO - fetch_dollar|Dollar price (1324.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.5 KRW) has been updated.
2023-09-05 14:38:12,626 - update_dollar - INFO - fetch_dollar|Dollar price (1324.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.5 KRW) has been updated.
2023-09-05 14:38:43,820 - update_dollar - INFO - fetch_dollar|Dollar price (1324.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.5 KRW) has been updated.
2023-09-05 14:39:14,891 - update_dollar - INFO - fetch_dollar|Dollar price (1324.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.5 KRW) has been updated.
2023-09-05 14:39:45,811 - update_dollar - INFO - fetch_dollar|Dollar price (1324.7 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.7 KRW) has been updated.
2023-09-05 14:40:16,795 - update_dollar - INFO - fetch_dollar|Dollar price (1324.7 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.7 KRW) has been updated.
2023-09-05 14:40:48,070 - update_dollar - INFO - fetch_dollar|Dollar price (1324.7 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.7 KRW) has been updated.
2023-09-05 14:41:19,075 - update_dollar - INFO - fetch_dollar|Dollar price (1324.7 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.7 KRW) has been updated.
2023-09-05 14:41:50,042 - update_dollar - INFO - fetch_dollar|Dollar price (1324.7 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.7 KRW) has been updated.
2023-09-05 14:42:20,954 - update_dollar - INFO - fetch_dollar|Dollar price (1324.7 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.7 KRW) has been updated.
2023-09-05 14:42:52,805 - update_dollar - INFO - fetch_dollar|Dollar price (1324.7 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.7 KRW) has been updated.
2023-09-05 14:43:23,871 - update_dollar - INFO - fetch_dollar|Dollar price (1324.7 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.7 KRW) has been updated.
2023-09-05 14:43:54,788 - update_dollar - INFO - fetch_dollar|Dollar price (1324.7 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.7 KRW) has been updated.
2023-09-05 14:44:25,534 - update_dollar - INFO - fetch_dollar|Dollar price (1324.7 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.7 KRW) has been updated.
2023-09-05 14:44:56,794 - update_dollar - INFO - fetch_dollar|Dollar price (1324.6 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.6 KRW) has been updated.
2023-09-05 14:45:27,794 - update_dollar - INFO - fetch_dollar|Dollar price (1324.6 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.6 KRW) has been updated.
2023-09-05 14:45:58,673 - update_dollar - INFO - fetch_dollar|Dollar price (1324.8 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.8 KRW) has been updated.
2023-09-05 14:46:29,714 - update_dollar - INFO - fetch_dollar|Dollar price (1324.8 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.8 KRW) has been updated.
2023-09-05 14:47:00,616 - update_dollar - INFO - fetch_dollar|Dollar price (1324.8 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.8 KRW) has been updated.
2023-09-05 14:47:31,926 - update_dollar - INFO - fetch_dollar|Dollar price (1324.6 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.6 KRW) has been updated.
2023-09-05 14:48:02,840 - update_dollar - INFO - fetch_dollar|Dollar price (1324.6 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.6 KRW) has been updated.
2023-09-05 14:48:33,745 - update_dollar - INFO - fetch_dollar|Dollar price (1324.6 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.6 KRW) has been updated.
2023-09-05 14:49:04,814 - update_dollar - INFO - fetch_dollar|Dollar price (1324.6 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.6 KRW) has been updated.
2023-09-05 14:49:35,875 - update_dollar - INFO - fetch_dollar|Dollar price (1324.8 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.8 KRW) has been updated.
2023-09-05 14:50:07,110 - update_dollar - INFO - fetch_dollar|Dollar price (1324.8 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.8 KRW) has been updated.
2023-09-05 14:50:37,979 - update_dollar - INFO - fetch_dollar|Dollar price (1324.8 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.8 KRW) has been updated.
2023-09-05 14:51:08,995 - update_dollar - INFO - fetch_dollar|Dollar price (1324.8 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.8 KRW) has been updated.
2023-09-05 14:51:40,297 - update_dollar - INFO - fetch_dollar|Dollar price (1324.8 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.8 KRW) has been updated.
2023-09-05 14:52:11,411 - update_dollar - INFO - fetch_dollar|Dollar price (1324.8 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.8 KRW) has been updated.
2023-09-05 14:52:42,457 - update_dollar - INFO - fetch_dollar|Dollar price (1325.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1325.0 KRW) has been updated.
2023-09-05 14:53:13,395 - update_dollar - INFO - fetch_dollar|Dollar price (1325.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1325.0 KRW) has been updated.
2023-09-05 14:53:44,483 - update_dollar - INFO - fetch_dollar|Dollar price (1325.3 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1325.3 KRW) has been updated.
2023-09-05 14:54:15,681 - update_dollar - INFO - fetch_dollar|Dollar price (1325.3 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1325.3 KRW) has been updated.
2023-09-05 14:54:46,612 - update_dollar - INFO - fetch_dollar|Dollar price (1325.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1325.5 KRW) has been updated.
2023-09-05 14:55:17,482 - update_dollar - INFO - fetch_dollar|Dollar price (1325.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1325.5 KRW) has been updated.
2023-09-05 14:55:48,637 - update_dollar - INFO - fetch_dollar|Dollar price (1325.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1325.5 KRW) has been updated.
2023-09-05 14:56:19,552 - update_dollar - INFO - fetch_dollar|Dollar price (1325.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1325.5 KRW) has been updated.
2023-09-05 14:56:50,683 - update_dollar - INFO - fetch_dollar|Dollar price (1325.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1325.5 KRW) has been updated.
2023-09-05 14:57:21,626 - update_dollar - INFO - fetch_dollar|Dollar price (1325.7 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1325.7 KRW) has been updated.
2023-09-05 14:57:52,554 - update_dollar - INFO - fetch_dollar|Dollar price (1326.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1326.0 KRW) has been updated.
2023-09-05 14:58:23,415 - update_dollar - INFO - fetch_dollar|Dollar price (1326.2 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1326.2 KRW) has been updated.
2023-09-05 14:58:54,301 - update_dollar - INFO - fetch_dollar|Dollar price (1326.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1326.5 KRW) has been updated.
2023-09-05 14:59:25,563 - update_dollar - INFO - fetch_dollar|Dollar price (1326.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1326.5 KRW) has been updated.
2023-09-05 14:59:56,549 - update_dollar - INFO - fetch_dollar|Dollar price (1326.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1326.5 KRW) has been updated.
2023-09-05 15:00:27,384 - update_dollar - INFO - fetch_dollar|Dollar price (1326.3 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1326.3 KRW) has been updated.
2023-09-05 15:00:58,290 - update_dollar - INFO - fetch_dollar|Dollar price (1326.3 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1326.3 KRW) has been updated.
2023-09-05 15:01:29,322 - update_dollar - INFO - fetch_dollar|Dollar price (1326.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1326.5 KRW) has been updated.
2023-09-05 15:02:00,552 - update_dollar - INFO - fetch_dollar|Dollar price (1326.3 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1326.3 KRW) has been updated.
2023-09-05 15:02:31,540 - update_dollar - INFO - fetch_dollar|Dollar price (1326.3 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1326.3 KRW) has been updated.
2023-09-05 15:03:02,460 - update_dollar - INFO - fetch_dollar|Dollar price (1326.3 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1326.3 KRW) has been updated.
2023-09-05 15:03:33,474 - update_dollar - INFO - fetch_dollar|Dollar price (1326.1 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1326.1 KRW) has been updated.
2023-09-05 15:04:04,458 - update_dollar - INFO - fetch_dollar|Dollar price (1326.1 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1326.1 KRW) has been updated.
2023-09-05 15:04:35,722 - update_dollar - INFO - fetch_dollar|Dollar price (1326.1 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1326.1 KRW) has been updated.
2023-09-05 15:05:06,660 - update_dollar - INFO - fetch_dollar|Dollar price (1326.1 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1326.1 KRW) has been updated.
2023-09-05 15:05:37,605 - update_dollar - INFO - fetch_dollar|Dollar price (1326.1 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1326.1 KRW) has been updated.
2023-09-05 15:06:08,520 - update_dollar - INFO - fetch_dollar|Dollar price (1326.1 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1326.1 KRW) has been updated.
2023-09-05 15:06:39,428 - update_dollar - INFO - fetch_dollar|Dollar price (1326.3 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1326.3 KRW) has been updated.
2023-09-05 15:07:10,656 - update_dollar - INFO - fetch_dollar|Dollar price (1326.3 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1326.3 KRW) has been updated.
2023-09-05 15:07:41,574 - update_dollar - INFO - fetch_dollar|Dollar price (1326.6 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1326.6 KRW) has been updated.
2023-09-05 15:08:12,665 - update_dollar - INFO - fetch_dollar|Dollar price (1326.6 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1326.6 KRW) has been updated.
2023-09-05 15:08:43,598 - update_dollar - INFO - fetch_dollar|Dollar price (1326.4 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1326.4 KRW) has been updated.
2023-09-05 15:09:14,466 - update_dollar - INFO - fetch_dollar|Dollar price (1326.4 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1326.4 KRW) has been updated.
2023-09-05 15:09:45,840 - update_dollar - INFO - fetch_dollar|Dollar price (1326.9 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1326.9 KRW) has been updated.
2023-09-05 15:10:16,786 - update_dollar - INFO - fetch_dollar|Dollar price (1326.9 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1326.9 KRW) has been updated.
2023-09-05 15:10:47,660 - update_dollar - INFO - fetch_dollar|Dollar price (1326.9 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1326.9 KRW) has been updated.
2023-09-05 15:11:18,594 - update_dollar - INFO - fetch_dollar|Dollar price (1326.7 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1326.7 KRW) has been updated.
2023-09-05 15:11:49,488 - update_dollar - INFO - fetch_dollar|Dollar price (1326.7 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1326.7 KRW) has been updated.
2023-09-05 15:12:20,718 - update_dollar - INFO - fetch_dollar|Dollar price (1326.9 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1326.9 KRW) has been updated.
2023-09-05 15:12:51,692 - update_dollar - INFO - fetch_dollar|Dollar price (1326.9 KRW) has been updated.

In [100]:
binance_ticker_df = pd.DataFrame(dict(core.exchange_websocket_dict['BINANCE_USD_M'].ticker_dict)).T.reset_index(drop=True)[['s','P','c','v','q']]
binance_ticker_df.rename(columns={"q": "atp24h", 'P': 'scr', 'c': 'tp'}, inplace=True)
binance_bookticker_df = pd.DataFrame(dict(core.exchange_websocket_dict['BINANCE_USD_M'].bookticker_dict)).T.reset_index(drop=True)[['s','b','a']]
binance_bookticker_df.rename(columns={"b": "bp", "a": "ap"}, inplace=True)
binance_merged_df = pd.merge(binance_ticker_df, binance_bookticker_df, on='s', how='inner')
binance_merged_df.loc[:, ['scr','tp','atp24h','ap','bp']] = binance_merged_df[['scr','tp','atp24h','ap','bp']].astype(float)
binance_merged_df = binance_merged_df.merge(core.info_dict['binance_usdm_info_df'][['symbol','baseAsset','quoteAsset']], left_on='s', right_on='symbol', how='inner')
binance_merged_df.drop(['symbol', 's'], axis=1, inplace=True)
binance_merged_df.rename(columns={'baseAsset':"base_asset", 'quoteAsset':"quote_asset"}, inplace=True)
binance_merged_df

,scr,tp,v,atp24h,bp,ap,base_asset,quote_asset
0,-1.756,0.0207,287709803,5959985.40693,0.02069,0.0207,SKL,USDT
1,4.817,0.5135,50935593,25534478.5828,0.5132,0.5134,CTK,USDT
2,-1.514,0.000384,5168871832,1988910.744376,0.000384,0.000384,SPELL,USDT
3,1.652,0.00806,2312311372,18357268.598497,0.008058,0.008059,AMB,USDT
4,-0.262,0.6476,35195232.8,22684279.4569,0.6475,0.6476,KAVA,USDT
...,...,...,...,...,...,...,...,...
187,-2.315,0.006962,403413665,2822211.997952,0.006961,0.006962,IOST,USDT
188,-2.387,0.736,10460298.5,7685803.134,0.735,0.736,ALICE,USDT
189,-2.103,0.01117,407818129,4564656.93913,0.01117,0.01118,CELR,USDT
190,-1.085,0.01367,180976896,2467807.69218,0.01367,0.01368,IOTX,USDT
191,-0.605,3.286,3688006,12004942.394,3.286,3.287,ICP,USDT

2023-09-05 13:45:26,050 - update_dollar - INFO - fetch_dollar|Dollar price (1324.3 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.3 KRW) has been updated.
2023-09-05 13:45:56,944 - update_dollar - INFO - fetch_dollar|Dollar price (1324.3 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.3 KRW) has been updated.
2023-09-05 13:46:27,894 - update_dollar - INFO - fetch_dollar|Dollar price (1324.3 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.3 KRW) has been updated.
2023-09-05 13:46:58,846 - update_dollar - INFO - fetch_dollar|Dollar price (1324.3 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.3 KRW) has been updated.
2023-09-05 13:47:29,741 - update_dollar - INFO - fetch_dollar|Dollar price (1324.4 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.4 KRW) has been updated.
2023-09-05 13:48:00,881 - update_dollar - INFO - fetch_dollar|Dollar price (1324.4 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.4 KRW) has been updated.
2023-09-05 13:48:31,921 - update_dollar - INFO - fetch_dollar|Dollar price (1324.4 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.4 KRW) has been updated.
2023-09-05 13:49:02,893 - update_dollar - INFO - fetch_dollar|Dollar price (1324.4 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.4 KRW) has been updated.
2023-09-05 13:49:33,674 - update_dollar - INFO - fetch_dollar|Dollar price (1324.8 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.8 KRW) has been updated.
2023-09-05 13:50:04,569 - update_dollar - INFO - fetch_dollar|Dollar price (1324.8 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.8 KRW) has been updated.
2023-09-05 13:50:35,723 - update_dollar - INFO - fetch_dollar|Dollar price (1324.8 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.8 KRW) has been updated.
2023-09-05 13:51:06,816 - update_dollar - INFO - fetch_dollar|Dollar price (1324.8 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.8 KRW) has been updated.
2023-09-05 13:51:37,890 - update_dollar - INFO - fetch_dollar|Dollar price (1324.8 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.8 KRW) has been updated.
2023-09-05 13:52:09,364 - update_dollar - INFO - fetch_dollar|Dollar price (1324.8 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.8 KRW) has been updated.
2023-09-05 13:52:40,344 - update_dollar - INFO - fetch_dollar|Dollar price (1324.8 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.8 KRW) has been updated.
2023-09-05 13:53:11,307 - update_dollar - INFO - fetch_dollar|Dollar price (1324.8 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.8 KRW) has been updated.
2023-09-05 13:53:42,376 - update_dollar - INFO - fetch_dollar|Dollar price (1324.8 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.8 KRW) has been updated.
2023-09-05 13:54:13,347 - update_dollar - INFO - fetch_dollar|Dollar price (1324.8 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.8 KRW) has been updated.
2023-09-05 13:54:44,378 - update_dollar - INFO - fetch_dollar|Dollar price (1324.6 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.6 KRW) has been updated.
2023-09-05 13:55:15,763 - update_dollar - INFO - fetch_dollar|Dollar price (1324.6 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.6 KRW) has been updated.
2023-09-05 13:55:46,735 - update_dollar - INFO - fetch_dollar|Dollar price (1324.6 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.6 KRW) has been updated.
2023-09-05 13:56:18,171 - update_dollar - INFO - fetch_dollar|Dollar price (1324.4 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.4 KRW) has been updated.
2023-09-05 13:56:48,966 - update_dollar - INFO - fetch_dollar|Dollar price (1324.4 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.4 KRW) has been updated.
2023-09-05 13:57:20,291 - update_dollar - INFO - fetch_dollar|Dollar price (1324.4 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.4 KRW) has been updated.
2023-09-05 13:57:51,342 - update_dollar - INFO - fetch_dollar|Dollar price (1324.2 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.2 KRW) has been updated.
2023-09-05 13:58:22,221 - update_dollar - INFO - fetch_dollar|Dollar price (1324.2 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.2 KRW) has been updated.
2023-09-05 13:58:53,226 - update_dollar - INFO - fetch_dollar|Dollar price (1324.2 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.2 KRW) has been updated.
2023-09-05 13:59:24,411 - update_dollar - INFO - fetch_dollar|Dollar price (1324.2 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.2 KRW) has been updated.
2023-09-05 13:59:55,405 - update_dollar - INFO - fetch_dollar|Dollar price (1324.2 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.2 KRW) has been updated.
2023-09-05 14:00:26,225 - update_dollar - INFO - fetch_dollar|Dollar price (1324.2 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.2 KRW) has been updated.
2023-09-05 14:00:57,029 - update_dollar - INFO - fetch_dollar|Dollar price (1324.2 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.2 KRW) has been updated.
2023-09-05 14:01:28,506 - update_dollar - INFO - fetch_dollar|Dollar price (1324.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.0 KRW) has been updated.
2023-09-05 14:01:59,478 - update_dollar - INFO - fetch_dollar|Dollar price (1324.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.0 KRW) has been updated.
2023-09-05 14:02:30,544 - update_dollar - INFO - fetch_dollar|Dollar price (1324.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.0 KRW) has been updated.
2023-09-05 14:03:01,463 - update_dollar - INFO - fetch_dollar|Dollar price (1324.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.0 KRW) has been updated.
2023-09-05 14:03:32,610 - update_dollar - INFO - fetch_dollar|Dollar price (1323.7 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1323.7 KRW) has been updated.
2023-09-05 14:04:03,708 - update_dollar - INFO - fetch_dollar|Dollar price (1323.7 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1323.7 KRW) has been updated.
2023-09-05 14:04:34,625 - update_dollar - INFO - fetch_dollar|Dollar price (1323.9 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1323.9 KRW) has been updated.
2023-09-05 14:05:05,581 - update_dollar - INFO - fetch_dollar|Dollar price (1323.9 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1323.9 KRW) has been updated.
2023-09-05 14:05:36,607 - update_dollar - INFO - fetch_dollar|Dollar price (1323.8 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1323.8 KRW) has been updated.
2023-09-05 14:06:07,476 - update_dollar - INFO - fetch_dollar|Dollar price (1323.8 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1323.8 KRW) has been updated.
2023-09-05 14:06:38,413 - update_dollar - INFO - fetch_dollar|Dollar price (1323.6 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1323.6 KRW) has been updated.
2023-09-05 14:07:09,204 - update_dollar - INFO - fetch_dollar|Dollar price (1323.6 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1323.6 KRW) has been updated.
2023-09-05 14:07:40,310 - update_dollar - INFO - fetch_dollar|Dollar price (1323.8 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1323.8 KRW) has been updated.
2023-09-05 14:08:11,266 - update_dollar - INFO - fetch_dollar|Dollar price (1323.8 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1323.8 KRW) has been updated.
2023-09-05 14:08:42,188 - update_dollar - INFO - fetch_dollar|Dollar price (1324.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.0 KRW) has been updated.
2023-09-05 14:09:13,196 - update_dollar - INFO - fetch_dollar|Dollar price (1324.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.0 KRW) has been updated.
2023-09-05 14:09:44,161 - update_dollar - INFO - fetch_dollar|Dollar price (1324.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.0 KRW) has been updated.
2023-09-05 14:10:15,598 - update_dollar - INFO - fetch_dollar|Dollar price (1324.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.0 KRW) has been updated.
2023-09-05 14:10:46,443 - update_dollar - INFO - fetch_dollar|Dollar price (1324.2 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.2 KRW) has been updated.
2023-09-05 14:11:17,451 - update_dollar - INFO - fetch_dollar|Dollar price (1324.2 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1324.2 KRW) has been updated.

In [99]:
binance_ticker_df = pd.DataFrame(dict(core.exchange_websocket_dict['BINANCE_COIN_M'].ticker_dict)).T.reset_index(drop=True)[['s','P','c','v','q']]
binance_ticker_df.rename(columns={"q": "atp24h", 'P': 'scr', 'c': 'tp'}, inplace=True)
binance_bookticker_df = pd.DataFrame(dict(core.exchange_websocket_dict['BINANCE_COIN_M'].bookticker_dict)).T.reset_index(drop=True)[['s','b','a']]
binance_bookticker_df.rename(columns={"b": "bp", "a": "ap"}, inplace=True)
binance_merged_df = pd.merge(binance_ticker_df, binance_bookticker_df, on='s', how='inner')
binance_merged_df.loc[:, ['scr','tp','atp24h','ap','bp']] = binance_merged_df[['scr','tp','atp24h','ap','bp']].astype(float)
binance_merged_df = binance_merged_df.merge(core.info_dict['binance_coinm_info_df'][['symbol','baseAsset','quoteAsset']], left_on='s', right_on='symbol', how='inner')
binance_merged_df.drop(['symbol', 's'], axis=1, inplace=True)
binance_merged_df.rename(columns={'baseAsset':"base_asset", 'quoteAsset':"quote_asset"}, inplace=True)
binance_merged_df

,scr,tp,v,atp24h,bp,ap,base_asset,quote_asset
0,-3.272,4.316,228789,519428.967339,4.316,4.317,UNI,USD
1,-1.05,1620.71,35470006,218237.507201,1620.71,1620.72,ETH,USD
2,-2.019,5.97,835429,1385571.01292,5.969,5.97,LINK,USD
3,-2.172,6.712,168723,249185.956446,6.71,6.711,ATOM,USD
4,1.925,0.5242,35410,689412.801392,0.524,0.5241,KNC,USD
5,-1.153,25683.7,7298775,28302.55886,25683.6,25683.7,BTC,USD
6,4.998,0.12837,587124,47422365.348047,0.12828,0.12834,XLM,USD
7,-2.411,1.336,118778,884734.365993,1.335,1.336,APE,USD
8,-2.441,1.3188,364090,2736477.480695,1.3183,1.3184,OP,USD
9,-0.615,1.454,69649,481749.088273,1.453,1.454,RUNE,USD
10,-0.918,0.5071,3615601,71687040.449097,0.5071,0.5072,XRP,USD
11,-0.06,24.918,57343,23103.309942,24.902,24.903,EGLD,USD
12,-2.521,0.2011,136336,6722512.587048,0.201,0.2011,FTM,USD
13,-0.838,140.77,52875,3728.298225,140.72,140.75,XMR,USD
14,-2.856,19.251,1701077,874971.589083,19.247,19.248,SOL,USD
15,0.065,0.0772,125692,16318362.233879,0.0772,0.07721,TRX,USD
16,-1.782,5.456,129719,236289.152549,5.455,5.456,APT,USD
17,1.263,0.5531,436614,7959125.140232,0.553,0.5531,MATIC,USD
18,-1.824,3.176,826168,2597979.517229,3.175,3.176,FIL,USD
19,-0.51,214.46,1779491,82850.336005,214.46,214.47,BNB,USD
20,-0.158,0.06335,1183702,187857340.659162,0.06334,0.06335,DOGE,USD
21,-1.342,0.1544,40666,2631155.355704,0.1543,0.1544,GMT,USD
22,-2.62,192.17,1188580,61599.758533,192.16,192.17,BCH,USD
23,-0.35,0.2566,581870,22743957.418856,0.2565,0.2566,ADA,USD
24,-1.119,0.2915,53302,1830435.419518,0.2915,0.2916,MANA,USD
25,-0.862,4.484,46605,104136.952863,4.484,4.485,AXS,USD
26,-1.257,15.234,367348,240225.699291,15.232,15.233,ETC,USD
27,-1.177,54.59,56594,10355.061013,54.58,54.59,AAVE,USD
28,-1.862,63.25,1578168,248021.693989,63.23,63.24,LTC,USD
29,-1.098,4.235,563389,1330259.558496,4.232,4.233,DOT,USD
30,-1.754,1.12,195877,1740827.511813,1.119,1.12,NEAR,USD
31,-2.209,9.74,162562,166057.859841,9.73,9.74,AVAX,USD
32,-1.499,0.3023,59802,1971919.340966,0.3022,0.3023,SAND,USD
33,-1.435,0.03983,21688,5443437.965992,0.03978,0.03979,ROSE,USD
34,-1.616,0.609,18508,303983.388853,0.609,0.61,THETA,USD
35,0.817,7.53,36351,48333.522172,7.527,7.533,ENS,USD
36,-1.365,0.578,318001,5501124.694032,0.578,0.579,EOS,USD
37,-1.572,0.0939,38466,4111248.005481,0.0939,0.094,ALGO,USD
38,-1.664,0.0591,22986,3862029.868249,0.0591,0.0592,CHZ,USD
39,-2.031,0.1592,6541,409814.66083,0.1593,0.1594,ICX,USD
40,-0.935,0.6884,5331,76926.968874,0.6886,0.6888,XTZ,USD