In [43]:
from threading import Thread
from multiprocessing import Process, Manager
import os
import json
import sys
import argparse
import datetime
import pandas as pd
from info_core import InitCore
# from exchange_plugin.common_info import InitCommonInfo
# from monitor_engine.kimp_core_monitor import InitKimpCoreMonitor
# from etc.db_handler.create_schema_tables import InitDBClient
# from trigger_engine.snatcher import InitSnatcher
from etc.register_monitor_msg import RegisterMonitorMsg
from etc.redis_connector.redis_connector import InitRedis
import _pickle as pickle
import time
import traceback

# for jupyter notebook
import nest_asyncio
nest_asyncio.apply()

In [2]:
redis_cli = InitRedis()

In [3]:
temp = pickle.loads(redis_cli.get_data('INFO_CORE|UPBIT_SPOT/KRW:BITHUMB_SPOT/KRW_1T_now'))
tempexit

TypeError: a bytes-like object is required, not 'NoneType'

In [2]:
logging_dir = "/home/info_core/"
with open("/home/info_core/info_core_config.json") as f:
    config = json.load(f)
proc_n = 3
# node = config['node']
node = 'info_core_dev'
monitor_bot_name = config['monitor_setting']['monitor_bot']
monitor_bot_token = config['telegram_bot_setting'][monitor_bot_name]
monitor_bot_api_url = config['monitor_setting']['monitor_bot_api_url']
admin_id = config['telegram_admin_id']['charlie1155']
register_monitor_msg = RegisterMonitorMsg(monitor_bot_token, monitor_bot_api_url, admin_id, logging_dir)
master_flag = config['node_settings'][node]['MASTER']
# Read api keys
exchange_api_key_dict = config['exchange_api_key']
# Exchange market settings
enabled_market_klines = config['node_settings'][node]['enabled_market_klines']
# total enabled market settings
total_enabled_market_klines = []
for each_market_code_list in config['node_settings'].values():
    total_enabled_market_klines += each_market_code_list['enabled_market_klines']
total_enabled_market_klines = list(set(total_enabled_market_klines))

# db dict
db_dict = config['database_setting'][config['node_settings'][node]['db_settings']]

my_okx_demo_api_key = "bbb8a09a-6ea2-4686-add5-1095c918b7f4"
my_okx_demo_secret_key = "FBEAD86057449BAEC3FFA8A80CE76E4F"
my_okx_demo_passphrase = "121431Rn!!"

In [3]:
enabled_market_klines

['OKX_USD_M/USDT:OKX_COIN_M/USD']

In [4]:
core = InitCore(logging_dir, master_flag, proc_n, node, admin_id, register_monitor_msg, exchange_api_key_dict, enabled_market_klines, total_enabled_market_klines, db_dict)

2023-12-18 08:24:12,603 - info_core - INFO - InitCore|InitCore initiated with proc_n=3
2023-12-18 08:24:13,080 - okx_plug - INFO - okx_plug_logger started.
2023-12-18 08:24:13,424 - upbit_plug - INFO - upbit_plug_logger started.
2023-12-18 08:24:13,521 - update_dollar - INFO - fetch_dollar|Dollar price (1299.5 KRW) has been updated.
2023-12-18 08:24:13,569 - binance_plug - INFO - binance_plug_logger started.
2023-12-18 08:24:13,570 - bithumb_plug - INFO - bithumb_plug_logger started.
2023-12-18 08:24:13,571 - bybit_plug - INFO - bybit_plug_logger started.
2023-12-18 08:24:13,571 - info_core - INFO - InitCore|update_upbit_spot_info_df thread has started.
2023-12-18 08:24:13,574 - info_core - INFO - InitCore|update_upbit_spot_ticker_df thread has started.
2023-12-18 08:24:13,576 - info_core - INFO - InitCore|update_binance_spot_ticker_df thread has started.
2023-12-18 08:24:13,578 - info_core - INFO - InitCore|update_binance_spot_info_df thread has started.
2023-12-18 08:24:13,580 - info_core - INFO - InitCore|update_binance_usd_m_ticker_df thread has started.
2023-12-18 08:24:13,582 - info_core - INFO - InitCore|update_binance_usd_m_info_df thread has started.
2023-12-18 08:24:13,584 - info_core - INFO - InitCore|update_binance_coin_m_ticker_df thread has started.
2023-12-18 08:24:13,586 - info_core - INFO - InitCore|update_binance_coin_m_info_df thread has started.
2023-12-18 08:24:13,587 - info_core - INFO - InitCore|update_okx_spot_ticker_df thread has started.
2023-12-18 08:24:13,589 - info_core - INFO - InitCore|update_okx_spot_info_df thread has started.
2023-12-18 08:24:13,590 - info_core - INFO - InitCore|update_okx_usd_m_ticker_df thread has started.
2023-12-18 08:24:13,592 - info_core - INFO - InitCore|update_okx_usd_m_info_df thread has started.
2023-12-18 08:24:13,594 - info_core - INFO - InitCore|update_okx_coin_m_ticker_df thread has started.
2023-12-18 08:24:13,595 - info_core - INFO - InitCore|update_okx_coin_m_info_df thread has started.
2023-12-18 08:24:13,596 - info_core - INFO - InitCore|update_bithumb_spot_info_df thread has started.
2023-12-18 08:24:13,598 - info_core - INFO - InitCore|update_bithumb_spot_ticker_df thread has started.
2023-12-18 08:24:13,601 - info_core - INFO - InitCore|update_bybit_spot_info_df thread has started.
2023-12-18 08:24:13,607 - info_core - INFO - InitCore|update_bybit_spot_ticker_df thread has started.
2023-12-18 08:24:13,670 - info_core - INFO - InitCore|update_bybit_usd_m_info_df thread has started.
2023-12-18 08:24:13,672 - info_core - INFO - InitCore|update_bybit_usd_m_ticker_df thread has started.
2023-12-18 08:24:13,675 - info_core - INFO - InitCore|update_bybit_coin_m_info_df thread has started.
2023-12-18 08:24:13,677 - info_core - INFO - InitCore|update_bybit_coin_m_ticker_df thread has started.
2023-12-18 08:24:13,679 - info_core - INFO - InitCore|Waiting for all info to be updated.
2023-12-18 08:24:13,733 - info_core - INFO - update_exchange_info_as_df|name:upbit_spot_info_df has been updated. (0.16 secs), error_count:0
2023-12-18 08:24:14,051 - info_core - INFO - update_exchange_info_as_df|name:okx_spot_info_df has been updated. (0.46 secs), error_count:0
2023-12-18 08:24:14,066 - info_core - INFO - update_exchange_info_as_df|name:bybit_coin_m_info_df has been updated. (0.39 secs), error_count:0
2023-12-18 08:24:14,111 - info_core - INFO - update_exchange_info_as_df|name:bybit_coin_m_ticker_df has been updated. (0.43 secs), error_count:0
2023-12-18 08:24:14,189 - info_core - INFO - update_exchange_info_as_df|name:binance_coin_m_ticker_df has been updated. (0.60 secs), error_count:0
2023-12-18 08:24:14,222 - info_core - INFO - update_exchange_info_as_df|name:upbit_spot_ticker_df has been updated. (0.65 secs), error_count:0
2023-12-18 08:24:14,399 - info_core - INFO - update_exchange_info_as_df|name:binance_coin_m_info_df has been updated. (0.81 secs), error_count:0
2023-12-18 08:24:14,672 - info_core - INFO - update_exchange_info_as_df|name:okx_coin_m_info_df has been updated. (1.08 secs), error_count:0
2023-12-18 08:24:14,770 - info_core - INFO - update_exchange_info_as_df|name:binance_usd_m_info_df has been updated. (1.19 secs), error_count:0
2023-12-18 08:24:14,841 - info_core - INFO - update_exchange_info_as_df|name:okx_usd_m_info_df has been updated. (1.25 secs), error_count:0
2023-12-18 08:24:14,857 - info_core - INFO - update_exchange_info_as_df|name:bithumb_spot_info_df has been updated. (1.26 secs), error_count:0
2023-12-18 08:24:14,908 - info_core - INFO - update_exchange_info_as_df|name:bybit_spot_info_df has been updated. (1.30 secs), error_count:0
2023-12-18 08:24:15,077 - info_core - INFO - update_exchange_info_as_df|name:bithumb_spot_ticker_df has been updated. (1.48 secs), error_count:0
2023-12-18 08:24:15,344 - info_core - INFO - update_exchange_info_as_df|name:bybit_usd_m_info_df has been updated. (1.67 secs), error_count:0
2023-12-18 08:24:15,419 - info_core - INFO - update_exchange_info_as_df|name:okx_spot_ticker_df has been updated. (1.83 secs), error_count:0
2023-12-18 08:24:15,809 - bybit_plug - INFO - self.info_dict is None or self.info_dict.get('bybit_spot_info_df') is None, Fetched from API
2023-12-18 08:24:15,812 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_usd_m_info_df') is None, Fetched from API
2023-12-18 08:24:15,634 - info_core - INFO - update_exchange_info_as_df|name:okx_coin_m_ticker_df has been updated. (2.04 secs), error_count:0
2023-12-18 08:24:15,695 - info_core - INFO - InitCore|Waiting for all info to be updated.
2023-12-18 08:24:15,962 - bybit_plug - INFO - self.info_dict is None or self.info_dict.get('bybit_usd_m_info_df') is None, Fetched from API
2023-12-18 08:24:15,833 - info_core - INFO - update_exchange_info_as_df|name:okx_usd_m_ticker_df has been updated. (2.24 secs), error_count:0
2023-12-18 08:24:16,043 - info_core - INFO - update_exchange_info_as_df|name:bybit_spot_ticker_df has been updated. (2.38 secs), error_count:0
2023-12-18 08:24:16,119 - info_core - INFO - update_exchange_info_as_df|name:bybit_usd_m_ticker_df has been updated. (2.45 secs), error_count:0
2023-12-18 08:24:16,135 - info_core - INFO - update_exchange_info_as_df|name:binance_spot_info_df has been updated. (2.56 secs), error_count:0
2023-12-18 08:24:17,254 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-12-18 08:24:17,329 - info_core - INFO - update_exchange_info_as_df|name:binance_spot_ticker_df has been updated. (3.75 secs), error_count:0
2023-12-18 08:24:17,332 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_ticker_df') is None, Fetched from API
2023-12-18 08:24:17,338 - info_core - INFO - update_exchange_info_as_df|name:binance_usd_m_ticker_df has been updated. (3.76 secs), error_count:0
2023-12-18 08:24:17,971 - info_core - INFO - InitCore|All info df has been updated.
2023-12-18 08:24:18,024 - okx_usd_m_websocket - INFO - 1th Okx ticker websocket does not exist. starting..
2023-12-18 08:24:18,026 - okx_usd_m_websocket - INFO - okx_ticker_websocket|1th okx_ticker_proc started.
2023-12-18 08:24:18,028 - okx_usd_m_websocket - INFO - [OKX USD_M]waiting for websocket data to be loaded..
2023-12-18 08:24:18,422 - okx_usd_m_websocket - INFO - okx_websocket|okx_websocket started
2023-12-18 08:24:18,539 - okx_usd_m_websocket - INFO - 2th Okx ticker websocket does not exist. starting..
2023-12-18 08:24:18,540 - okx_usd_m_websocket - INFO - okx_ticker_websocket|2th okx_ticker_proc started.
2023-12-18 08:24:18,956 - okx_usd_m_websocket - INFO - okx_websocket|okx_websocket started
2023-12-18 08:24:19,069 - okx_usd_m_websocket - INFO - 3th Okx ticker websocket does not exist. starting..
2023-12-18 08:24:19,070 - okx_usd_m_websocket - INFO - okx_ticker_websocket|3th okx_ticker_proc started.
2023-12-18 08:24:19,463 - okx_usd_m_websocket - INFO - okx_websocket|okx_websocket started
2023-12-18 08:24:20,040 - okx_usd_m_websocket - INFO - [OKX USD_M]started monitor_shared_symbol_change..
2023-12-18 08:24:20,042 - okx_usd_m_websocket - INFO - [OKX USD_M]started monitor_websocket_last_update..
2023-12-18 08:24:20,089 - okx_coin_m_websocket - INFO - 1th Okx ticker websocket does not exist. starting..
2023-12-18 08:24:20,091 - okx_coin_m_websocket - INFO - okx_ticker_websocket|1th okx_ticker_proc started.
2023-12-18 08:24:20,093 - okx_coin_m_websocket - INFO - [OKX COIN_M]waiting for websocket data to be loaded..
2023-12-18 08:24:20,093 - okx_coin_m_websocket - INFO - [OKX COIN_M]waiting for websocket data to be loaded..
2023-12-18 08:24:20,480 - okx_coin_m_websocket - INFO - okx_websocket|okx_websocket started
2023-12-18 08:24:20,604 - okx_coin_m_websocket - INFO - 2th Okx ticker websocket does not exist. starting..
2023-12-18 08:24:20,605 - okx_coin_m_websocket - INFO - okx_ticker_websocket|2th okx_ticker_proc started.
2023-12-18 08:24:20,989 - okx_coin_m_websocket - INFO - okx_websocket|okx_websocket started
2023-12-18 08:24:21,115 - okx_coin_m_websocket - INFO - 3th Okx ticker websocket does not exist. starting..
2023-12-18 08:24:21,117 - okx_coin_m_websocket - INFO - okx_ticker_websocket|3th okx_ticker_proc started.
2023-12-18 08:24:21,505 - okx_coin_m_websocket - INFO - okx_websocket|okx_websocket started
2023-12-18 08:24:22,107 - okx_coin_m_websocket - INFO - [OKX COIN_M]started monitor_shared_symbol_change..
2023-12-18 08:24:22,109 - okx_coin_m_websocket - INFO - [OKX COIN_M]started monitor_websocket_last_update..
2023-12-18 08:24:22,109 - info_core - INFO - InitCore|exchange_websocket_dict, dict_keys(['OKX_USD_M', 'OKX_COIN_M']) has been initiated.
2023-12-18 08:24:32,127 - arbitrage_core - INFO - InitArbitrageCore Started.
2023-12-18 08:24:32,131 - info_core - INFO - update_fundingrate|BINANCE update_fundingrate thread has started.
2023-12-18 08:24:32,132 - info_core - INFO - update_fundingrate|OKX update_fundingrate thread has started.
2023-12-18 08:24:32,143 - arbitrage_core - INFO - store_funding_diff_loop started.
2023-12-18 08:24:32,151 - kline_core - INFO - InitKlineCore started.
2023-12-18 08:24:32,132 - info_core - INFO - update_fundingrate|BYBIT update_fundingrate thread has started.
2023-12-18 08:24:32,133 - info_core - INFO - update_wallet_status|UPBIT update_wallet_status thread has started.
2023-12-18 08:24:32,133 - info_core - INFO - update_wallet_status|BINANCE update_wallet_status thread has started.
2023-12-18 08:24:32,133 - info_core - INFO - update_wallet_status|OKX update_wallet_status thread has started.
2023-12-18 08:24:32,133 - info_core - INFO - update_wallet_status|BITHUMB update_wallet_status thread has started.
2023-12-18 08:24:32,133 - info_core - INFO - update_wallet_status|BYBIT update_wallet_status thread has started.
2023-12-18 08:24:32,153 - arbitrage_core - INFO - store_average_funding_rate_loop started.
2023-12-18 08:24:32,157 - kline_core - INFO - register_enabled_market_klines|Registering enabled market klines:['OKX_USD_M/USDT:OKX_COIN_M/USD'] to redis Started..
2023-12-18 08:24:33,256 - arbitrage_core - INFO - store_funding_diff took 1.1061251163482666 seconds.
2023-12-18 08:24:33,584 - kline_core - INFO - ohlc_min_resample_loader has started. OKX_USD_M/USDT:OKX_COIN_M/USD_5T_kline, initial generating and storing resampled_ohlc_history_df(length: 18018): 0.39884448051452637
2023-12-18 08:24:34,100 - kline_core - INFO - resampling ohlc_df(length: 9900): 0.4022526741027832
2023-12-18 08:24:34,103 - kline_core - INFO - redis saving OKX_USD_M/USDT:OKX_COIN_M/USD_5T_kline time: 0.002125978469848633
2023-12-18 08:24:34,104 - kline_core - INFO - redis publishing OKX_USD_M/USDT:OKX_COIN_M/USD_5T_kline time: 0.00024366378784179688
2023-12-18 08:24:34,382 - kline_core - INFO - insert_kline_to_db|database: OKX_USD_M/USDT:OKX_COIN_M/USD, Filtering 11 klines for 11 unique base_assets took 0.14232969284057617 seconds
2023-12-18 08:24:34,386 - kline_core - INFO - insert_kline_to_db|database: OKX_USD_M/USDT:OKX_COIN_M/USD, Inserting 11 klines for 11 unique base_assets took 0.03449845314025879 seconds
2023-12-18 08:24:34,387 - kline_core - INFO - insert_kline_to_db|channel_name: INFO_CORE|OKX_USD_M/USDT:OKX_COIN_M/USD_5T_kline, Inserting 11 klines for 11 unique base_assets took 0.28058385848999023 seconds
2023-12-18 08:24:34,592 - kline_core - INFO - ohlc_min_resample_loader has started. OKX_USD_M/USDT:OKX_COIN_M/USD_15T_kline, initial generating and storing resampled_ohlc_history_df(length: 2222): 0.39454030990600586
2023-12-18 08:24:34,791 - kline_core - INFO - resampling ohlc_df(length: 9900): 0.5710394382476807
2023-12-18 08:24:34,794 - kline_core - INFO - redis saving OKX_USD_M/USDT:OKX_COIN_M/USD_5T_kline time: 0.0020804405212402344
2023-12-18 08:24:34,795 - kline_core - INFO - redis publishing OKX_USD_M/USDT:OKX_COIN_M/USD_5T_kline time: 0.00017142295837402344
2023-12-18 08:24:34,812 - kline_core - INFO - OKX_USD_M/USDT:OKX_COIN_M/USD_5T_kline base_asset is not matched. added: [], removed: ['AVAX', 'BCH', 'BTC', 'EOS', 'LINK', 'NEO', 'SUSHI', 'THETA', 'XRP', 'YFI', 'ZEC']
2023-12-18 08:24:34,818 - kline_core - INFO - resampled_ohlc_history_df has been overwritten. removed_list: ['AVAX', 'BCH', 'BTC', 'EOS', 'LINK', 'NEO', 'SUSHI', 'THETA', 'XRP', 'YFI', 'ZEC']
2023-12-18 08:24:35,056 - kline_core - INFO - resampling ohlc_df(length: 3333): 0.3553290367126465
2023-12-18 08:24:35,059 - kline_core - INFO - redis saving OKX_USD_M/USDT:OKX_COIN_M/USD_15T_kline time: 0.0012853145599365234
2023-12-18 08:24:35,059 - kline_core - INFO - redis publishing OKX_USD_M/USDT:OKX_COIN_M/USD_15T_kline time: 0.00023055076599121094
2023-12-18 08:24:35,063 - okx_usd_m_websocket - INFO - monitor_websocket_last_update|1th_ticker_proc has no ticker_dict data. Restarting websocket..
2023-12-18 08:24:35,411 - info_core - INFO - update_wallet_status|UPBIT update_wallet_status took 3.257375478744507 secs, read_time: 0.22736763954162598, write_time: 2.127814769744873, calculate_time: 0, api_time: 0.8743109703063965
2023-12-18 08:24:35,504 - kline_core - INFO - resampling ohlc_df(length: 3333): 0.2292799949645996
2023-12-18 08:24:35,505 - kline_core - INFO - redis saving OKX_USD_M/USDT:OKX_COIN_M/USD_15T_kline time: 0.0010199546813964844
2023-12-18 08:24:35,506 - kline_core - INFO - redis publishing OKX_USD_M/USDT:OKX_COIN_M/USD_15T_kline time: 0.0002086162567138672
2023-12-18 08:24:35,519 - kline_core - INFO - OKX_USD_M/USDT:OKX_COIN_M/USD_15T_kline base_asset is not matched. added: [], removed: ['AVAX', 'BCH', 'BTC', 'EOS', 'LINK', 'NEO', 'SUSHI', 'THETA', 'XRP', 'YFI', 'ZEC']
2023-12-18 08:24:35,524 - kline_core - INFO - resampled_ohlc_history_df has been overwritten. removed_list: ['AVAX', 'BCH', 'BTC', 'EOS', 'LINK', 'NEO', 'SUSHI', 'THETA', 'XRP', 'YFI', 'ZEC']
2023-12-18 08:24:35,535 - kline_core - INFO - ohlc_min_resample_loader has started. OKX_USD_M/USDT:OKX_COIN_M/USD_30T_kline, initial generating and storing resampled_ohlc_history_df(length: 1122): 0.33178257942199707
2023-12-18 08:24:35,610 - kline_core - INFO - insert_kline_to_db|database: OKX_USD_M/USDT:OKX_COIN_M/USD, Filtering 22 klines for 22 unique base_assets took 0.023612022399902344 seconds
2023-12-18 08:24:35,611 - kline_core - INFO - insert_kline_to_db|database: OKX_USD_M/USDT:OKX_COIN_M/USD, Inserting 22 klines for 22 unique base_assets took 0.03151226043701172 seconds
2023-12-18 08:24:35,611 - kline_core - INFO - insert_kline_to_db|channel_name: INFO_CORE|OKX_USD_M/USDT:OKX_COIN_M/USD_30T_kline, Inserting 22 klines for 22 unique base_assets took 0.07362246513366699 seconds
2023-12-18 08:24:35,868 - kline_core - INFO - resampling ohlc_df(length: 1122): 0.2286083698272705
2023-12-18 08:24:35,870 - kline_core - INFO - redis saving OKX_USD_M/USDT:OKX_COIN_M/USD_30T_kline time: 0.0005142688751220703
2023-12-18 08:24:35,870 - kline_core - INFO - redis publishing OKX_USD_M/USDT:OKX_COIN_M/USD_30T_kline time: 0.00014710426330566406
2023-12-18 08:24:35,879 - kline_core - INFO - OKX_USD_M/USDT:OKX_COIN_M/USD_30T_kline base_asset is not matched. added: ['AVAX', 'BCH', 'BTC', 'EOS', 'LINK', 'NEO', 'SUSHI', 'THETA', 'XRP', 'YFI', 'ZEC'], removed: []
2023-12-18 08:24:36,100 - okx_usd_m_websocket - INFO - okx_ticker_websocket|1th okx_ticker_proc terminated.
2023-12-18 08:24:36,110 - okx_usd_m_websocket - INFO - ticker_websocket|restarted 1th ticker websocket.. alive state: True
2023-12-18 08:24:36,463 - kline_core - INFO - ohlc_hour_resample_loader has started. OKX_USD_M/USDT:OKX_COIN_M/USD_1H_kline, initial generating and storing resampled_ohlc_history_df(length: 572): 0.2496781349182129
2023-12-18 08:24:36,511 - okx_usd_m_websocket - INFO - okx_websocket|okx_websocket started
2023-12-18 08:24:36,624 - info_core - INFO - update_fundingrate|BINANCE update_fundingrate took 4.48399019241333 secs, read_time: 1.2836074829101562, write_time: 2.362907648086548, calculate_time: 0.21645045280456543, api_time: 0.5655951499938965
2023-12-18 08:24:36,690 - info_core - INFO - update_fundingrate|BYBIT update_fundingrate took 4.540565729141235 secs, read_time: 1.145024061203003, write_time: 1.879335880279541, calculate_time: 0.3128659725189209, api_time: 1.1732466220855713

resampling ohlc_df(length: 572): 0.24990177154541016

2023-12-18 08:24:36,942 - kline_core - INFO - OKX_USD_M/USDT:OKX_COIN_M/USD_1H_kline base_asset is not matched. added: ['AVAX', 'BCH', 'BTC', 'EOS', 'LINK', 'NEO', 'SUSHI', 'THETA', 'XRP', 'YFI', 'ZEC'], removed: []
2023-12-18 08:24:37,473 - kline_core - INFO - ohlc_hour_resample_loader has started. OKX_USD_M/USDT:OKX_COIN_M/USD_4H_kline, initial generating and storing resampled_ohlc_history_df(length: 176): 0.25006771087646484

resampling ohlc_df(length: 176): 0.24282288551330566

2023-12-18 08:24:37,830 - kline_core - INFO - OKX_USD_M/USDT:OKX_COIN_M/USD_4H_kline base_asset is not matched. added: ['AVAX', 'BCH', 'BTC', 'EOS', 'LINK', 'NEO', 'SUSHI', 'THETA', 'XRP', 'YFI', 'ZEC'], removed: []

2023-12-18 08:24:38,557 - info_core - INFO - update_wallet_status|OKX update_wallet_status took 6.399652481079102 secs, read_time: 0.26213788986206055, write_time: 3.0188045501708984, calculate_time: 0, api_time: 3.084972381591797
2023-12-18 08:24:41,087 - kline_core - INFO - resampling ohlc_df(length: 3333): 0.4516103267669678
2023-12-18 08:24:41,089 - kline_core - INFO - redis saving OKX_USD_M/USDT:OKX_COIN_M/USD_15T_kline time: 0.0008413791656494141
2023-12-18 08:24:41,089 - kline_core - INFO - redis publishing OKX_USD_M/USDT:OKX_COIN_M/USD_15T_kline time: 0.00012755393981933594
2023-12-18 08:24:41,247 - kline_core - INFO - resampling ohlc_df(length: 1122): 0.25818467140197754
2023-12-18 08:24:41,248 - kline_core - INFO - redis saving OKX_USD_M/USDT:OKX_COIN_M/USD_30T_kline time: 0.0004639625549316406
2023-12-18 08:24:41,249 - kline_core - INFO - redis publishing OKX_USD_M/USDT:OKX_COIN_M/USD_30T_kline time: 0.00014519691467285156
2023-12-18 08:24:41,258 - kline_core - INFO - OKX_USD_M/USDT:OKX_COIN_M/USD_30T_kline base_asset is not matched. added: ['AVAX', 'BCH', 'BTC', 'EOS', 'LINK', 'NEO', 'SUSHI', 'THETA', 'XRP', 'YFI', 'ZEC'], removed: []

resampling ohlc_df(length: 572): 0.24746060371398926

2023-12-18 08:24:42,302 - kline_core - INFO - OKX_USD_M/USDT:OKX_COIN_M/USD_1H_kline base_asset is not matched. added: ['AVAX', 'BCH', 'BTC', 'EOS', 'LINK', 'NEO', 'SUSHI', 'THETA', 'XRP', 'YFI', 'ZEC'], removed: []

resampling ohlc_df(length: 176): 0.24631714820861816

2023-12-18 08:24:43,192 - kline_core - INFO - OKX_USD_M/USDT:OKX_COIN_M/USD_4H_kline base_asset is not matched. added: ['AVAX', 'BCH', 'BTC', 'EOS', 'LINK', 'NEO', 'SUSHI', 'THETA', 'XRP', 'YFI', 'ZEC'], removed: []
2023-12-18 08:24:43,816 - info_core - INFO - update_exchange_info_as_df|name:upbit_spot_info_df has been updated. (0.01 secs), error_count:0
2023-12-18 08:24:44,265 - info_core - INFO - update_exchange_info_as_df|name:okx_spot_info_df has been updated. (0.16 secs), error_count:0
2023-12-18 08:24:44,313 - info_core - ERROR - update_exchange_info_as_df|name:binance_coin_m_ticker_df, Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 454, in getresponse
    httplib_response = super().getresponse()
  File "/usr/local/lib/python3.9/http/client.py", line 1377, in getresponse
    response.begin()
  File "/usr/local/lib/python3.9/http/client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.9/http/client.py", line 289, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 454, in getresponse
    httplib_response = super().getresponse()
  File "/usr/local/lib/python3.9/http/client.py", line 1377, in getresponse
    response.begin()
  File "/usr/local/lib/python3.9/http/client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.9/http/client.py", line 289, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/info_core/info_core.py", line 293, in update_exchange_info_as_df
    self.info_dict[data_name] = self.binance_adaptor.coin_m_all_tickers()
  File "/home/info_core/exchange_plugin/binance_plug.py", line 98, in coin_m_all_tickers
    df = pd.DataFrame(self.pub_client.futures_coin_ticker())
  File "/usr/local/lib/python3.9/site-packages/binance/client.py", line 6803, in futures_coin_ticker
    return self._request_futures_coin_api("get", "ticker/24hr", data=params)
  File "/usr/local/lib/python3.9/site-packages/binance/client.py", line 393, in _request_futures_coin_api
    return self._request(method, uri, signed, True, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/binance/client.py", line 358, in _request
    self.response = getattr(self.session, method)(uri, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

2023-12-18 08:24:44,445 - info_core - INFO - update_exchange_info_as_df|name:bybit_coin_m_ticker_df has been updated. (0.20 secs), error_count:0
2023-12-18 08:24:44,528 - info_core - INFO - update_exchange_info_as_df|name:upbit_spot_ticker_df has been updated. (0.22 secs), error_count:0
2023-12-18 08:24:44,531 - info_core - INFO - update_exchange_info_as_df|name:bybit_coin_m_info_df has been updated. (0.38 secs), error_count:0
2023-12-18 08:24:44,536 - update_dollar - INFO - fetch_dollar|Dollar price (1299.5 KRW) has been updated.
2023-12-18 08:24:44,881 - info_core - ERROR - update_exchange_info_as_df|name:binance_usd_m_info_df, Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 454, in getresponse
    httplib_response = super().getresponse()
  File "/usr/local/lib/python3.9/http/client.py", line 1377, in getresponse
    response.begin()
  File "/usr/local/lib/python3.9/http/client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.9/http/client.py", line 289, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 454, in getresponse
    httplib_response = super().getresponse()
  File "/usr/local/lib/python3.9/http/client.py", line 1377, in getresponse
    response.begin()
  File "/usr/local/lib/python3.9/http/client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.9/http/client.py", line 289, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/info_core/info_core.py", line 291, in update_exchange_info_as_df
    self.info_dict[data_name] = self.binance_adaptor.usd_m_exchange_info()
  File "/home/info_core/exchange_plugin/binance_plug.py", line 57, in usd_m_exchange_info
    df = pd.DataFrame(self.pub_client.futures_exchange_info()['symbols'])
  File "/usr/local/lib/python3.9/site-packages/binance/client.py", line 6161, in futures_exchange_info
    return self._request_futures_api('get', 'exchangeInfo')
  File "/usr/local/lib/python3.9/site-packages/binance/client.py", line 383, in _request_futures_api
    return self._request(method, uri, signed, True, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/binance/client.py", line 358, in _request
    self.response = getattr(self.session, method)(uri, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

2023-12-18 08:24:44,932 - info_core - INFO - update_exchange_info_as_df|name:binance_coin_m_info_df has been updated. (0.19 secs), error_count:0
2023-12-18 08:24:45,034 - info_core - INFO - update_exchange_info_as_df|name:okx_coin_m_info_df has been updated. (0.27 secs), error_count:0
2023-12-18 08:24:45,213 - info_core - INFO - update_exchange_info_as_df|name:okx_usd_m_info_df has been updated. (0.26 secs), error_count:0
2023-12-18 08:24:45,800 - info_core - INFO - update_exchange_info_as_df|name:bybit_spot_info_df has been updated. (0.46 secs), error_count:0
2023-12-18 08:24:45,896 - info_core - INFO - update_exchange_info_as_df|name:bithumb_spot_info_df has been updated. (0.58 secs), error_count:0
2023-12-18 08:24:46,044 - info_core - INFO - update_exchange_info_as_df|name:bithumb_spot_ticker_df has been updated. (0.42 secs), error_count:0
2023-12-18 08:24:46,156 - info_core - INFO - update_exchange_info_as_df|name:okx_spot_ticker_df has been updated. (0.26 secs), error_count:0
2023-12-18 08:24:46,171 - info_core - INFO - update_exchange_info_as_df|name:okx_coin_m_ticker_df has been updated. (0.19 secs), error_count:0
2023-12-18 08:24:46,376 - info_core - INFO - update_exchange_info_as_df|name:okx_usd_m_ticker_df has been updated. (0.31 secs), error_count:0
2023-12-18 08:24:46,408 - info_core - INFO - update_exchange_info_as_df|name:bybit_usd_m_info_df has been updated. (0.62 secs), error_count:0
2023-12-18 08:24:46,747 - info_core - INFO - update_exchange_info_as_df|name:bybit_spot_ticker_df has been updated. (0.60 secs), error_count:0
2023-12-18 08:24:46,777 - info_core - INFO - update_exchange_info_as_df|name:binance_spot_info_df has been updated. (0.61 secs), error_count:0
2023-12-18 08:24:46,781 - info_core - INFO - update_exchange_info_as_df|name:bybit_usd_m_ticker_df has been updated. (0.61 secs), error_count:0
2023-12-18 08:24:46,816 - info_core - INFO - update_wallet_status|BINANCE update_wallet_status took 14.659924507141113 secs, read_time: 0.5588185787200928, write_time: 12.939040184020996, calculate_time: 0, api_time: 1.0411252975463867

resampling ohlc_df(length: 858): 0.36605143547058105

2023-12-18 08:24:47,897 - info_core - INFO - update_exchange_info_as_df|name:binance_usd_m_ticker_df has been updated. (0.53 secs), error_count:0
2023-12-18 08:24:47,907 - info_core - INFO - update_exchange_info_as_df|name:binance_spot_ticker_df has been updated. (0.55 secs), error_count:0

resampling ohlc_df(length: 264): 0.37563419342041016

2023-12-18 08:24:48,837 - info_core - INFO - update_wallet_status|BITHUMB update_wallet_status took 16.68201231956482 secs, read_time: 0.013160467147827148, write_time: 4.26763653755188, calculate_time: 0, api_time: 12.33250379562378
2023-12-18 08:24:55,418 - arbitrage_core - INFO - store_average_funding_rate took 23.263394117355347 seconds.
2023-12-18 08:24:58,718 - info_core - INFO - update_wallet_status|BYBIT update_wallet_status took 26.559138298034668 secs, read_time: 3.014350652694702, write_time: 22.661323308944702, calculate_time: 0, api_time: 0.8425107002258301
2023-12-18 08:25:00,446 - kline_core - INFO - resampling ohlc_df(length: 9900): 0.40354108810424805
2023-12-18 08:25:00,449 - kline_core - INFO - redis saving OKX_USD_M/USDT:OKX_COIN_M/USD_5T_kline time: 0.001975536346435547
2023-12-18 08:25:00,450 - kline_core - INFO - redis publishing OKX_USD_M/USDT:OKX_COIN_M/USD_5T_kline time: 0.0001964569091796875
2023-12-18 08:25:00,628 - kline_core - INFO - insert_kline_to_db|database: OKX_USD_M/USDT:OKX_COIN_M/USD, Filtering 30 klines for 30 unique base_assets took 0.2883644104003906 seconds
2023-12-18 08:25:00,636 - kline_core - INFO - insert_kline_to_db|database: OKX_USD_M/USDT:OKX_COIN_M/USD, Inserting 30 klines for 30 unique base_assets took 0.09732866287231445 seconds
2023-12-18 08:25:00,637 - kline_core - INFO - insert_kline_to_db|channel_name: INFO_CORE|OKX_USD_M/USDT:OKX_COIN_M/USD_1T_kline, Inserting 30 klines for 30 unique base_assets took 0.5735793113708496 seconds
2023-12-18 08:25:34,264 - arbitrage_core - INFO - store_funding_diff took 0.9510412216186523 seconds.
2023-12-18 08:25:35,856 - info_core - INFO - update_wallet_status|UPBIT update_wallet_status took 0.3780050277709961 secs, read_time: 0.004136085510253906, write_time: 0.23841285705566406, calculate_time: 0, api_time: 0.11919069290161133
2023-12-18 08:25:37,932 - info_core - INFO - update_fundingrate|BINANCE update_fundingrate took 1.2380340099334717 secs, read_time: 0.6066710948944092, write_time: 0.20968198776245117, calculate_time: 0.023118257522583008, api_time: 0.3678159713745117
2023-12-18 08:25:38,031 - info_core - INFO - update_fundingrate|BYBIT update_fundingrate took 1.2289361953735352 secs, read_time: 0.49399757385253906, write_time: 0.20810914039611816, calculate_time: 0.0326690673828125, api_time: 0.46540236473083496
2023-12-18 08:25:39,318 - info_core - INFO - update_wallet_status|OKX update_wallet_status took 0.6967949867248535 secs, read_time: 0.007891416549682617, write_time: 0.41997742652893066, calculate_time: 0, api_time: 0.24322795867919922
2023-12-18 08:25:48,515 - info_core - INFO - update_wallet_status|BINANCE update_wallet_status took 1.6365954875946045 secs, read_time: 0.022230863571166992, write_time: 1.375089168548584, calculate_time: 0, api_time: 0.1770012378692627
2023-12-18 08:25:49,357 - info_core - INFO - update_fundingrate|OKX update_fundingrate took 77.21527695655823 secs, read_time: 1.0496723651885986, write_time: 0.06264305114746094, calculate_time: 0.011460065841674805, api_time: 76.07800245285034
2023-12-18 08:25:53,851 - info_core - INFO - update_wallet_status|BITHUMB update_wallet_status took 4.945399522781372 secs, read_time: 0.005017757415771484, write_time: 0.23537421226501465, calculate_time: 0, api_time: 4.6878392696380615
2023-12-18 08:26:00,640 - kline_core - INFO - insert_kline_to_db|database: OKX_USD_M/USDT:OKX_COIN_M/USD, Filtering 27 klines for 27 unique base_assets took 0.3063228130340576 seconds
2023-12-18 08:26:00,646 - kline_core - INFO - insert_kline_to_db|database: OKX_USD_M/USDT:OKX_COIN_M/USD, Inserting 27 klines for 27 unique base_assets took 0.08173751831054688 seconds
2023-12-18 08:26:00,646 - kline_core - INFO - insert_kline_to_db|channel_name: INFO_CORE|OKX_USD_M/USDT:OKX_COIN_M/USD_1T_kline, Inserting 27 klines for 27 unique base_assets took 0.5384054183959961 seconds
2023-12-18 08:26:22,353 - info_core - INFO - update_wallet_status|BYBIT update_wallet_status took 23.573873281478882 secs, read_time: 1.9813892841339111, write_time: 21.124744176864624, calculate_time: 0, api_time: 0.4305732250213623
2023-12-18 08:26:35,319 - arbitrage_core - INFO - store_funding_diff took 1.0057201385498047 seconds.
2023-12-18 08:26:36,299 - info_core - INFO - update_wallet_status|UPBIT update_wallet_status took 0.38513946533203125 secs, read_time: 0.0042209625244140625, write_time: 0.23888182640075684, calculate_time: 0, api_time: 0.12536907196044922
2023-12-18 08:26:39,147 - info_core - INFO - update_fundingrate|BYBIT update_fundingrate took 1.067521572113037 secs, read_time: 0.29689526557922363, write_time: 0.2958345413208008, calculate_time: 0.03189802169799805, api_time: 0.40829992294311523
2023-12-18 08:26:39,179 - info_core - INFO - update_fundingrate|BINANCE update_fundingrate took 1.2181062698364258 secs, read_time: 0.4429957866668701, write_time: 0.29381251335144043, calculate_time: 0.029392719268798828, api_time: 0.40405893325805664
2023-12-18 08:26:40,088 - info_core - INFO - update_wallet_status|OKX update_wallet_status took 0.7103569507598877 secs, read_time: 0.007238626480102539, write_time: 0.4349558353424072, calculate_time: 0, api_time: 0.2418959140777588
2023-12-18 08:26:50,279 - info_core - INFO - update_wallet_status|BINANCE update_wallet_status took 1.7068760395050049 secs, read_time: 0.015031576156616211, write_time: 1.4790294170379639, calculate_time: 0, api_time: 0.14768576622009277
2023-12-18 08:26:58,871 - info_core - INFO - update_wallet_status|BITHUMB update_wallet_status took 4.961602210998535 secs, read_time: 0.002763986587524414, write_time: 0.24398303031921387, calculate_time: 0, api_time: 4.6979193687438965
2023-12-18 08:27:00,675 - kline_core - INFO - insert_kline_to_db|database: OKX_USD_M/USDT:OKX_COIN_M/USD, Filtering 28 klines for 14 unique base_assets took 0.27278709411621094 seconds
2023-12-18 08:27:00,676 - kline_core - INFO - insert_kline_to_db|database: OKX_USD_M/USDT:OKX_COIN_M/USD, Inserting 28 klines for 14 unique base_assets took 0.032733917236328125 seconds
2023-12-18 08:27:00,677 - kline_core - INFO - insert_kline_to_db|channel_name: INFO_CORE|OKX_USD_M/USDT:OKX_COIN_M/USD_1T_kline, Inserting 28 klines for 14 unique base_assets took 0.4960508346557617 seconds
2023-12-18 08:27:18,899 - arbitrage_core - INFO - store_average_funding_rate took 23.381556272506714 seconds.
2023-12-18 08:27:36,513 - arbitrage_core - INFO - store_funding_diff took 1.135596513748169 seconds.
2023-12-18 08:27:40,768 - info_core - INFO - update_wallet_status|UPBIT update_wallet_status took 4.368836879730225 secs, read_time: 0.04804515838623047, write_time: 4.160794496536255, calculate_time: 0, api_time: 0.1380019187927246
2023-12-18 08:27:44,054 - info_core - INFO - update_fundingrate|BYBIT update_fundingrate took 4.830979347229004 secs, read_time: 0.6596052646636963, write_time: 2.6663506031036377, calculate_time: 0.28861451148986816, api_time: 1.1868934631347656
2023-12-18 08:27:44,944 - info_core - INFO - update_fundingrate|BINANCE update_fundingrate took 5.6932055950164795 secs, read_time: 1.5080220699310303, write_time: 3.2750892639160156, calculate_time: 0.24740028381347656, api_time: 0.6286263465881348
2023-12-18 08:27:47,474 - info_core - INFO - update_wallet_status|OKX update_wallet_status took 7.173289060592651 secs, read_time: 0.16892385482788086, write_time: 4.534494400024414, calculate_time: 0, api_time: 2.432800054550171
2023-12-18 08:27:47,477 - info_core - INFO - update_wallet_status|BYBIT update_wallet_status took 25.062040090560913 secs, read_time: 1.7998511791229248, write_time: 22.74209713935852, calculate_time: 0, api_time: 0.48330068588256836
2023-12-18 08:27:52,005 - info_core - INFO - update_wallet_status|BINANCE update_wallet_status took 1.671858310699463 secs, read_time: 0.017032861709594727, write_time: 1.3331859111785889, calculate_time: 0, api_time: 0.2547414302825928
2023-12-18 08:28:00,721 - kline_core - INFO - insert_kline_to_db|database: OKX_USD_M/USDT:OKX_COIN_M/USD, Filtering 33 klines for 33 unique base_assets took 0.2821311950683594 seconds
2023-12-18 08:28:00,723 - kline_core - INFO - insert_kline_to_db|database: OKX_USD_M/USDT:OKX_COIN_M/USD, Inserting 33 klines for 33 unique base_assets took 0.10423970222473145 seconds
2023-12-18 08:28:00,724 - kline_core - INFO - insert_kline_to_db|channel_name: INFO_CORE|OKX_USD_M/USDT:OKX_COIN_M/USD_1T_kline, Inserting 33 klines for 33 unique base_assets took 0.5523853302001953 seconds
2023-12-18 08:28:04,731 - info_core - INFO - update_wallet_status|BITHUMB update_wallet_status took 5.817420721054077 secs, read_time: 0.003178119659423828, write_time: 0.25864076614379883, calculate_time: 0, api_time: 5.5375378131866455
2023-12-18 08:28:37,483 - arbitrage_core - INFO - store_funding_diff took 0.9337673187255859 seconds.
2023-12-18 08:28:41,245 - info_core - INFO - update_wallet_status|UPBIT update_wallet_status took 0.40908145904541016 secs, read_time: 0.004548311233520508, write_time: 0.24132800102233887, calculate_time: 0, api_time: 0.14647388458251953
2023-12-18 08:28:45,311 - info_core - INFO - update_fundingrate|BYBIT update_fundingrate took 1.1939897537231445 secs, read_time: 0.343186616897583, write_time: 0.3040146827697754, calculate_time: 0.05744528770446777, api_time: 0.44939160346984863
2023-12-18 08:28:45,904 - info_core - INFO - update_fundingrate|BINANCE update_fundingrate took 0.8993618488311768 secs, read_time: 0.36520910263061523, write_time: 0.1295154094696045, calculate_time: 0.019145965576171875, api_time: 0.35848546028137207
2023-12-18 08:28:52,966 - info_core - INFO - update_wallet_status|OKX update_wallet_status took 5.4564197063446045 secs, read_time: 0.0062863826751708984, write_time: 3.3367919921875, calculate_time: 0, api_time: 2.077570676803589
2023-12-18 08:29:00,782 - kline_core - INFO - insert_kline_to_db|database: OKX_USD_M/USDT:OKX_COIN_M/USD, Filtering 2 klines for 2 unique base_assets took 0.41057586669921875 seconds
2023-12-18 08:29:00,783 - kline_core - INFO - insert_kline_to_db|database: OKX_USD_M/USDT:OKX_COIN_M/USD, Inserting 2 klines for 2 unique base_assets took 0.0052356719970703125 seconds
2023-12-18 08:29:00,784 - kline_core - INFO - insert_kline_to_db|channel_name: INFO_CORE|OKX_USD_M/USDT:OKX_COIN_M/USD_1T_kline, Inserting 2 klines for 2 unique base_assets took 0.6210811138153076 seconds
2023-12-18 08:29:10,338 - info_core - INFO - update_wallet_status|BINANCE update_wallet_status took 18.235234022140503 secs, read_time: 0.28698110580444336, write_time: 17.68963599205017, calculate_time: 0, api_time: 0.16602301597595215
2023-12-18 08:29:14,565 - info_core - INFO - update_wallet_status|BYBIT update_wallet_status took 27.05887222290039 secs, read_time: 2.0744082927703857, write_time: 24.38716745376587, calculate_time: 0, api_time: 0.5558462142944336
2023-12-18 08:29:15,237 - info_core - INFO - update_wallet_status|BITHUMB update_wallet_status took 10.396000862121582 secs, read_time: 0.027982473373413086, write_time: 0.26526570320129395, calculate_time: 0, api_time: 10.083894491195679
2023-12-18 08:29:38,613 - arbitrage_core - INFO - store_funding_diff took 1.0834736824035645 seconds.
2023-12-18 08:29:41,640 - arbitrage_core - INFO - store_average_funding_rate took 22.634845972061157 seconds.
2023-12-18 08:29:41,669 - info_core - INFO - update_wallet_status|UPBIT update_wallet_status took 0.37598466873168945 secs, read_time: 0.0046422481536865234, write_time: 0.22762346267700195, calculate_time: 0, api_time: 0.12764930725097656
2023-12-18 08:29:46,422 - info_core - INFO - update_fundingrate|BYBIT update_fundingrate took 1.0321829319000244 secs, read_time: 0.1890120506286621, write_time: 0.22060537338256836, calculate_time: 0.06862449645996094, api_time: 0.5242066383361816
2023-12-18 08:29:47,020 - info_core - INFO - update_fundingrate|BINANCE update_fundingrate took 1.0551776885986328 secs, read_time: 0.4971649646759033, write_time: 0.12172245979309082, calculate_time: 0.03236746788024902, api_time: 0.3753983974456787
2023-12-18 08:29:53,774 - info_core - INFO - update_wallet_status|OKX update_wallet_status took 0.7041010856628418 secs, read_time: 0.008305788040161133, write_time: 0.41333866119384766, calculate_time: 0, api_time: 0.25730037689208984
2023-12-18 08:30:00,422 - kline_core - INFO - resampling ohlc_df(length: 3333): 0.38503479957580566
2023-12-18 08:30:00,424 - kline_core - INFO - redis saving OKX_USD_M/USDT:OKX_COIN_M/USD_15T_kline time: 0.0012352466583251953
2023-12-18 08:30:00,425 - kline_core - INFO - redis publishing OKX_USD_M/USDT:OKX_COIN_M/USD_15T_kline time: 0.00021147727966308594
2023-12-18 08:30:00,489 - kline_core - INFO - resampling ohlc_df(length: 9900): 0.4346334934234619
2023-12-18 08:30:00,492 - kline_core - INFO - redis saving OKX_USD_M/USDT:OKX_COIN_M/USD_5T_kline time: 0.0022439956665039062
2023-12-18 08:30:00,493 - kline_core - INFO - redis publishing OKX_USD_M/USDT:OKX_COIN_M/USD_5T_kline time: 0.0001392364501953125
2023-12-18 08:30:00,539 - kline_core - INFO - resampling ohlc_df(length: 1683): 0.4461359977722168
2023-12-18 08:30:00,541 - kline_core - INFO - redis saving OKX_USD_M/USDT:OKX_COIN_M/USD_30T_kline time: 0.0007855892181396484
2023-12-18 08:30:00,542 - kline_core - INFO - redis publishing OKX_USD_M/USDT:OKX_COIN_M/USD_30T_kline time: 0.00015544891357421875
2023-12-18 08:30:00,630 - kline_core - INFO - insert_kline_to_db|database: OKX_USD_M/USDT:OKX_COIN_M/USD, Filtering 14 klines for 7 unique base_assets took 0.27254271507263184 seconds
2023-12-18 08:30:00,631 - kline_core - INFO - insert_kline_to_db|database: OKX_USD_M/USDT:OKX_COIN_M/USD, Inserting 14 klines for 7 unique base_assets took 0.01459050178527832 seconds
2023-12-18 08:30:00,632 - kline_core - INFO - insert_kline_to_db|channel_name: INFO_CORE|OKX_USD_M/USDT:OKX_COIN_M/USD_1T_kline, Inserting 14 klines for 7 unique base_assets took 0.45697593688964844 seconds
2023-12-18 08:30:05,715 - info_core - INFO - update_fundingrate|OKX update_fundingrate took 76.18935871124268 secs, read_time: 0.2585785388946533, write_time: 0.06693577766418457, calculate_time: 0.010426521301269531, api_time: 75.83897471427917
2023-12-18 08:30:12,197 - info_core - INFO - update_wallet_status|BINANCE update_wallet_status took 1.8033313751220703 secs, read_time: 0.018448829650878906, write_time: 1.549128532409668, calculate_time: 0, api_time: 0.15723752975463867
2023-12-18 08:30:32,055 - info_core - INFO - update_wallet_status|BITHUMB update_wallet_status took 16.633368968963623 secs, read_time: 0.054789066314697266, write_time: 5.565685987472534, calculate_time: 0, api_time: 10.984492540359497
2023-12-18 08:30:39,646 - arbitrage_core - INFO - store_funding_diff took 1.0246832370758057 seconds.
2023-12-18 08:30:40,714 - info_core - INFO - update_wallet_status|BYBIT update_wallet_status took 26.088090658187866 secs, read_time: 2.4205245971679688, write_time: 23.132651567459106, calculate_time: 0, api_time: 0.49352121353149414
2023-12-18 08:30:42,071 - info_core - INFO - update_wallet_status|UPBIT update_wallet_status took 0.3929023742675781 secs, read_time: 0.004006147384643555, write_time: 0.2295384407043457, calculate_time: 0, api_time: 0.14350104331970215
2023-12-18 08:30:47,823 - info_core - INFO - update_fundingrate|BYBIT update_fundingrate took 1.3617157936096191 secs, read_time: 0.1804361343383789, write_time: 0.43232250213623047, calculate_time: 0.018335580825805664, api_time: 0.6982998847961426
2023-12-18 08:30:48,113 - info_core - INFO - update_fundingrate|BINANCE update_fundingrate took 1.0320408344268799 secs, read_time: 0.3833584785461426, write_time: 0.22610712051391602, calculate_time: 0.0254671573638916, api_time: 0.355541467666626
2023-12-18 08:30:54,544 - info_core - INFO - update_wallet_status|OKX update_wallet_status took 0.7093439102172852 secs, read_time: 0.00956273078918457, write_time: 0.3944661617279053, calculate_time: 0, api_time: 0.281463623046875
2023-12-18 08:31:00,674 - kline_core - INFO - insert_kline_to_db|database: OKX_USD_M/USDT:OKX_COIN_M/USD, Filtering 33 klines for 33 unique base_assets took 0.2915499210357666 seconds
2023-12-18 08:31:00,678 - kline_core - INFO - insert_kline_to_db|database: OKX_USD_M/USDT:OKX_COIN_M/USD, Inserting 33 klines for 33 unique base_assets took 0.09585213661193848 seconds
2023-12-18 08:31:00,679 - kline_core - INFO - insert_kline_to_db|channel_name: INFO_CORE|OKX_USD_M/USDT:OKX_COIN_M/USD_1T_kline, Inserting 33 klines for 33 unique base_assets took 0.5466225147247314 seconds
2023-12-18 08:31:13,683 - info_core - INFO - update_wallet_status|BINANCE update_wallet_status took 1.4251036643981934 secs, read_time: 0.016815662384033203, write_time: 1.1978890895843506, calculate_time: 0, api_time: 0.15050888061523438
2023-12-18 08:31:38,296 - info_core - INFO - update_wallet_status|BITHUMB update_wallet_status took 6.178818941116333 secs, read_time: 0.0033817291259765625, write_time: 0.2623937129974365, calculate_time: 0, api_time: 5.895088195800781
2023-12-18 08:31:40,665 - arbitrage_core - INFO - store_funding_diff took 0.9595518112182617 seconds.
2023-12-18 08:31:43,085 - info_core - INFO - update_wallet_status|UPBIT update_wallet_status took 0.9474153518676758 secs, read_time: 0.00487518310546875, write_time: 0.4120049476623535, calculate_time: 0, api_time: 0.5147979259490967
2023-12-18 08:31:52,461 - info_core - INFO - update_fundingrate|BYBIT update_fundingrate took 4.573985815048218 secs, read_time: 0.4406108856201172, write_time: 2.747176170349121, calculate_time: 0.12580537796020508, api_time: 1.2295420169830322
2023-12-18 08:31:53,093 - info_core - INFO - update_fundingrate|BINANCE update_fundingrate took 4.888713121414185 secs, read_time: 0.9298622608184814, write_time: 3.028750419616699, calculate_time: 0.20819950103759766, api_time: 0.6888871192932129
2023-12-18 08:32:00,724 - kline_core - INFO - insert_kline_to_db|database: OKX_USD_M/USDT:OKX_COIN_M/USD, Filtering 31 klines for 31 unique base_assets took 0.3727743625640869 seconds
2023-12-18 08:32:00,742 - kline_core - INFO - insert_kline_to_db|database: OKX_USD_M/USDT:OKX_COIN_M/USD, Inserting 31 klines for 31 unique base_assets took 0.09009599685668945 seconds
2023-12-18 08:32:00,746 - kline_core - INFO - insert_kline_to_db|channel_name: INFO_CORE|OKX_USD_M/USDT:OKX_COIN_M/USD_1T_kline, Inserting 31 klines for 31 unique base_assets took 0.656456470489502 seconds
2023-12-18 08:32:04,136 - info_core - INFO - update_wallet_status|OKX update_wallet_status took 9.527249336242676 secs, read_time: 0.05450558662414551, write_time: 7.698652744293213, calculate_time: 0, api_time: 1.7340092658996582
2023-12-18 08:32:04,362 - arbitrage_core - INFO - store_average_funding_rate took 22.623658180236816 seconds.
2023-12-18 08:32:07,763 - info_core - INFO - update_wallet_status|BYBIT update_wallet_status took 26.9896981716156 secs, read_time: 2.0736844539642334, write_time: 24.380157232284546, calculate_time: 0, api_time: 0.4949345588684082
2023-12-18 08:32:15,450 - info_core - INFO - update_wallet_status|BINANCE update_wallet_status took 1.707707405090332 secs, read_time: 0.01552271842956543, write_time: 1.3645765781402588, calculate_time: 0, api_time: 0.25829172134399414
2023-12-18 08:32:41,801 - arbitrage_core - INFO - store_funding_diff took 1.0755424499511719 seconds.
2023-12-18 08:32:43,594 - info_core - INFO - update_wallet_status|UPBIT update_wallet_status took 0.44876790046691895 secs, read_time: 0.005554676055908203, write_time: 0.2753262519836426, calculate_time: 0, api_time: 0.15038824081420898
2023-12-18 08:32:44,006 - info_core - INFO - update_wallet_status|BITHUMB update_wallet_status took 5.700962781906128 secs, read_time: 0.0031049251556396484, write_time: 0.243757963180542, calculate_time: 0, api_time: 5.437241554260254

In [14]:
start = time.time()
core.get_premium_df("OKX_USD_M/USDT", "OKX_COIN_M/USD")
time.time()-start

0.026299238204956055

2023-12-18 07:40:05,788 - info_core - INFO - update_exchange_info_as_df|name:binance_coin_m_info_df has been updated. (0.06 secs), error_count:0
2023-12-18 07:40:06,024 - info_core - INFO - update_exchange_info_as_df|name:binance_coin_m_ticker_df has been updated. (0.05 secs), error_count:0
2023-12-18 07:40:09,420 - info_core - INFO - update_exchange_info_as_df|name:okx_spot_info_df has been updated. (0.17 secs), error_count:0
2023-12-18 07:40:10,066 - info_core - INFO - update_exchange_info_as_df|name:okx_usd_m_ticker_df has been updated. (0.14 secs), error_count:0
2023-12-18 07:40:10,656 - info_core - INFO - update_exchange_info_as_df|name:bybit_coin_m_info_df has been updated. (0.15 secs), error_count:0
2023-12-18 07:40:11,058 - update_dollar - INFO - fetch_dollar|Dollar price (1299.0 KRW) has been updated.
2023-12-18 07:40:11,446 - info_core - INFO - update_exchange_info_as_df|name:bybit_coin_m_ticker_df has been updated. (0.14 secs), error_count:0
2023-12-18 07:40:11,695 - info_core - INFO - update_exchange_info_as_df|name:upbit_spot_ticker_df has been updated. (0.15 secs), error_count:0
2023-12-18 07:40:11,916 - info_core - INFO - update_exchange_info_as_df|name:binance_usd_m_info_df has been updated. (0.12 secs), error_count:0
2023-12-18 07:40:12,025 - info_core - INFO - update_exchange_info_as_df|name:binance_usd_m_ticker_df has been updated. (0.11 secs), error_count:0
2023-12-18 07:40:12,048 - info_core - INFO - update_exchange_info_as_df|name:okx_coin_m_ticker_df has been updated. (0.14 secs), error_count:0
2023-12-18 07:40:14,532 - info_core - INFO - update_exchange_info_as_df|name:okx_spot_ticker_df has been updated. (0.20 secs), error_count:0
2023-12-18 07:40:16,827 - info_core - INFO - update_exchange_info_as_df|name:okx_usd_m_info_df has been updated. (0.42 secs), error_count:0
2023-12-18 07:40:17,155 - info_core - INFO - update_exchange_info_as_df|name:okx_coin_m_info_df has been updated. (0.30 secs), error_count:0
2023-12-18 07:40:17,660 - info_core - INFO - update_exchange_info_as_df|name:bithumb_spot_info_df has been updated. (0.57 secs), error_count:0
2023-12-18 07:40:18,477 - info_core - INFO - update_exchange_info_as_df|name:bithumb_spot_ticker_df has been updated. (0.22 secs), error_count:0
2023-12-18 07:40:21,353 - info_core - INFO - update_exchange_info_as_df|name:bybit_spot_ticker_df has been updated. (0.37 secs), error_count:0
2023-12-18 07:40:26,634 - info_core - INFO - update_exchange_info_as_df|name:binance_spot_info_df has been updated. (0.40 secs), error_count:0
2023-12-18 07:40:27,146 - info_core - INFO - update_exchange_info_as_df|name:bybit_usd_m_ticker_df has been updated. (0.61 secs), error_count:0
2023-12-18 07:40:28,651 - info_core - INFO - update_exchange_info_as_df|name:bybit_usd_m_info_df has been updated. (0.56 secs), error_count:0
2023-12-18 07:40:30,216 - info_core - INFO - update_exchange_info_as_df|name:bybit_spot_info_df has been updated. (0.58 secs), error_count:0
2023-12-18 07:40:31,402 - info_core - INFO - update_exchange_info_as_df|name:binance_spot_ticker_df has been updated. (0.47 secs), error_count:0
2023-12-18 07:40:32,365 - info_core - INFO - update_exchange_info_as_df|name:upbit_spot_info_df has been updated. (0.01 secs), error_count:0
2023-12-18 07:40:35,848 - info_core - INFO - update_exchange_info_as_df|name:binance_coin_m_info_df has been updated. (0.06 secs), error_count:0
2023-12-18 07:40:36,106 - info_core - INFO - update_exchange_info_as_df|name:binance_coin_m_ticker_df has been updated. (0.05 secs), error_count:0
2023-12-18 07:40:39,597 - info_core - INFO - update_exchange_info_as_df|name:okx_spot_info_df has been updated. (0.15 secs), error_count:0
2023-12-18 07:40:40,254 - info_core - INFO - update_exchange_info_as_df|name:okx_usd_m_ticker_df has been updated. (0.16 secs), error_count:0
2023-12-18 07:40:40,862 - info_core - INFO - update_exchange_info_as_df|name:bybit_coin_m_info_df has been updated. (0.18 secs), error_count:0
2023-12-18 07:40:41,646 - info_core - INFO - update_exchange_info_as_df|name:bybit_coin_m_ticker_df has been updated. (0.17 secs), error_count:0
2023-12-18 07:40:41,883 - info_core - INFO - update_exchange_info_as_df|name:upbit_spot_ticker_df has been updated. (0.16 secs), error_count:0
2023-12-18 07:40:41,927 - update_dollar - INFO - fetch_dollar|Dollar price (1299.0 KRW) has been updated.
2023-12-18 07:40:42,077 - info_core - INFO - update_exchange_info_as_df|name:binance_usd_m_info_df has been updated. (0.13 secs), error_count:0
2023-12-18 07:40:42,167 - info_core - INFO - update_exchange_info_as_df|name:binance_usd_m_ticker_df has been updated. (0.09 secs), error_count:0
2023-12-18 07:40:42,275 - info_core - INFO - update_exchange_info_as_df|name:okx_coin_m_ticker_df has been updated. (0.20 secs), error_count:0
2023-12-18 07:40:44,760 - info_core - INFO - update_exchange_info_as_df|name:okx_spot_ticker_df has been updated. (0.21 secs), error_count:0
2023-12-18 07:40:47,130 - info_core - INFO - update_exchange_info_as_df|name:okx_usd_m_info_df has been updated. (0.28 secs), error_count:0
2023-12-18 07:40:47,457 - info_core - INFO - update_exchange_info_as_df|name:okx_coin_m_info_df has been updated. (0.27 secs), error_count:0
2023-12-18 07:40:47,950 - info_core - INFO - update_exchange_info_as_df|name:bithumb_spot_info_df has been updated. (0.28 secs), error_count:0
2023-12-18 07:40:48,693 - info_core - INFO - update_exchange_info_as_df|name:bithumb_spot_ticker_df has been updated. (0.19 secs), error_count:0
2023-12-18 07:40:51,933 - info_core - INFO - update_exchange_info_as_df|name:bybit_spot_ticker_df has been updated. (0.56 secs), error_count:0
2023-12-18 07:40:57,121 - info_core - INFO - update_exchange_info_as_df|name:binance_spot_info_df has been updated. (0.46 secs), error_count:0
2023-12-18 07:40:57,342 - info_core - INFO - update_exchange_info_as_df|name:bybit_usd_m_ticker_df has been updated. (0.17 secs), error_count:0
2023-12-18 07:40:59,151 - info_core - INFO - update_exchange_info_as_df|name:bybit_usd_m_info_df has been updated. (0.47 secs), error_count:0
2023-12-18 07:41:01,068 - info_core - INFO - update_exchange_info_as_df|name:bybit_spot_info_df has been updated. (0.82 secs), error_count:0
2023-12-18 07:41:02,038 - info_core - INFO - update_exchange_info_as_df|name:binance_spot_ticker_df has been updated. (0.60 secs), error_count:0
2023-12-18 07:41:02,405 - info_core - INFO - update_exchange_info_as_df|name:upbit_spot_info_df has been updated. (0.01 secs), error_count:0
2023-12-18 07:41:05,961 - info_core - INFO - update_exchange_info_as_df|name:binance_coin_m_info_df has been updated. (0.08 secs), error_count:0
2023-12-18 07:41:06,232 - info_core - INFO - update_exchange_info_as_df|name:binance_coin_m_ticker_df has been updated. (0.10 secs), error_count:0

In [52]:
target_market_code = 'OKX_USD_M/USDT'
origin_market_code = 'OKX_COIN_M/USD'

get_premium_df(core, target_market_code, origin_market_code)

get_price_df processing time: 0.02441716194152832
premium_df processing time: 0.01241159439086914
total processing time: 0.0414881706237793

,tp_premium,LS_premium,SL_premium,LS_SL_spread,base_asset,quote_asset,tp,ap,bp,scr,atp24h,converted_tp,converted_ap,converted_bp,dollar
0,0.041262,0.046361,0.045876,0.000486,BTC,USDT,41217.2,41217.2,41217.1,-1.483583,4.428525e+09,41200.2,41198.2,41198.1,1299.5
1,0.048727,0.049187,0.048267,0.00092,ETH,USDT,2176.45,2176.46,2176.45,-1.719552,3.477152e+09,2175.39,2175.4,2175.39,1299.5
2,0.014399,0.072036,0.014401,0.057635,SOL,USDT,69.46,69.46,69.45,-4.285517,5.219317e+08,69.45,69.44,69.41,1299.5
3,0.040999,0.092267,0.0,0.092267,AVAX,USDT,39.041,39.053,39.045,-7.332067,2.287990e+08,39.025,39.045,39.017,1299.5
4,0.058893,0.058904,0.0,0.058904,FIL,USDT,5.097,5.096,5.095,-9.611633,2.225614e+08,5.094,5.095,5.093,1299.5
5,-0.021942,0.010975,-0.043879,0.054853,DOGE,USDT,0.09113,0.09113,0.09112,-3.382103,1.311250e+08,0.09115,0.09116,0.09112,1299.5
6,0.133222,0.066567,0.033278,0.033289,XRP,USDT,0.6013,0.6013,0.6012,-2.338801,8.747478e+07,0.6005,0.601,0.6009,1299.5
7,0.042463,0.056617,0.028305,0.028313,LTC,USDT,70.68,70.69,70.68,-3.07186,7.243951e+07,70.65,70.66,70.65,1299.5
8,0.07046,0.052836,-0.017603,0.070438,ADA,USDT,0.5681,0.5681,0.568,-4.77707,7.094268e+07,0.5677,0.5681,0.5678,1299.5
9,-0.065036,0.026038,-0.013016,0.039054,EOS,USDT,0.7683,0.7683,0.7682,-4.736516,6.201605e+07,0.7688,0.7683,0.7681,1299.5
10,0.028124,0.056269,0.009375,0.046895,ATOM,USDT,10.67,10.669,10.668,-8.017241,5.860474e+07,10.667,10.667,10.663,1299.5
11,0.089874,0.074895,0.014972,0.059923,DOT,USDT,6.682,6.681,6.68,-4.814815,5.818540e+07,6.676,6.679,6.676,1299.5
12,0.035373,0.028295,-0.042415,0.070709,LINK,USDT,14.14,14.141,14.14,0.056609,5.791929e+07,14.135,14.146,14.137,1299.5
13,0.098328,0.081927,0.03276,0.049167,CRV,USDT,0.6108,0.6108,0.6107,-2.599266,4.467975e+07,0.6102,0.6105,0.6103,1299.5
14,0.102267,0.085208,0.017033,0.068175,UNI,USDT,5.873,5.873,5.872,-4.28618,3.551966e+07,5.867,5.871,5.868,1299.5
15,0.044723,0.089445,0.0,0.089445,BCH,USDT,223.7,223.8,223.7,-1.799824,3.160290e+07,223.6,223.7,223.6,1299.5
16,0.102197,0.153296,0.051073,0.102223,ETC,USDT,19.59,19.6,19.59,-3.354711,2.940792e+07,19.57,19.58,19.57,1299.5
17,0.021358,0.021358,-0.021354,0.042712,BSV,USDT,46.83,46.83,46.82,-4.700855,1.448658e+07,46.82,46.83,46.82,1299.5
18,-0.026698,0.062355,-0.026707,0.089062,SUSHI,USDT,1.1234,1.1233,1.123,-4.277437,1.329317e+07,1.1237,1.1233,1.1226,1299.5
19,0.26943,0.103434,-0.020665,0.124099,SAND,USDT,0.4838,0.4839,0.4838,-5.285826,1.142671e+07,0.4825,0.4839,0.4834,1299.5
20,-0.029925,-0.049845,-0.089695,0.03985,TRX,USDT,0.10022,0.10026,0.10025,-1.860556,9.420379e+06,0.10025,0.10034,0.10031,1299.5
21,0.056465,0.088753,-0.08058,0.169333,NEO,USDT,12.404,12.405,12.4,-2.323018,8.108706e+06,12.397,12.41,12.394,1299.5
22,0.150118,0.128673,-0.021422,0.150095,MANA,USDT,0.467,0.4669,0.4667,-5.941591,6.831584e+06,0.4663,0.4668,0.4663,1299.5
23,0.053533,0.160772,-0.053505,0.214276,ALGO,USDT,0.1869,0.1869,0.1868,-4.350051,6.593598e+06,0.1868,0.1869,0.1866,1299.5
24,0.275413,0.124969,0.037472,0.087497,YFI,USDT,8010.0,8012.0,8009.0,-4.688244,5.870990e+06,7988.0,8006.0,8002.0,1299.5
25,0.0,0.176678,-0.035273,0.211952,KSM,USDT,28.35,28.35,28.34,-5.5,5.654728e+06,28.35,28.35,28.3,1299.5
26,0.065274,0.130634,-0.065232,0.195865,GRT,USDT,0.1533,0.1533,0.1532,-4.545455,4.338836e+06,0.1532,0.1533,0.1531,1299.5
27,0.103663,0.207541,0.034542,0.172998,ZEC,USDT,28.97,28.97,28.96,-2.490744,4.269144e+06,28.94,28.95,28.91,1299.5
28,0.250836,0.167084,0.0,0.167084,XLM,USDT,0.1199,0.1199,0.1198,-3.22841,3.988857e+06,0.1196,0.1198,0.1197,1299.5
29,0.085179,0.113604,-0.028369,0.141973,1INCH,USDT,0.3525,0.3525,0.3524,-4.133805,3.863874e+06,0.3522,0.3525,0.3521,1299.5
30,0.0,0.1001,-0.1,0.2001,THETA,USDT,1.0,1.0,0.999,-6.629318,3.774600e+06,1.0,1.0,0.999,1299.5
31,0.059595,0.298507,-0.059524,0.358031,XMR,USDT,167.9,168.0,167.9,-0.356083,3.572677e+06,167.8,168.0,167.5,1299.5
32,0.356448,0.096931,0.0323,0.064631,DASH,USDT,30.97,30.98,30.97,-4.295426,3.211710e+06,30.86,30.96,30.95,1299.5

In [53]:
test_get_premium_df(core, target_market_code, origin_market_code)

get_price_df processing time: 0.10197234153747559
premium_df processing time: 0.006357669830322266
total processing time: 0.11172628402709961

,tp_premium,LS_premium,SL_premium,LS_SL_spread,base_asset,quote_asset,tp,ap,bp,scr,atp24h,converted_tp,converted_ap,converted_bp,dollar
0,0.041262,0.046361,0.045876,0.000486,BTC,USDT,41217.2,41217.2,41217.1,-1.483583,4.428525e+09,41200.2,41198.2,41198.1,1299.5
1,0.048727,0.049187,0.048267,0.00092,ETH,USDT,2176.45,2176.46,2176.45,-1.719552,3.477152e+09,2175.39,2175.4,2175.39,1299.5
2,0.014399,0.072036,0.014401,0.057635,SOL,USDT,69.46,69.46,69.45,-4.285517,5.219317e+08,69.45,69.44,69.41,1299.5
3,0.040999,0.09483,0.0,0.09483,AVAX,USDT,39.041,39.054,39.046,-7.332067,2.287990e+08,39.025,39.046,39.017,1299.5
4,0.058893,0.058904,0.0,0.058904,FIL,USDT,5.097,5.096,5.095,-9.611633,2.225614e+08,5.094,5.095,5.093,1299.5
5,-0.021942,0.010975,-0.043879,0.054853,DOGE,USDT,0.09113,0.09113,0.09112,-3.382103,1.311250e+08,0.09115,0.09116,0.09112,1299.5
6,0.133222,0.066567,0.033278,0.033289,XRP,USDT,0.6013,0.6013,0.6012,-2.338801,8.747478e+07,0.6005,0.601,0.6009,1299.5
7,0.042463,0.056617,0.028305,0.028313,LTC,USDT,70.68,70.69,70.68,-3.07186,7.243951e+07,70.65,70.66,70.65,1299.5
8,0.07046,0.052836,-0.017603,0.070438,ADA,USDT,0.5681,0.5681,0.568,-4.77707,7.094268e+07,0.5677,0.5681,0.5678,1299.5
9,-0.065036,0.013017,-0.013016,0.026033,EOS,USDT,0.7683,0.7683,0.7682,-4.736516,6.201605e+07,0.7688,0.7683,0.7682,1299.5
10,0.018749,0.056269,0.009375,0.046895,ATOM,USDT,10.669,10.669,10.668,-8.025862,5.859928e+07,10.667,10.667,10.663,1299.5
11,0.089874,0.074895,0.014972,0.059923,DOT,USDT,6.682,6.681,6.68,-4.814815,5.818540e+07,6.676,6.679,6.676,1299.5
12,0.035373,0.028295,-0.028281,0.056575,LINK,USDT,14.14,14.141,14.14,0.056609,5.791929e+07,14.135,14.144,14.137,1299.5
13,0.098328,0.081927,0.03276,0.049167,CRV,USDT,0.6108,0.6108,0.6107,-2.599266,4.467975e+07,0.6102,0.6105,0.6103,1299.5
14,0.102267,0.085208,0.017033,0.068175,UNI,USDT,5.873,5.873,5.872,-4.28618,3.551966e+07,5.867,5.871,5.868,1299.5
15,0.044723,0.089445,0.0,0.089445,BCH,USDT,223.7,223.8,223.7,-1.799824,3.160290e+07,223.6,223.7,223.6,1299.5
16,0.102197,0.153296,0.051073,0.102223,ETC,USDT,19.59,19.6,19.59,-3.354711,2.940792e+07,19.57,19.58,19.57,1299.5
17,0.0,0.021363,-0.021358,0.042721,BSV,USDT,46.82,46.82,46.81,-4.721205,1.448630e+07,46.82,46.82,46.81,1299.5
18,-0.026698,0.062355,-0.026707,0.089062,SUSHI,USDT,1.1234,1.1233,1.123,-4.277437,1.329317e+07,1.1237,1.1233,1.1226,1299.5
19,0.26943,0.103434,-0.020665,0.124099,SAND,USDT,0.4838,0.4839,0.4838,-5.285826,1.142671e+07,0.4825,0.4839,0.4834,1299.5
20,-0.029925,-0.049845,-0.089695,0.03985,TRX,USDT,0.10022,0.10026,0.10025,-1.860556,9.420379e+06,0.10025,0.10034,0.10031,1299.5
21,0.056465,0.088753,-0.08058,0.169333,NEO,USDT,12.404,12.405,12.4,-2.323018,8.108706e+06,12.397,12.41,12.394,1299.5
22,0.150118,0.128673,-0.021422,0.150095,MANA,USDT,0.467,0.4669,0.4667,-5.941591,6.831584e+06,0.4663,0.4668,0.4663,1299.5
23,0.053533,0.160772,-0.053505,0.214276,ALGO,USDT,0.1869,0.1869,0.1868,-4.350051,6.593598e+06,0.1868,0.1869,0.1866,1299.5
24,0.275413,0.124969,0.024978,0.099991,YFI,USDT,8010.0,8012.0,8009.0,-4.688244,5.870990e+06,7988.0,8007.0,8002.0,1299.5
25,0.0,0.176678,-0.035273,0.211952,KSM,USDT,28.35,28.35,28.34,-5.5,5.654728e+06,28.35,28.35,28.3,1299.5
26,0.065274,0.130634,-0.065232,0.195865,GRT,USDT,0.1533,0.1533,0.1532,-4.545455,4.338836e+06,0.1532,0.1533,0.1531,1299.5
27,0.103663,0.207541,0.034542,0.172998,ZEC,USDT,28.97,28.97,28.96,-2.490744,4.269144e+06,28.94,28.95,28.91,1299.5
28,0.250836,0.167084,0.0,0.167084,XLM,USDT,0.1199,0.1199,0.1198,-3.22841,3.988857e+06,0.1196,0.1198,0.1197,1299.5
29,0.085179,0.142005,-0.028369,0.170374,1INCH,USDT,0.3525,0.3526,0.3524,-4.133805,3.863874e+06,0.3522,0.3525,0.3521,1299.5
30,0.0,0.1001,-0.1,0.2001,THETA,USDT,1.0,1.0,0.999,-6.629318,3.774600e+06,1.0,1.0,0.999,1299.5
31,0.059595,0.298507,-0.059524,0.358031,XMR,USDT,167.9,168.0,167.9,-0.356083,3.572677e+06,167.8,168.0,167.5,1299.5
32,0.356448,0.096931,0.0323,0.064631,DASH,USDT,30.97,30.98,30.97,-4.295426,3.211710e+06,30.86,30.96,30.95,1299.5

2023-12-18 08:30:48,604 - info_core - INFO - update_exchange_info_as_df|name:okx_coin_m_ticker_df has been updated. (0.17 secs), error_count:0
2023-12-18 08:30:48,687 - info_core - INFO - update_exchange_info_as_df|name:okx_coin_m_info_df has been updated. (0.28 secs), error_count:0
2023-12-18 08:30:48,706 - info_core - INFO - update_exchange_info_as_df|name:okx_usd_m_ticker_df has been updated. (0.15 secs), error_count:0
2023-12-18 08:30:48,890 - info_core - INFO - update_exchange_info_as_df|name:okx_usd_m_info_df has been updated. (0.27 secs), error_count:0
2023-12-18 08:30:49,423 - info_core - INFO - update_exchange_info_as_df|name:okx_spot_ticker_df has been updated. (0.20 secs), error_count:0
2023-12-18 08:30:49,711 - info_core - INFO - update_exchange_info_as_df|name:binance_usd_m_ticker_df has been updated. (0.08 secs), error_count:0
2023-12-18 08:30:50,275 - info_core - INFO - update_exchange_info_as_df|name:bithumb_spot_info_df has been updated. (0.32 secs), error_count:0
2023-12-18 08:30:50,972 - info_core - INFO - update_exchange_info_as_df|name:bithumb_spot_ticker_df has been updated. (0.39 secs), error_count:0
2023-12-18 08:30:52,548 - info_core - INFO - update_exchange_info_as_df|name:bybit_spot_ticker_df has been updated. (0.17 secs), error_count:0
2023-12-18 08:30:52,675 - info_core - INFO - update_exchange_info_as_df|name:bybit_usd_m_ticker_df has been updated. (0.59 secs), error_count:0
2023-12-18 08:30:53,307 - info_core - INFO - update_exchange_info_as_df|name:bybit_spot_info_df has been updated. (0.33 secs), error_count:0
2023-12-18 08:30:53,686 - info_core - INFO - update_exchange_info_as_df|name:binance_spot_info_df has been updated. (0.38 secs), error_count:0
2023-12-18 08:30:55,109 - info_core - INFO - update_exchange_info_as_df|name:bybit_usd_m_info_df has been updated. (0.77 secs), error_count:0
2023-12-18 08:30:55,514 - update_dollar - INFO - fetch_dollar|Dollar price (1299.5 KRW) has been updated.
2023-12-18 08:30:55,523 - info_core - INFO - update_exchange_info_as_df|name:binance_spot_ticker_df has been updated. (0.58 secs), error_count:0
2023-12-18 08:31:14,392 - info_core - INFO - update_exchange_info_as_df|name:upbit_spot_info_df has been updated. (0.01 secs), error_count:0
2023-12-18 08:31:15,377 - info_core - INFO - update_exchange_info_as_df|name:binance_coin_m_ticker_df has been updated. (0.06 secs), error_count:0
2023-12-18 08:31:16,655 - info_core - INFO - update_exchange_info_as_df|name:binance_coin_m_info_df has been updated. (0.06 secs), error_count:0
2023-12-18 08:31:16,765 - info_core - INFO - update_exchange_info_as_df|name:okx_spot_info_df has been updated. (0.16 secs), error_count:0
2023-12-18 08:31:17,118 - info_core - INFO - update_exchange_info_as_df|name:upbit_spot_ticker_df has been updated. (0.17 secs), error_count:0
2023-12-18 08:31:17,193 - info_core - INFO - update_exchange_info_as_df|name:binance_usd_m_info_df has been updated. (0.14 secs), error_count:0
2023-12-18 08:31:17,449 - info_core - INFO - update_exchange_info_as_df|name:bybit_coin_m_info_df has been updated. (0.14 secs), error_count:0
2023-12-18 08:31:17,496 - info_core - INFO - update_exchange_info_as_df|name:bybit_coin_m_ticker_df has been updated. (0.14 secs), error_count:0
2023-12-18 08:31:18,765 - info_core - INFO - update_exchange_info_as_df|name:okx_coin_m_ticker_df has been updated. (0.15 secs), error_count:0
2023-12-18 08:31:18,869 - info_core - INFO - update_exchange_info_as_df|name:okx_usd_m_ticker_df has been updated. (0.14 secs), error_count:0
2023-12-18 08:31:19,011 - info_core - INFO - update_exchange_info_as_df|name:okx_coin_m_info_df has been updated. (0.29 secs), error_count:0
2023-12-18 08:31:19,223 - info_core - INFO - update_exchange_info_as_df|name:okx_usd_m_info_df has been updated. (0.30 secs), error_count:0
2023-12-18 08:31:19,649 - info_core - INFO - update_exchange_info_as_df|name:okx_spot_ticker_df has been updated. (0.20 secs), error_count:0
2023-12-18 08:31:19,824 - info_core - INFO - update_exchange_info_as_df|name:binance_usd_m_ticker_df has been updated. (0.08 secs), error_count:0
2023-12-18 08:31:20,694 - info_core - INFO - update_exchange_info_as_df|name:bithumb_spot_info_df has been updated. (0.39 secs), error_count:0
2023-12-18 08:31:21,572 - info_core - INFO - update_exchange_info_as_df|name:bithumb_spot_ticker_df has been updated. (0.57 secs), error_count:0
2023-12-18 08:31:22,725 - info_core - INFO - update_exchange_info_as_df|name:bybit_spot_ticker_df has been updated. (0.15 secs), error_count:0
2023-12-18 08:31:23,236 - info_core - INFO - update_exchange_info_as_df|name:bybit_usd_m_ticker_df has been updated. (0.53 secs), error_count:0
2023-12-18 08:31:23,714 - info_core - INFO - update_exchange_info_as_df|name:bybit_spot_info_df has been updated. (0.38 secs), error_count:0
2023-12-18 08:31:24,185 - info_core - INFO - update_exchange_info_as_df|name:binance_spot_info_df has been updated. (0.47 secs), error_count:0
2023-12-18 08:31:26,165 - info_core - INFO - update_exchange_info_as_df|name:bybit_usd_m_info_df has been updated. (1.03 secs), error_count:0
2023-12-18 08:31:26,369 - info_core - INFO - update_exchange_info_as_df|name:binance_spot_ticker_df has been updated. (0.80 secs), error_count:0
2023-12-18 08:31:26,373 - update_dollar - INFO - fetch_dollar|Dollar price (1299.5 KRW) has been updated.
2023-12-18 08:31:44,433 - info_core - INFO - update_exchange_info_as_df|name:upbit_spot_info_df has been updated. (0.01 secs), error_count:0
2023-12-18 08:31:45,460 - info_core - INFO - update_exchange_info_as_df|name:binance_coin_m_ticker_df has been updated. (0.05 secs), error_count:0
2023-12-18 08:31:46,741 - info_core - INFO - update_exchange_info_as_df|name:binance_coin_m_info_df has been updated. (0.06 secs), error_count:0
2023-12-18 08:31:46,937 - info_core - INFO - update_exchange_info_as_df|name:okx_spot_info_df has been updated. (0.14 secs), error_count:0
2023-12-18 08:31:47,297 - info_core - INFO - update_exchange_info_as_df|name:upbit_spot_ticker_df has been updated. (0.17 secs), error_count:0
2023-12-18 08:31:47,371 - info_core - INFO - update_exchange_info_as_df|name:binance_usd_m_info_df has been updated. (0.14 secs), error_count:0
2023-12-18 08:31:47,678 - info_core - INFO - update_exchange_info_as_df|name:bybit_coin_m_ticker_df has been updated. (0.15 secs), error_count:0
2023-12-18 08:31:47,790 - info_core - INFO - update_exchange_info_as_df|name:bybit_coin_m_info_df has been updated. (0.31 secs), error_count:0
2023-12-18 08:31:48,921 - info_core - INFO - update_exchange_info_as_df|name:okx_coin_m_ticker_df has been updated. (0.15 secs), error_count:0
2023-12-18 08:31:49,130 - info_core - INFO - update_exchange_info_as_df|name:okx_usd_m_ticker_df has been updated. (0.24 secs), error_count:0
2023-12-18 08:31:49,307 - info_core - INFO - update_exchange_info_as_df|name:okx_coin_m_info_df has been updated. (0.27 secs), error_count:0
2023-12-18 08:31:49,516 - info_core - INFO - update_exchange_info_as_df|name:okx_usd_m_info_df has been updated. (0.26 secs), error_count:0
2023-12-18 08:31:49,946 - info_core - INFO - update_exchange_info_as_df|name:binance_usd_m_ticker_df has been updated. (0.09 secs), error_count:0
2023-12-18 08:31:50,022 - info_core - INFO - update_exchange_info_as_df|name:okx_spot_ticker_df has been updated. (0.34 secs), error_count:0
2023-12-18 08:31:50,890 - info_core - INFO - update_exchange_info_as_df|name:bithumb_spot_info_df has been updated. (0.17 secs), error_count:0
2023-12-18 08:31:51,867 - info_core - INFO - update_exchange_info_as_df|name:bithumb_spot_ticker_df has been updated. (0.27 secs), error_count:0
2023-12-18 08:31:52,911 - info_core - INFO - update_exchange_info_as_df|name:bybit_spot_ticker_df has been updated. (0.16 secs), error_count:0
2023-12-18 08:31:53,426 - info_core - INFO - update_exchange_info_as_df|name:bybit_usd_m_ticker_df has been updated. (0.16 secs), error_count:0
2023-12-18 08:31:54,148 - info_core - INFO - update_exchange_info_as_df|name:bybit_spot_info_df has been updated. (0.40 secs), error_count:0
2023-12-18 08:31:54,588 - info_core - INFO - update_exchange_info_as_df|name:binance_spot_info_df has been updated. (0.37 secs), error_count:0
2023-12-18 08:31:56,554 - info_core - INFO - update_exchange_info_as_df|name:bybit_usd_m_info_df has been updated. (0.34 secs), error_count:0
2023-12-18 08:31:56,979 - info_core - INFO - update_exchange_info_as_df|name:binance_spot_ticker_df has been updated. (0.52 secs), error_count:0
2023-12-18 08:31:57,334 - update_dollar - INFO - fetch_dollar|Dollar price (1299.5 KRW) has been updated.
2023-12-18 08:32:14,475 - info_core - INFO - update_exchange_info_as_df|name:upbit_spot_info_df has been updated. (0.01 secs), error_count:0
2023-12-18 08:32:15,540 - info_core - INFO - update_exchange_info_as_df|name:binance_coin_m_ticker_df has been updated. (0.05 secs), error_count:0
2023-12-18 08:32:16,831 - info_core - INFO - update_exchange_info_as_df|name:binance_coin_m_info_df has been updated. (0.06 secs), error_count:0
2023-12-18 08:32:17,117 - info_core - INFO - update_exchange_info_as_df|name:okx_spot_info_df has been updated. (0.15 secs), error_count:0
2023-12-18 08:32:17,488 - info_core - INFO - update_exchange_info_as_df|name:upbit_spot_ticker_df has been updated. (0.16 secs), error_count:0
2023-12-18 08:32:17,568 - info_core - INFO - update_exchange_info_as_df|name:binance_usd_m_info_df has been updated. (0.14 secs), error_count:0
2023-12-18 08:32:17,848 - info_core - INFO - update_exchange_info_as_df|name:bybit_coin_m_ticker_df has been updated. (0.14 secs), error_count:0
2023-12-18 08:32:17,960 - info_core - INFO - update_exchange_info_as_df|name:bybit_coin_m_info_df has been updated. (0.15 secs), error_count:0
2023-12-18 08:32:19,100 - info_core - INFO - update_exchange_info_as_df|name:okx_coin_m_ticker_df has been updated. (0.16 secs), error_count:0
2023-12-18 08:32:19,297 - info_core - INFO - update_exchange_info_as_df|name:okx_usd_m_ticker_df has been updated. (0.14 secs), error_count:0
2023-12-18 08:32:19,600 - info_core - INFO - update_exchange_info_as_df|name:okx_coin_m_info_df has been updated. (0.26 secs), error_count:0
2023-12-18 08:32:19,803 - info_core - INFO - update_exchange_info_as_df|name:okx_usd_m_info_df has been updated. (0.26 secs), error_count:0
2023-12-18 08:32:20,071 - info_core - INFO - update_exchange_info_as_df|name:binance_usd_m_ticker_df has been updated. (0.09 secs), error_count:0
2023-12-18 08:32:20,259 - info_core - INFO - update_exchange_info_as_df|name:okx_spot_ticker_df has been updated. (0.20 secs), error_count:0
2023-12-18 08:32:21,144 - info_core - INFO - update_exchange_info_as_df|name:bithumb_spot_info_df has been updated. (0.24 secs), error_count:0
2023-12-18 08:32:22,268 - info_core - INFO - update_exchange_info_as_df|name:bithumb_spot_ticker_df has been updated. (0.37 secs), error_count:0
2023-12-18 08:32:23,123 - info_core - INFO - update_exchange_info_as_df|name:bybit_spot_ticker_df has been updated. (0.18 secs), error_count:0
2023-12-18 08:32:23,630 - info_core - INFO - update_exchange_info_as_df|name:bybit_usd_m_ticker_df has been updated. (0.18 secs), error_count:0
2023-12-18 08:32:24,692 - info_core - INFO - update_exchange_info_as_df|name:bybit_spot_info_df has been updated. (0.51 secs), error_count:0
2023-12-18 08:32:25,034 - info_core - INFO - update_exchange_info_as_df|name:binance_spot_info_df has been updated. (0.40 secs), error_count:0
2023-12-18 08:32:26,994 - info_core - INFO - update_exchange_info_as_df|name:bybit_usd_m_info_df has been updated. (0.43 secs), error_count:0
2023-12-18 08:32:27,532 - info_core - INFO - update_exchange_info_as_df|name:binance_spot_ticker_df has been updated. (0.52 secs), error_count:0
2023-12-18 08:32:28,294 - update_dollar - INFO - fetch_dollar|Dollar price (1299.5 KRW) has been updated.
2023-12-18 08:32:44,519 - info_core - INFO - update_exchange_info_as_df|name:upbit_spot_info_df has been updated. (0.01 secs), error_count:0
2023-12-18 08:32:45,610 - info_core - INFO - update_exchange_info_as_df|name:binance_coin_m_ticker_df has been updated. (0.06 secs), error_count:0
2023-12-18 08:32:46,892 - info_core - INFO - update_exchange_info_as_df|name:binance_coin_m_info_df has been updated. (0.06 secs), error_count:0
2023-12-18 08:32:47,302 - info_core - INFO - update_exchange_info_as_df|name:okx_spot_info_df has been updated. (0.15 secs), error_count:0
2023-12-18 08:32:47,661 - info_core - INFO - update_exchange_info_as_df|name:upbit_spot_ticker_df has been updated. (0.14 secs), error_count:0
2023-12-18 08:32:47,744 - info_core - INFO - update_exchange_info_as_df|name:binance_usd_m_info_df has been updated. (0.14 secs), error_count:0
2023-12-18 08:32:48,019 - info_core - INFO - update_exchange_info_as_df|name:bybit_coin_m_ticker_df has been updated. (0.14 secs), error_count:0
2023-12-18 08:32:48,145 - info_core - INFO - update_exchange_info_as_df|name:bybit_coin_m_info_df has been updated. (0.16 secs), error_count:0
2023-12-18 08:32:49,265 - info_core - INFO - update_exchange_info_as_df|name:okx_coin_m_ticker_df has been updated. (0.15 secs), error_count:0
2023-12-18 08:32:49,464 - info_core - INFO - update_exchange_info_as_df|name:okx_usd_m_ticker_df has been updated. (0.14 secs), error_count:0
2023-12-18 08:32:49,895 - info_core - INFO - update_exchange_info_as_df|name:okx_coin_m_info_df has been updated. (0.27 secs), error_count:0
2023-12-18 08:32:50,116 - info_core - INFO - update_exchange_info_as_df|name:okx_usd_m_info_df has been updated. (0.28 secs), error_count:0
2023-12-18 08:32:50,198 - info_core - INFO - update_exchange_info_as_df|name:binance_usd_m_ticker_df has been updated. (0.10 secs), error_count:0
2023-12-18 08:32:50,495 - info_core - INFO - update_exchange_info_as_df|name:okx_spot_ticker_df has been updated. (0.20 secs), error_count:0
2023-12-18 08:32:51,412 - info_core - INFO - update_exchange_info_as_df|name:bithumb_spot_info_df has been updated. (0.24 secs), error_count:0
2023-12-18 08:32:52,711 - info_core - INFO - update_exchange_info_as_df|name:bithumb_spot_ticker_df has been updated. (0.41 secs), error_count:0
2023-12-18 08:32:53,380 - info_core - INFO - update_exchange_info_as_df|name:bybit_spot_ticker_df has been updated. (0.23 secs), error_count:0
2023-12-18 08:32:54,038 - info_core - INFO - update_exchange_info_as_df|name:bybit_usd_m_ticker_df has been updated. (0.38 secs), error_count:0
2023-12-18 08:32:55,394 - info_core - INFO - update_exchange_info_as_df|name:bybit_spot_info_df has been updated. (0.67 secs), error_count:0
2023-12-18 08:32:55,713 - info_core - INFO - update_exchange_info_as_df|name:binance_spot_info_df has been updated. (0.65 secs), error_count:0
2023-12-18 08:32:57,604 - info_core - INFO - update_exchange_info_as_df|name:bybit_usd_m_info_df has been updated. (0.58 secs), error_count:0
2023-12-18 08:32:58,053 - info_core - INFO - update_exchange_info_as_df|name:binance_spot_ticker_df has been updated. (0.48 secs), error_count:0
2023-12-18 08:32:59,052 - update_dollar - INFO - fetch_dollar|Dollar price (1299.5 KRW) has been updated.
2023-12-18 08:33:14,563 - info_core - INFO - update_exchange_info_as_df|name:upbit_spot_info_df has been updated. (0.01 secs), error_count:0
2023-12-18 08:33:15,697 - info_core - INFO - update_exchange_info_as_df|name:binance_coin_m_ticker_df has been updated. (0.06 secs), error_count:0
2023-12-18 08:33:16,981 - info_core - INFO - update_exchange_info_as_df|name:binance_coin_m_info_df has been updated. (0.06 secs), error_count:0
2023-12-18 08:33:17,490 - info_core - INFO - update_exchange_info_as_df|name:okx_spot_info_df has been updated. (0.16 secs), error_count:0
2023-12-18 08:33:17,856 - info_core - INFO - update_exchange_info_as_df|name:upbit_spot_ticker_df has been updated. (0.16 secs), error_count:0
2023-12-18 08:33:17,975 - info_core - INFO - update_exchange_info_as_df|name:binance_usd_m_info_df has been updated. (0.12 secs), error_count:0
2023-12-18 08:33:18,334 - info_core - INFO - update_exchange_info_as_df|name:bybit_coin_m_ticker_df has been updated. (0.28 secs), error_count:0
2023-12-18 08:33:18,470 - info_core - INFO - update_exchange_info_as_df|name:bybit_coin_m_info_df has been updated. (0.29 secs), error_count:0
2023-12-18 08:33:19,441 - info_core - INFO - update_exchange_info_as_df|name:okx_coin_m_ticker_df has been updated. (0.15 secs), error_count:0
2023-12-18 08:33:19,628 - info_core - INFO - update_exchange_info_as_df|name:okx_usd_m_ticker_df has been updated. (0.13 secs), error_count:0
2023-12-18 08:33:20,189 - info_core - INFO - update_exchange_info_as_df|name:okx_coin_m_info_df has been updated. (0.26 secs), error_count:0
2023-12-18 08:33:20,322 - info_core - INFO - update_exchange_info_as_df|name:binance_usd_m_ticker_df has been updated. (0.09 secs), error_count:0
2023-12-18 08:33:20,452 - info_core - INFO - update_exchange_info_as_df|name:okx_usd_m_info_df has been updated. (0.31 secs), error_count:0
2023-12-18 08:33:20,719 - info_core - INFO - update_exchange_info_as_df|name:okx_spot_ticker_df has been updated. (0.19 secs), error_count:0
2023-12-18 08:33:21,642 - info_core - INFO - update_exchange_info_as_df|name:bithumb_spot_info_df has been updated. (0.20 secs), error_count:0
2023-12-18 08:33:22,920 - info_core - INFO - update_exchange_info_as_df|name:bithumb_spot_ticker_df has been updated. (0.18 secs), error_count:0
2023-12-18 08:33:23,947 - info_core - INFO - update_exchange_info_as_df|name:bybit_spot_ticker_df has been updated. (0.54 secs), error_count:0
2023-12-18 08:33:24,720 - info_core - INFO - update_exchange_info_as_df|name:bybit_usd_m_ticker_df has been updated. (0.65 secs), error_count:0
2023-12-18 08:33:25,986 - info_core - INFO - update_exchange_info_as_df|name:bybit_spot_info_df has been updated. (0.56 secs), error_count:0
2023-12-18 08:33:26,310 - info_core - INFO - update_exchange_info_as_df|name:binance_spot_info_df has been updated. (0.57 secs), error_count:0
2023-12-18 08:33:28,024 - info_core - INFO - update_exchange_info_as_df|name:bybit_usd_m_info_df has been updated. (0.39 secs), error_count:0
2023-12-18 08:33:28,497 - info_core - INFO - update_exchange_info_as_df|name:binance_spot_ticker_df has been updated. (0.43 secs), error_count:0
2023-12-18 08:33:29,919 - update_dollar - INFO - fetch_dollar|Dollar price (1299.5 KRW) has been updated.
2023-12-18 08:33:44,593 - info_core - INFO - update_exchange_info_as_df|name:upbit_spot_info_df has been updated. (0.01 secs), error_count:0
2023-12-18 08:33:45,785 - info_core - INFO - update_exchange_info_as_df|name:binance_coin_m_ticker_df has been updated. (0.06 secs), error_count:0