In [1]:
import os
import json
import sys
import argparse
import datetime
import pandas as pd
from kp_info_loader_core import InitCore
# from exchange_plugin.common_info import InitCommonInfo
# from monitor_engine.kimp_core_monitor import InitKimpCoreMonitor
# from etc.db_handler.create_schema_tables import InitDBClient
# from trigger_engine.snatcher import InitSnatcher
from etc.register_monitor_msg import RegisterMonitorMsg
from etc.redis_connector.redis_connector import InitRedis
import _pickle as pickle

# for jupyter notebook
import nest_asyncio
nest_asyncio.apply()

ModuleNotFoundError: No module named 'kp_info_loader_core'

In [2]:
redis_cli = InitRedis()

In [ ]:
temp = pickle.loads(redis_cli.get_data('INFO_CORE|UPBIT_SPOT/KRW:BITHUMB_SPOT/KRW_1T_now'))
tempexit

In [4]:
node = 'TEST'
register_monitor_msg.register(admin_id, node, 'info', f"kp_info_loader_main|node:{node} has started.", content=None, code=None, sent_switch=0, send_counts=1, remark=None)

NameError: name 'register_monitor_msg' is not defined

In [3]:
logging_dir = "/home/kp_info_loader/"
with open("/home/kp_info_loader/info_core_config.json") as f:
    config = json.load(f)
proc_n = 3
# node = config['node']
node = 'info_core'
monitor_bot_name = config['monitor_setting']['monitor_bot']
monitor_bot_token = config['telegram_bot_setting'][monitor_bot_name]
monitor_bot_api_url = config['monitor_setting']['monitor_bot_api_url']
admin_id = config['telegram_admin_id']['charlie1155']
register_monitor_msg = RegisterMonitorMsg(monitor_bot_token, monitor_bot_api_url, admin_id, logging_dir)
master_flag = config['node_settings'][node]['MASTER']
# Read api keys
exchange_api_key_dict = config['exchange_api_key']
# Exchange market settings
enabled_market_klines = config['node_settings'][node]['enabled_market_klines']
# total enabled market settings
total_enabled_market_klines = []
for each_market_code_list in config['node_settings'].values():
    total_enabled_market_klines += each_market_code_list['enabled_market_klines']

# db dict
db_dict = config['database_setting'][config['node_settings'][node]['db_settings']]

my_okx_demo_api_key = "bbb8a09a-6ea2-4686-add5-1095c918b7f4"
my_okx_demo_secret_key = "FBEAD86057449BAEC3FFA8A80CE76E4F"
my_okx_demo_passphrase = "121431Rn!!"

FileNotFoundError: [Errno 2] No such file or directory: '/home/kp_info_loader/kp_info_loader_config.json'

In [4]:
core = InitCore(logging_dir, master_flag, proc_n, node, admin_id, register_monitor_msg, exchange_api_key_dict, enabled_market_klines, total_enabled_market_klines, db_dict)

2023-11-21 18:47:24,344 - kp_info_loader - INFO - InitCore|InitCore initiated with proc_n=3
2023-11-21 18:47:24,522 - okx_plug - INFO - okx_plug_logger started.
2023-11-21 18:47:24,806 - upbit_plug - INFO - upbit_plug_logger started.
2023-11-21 18:47:24,924 - binance_plug - INFO - binance_plug_logger started.
2023-11-21 18:47:24,925 - bithumb_plug - INFO - bithumb_plug_logger started.
2023-11-21 18:47:24,927 - bybit_plug - INFO - bybit_plug_logger started.
2023-11-21 18:47:24,928 - kp_info_loader - INFO - InitCore|update_upbit_spot_info_df thread has started.
2023-11-21 18:47:24,930 - kp_info_loader - INFO - InitCore|update_upbit_spot_ticker_df thread has started.
2023-11-21 18:47:24,933 - kp_info_loader - INFO - InitCore|update_binance_spot_ticker_df thread has started.
2023-11-21 18:47:24,934 - kp_info_loader - INFO - InitCore|update_binance_spot_info_df thread has started.
2023-11-21 18:47:24,938 - kp_info_loader - INFO - InitCore|update_binance_usd_m_ticker_df thread has started.
2023-11-21 18:47:24,940 - kp_info_loader - INFO - InitCore|update_binance_usd_m_info_df thread has started.
2023-11-21 18:47:24,942 - kp_info_loader - INFO - InitCore|update_binance_coin_m_ticker_df thread has started.
2023-11-21 18:47:24,944 - kp_info_loader - INFO - InitCore|update_binance_coin_m_info_df thread has started.
2023-11-21 18:47:24,946 - kp_info_loader - INFO - InitCore|update_okx_spot_ticker_df thread has started.
2023-11-21 18:47:24,948 - kp_info_loader - INFO - InitCore|update_okx_spot_info_df thread has started.
2023-11-21 18:47:24,949 - kp_info_loader - INFO - InitCore|update_okx_usd_m_ticker_df thread has started.
2023-11-21 18:47:24,950 - kp_info_loader - INFO - InitCore|update_okx_usd_m_info_df thread has started.
2023-11-21 18:47:24,951 - kp_info_loader - INFO - InitCore|update_okx_coin_m_ticker_df thread has started.
2023-11-21 18:47:24,952 - kp_info_loader - INFO - InitCore|update_okx_coin_m_info_df thread has started.
2023-11-21 18:47:24,954 - kp_info_loader - INFO - InitCore|update_bithumb_spot_info_df thread has started.
2023-11-21 18:47:24,958 - kp_info_loader - INFO - InitCore|update_bithumb_spot_ticker_df thread has started.
2023-11-21 18:47:24,960 - kp_info_loader - INFO - InitCore|update_bybit_spot_info_df thread has started.
2023-11-21 18:47:24,963 - kp_info_loader - INFO - InitCore|update_bybit_spot_ticker_df thread has started.
2023-11-21 18:47:24,964 - kp_info_loader - INFO - InitCore|update_bybit_usd_m_info_df thread has started.
2023-11-21 18:47:24,981 - kp_info_loader - INFO - InitCore|update_bybit_usd_m_ticker_df thread has started.
2023-11-21 18:47:24,985 - kp_info_loader - INFO - InitCore|update_bybit_coin_m_info_df thread has started.
2023-11-21 18:47:24,986 - kp_info_loader - INFO - InitCore|update_bybit_coin_m_ticker_df thread has started.
2023-11-21 18:47:24,987 - kp_info_loader - INFO - InitCore|Waiting for all info to be updated.
2023-11-21 18:47:25,678 - bybit_plug - INFO - self.info_dict is None or self.info_dict.get('bybit_coin_m_info_df') is None, Fetched from API
2023-11-21 18:47:26,543 - bybit_plug - INFO - self.info_dict is None or self.info_dict.get('bybit_usd_m_info_df') is None, Fetched from API
2023-11-21 18:47:27,003 - kp_info_loader - INFO - InitCore|Waiting for all info to be updated.
2023-11-21 18:47:27,179 - update_dollar - INFO - fetch_dollar|Dollar price (1292.0 KRW) has been updated.
2023-11-21 18:47:27,181 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_usd_m_info_df') is None, Fetched from API
2023-11-21 18:47:27,352 - bybit_plug - INFO - self.info_dict is None or self.info_dict.get('bybit_spot_info_df') is None, Fetched from API
2023-11-21 18:47:28,481 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_ticker_df') is None, Fetched from API
2023-11-21 18:47:29,139 - kp_info_loader - INFO - InitCore|All info df has been updated.
2023-11-21 18:47:29,228 - binance_spot_websocket - INFO - [BINANCE SPOT]1th_bookticker_proc is not in self.websocket_proc_dict. starting..
2023-11-21 18:47:29,229 - binance_spot_websocket - INFO - [BINANCE SPOT]started monitor_shared_symbol_change..
2023-11-21 18:47:29,229 - binance_spot_websocket - INFO - started monitor_websocket_last_update..
2023-11-21 18:47:29,249 - binance_spot_websocket - INFO - [BINANCE SPOT]started 1th_bookticker_proc websocket proc..
2023-11-21 18:47:29,287 - binance_usd_m_websocket - INFO - [BINANCE USD_M]1th_bookticker_proc is not in self.websocket_proc_dict. starting..
2023-11-21 18:47:29,288 - binance_usd_m_websocket - INFO - [BINANCE USD_M]started monitor_shared_symbol_change..
2023-11-21 18:47:29,288 - binance_usd_m_websocket - INFO - started monitor_websocket_last_update..
2023-11-21 18:47:29,304 - binance_usd_m_websocket - INFO - [BINANCE USD_M]started 1th_bookticker_proc websocket proc..
2023-11-21 18:47:29,355 - bybit_usd_m_websocket - INFO - 1th Bybit ticker websocket does not exist. starting..
2023-11-21 18:47:29,356 - bybit_usd_m_websocket - INFO - [BYBIT USD_M]started monitor_shared_symbol_change..
2023-11-21 18:47:29,356 - bybit_usd_m_websocket - INFO - [BYBIT USD_M]started monitor_websocket_last_update..
2023-11-21 18:47:29,356 - bybit_usd_m_websocket - INFO - bybit_ticker_websocket|1th bybit_ticker_proc started.
2023-11-21 18:47:29,412 - upbit_websocket - INFO - 1th Upbit ticker websocket does not exist. starting..
2023-11-21 18:47:29,413 - upbit_websocket - INFO - [UPBIT SPOT]started monitor_shared_symbol_change..
2023-11-21 18:47:29,414 - kp_info_loader - INFO - InitCore|exchange_websocket_dict, dict_keys(['BINANCE_SPOT', 'BINANCE_USD_M', 'BYBIT_USD_M', 'UPBIT_SPOT']) has been initiated.
2023-11-21 18:47:29,413 - upbit_websocket - INFO - upbit_orderbook_ticker_websocket|1th upbit_ticker_proc started.
2023-11-21 18:47:29,413 - upbit_websocket - INFO - [UPBIT SPOT]started monitor_websocket_last_update..
2023-11-21 18:47:29,495 - upbit_websocket - INFO - upbit_websocket|upbit_websocket started
2023-11-21 18:47:29,752 - binance_spot_websocket - INFO - [BINANCE SPOT]2th_bookticker_proc is not in self.websocket_proc_dict. starting..
2023-11-21 18:47:29,762 - binance_spot_websocket - INFO - [BINANCE SPOT]started 2th_bookticker_proc websocket proc..
2023-11-21 18:47:29,806 - binance_usd_m_websocket - INFO - [BINANCE USD_M]2th_bookticker_proc is not in self.websocket_proc_dict. starting..
2023-11-21 18:47:29,817 - binance_usd_m_websocket - INFO - [BINANCE USD_M]started 2th_bookticker_proc websocket proc..
2023-11-21 18:47:29,874 - bybit_usd_m_websocket - INFO - 1th Bybit orderbook websocket does not exist. starting..
2023-11-21 18:47:29,875 - bybit_usd_m_websocket - INFO - bybit_orderbook_websocket|1th bybit_orderbook_proc started.
2023-11-21 18:47:29,960 - upbit_websocket - INFO - 1th Upbit orderbook websocket does not exist. starting..
2023-11-21 18:47:29,962 - upbit_websocket - INFO - upbit_orderbook_ticker_websocket|1th upbit_orderbook_proc started.
2023-11-21 18:47:30,005 - upbit_websocket - INFO - upbit_websocket|upbit_websocket started
2023-11-21 18:47:30,264 - binance_spot_websocket - INFO - [BINANCE SPOT]3th_bookticker_proc is not in self.websocket_proc_dict. starting..
2023-11-21 18:47:30,276 - binance_spot_websocket - INFO - [BINANCE SPOT]started 3th_bookticker_proc websocket proc..
2023-11-21 18:47:30,320 - binance_usd_m_websocket - INFO - [BINANCE USD_M]3th_bookticker_proc is not in self.websocket_proc_dict. starting..
2023-11-21 18:47:30,331 - binance_usd_m_websocket - INFO - [BINANCE USD_M]started 3th_bookticker_proc websocket proc..
2023-11-21 18:47:30,383 - bybit_usd_m_websocket - INFO - 2th Bybit ticker websocket does not exist. starting..
2023-11-21 18:47:30,384 - bybit_usd_m_websocket - INFO - bybit_ticker_websocket|2th bybit_ticker_proc started.
2023-11-21 18:47:30,474 - upbit_websocket - INFO - 2th Upbit ticker websocket does not exist. starting..
2023-11-21 18:47:30,475 - upbit_websocket - INFO - upbit_orderbook_ticker_websocket|2th upbit_ticker_proc started.
2023-11-21 18:47:30,537 - upbit_websocket - INFO - upbit_websocket|upbit_websocket started
2023-11-21 18:47:30,778 - binance_spot_websocket - INFO - [BINANCE SPOT]4th_bookticker_proc is not in self.websocket_proc_dict. starting..
2023-11-21 18:47:30,788 - binance_spot_websocket - INFO - [BINANCE SPOT]started 4th_bookticker_proc websocket proc..
2023-11-21 18:47:30,834 - binance_usd_m_websocket - INFO - [BINANCE USD_M]4th_bookticker_proc is not in self.websocket_proc_dict. starting..
2023-11-21 18:47:30,843 - binance_usd_m_websocket - INFO - [BINANCE USD_M]started 4th_bookticker_proc websocket proc..
2023-11-21 18:47:30,896 - bybit_usd_m_websocket - INFO - 2th Bybit orderbook websocket does not exist. starting..
2023-11-21 18:47:30,897 - bybit_usd_m_websocket - INFO - bybit_orderbook_websocket|2th bybit_orderbook_proc started.
2023-11-21 18:47:30,984 - upbit_websocket - INFO - 2th Upbit orderbook websocket does not exist. starting..
2023-11-21 18:47:30,986 - upbit_websocket - INFO - upbit_orderbook_ticker_websocket|2th upbit_orderbook_proc started.
2023-11-21 18:47:31,025 - upbit_websocket - INFO - upbit_websocket|upbit_websocket started
2023-11-21 18:47:31,290 - binance_spot_websocket - INFO - [BINANCE SPOT]5th_bookticker_proc is not in self.websocket_proc_dict. starting..
2023-11-21 18:47:31,299 - binance_spot_websocket - INFO - [BINANCE SPOT]started 5th_bookticker_proc websocket proc..
2023-11-21 18:47:31,345 - binance_usd_m_websocket - INFO - [BINANCE USD_M]5th_bookticker_proc is not in self.websocket_proc_dict. starting..
2023-11-21 18:47:31,356 - binance_usd_m_websocket - INFO - [BINANCE USD_M]started 5th_bookticker_proc websocket proc..
2023-11-21 18:47:31,408 - bybit_usd_m_websocket - INFO - 3th Bybit ticker websocket does not exist. starting..
2023-11-21 18:47:31,409 - bybit_usd_m_websocket - INFO - bybit_ticker_websocket|3th bybit_ticker_proc started.
2023-11-21 18:47:31,498 - upbit_websocket - INFO - 3th Upbit ticker websocket does not exist. starting..
2023-11-21 18:47:31,500 - upbit_websocket - INFO - upbit_orderbook_ticker_websocket|3th upbit_ticker_proc started.
2023-11-21 18:47:31,544 - upbit_websocket - INFO - upbit_websocket|upbit_websocket started
2023-11-21 18:47:31,801 - binance_spot_websocket - INFO - [BINANCE SPOT]6th_bookticker_proc is not in self.websocket_proc_dict. starting..
2023-11-21 18:47:31,813 - binance_spot_websocket - INFO - [BINANCE SPOT]started 6th_bookticker_proc websocket proc..
2023-11-21 18:47:31,858 - binance_usd_m_websocket - INFO - [BINANCE USD_M]6th_bookticker_proc is not in self.websocket_proc_dict. starting..
2023-11-21 18:47:31,870 - binance_usd_m_websocket - INFO - [BINANCE USD_M]started 6th_bookticker_proc websocket proc..
2023-11-21 18:47:31,921 - bybit_usd_m_websocket - INFO - 3th Bybit orderbook websocket does not exist. starting..
2023-11-21 18:47:31,921 - bybit_usd_m_websocket - INFO - bybit_orderbook_websocket|3th bybit_orderbook_proc started.
2023-11-21 18:47:32,011 - upbit_websocket - INFO - 3th Upbit orderbook websocket does not exist. starting..
2023-11-21 18:47:32,012 - upbit_websocket - INFO - upbit_orderbook_ticker_websocket|3th upbit_orderbook_proc started.
2023-11-21 18:47:32,054 - upbit_websocket - INFO - upbit_websocket|upbit_websocket started
2023-11-21 18:47:32,317 - binance_spot_websocket - INFO - [BINANCE SPOT]ticker_proc is not in self.websocket_proc_dict. starting..
2023-11-21 18:47:32,328 - binance_spot_websocket - INFO - [BINANCE SPOT]started ticker_proc websocket proc..
2023-11-21 18:47:32,373 - binance_usd_m_websocket - INFO - [BINANCE USD_M]ticker_proc is not in self.websocket_proc_dict. starting..
2023-11-21 18:47:32,383 - binance_usd_m_websocket - INFO - [BINANCE USD_M]started ticker_proc websocket proc..
2023-11-21 18:47:32,384 - binance_usd_m_websocket - INFO - [BINANCE USD_M]liquidation_proc is not in self.websocket_proc_dict. starting..
2023-11-21 18:47:32,392 - binance_usd_m_websocket - INFO - [BINANCE USD_M]started liquidation_proc websocket proc..
2023-11-21 18:47:32,399 - binance_usd_m_websocket - INFO - started liquidation_websocket for USD_M..
2023-11-21 18:47:39,425 - kp_info_loader - INFO - update_fundingrate|BINANCE update_fundingrate thread has started.
2023-11-21 18:47:39,426 - kp_info_loader - INFO - update_fundingrate|OKX update_fundingrate thread has started.
2023-11-21 18:47:39,429 - kp_info_loader - INFO - update_fundingrate|BYBIT update_fundingrate thread has started.
2023-11-21 18:47:39,430 - kp_info_loader - INFO - update_wallet_status|UPBIT update_wallet_status thread has started.
2023-11-21 18:47:39,431 - kp_info_loader - INFO - update_wallet_status|BINANCE update_wallet_status thread has started.
2023-11-21 18:47:39,432 - kp_info_loader - INFO - update_wallet_status|OKX update_wallet_status thread has started.
2023-11-21 18:47:39,437 - arbitrage_core - INFO - InitArbitrageCore Started.
2023-11-21 18:47:39,433 - kp_info_loader - INFO - update_wallet_status|BITHUMB update_wallet_status thread has started.
2023-11-21 18:47:39,434 - kp_info_loader - INFO - update_wallet_status|BYBIT update_wallet_status thread has started.
2023-11-21 18:47:39,465 - arbitrage_core - INFO - store_funding_diff_loop started.
2023-11-21 18:47:39,493 - kline_core - INFO - InitKlineCore started.
2023-11-21 18:47:39,497 - arbitrage_core - INFO - store_average_funding_rate_loop started.
2023-11-21 18:47:42,157 - kline_core - INFO - ohlc_min_resample_loader has started. UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_5T_kline, initial generating and storing resampled_ohlc_history_df(length: 5002): 0.9318187236785889
2023-11-21 18:47:43,390 - kline_core - INFO - ohlc_min_resample_loader has started. UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_15T_kline, initial generating and storing resampled_ohlc_history_df(length: 1722): 0.7869393825531006
2023-11-21 18:47:44,539 - kline_core - INFO - ohlc_min_resample_loader has started. UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_30T_kline, initial generating and storing resampled_ohlc_history_df(length: 902): 0.791114091873169
2023-11-21 18:47:45,840 - kline_core - INFO - ohlc_hour_resample_loader has started. UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_1H_kline, initial generating and storing resampled_ohlc_history_df(length: 492): 0.9205367565155029
2023-11-21 18:47:46,889 - kline_core - INFO - resampling ohlc_df(length: 902): 0.8362443447113037
2023-11-21 18:47:46,891 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_30T_kline time: 0.00047397613525390625
2023-11-21 18:47:46,890 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_30T_kline time: 0.0004639625549316406
2023-11-21 18:47:46,901 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_30T_kline base_asset is not matched. added: ['MBL'], removed: []
2023-11-21 18:47:46,913 - kline_core - INFO - resampling ohlc_df(length: 1722): 0.8770718574523926
2023-11-21 18:47:46,914 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_15T_kline time: 0.0005838871002197266
2023-11-21 18:47:46,915 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_15T_kline time: 0.0003662109375

resampling ohlc_df(length: 492): 0.8702423572540283

2023-11-21 18:47:46,927 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_15T_kline base_asset is not matched. added: ['MBL'], removed: []
2023-11-21 18:47:46,932 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_1H_kline base_asset is not matched. added: ['MBL'], removed: []
2023-11-21 18:47:47,074 - kline_core - INFO - resampling ohlc_df(length: 5063): 0.9862587451934814
2023-11-21 18:47:47,076 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_5T_kline time: 0.0011448860168457031
2023-11-21 18:47:47,078 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_5T_kline time: 0.0006477832794189453
2023-11-21 18:47:47,397 - kline_core - INFO - ohlc_hour_resample_loader has started. UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_4H_kline, initial generating and storing resampled_ohlc_history_df(length: 164): 0.9107208251953125
2023-11-21 18:47:48,051 - kline_core - INFO - resampling ohlc_df(length: 5124): 0.8594369888305664
2023-11-21 18:47:48,052 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_5T_kline time: 0.0010635852813720703
2023-11-21 18:47:48,053 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_5T_kline time: 0.0006165504455566406

resampling ohlc_df(length: 164): 0.7579967975616455

2023-11-21 18:47:48,268 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_4H_kline base_asset is not matched. added: ['ARDR', 'MBL'], removed: []
2023-11-21 18:47:49,286 - kline_core - INFO - ohlc_day_resample_loader has started. UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_1D_kline, initial generating and storing resampled_ohlc_history_df(length: 82): 0.774146556854248

resampling ohlc_df(length: 82): 0.7778806686401367

2023-11-21 18:47:50,179 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_1D_kline base_asset is not matched. added: ['ARDR', 'MBL'], removed: []
2023-11-21 18:47:52,309 - kline_core - INFO - ohlc_min_resample_loader has started. UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_5T_kline, initial generating and storing resampled_ohlc_history_df(length: 4392): 0.807373046875
2023-11-21 18:47:52,371 - kline_core - INFO - resampling ohlc_df(length: 5185): 1.0026779174804688
2023-11-21 18:47:52,374 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_5T_kline time: 0.0014758110046386719
2023-11-21 18:47:52,375 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_5T_kline time: 0.0005612373352050781
2023-11-21 18:47:52,900 - kline_core - INFO - resampling ohlc_df(length: 902): 0.8913662433624268
2023-11-21 18:47:52,901 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_30T_kline time: 0.0005633831024169922
2023-11-21 18:47:52,903 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_30T_kline time: 0.0003247261047363281
2023-11-21 18:47:52,919 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_30T_kline base_asset is not matched. added: ['ARDR', 'MBL', 'PLA'], removed: []

resampling ohlc_df(length: 492): 0.9308843612670898

2023-11-21 18:47:52,984 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_1H_kline base_asset is not matched. added: ['ARDR', 'MBL', 'PLA'], removed: []
2023-11-21 18:47:52,997 - kline_core - INFO - resampling ohlc_df(length: 1764): 0.9640994071960449
2023-11-21 18:47:52,998 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_15T_kline time: 0.0005908012390136719
2023-11-21 18:47:52,999 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_15T_kline time: 0.0003635883331298828
2023-11-21 18:47:53,013 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_15T_kline base_asset is not matched. added: ['PLA'], removed: []
2023-11-21 18:47:53,421 - kline_core - INFO - ohlc_min_resample_loader has started. UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_15T_kline, initial generating and storing resampled_ohlc_history_df(length: 1512): 0.7924797534942627

resampling ohlc_df(length: 164): 0.8592736721038818

2023-11-21 18:47:54,245 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_4H_kline base_asset is not matched. added: ['ARDR', 'MBL', 'PLA'], removed: []
2023-11-21 18:47:54,625 - kline_core - INFO - ohlc_min_resample_loader has started. UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_30T_kline, initial generating and storing resampled_ohlc_history_df(length: 792): 0.7609066963195801
2023-11-21 18:47:54,737 - kline_core - INFO - resampling ohlc_df(length: 1512): 0.7680544853210449
2023-11-21 18:47:54,758 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_5T_kline time: 0.0004277229309082031
2023-11-21 18:47:54,739 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_15T_kline time: 0.0005638599395751953
2023-11-21 18:47:54,740 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_15T_kline time: 0.00032973289489746094
2023-11-21 18:47:54,751 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_15T_kline base_asset is not matched. added: ['FLOW'], removed: []
2023-11-21 18:47:54,755 - kline_core - INFO - resampling ohlc_df(length: 4453): 0.7901809215545654
2023-11-21 18:47:54,757 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_5T_kline time: 0.0010037422180175781
2023-11-21 18:47:55,501 - kline_core - INFO - resampling ohlc_df(length: 792): 0.7712984085083008
2023-11-21 18:47:55,502 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_30T_kline time: 0.00038123130798339844
2023-11-21 18:47:55,503 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_30T_kline time: 0.00018024444580078125
2023-11-21 18:47:55,512 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_30T_kline base_asset is not matched. added: ['FLOW'], removed: []
2023-11-21 18:47:56,064 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_1D_kline base_asset is not matched. added: ['ARDR', 'MBL', 'PLA'], removed: []

resampling ohlc_df(length: 82): 0.7672216892242432

2023-11-21 18:47:56,693 - kline_core - INFO - ohlc_hour_resample_loader has started. UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_1H_kline, initial generating and storing resampled_ohlc_history_df(length: 432): 0.7713878154754639

resampling ohlc_df(length: 432): 0.7454752922058105

2023-11-21 18:47:57,553 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_1H_kline base_asset is not matched. added: ['FLOW'], removed: []
2023-11-21 18:47:57,796 - kline_core - INFO - resampling ohlc_df(length: 5246): 1.0215535163879395
2023-11-21 18:47:57,798 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_5T_kline time: 0.0012826919555664062
2023-11-21 18:47:57,799 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_5T_kline time: 0.0005276203155517578
2023-11-21 18:47:58,852 - kline_core - INFO - resampling ohlc_df(length: 5307): 0.9392871856689453
2023-11-21 18:47:58,854 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_5T_kline time: 0.0011196136474609375
2023-11-21 18:47:58,856 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_5T_kline time: 0.0007026195526123047

resampling ohlc_df(length: 492): 0.8764495849609375

2023-11-21 18:47:59,024 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_15T_kline base_asset is not matched. added: ['JST'], removed: []
2023-11-21 18:47:59,006 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_15T_kline time: 0.000301361083984375
2023-11-21 18:47:58,978 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_1H_kline base_asset is not matched. added: ['ARDR', 'IQ', 'JST', 'MBL', 'PLA'], removed: []
2023-11-21 18:47:58,985 - kline_core - INFO - resampling ohlc_df(length: 924): 0.96095871925354
2023-11-21 18:47:58,987 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_30T_kline time: 0.00045680999755859375
2023-11-21 18:47:58,987 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_30T_kline time: 0.00026917457580566406
2023-11-21 18:47:58,997 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_30T_kline base_asset is not matched. added: ['IQ', 'JST', 'PLA'], removed: []
2023-11-21 18:47:59,004 - kline_core - INFO - resampling ohlc_df(length: 1806): 0.8828613758087158
2023-11-21 18:47:59,005 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_15T_kline time: 0.0006840229034423828
2023-11-21 18:47:59,517 - kline_core - INFO - ohlc_hour_resample_loader has started. UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_4H_kline, initial generating and storing resampled_ohlc_history_df(length: 144): 0.7988638877868652

resampling ohlc_df(length: 164): 0.8285953998565674

2023-11-21 18:48:00,189 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_4H_kline base_asset is not matched. added: ['ARDR', 'IQ', 'JST', 'MBL', 'PLA'], removed: []

resampling ohlc_df(length: 144): 0.7027506828308105

2023-11-21 18:48:00,334 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_4H_kline base_asset is not matched. added: ['FLOW'], removed: []
2023-11-21 18:48:00,601 - kline_core - INFO - resampling ohlc_df(length: 1533): 0.7443077564239502
2023-11-21 18:48:00,603 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_15T_kline time: 0.00048732757568359375
2023-11-21 18:48:02,923 - update_dollar - INFO - fetch_dollar|Dollar price (1292.0 KRW) has been updated.
2023-11-21 18:48:00,604 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_15T_kline time: 0.0002410411834716797
2023-11-21 18:48:00,845 - kline_core - INFO - resampling ohlc_df(length: 5368): 1.1498336791992188
2023-11-21 18:48:00,847 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_5T_kline time: 0.0012285709381103516
2023-11-21 18:48:00,848 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_5T_kline time: 0.0006628036499023438
2023-11-21 18:48:01,406 - kline_core - INFO - resampling ohlc_df(length: 803): 0.7863430976867676
2023-11-21 18:48:01,407 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_30T_kline time: 0.0004489421844482422
2023-11-21 18:48:01,408 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_30T_kline time: 0.0003151893615722656

resampling ohlc_df(length: 82): 0.8154544830322266

2023-11-21 18:48:01,998 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_1D_kline base_asset is not matched. added: ['ARDR', 'IQ', 'JST', 'MBL', 'PLA', 'PUNDIX'], removed: []
2023-11-21 18:48:02,208 - kline_core - INFO - ohlc_day_resample_loader has started. UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_1D_kline, initial generating and storing resampled_ohlc_history_df(length: 72): 0.8938713073730469

resampling ohlc_df(length: 72): 0.687185525894165

2023-11-21 18:48:03,007 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_1D_kline base_asset is not matched. added: ['FLOW'], removed: []

resampling ohlc_df(length: 438): 0.7668654918670654

2023-11-21 18:48:05,001 - kline_core - INFO - resampling ohlc_df(length: 946): 0.8974754810333252
2023-11-21 18:48:05,003 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_30T_kline time: 0.0005459785461425781
2023-11-21 18:48:05,004 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_30T_kline time: 0.0003173351287841797
2023-11-21 18:48:05,020 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_30T_kline base_asset is not matched. added: ['JST', 'PUNDIX'], removed: []

resampling ohlc_df(length: 504): 0.9700686931610107

2023-11-21 18:48:05,064 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_1H_kline base_asset is not matched. added: ['IQ', 'JST', 'PLA', 'PUNDIX'], removed: []
2023-11-21 18:48:05,116 - kline_core - INFO - resampling ohlc_df(length: 1848): 0.9821248054504395
2023-11-21 18:48:05,118 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_15T_kline time: 0.0007257461547851562
2023-11-21 18:48:05,119 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_15T_kline time: 0.00047898292541503906
2023-11-21 18:48:05,478 - kline_core - INFO - ohlc_min_resample_loader has started. UPBIT_SPOT/KRW:BYBIT_USD_M/USDT_5T_kline, initial generating and storing resampled_ohlc_history_df(length: 5002): 0.9415161609649658

resampling ohlc_df(length: 146): 0.7561259269714355
resampling ohlc_df(length: 168): 1.0565195083618164

2023-11-21 18:48:06,360 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_4H_kline base_asset is not matched. added: ['IQ', 'JST', 'PLA', 'PUNDIX'], removed: []
2023-11-21 18:48:07,116 - kline_core - INFO - ohlc_min_resample_loader has started. UPBIT_SPOT/KRW:BYBIT_USD_M/USDT_15T_kline, initial generating and storing resampled_ohlc_history_df(length: 1722): 0.8935000896453857

resampling ohlc_df(length: 84): 0.8720088005065918

2023-11-21 18:48:07,988 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_1D_kline base_asset is not matched. added: ['IQ', 'JST', 'PLA', 'PUNDIX'], removed: []

resampling ohlc_df(length: 146): 0.8264577388763428

2023-11-21 18:48:08,542 - kline_core - INFO - resampling ohlc_df(length: 1533): 0.8383803367614746
2023-11-21 18:48:08,543 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_15T_kline time: 0.0005192756652832031
2023-11-21 18:48:08,545 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_15T_kline time: 0.0003604888916015625
2023-11-21 18:48:08,545 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_4H_kline base_asset is not matched. added: ['BAT'], removed: []
2023-11-21 18:48:08,554 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_15T_kline base_asset is not matched. added: ['BAT'], removed: []
2023-11-21 18:48:08,571 - kline_core - INFO - resampling ohlc_df(length: 4526): 0.8604445457458496
2023-11-21 18:48:08,573 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_5T_kline time: 0.0009555816650390625
2023-11-21 18:48:08,574 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_5T_kline time: 0.00033664703369140625
2023-11-21 18:48:08,582 - kline_core - INFO - resampling ohlc_df(length: 803): 0.7905716896057129
2023-11-21 18:48:08,583 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_30T_kline time: 0.0004973411560058594
2023-11-21 18:48:08,584 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_30T_kline time: 0.0002925395965576172
2023-11-21 18:48:08,592 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_5T_kline base_asset is not matched. added: ['BAT'], removed: []
2023-11-21 18:48:08,593 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_30T_kline base_asset is not matched. added: ['BAT'], removed: []

resampling ohlc_df(length: 438): 0.857590913772583

2023-11-21 18:48:08,611 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_1H_kline base_asset is not matched. added: ['BAT'], removed: []
2023-11-21 18:48:08,751 - kline_core - INFO - ohlc_min_resample_loader has started. UPBIT_SPOT/KRW:BYBIT_USD_M/USDT_30T_kline, initial generating and storing resampled_ohlc_history_df(length: 902): 0.9130403995513916

resampling ohlc_df(length: 73): 0.7454924583435059

2023-11-21 18:48:08,868 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_1D_kline base_asset is not matched. added: ['BAT'], removed: []
2023-11-21 18:48:10,407 - kline_core - INFO - ohlc_hour_resample_loader has started. UPBIT_SPOT/KRW:BYBIT_USD_M/USDT_1H_kline, initial generating and storing resampled_ohlc_history_df(length: 492): 0.907872200012207

resampling ohlc_df(length: 516): 0.839153528213501

2023-11-21 18:48:11,028 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_1H_kline base_asset is not matched. added: ['JST', 'PUNDIX'], removed: []
2023-11-21 18:48:11,051 - kline_core - INFO - resampling ohlc_df(length: 968): 0.9232585430145264
2023-11-21 18:48:11,053 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_30T_kline time: 0.0005214214324951172
2023-11-21 18:48:11,054 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_30T_kline time: 0.00022459030151367188

resampling ohlc_df(length: 172): 0.8644106388092041

2023-11-21 18:48:12,342 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_4H_kline base_asset is not matched. added: ['JST', 'PUNDIX'], removed: []
2023-11-21 18:48:12,454 - kline_core - INFO - ohlc_hour_resample_loader has started. UPBIT_SPOT/KRW:BYBIT_USD_M/USDT_4H_kline, initial generating and storing resampled_ohlc_history_df(length: 164): 0.8717913627624512

resampling ohlc_df(length: 86): 0.9058234691619873

2023-11-21 18:48:14,010 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_1D_kline base_asset is not matched. added: ['JST', 'PUNDIX'], removed: []
2023-11-21 18:48:14,174 - kline_core - INFO - ohlc_day_resample_loader has started. UPBIT_SPOT/KRW:BYBIT_USD_M/USDT_1D_kline, initial generating and storing resampled_ohlc_history_df(length: 82): 0.8467140197753906

resampling ohlc_df(length: 146): 0.7939088344573975

2023-11-21 18:48:14,452 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_4H_kline base_asset is not matched. added: ['BAT'], removed: []
2023-11-21 18:48:14,455 - kline_core - INFO - resampling ohlc_df(length: 1606): 0.7945656776428223
2023-11-21 18:48:14,457 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_15T_kline time: 0.0007348060607910156
2023-11-21 18:48:14,458 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_15T_kline time: 0.00024628639221191406
2023-11-21 18:48:14,469 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_15T_kline base_asset is not matched. added: ['BAT'], removed: []
2023-11-21 18:48:14,474 - kline_core - INFO - resampling ohlc_df(length: 803): 0.772493839263916
2023-11-21 18:48:14,475 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_30T_kline time: 0.0004055500030517578
2023-11-21 18:48:14,476 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_30T_kline time: 0.00021839141845703125
2023-11-21 18:48:14,485 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_30T_kline base_asset is not matched. added: ['BAT'], removed: []

resampling ohlc_df(length: 438): 0.806260347366333

2023-11-21 18:48:14,535 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_1H_kline base_asset is not matched. added: ['BAT'], removed: []
2023-11-21 18:48:14,537 - kline_core - INFO - resampling ohlc_df(length: 4526): 0.8274796009063721
2023-11-21 18:48:14,539 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_5T_kline time: 0.0010728836059570312
2023-11-21 18:48:14,541 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_5T_kline time: 0.0005638599395751953
2023-11-21 18:48:14,558 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_5T_kline base_asset is not matched. added: ['BAT'], removed: []

resampling ohlc_df(length: 73): 0.708892822265625

2023-11-21 18:48:14,692 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_1D_kline base_asset is not matched. added: ['BAT'], removed: []

resampling ohlc_df(length: 528): 0.948793888092041

2023-11-21 18:48:17,740 - kline_core - INFO - ohlc_min_resample_loader has started. UPBIT_SPOT/KRW:UPBIT_SPOT/BTC_5T_kline, initial generating and storing resampled_ohlc_history_df(length: 5917): 1.1645236015319824

resampling ohlc_df(length: 176): 0.887331485748291

2023-11-21 18:48:19,190 - kline_core - INFO - ohlc_min_resample_loader has started. UPBIT_SPOT/KRW:UPBIT_SPOT/BTC_15T_kline, initial generating and storing resampled_ohlc_history_df(length: 2037): 1.074021577835083

resampling ohlc_df(length: 528): 0.9839413166046143

2023-11-21 18:48:20,047 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_1H_kline base_asset is not matched. added: ['ONG'], removed: []

resampling ohlc_df(length: 88): 1.0102112293243408

2023-11-21 18:48:20,162 - kline_core - INFO - resampling ohlc_df(length: 968): 1.0914051532745361
2023-11-21 18:48:20,170 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_30T_kline time: 0.0006916522979736328
2023-11-21 18:48:20,172 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_30T_kline time: 0.00041866302490234375
2023-11-21 18:48:20,172 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_1D_kline base_asset is not matched. added: ['ONG'], removed: []

resampling ohlc_df(length: 176): 1.1227993965148926

2023-11-21 18:48:20,204 - kline_core - INFO - resampling ohlc_df(length: 1848): 1.1767916679382324
2023-11-21 18:48:20,208 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_15T_kline time: 0.000993490219116211

2023-11-21 18:48:20,198 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_30T_kline base_asset is not matched. added: ['ONG'], removed: []
2023-11-21 18:48:20,210 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_15T_kline time: 0.00035309791564941406
2023-11-21 18:48:20,223 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_4H_kline base_asset is not matched. added: ['ONG'], removed: []
2023-11-21 18:48:20,234 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_15T_kline base_asset is not matched. added: ['ONG'], removed: []
2023-11-21 18:48:20,286 - kline_core - INFO - resampling ohlc_df(length: 5456): 1.1532440185546875
2023-11-21 18:48:20,288 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_5T_kline time: 0.0011935234069824219
2023-11-21 18:48:20,290 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_5T_kline time: 0.0007784366607666016
2023-11-21 18:48:20,318 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_5T_kline base_asset is not matched. added: ['ONG'], removed: []

resampling ohlc_df(length: 146): 0.9477536678314209

2023-11-21 18:48:20,520 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_4H_kline base_asset is not matched. added: ['BAT', 'WAXP'], removed: []
2023-11-21 18:48:20,534 - kline_core - INFO - resampling ohlc_df(length: 803): 0.9419589042663574
2023-11-21 18:48:20,536 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_30T_kline time: 0.0006356239318847656
2023-11-21 18:48:20,538 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_30T_kline time: 0.0003337860107421875
2023-11-21 18:48:20,545 - kline_core - INFO - resampling ohlc_df(length: 1606): 0.9677364826202393
2023-11-21 18:48:20,547 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_15T_kline time: 0.0006580352783203125
2023-11-21 18:48:20,548 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_15T_kline time: 0.0003859996795654297
2023-11-21 18:48:20,551 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_30T_kline base_asset is not matched. added: ['BAT', 'WAXP'], removed: []
2023-11-21 18:48:20,561 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_15T_kline base_asset is not matched. added: ['BAT', 'WAXP'], removed: []

resampling ohlc_df(length: 438): 0.9815635681152344

2023-11-21 18:48:20,634 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_1H_kline base_asset is not matched. added: ['BAT', 'WAXP'], removed: []

resampling ohlc_df(length: 73): 0.9298839569091797

2023-11-21 18:48:20,738 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_1D_kline base_asset is not matched. added: ['BAT', 'WAXP'], removed: []
2023-11-21 18:48:20,779 - kline_core - INFO - resampling ohlc_df(length: 4526): 1.1045801639556885
2023-11-21 18:48:20,781 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_5T_kline time: 0.0011188983917236328
2023-11-21 18:48:20,782 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_5T_kline time: 0.0005612373352050781
2023-11-21 18:48:20,804 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_5T_kline base_asset is not matched. added: ['BAT', 'WAXP'], removed: []
2023-11-21 18:48:21,404 - kline_core - INFO - ohlc_min_resample_loader has started. UPBIT_SPOT/KRW:UPBIT_SPOT/BTC_30T_kline, initial generating and storing resampled_ohlc_history_df(length: 1067): 1.0285484790802002
2023-11-21 18:48:22,871 - kline_core - INFO - ohlc_hour_resample_loader has started. UPBIT_SPOT/KRW:UPBIT_SPOT/BTC_1H_kline, initial generating and storing resampled_ohlc_history_df(length: 582): 0.9949979782104492
2023-11-21 18:48:24,297 - kline_core - INFO - ohlc_hour_resample_loader has started. UPBIT_SPOT/KRW:UPBIT_SPOT/BTC_4H_kline, initial generating and storing resampled_ohlc_history_df(length: 194): 1.0058131217956543
2023-11-21 18:48:25,860 - kline_core - INFO - ohlc_day_resample_loader has started. UPBIT_SPOT/KRW:UPBIT_SPOT/BTC_1D_kline, initial generating and storing resampled_ohlc_history_df(length: 97): 1.000511884689331

resampling ohlc_df(length: 528): 0.9573121070861816

2023-11-21 18:48:26,149 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_1H_kline base_asset is not matched. added: ['ONG'], removed: []

resampling ohlc_df(length: 88): 1.001894474029541

2023-11-21 18:48:26,305 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_1D_kline base_asset is not matched. added: ['ONG'], removed: []
2023-11-21 18:48:26,310 - kline_core - INFO - resampling ohlc_df(length: 968): 0.9900252819061279
2023-11-21 18:48:26,312 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_30T_kline time: 0.0016243457794189453
2023-11-21 18:48:26,314 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_30T_kline time: 0.0002415180206298828
2023-11-21 18:48:26,326 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_30T_kline base_asset is not matched. added: ['ONG'], removed: []

resampling ohlc_df(length: 176): 1.0394833087921143

2023-11-21 18:48:26,379 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_4H_kline base_asset is not matched. added: ['ONG'], removed: []

2023-11-21 18:48:26,440 - kline_core - INFO - resampling ohlc_df(length: 1936): 1.098606824874878
2023-11-21 18:48:26,441 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_15T_kline time: 0.0008463859558105469
2023-11-21 18:48:26,443 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_15T_kline time: 0.0004723072052001953
2023-11-21 18:48:26,458 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_15T_kline base_asset is not matched. added: ['ONG'], removed: []
2023-11-21 18:48:26,503 - kline_core - INFO - resampling ohlc_df(length: 5456): 1.0698847770690918
2023-11-21 18:48:26,506 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_5T_kline time: 0.001374959945678711
2023-11-21 18:48:26,507 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_5T_kline time: 0.0009083747863769531
2023-11-21 18:48:26,534 - kline_core - INFO - resampling ohlc_df(length: 803): 0.8779833316802979
2023-11-21 18:48:26,536 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_30T_kline time: 0.0004775524139404297
2023-11-21 18:48:26,537 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_30T_kline time: 0.0002930164337158203
2023-11-21 18:48:26,540 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_5T_kline base_asset is not matched. added: ['ONG'], removed: []
2023-11-21 18:48:26,550 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_30T_kline base_asset is not matched. added: ['BAT', 'WAXP'], removed: []

resampling ohlc_df(length: 146): 0.925013542175293

2023-11-21 18:48:26,563 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_4H_kline base_asset is not matched. added: ['BAT', 'WAXP'], removed: []
2023-11-21 18:48:26,624 - kline_core - INFO - resampling ohlc_df(length: 1606): 0.955543041229248
2023-11-21 18:48:26,626 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_15T_kline time: 0.000762939453125
2023-11-21 18:48:26,627 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_15T_kline time: 0.00029587745666503906
2023-11-21 18:48:26,642 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_15T_kline base_asset is not matched. added: ['BAT', 'WAXP'], removed: []

resampling ohlc_df(length: 438): 0.9322350025177002
resampling ohlc_df(length: 73): 0.8303713798522949

2023-11-21 18:48:26,680 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_1D_kline base_asset is not matched. added: ['BAT', 'WAXP'], removed: []
2023-11-21 18:48:26,680 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_1H_kline base_asset is not matched. added: ['BAT', 'WAXP'], removed: []
2023-11-21 18:48:26,762 - kline_core - INFO - resampling ohlc_df(length: 4526): 0.8375484943389893
2023-11-21 18:48:26,763 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_5T_kline time: 0.0010013580322265625
2023-11-21 18:48:26,765 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_5T_kline time: 0.0007848739624023438
2023-11-21 18:48:26,784 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_5T_kline base_asset is not matched. added: ['BAT', 'WAXP'], removed: []
2023-11-21 18:48:26,892 - kline_core - INFO - subscribe_kline_channel|Subscribing to kline channels Started..
2023-11-21 18:48:26,894 - kline_core - INFO - subscribe_kline_channel|Subscribing to INFO_CORE|UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_1T_kline
2023-11-21 18:48:26,894 - kline_core - INFO - subscribe_kline_channel|Subscribing to INFO_CORE|UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_5T_kline
2023-11-21 18:48:26,895 - kline_core - INFO - subscribe_kline_channel|Subscribing to INFO_CORE|UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_15T_kline
2023-11-21 18:48:26,895 - kline_core - INFO - subscribe_kline_channel|Subscribing to INFO_CORE|UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_30T_kline
2023-11-21 18:48:26,896 - kline_core - INFO - subscribe_kline_channel|Subscribing to INFO_CORE|UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_1H_kline
2023-11-21 18:48:26,896 - kline_core - INFO - subscribe_kline_channel|Subscribing to INFO_CORE|UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_4H_kline
2023-11-21 18:48:26,897 - kline_core - INFO - subscribe_kline_channel|Subscribing to INFO_CORE|UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_1D_kline
2023-11-21 18:48:26,897 - kline_core - INFO - subscribe_kline_channel|Subscribing to INFO_CORE|UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_1T_kline
2023-11-21 18:48:26,898 - kline_core - INFO - subscribe_kline_channel|Subscribing to INFO_CORE|UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_5T_kline
2023-11-21 18:48:26,899 - kline_core - INFO - subscribe_kline_channel|Subscribing to INFO_CORE|UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_15T_kline
2023-11-21 18:48:26,899 - kline_core - INFO - subscribe_kline_channel|Subscribing to INFO_CORE|UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_30T_kline
2023-11-21 18:48:26,900 - kline_core - INFO - subscribe_kline_channel|Subscribing to INFO_CORE|UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_1H_kline
2023-11-21 18:48:26,900 - kline_core - INFO - subscribe_kline_channel|Subscribing to INFO_CORE|UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_4H_kline
2023-11-21 18:48:26,901 - kline_core - INFO - subscribe_kline_channel|Subscribing to INFO_CORE|UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_1D_kline
2023-11-21 18:48:26,901 - kline_core - INFO - subscribe_kline_channel|Subscribing to INFO_CORE|UPBIT_SPOT/KRW:BYBIT_USD_M/USDT_1T_kline
2023-11-21 18:48:26,902 - kline_core - INFO - subscribe_kline_channel|Subscribing to INFO_CORE|UPBIT_SPOT/KRW:BYBIT_USD_M/USDT_5T_kline
2023-11-21 18:48:26,903 - kline_core - INFO - subscribe_kline_channel|Subscribing to INFO_CORE|UPBIT_SPOT/KRW:BYBIT_USD_M/USDT_15T_kline
2023-11-21 18:48:26,903 - kline_core - INFO - subscribe_kline_channel|Subscribing to INFO_CORE|UPBIT_SPOT/KRW:BYBIT_USD_M/USDT_30T_kline
2023-11-21 18:48:26,904 - kline_core - INFO - subscribe_kline_channel|Subscribing to INFO_CORE|UPBIT_SPOT/KRW:BYBIT_USD_M/USDT_1H_kline
2023-11-21 18:48:26,904 - kline_core - INFO - subscribe_kline_channel|Subscribing to INFO_CORE|UPBIT_SPOT/KRW:BYBIT_USD_M/USDT_4H_kline
2023-11-21 18:48:26,905 - kline_core - INFO - subscribe_kline_channel|Subscribing to INFO_CORE|UPBIT_SPOT/KRW:BYBIT_USD_M/USDT_1D_kline
2023-11-21 18:48:26,905 - kline_core - INFO - subscribe_kline_channel|Subscribing to INFO_CORE|UPBIT_SPOT/KRW:UPBIT_SPOT/BTC_1T_kline
2023-11-21 18:48:26,906 - kline_core - INFO - subscribe_kline_channel|Subscribing to INFO_CORE|UPBIT_SPOT/KRW:UPBIT_SPOT/BTC_5T_kline
2023-11-21 18:48:26,906 - kline_core - INFO - subscribe_kline_channel|Subscribing to INFO_CORE|UPBIT_SPOT/KRW:UPBIT_SPOT/BTC_15T_kline
2023-11-21 18:48:26,907 - kline_core - INFO - subscribe_kline_channel|Subscribing to INFO_CORE|UPBIT_SPOT/KRW:UPBIT_SPOT/BTC_30T_kline
2023-11-21 18:48:26,907 - kline_core - INFO - subscribe_kline_channel|Subscribing to INFO_CORE|UPBIT_SPOT/KRW:UPBIT_SPOT/BTC_1H_kline
2023-11-21 18:48:26,908 - kline_core - INFO - subscribe_kline_channel|Subscribing to INFO_CORE|UPBIT_SPOT/KRW:UPBIT_SPOT/BTC_4H_kline
2023-11-21 18:48:26,908 - kline_core - INFO - subscribe_kline_channel|Subscribing to INFO_CORE|UPBIT_SPOT/KRW:UPBIT_SPOT/BTC_1D_kline

resampling ohlc_df(length: 528): 1.0240983963012695

2023-11-21 18:48:32,294 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_1H_kline base_asset is not matched. added: ['ONG'], removed: []

resampling ohlc_df(length: 88): 0.9774119853973389

2023-11-21 18:48:32,449 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_1D_kline base_asset is not matched. added: ['ONG'], removed: []
2023-11-21 18:48:32,483 - kline_core - INFO - resampling ohlc_df(length: 968): 1.0510287284851074
2023-11-21 18:48:32,485 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_30T_kline time: 0.0005853176116943359
2023-11-21 18:48:32,486 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_30T_kline time: 0.0003094673156738281
2023-11-21 18:48:32,501 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_30T_kline base_asset is not matched. added: ['ONG'], removed: []

resampling ohlc_df(length: 176): 1.0641446113586426
resampling ohlc_df(length: 146): 0.8855342864990234

2023-11-21 18:48:32,560 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_4H_kline base_asset is not matched. added: ['ONG'], removed: []
2023-11-21 18:48:32,568 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_4H_kline base_asset is not matched. added: ['BAT', 'WAXP'], removed: []
2023-11-21 18:48:32,610 - kline_core - INFO - resampling ohlc_df(length: 803): 0.9534566402435303
2023-11-21 18:48:32,611 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_30T_kline time: 0.0005548000335693359
2023-11-21 18:48:32,613 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_30T_kline time: 0.00035309791564941406
2023-11-21 18:48:32,623 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_30T_kline base_asset is not matched. added: ['BAT', 'WAXP'], removed: []

resampling ohlc_df(length: 73): 0.858144998550415

2023-11-21 18:48:32,652 - kline_core - INFO - resampling ohlc_df(length: 1936): 1.0873477458953857
2023-11-21 18:48:32,654 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_15T_kline time: 0.0008037090301513672
2023-11-21 18:48:32,655 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_15T_kline time: 0.0005257129669189453
2023-11-21 18:48:32,657 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_1D_kline base_asset is not matched. added: ['BAT', 'WAXP'], removed: []
2023-11-21 18:48:32,675 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_15T_kline base_asset is not matched. added: ['ONG'], removed: []
2023-11-21 18:48:32,695 - kline_core - INFO - resampling ohlc_df(length: 1606): 0.9450440406799316
2023-11-21 18:48:32,696 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_15T_kline time: 0.0006546974182128906
2023-11-21 18:48:32,697 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_15T_kline time: 0.0003249645233154297
2023-11-21 18:48:32,709 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_15T_kline base_asset is not matched. added: ['BAT', 'WAXP'], removed: []

resampling ohlc_df(length: 438): 0.9296281337738037

2023-11-21 18:48:32,731 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_1H_kline base_asset is not matched. added: ['BAT', 'WAXP'], removed: []
2023-11-21 18:48:36,136 - update_dollar - INFO - fetch_dollar|Dollar price (1292.0 KRW) has been updated.
2023-11-21 18:48:32,818 - kline_core - INFO - resampling ohlc_df(length: 5456): 1.1570050716400146
2023-11-21 18:48:32,820 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_5T_kline time: 0.0015196800231933594
2023-11-21 18:48:32,821 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_5T_kline time: 0.0009632110595703125
2023-11-21 18:48:32,850 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_5T_kline base_asset is not matched. added: ['ONG'], removed: []
2023-11-21 18:48:32,867 - kline_core - INFO - resampling ohlc_df(length: 4526): 0.9633901119232178
2023-11-21 18:48:32,869 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_5T_kline time: 0.0009191036224365234
2023-11-21 18:48:32,870 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_5T_kline time: 0.0009424686431884766
2023-11-21 18:48:32,875 - kline_core - INFO - insert_kline_to_db|database: UPBIT_SPOT/KRW:BINANCE_SPOT/USDT, Filtering 352 klines for 88 unique base_assets took 0.1478409767150879 seconds
2023-11-21 18:48:32,875 - kline_core - INFO - insert_kline_to_db|database: UPBIT_SPOT/KRW:BINANCE_SPOT/USDT, Inserting 352 klines for 88 unique base_assets took 0.2553567886352539 seconds
2023-11-21 18:48:32,876 - kline_core - INFO - insert_kline_to_db|channel_name: INFO_CORE|UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_1H_kline, Inserting 352 klines for 88 unique base_assets took 0.5888693332672119 seconds
2023-11-21 18:48:32,880 - kline_core - INFO - insert_kline_to_db|INFO_CORE|UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_1D_kline No klines to be inserted
2023-11-21 18:48:32,890 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_5T_kline base_asset is not matched. added: ['BAT', 'WAXP'], removed: []
2023-11-21 18:48:33,393 - kline_core - INFO - insert_kline_to_db|database: UPBIT_SPOT/KRW:BINANCE_SPOT/USDT, Filtering 176 klines for 88 unique base_assets took 0.1458113193511963 seconds
2023-11-21 18:48:33,394 - kline_core - INFO - insert_kline_to_db|database: UPBIT_SPOT/KRW:BINANCE_SPOT/USDT, Inserting 176 klines for 88 unique base_assets took 0.19996953010559082 seconds
2023-11-21 18:48:33,395 - kline_core - INFO - insert_kline_to_db|channel_name: INFO_CORE|UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_30T_kline, Inserting 176 klines for 88 unique base_assets took 0.511399507522583 seconds
2023-11-21 18:48:33,791 - kline_core - INFO - insert_kline_to_db|database: UPBIT_SPOT/KRW:BINANCE_SPOT/USDT, Filtering 88 klines for 88 unique base_assets took 0.08851909637451172 seconds
2023-11-21 18:48:33,792 - kline_core - INFO - insert_kline_to_db|database: UPBIT_SPOT/KRW:BINANCE_SPOT/USDT, Inserting 88 klines for 88 unique base_assets took 0.19466352462768555 seconds
2023-11-21 18:48:33,792 - kline_core - INFO - insert_kline_to_db|channel_name: INFO_CORE|UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_4H_kline, Inserting 88 klines for 88 unique base_assets took 0.3941192626953125 seconds
2023-11-21 18:48:34,138 - kline_core - INFO - insert_kline_to_db|database: UPBIT_SPOT/KRW:BINANCE_USD_M/USDT, Filtering 73 klines for 73 unique base_assets took 0.07973027229309082 seconds
2023-11-21 18:48:34,139 - kline_core - INFO - insert_kline_to_db|database: UPBIT_SPOT/KRW:BINANCE_USD_M/USDT, Inserting 73 klines for 73 unique base_assets took 0.17065691947937012 seconds
2023-11-21 18:48:34,139 - kline_core - INFO - insert_kline_to_db|channel_name: INFO_CORE|UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_4H_kline, Inserting 73 klines for 73 unique base_assets took 0.3441624641418457 seconds
2023-11-21 18:48:34,533 - kline_core - INFO - insert_kline_to_db|database: UPBIT_SPOT/KRW:BINANCE_USD_M/USDT, Filtering 146 klines for 73 unique base_assets took 0.10180401802062988 seconds
2023-11-21 18:48:34,534 - kline_core - INFO - insert_kline_to_db|database: UPBIT_SPOT/KRW:BINANCE_USD_M/USDT, Inserting 146 klines for 73 unique base_assets took 0.16193485260009766 seconds
2023-11-21 18:48:34,535 - kline_core - INFO - insert_kline_to_db|channel_name: INFO_CORE|UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_30T_kline, Inserting 146 klines for 73 unique base_assets took 0.3925511837005615 seconds
2023-11-21 18:48:34,538 - kline_core - INFO - insert_kline_to_db|INFO_CORE|UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_1D_kline No klines to be inserted
2023-11-21 18:48:35,191 - kline_core - INFO - insert_kline_to_db|database: UPBIT_SPOT/KRW:BINANCE_SPOT/USDT, Filtering 176 klines for 88 unique base_assets took 0.20142030715942383 seconds
2023-11-21 18:48:35,192 - kline_core - INFO - insert_kline_to_db|database: UPBIT_SPOT/KRW:BINANCE_SPOT/USDT, Inserting 176 klines for 88 unique base_assets took 0.20842814445495605 seconds
2023-11-21 18:48:35,192 - kline_core - INFO - insert_kline_to_db|channel_name: INFO_CORE|UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_15T_kline, Inserting 176 klines for 88 unique base_assets took 0.6490800380706787 seconds
2023-11-21 18:48:35,728 - kline_core - INFO - insert_kline_to_db|database: UPBIT_SPOT/KRW:BINANCE_USD_M/USDT, Filtering 146 klines for 73 unique base_assets took 0.16625046730041504 seconds
2023-11-21 18:48:35,729 - kline_core - INFO - insert_kline_to_db|database: UPBIT_SPOT/KRW:BINANCE_USD_M/USDT, Inserting 146 klines for 73 unique base_assets took 0.17002224922180176 seconds
2023-11-21 18:48:35,729 - kline_core - INFO - insert_kline_to_db|channel_name: INFO_CORE|UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_15T_kline, Inserting 146 klines for 73 unique base_assets took 0.5330929756164551 seconds
2023-11-21 18:48:36,137 - kline_core - INFO - insert_kline_to_db|database: UPBIT_SPOT/KRW:BINANCE_USD_M/USDT, Filtering 292 klines for 73 unique base_assets took 0.09996199607849121 seconds
2023-11-21 18:48:36,138 - kline_core - INFO - insert_kline_to_db|database: UPBIT_SPOT/KRW:BINANCE_USD_M/USDT, Inserting 292 klines for 73 unique base_assets took 0.17967629432678223 seconds
2023-11-21 18:48:36,138 - kline_core - INFO - insert_kline_to_db|channel_name: INFO_CORE|UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_1H_kline, Inserting 292 klines for 73 unique base_assets took 0.4066140651702881 seconds
2023-11-21 18:48:36,999 - kline_core - INFO - insert_kline_to_db|database: UPBIT_SPOT/KRW:BINANCE_SPOT/USDT, Filtering 88 klines for 88 unique base_assets took 0.38814210891723633 seconds
2023-11-21 18:48:37,000 - kline_core - INFO - insert_kline_to_db|database: UPBIT_SPOT/KRW:BINANCE_SPOT/USDT, Inserting 88 klines for 88 unique base_assets took 0.16303038597106934 seconds
2023-11-21 18:48:37,001 - kline_core - INFO - insert_kline_to_db|channel_name: INFO_CORE|UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_5T_kline, Inserting 88 klines for 88 unique base_assets took 0.8545825481414795 seconds
2023-11-21 18:48:37,640 - kline_core - INFO - insert_kline_to_db|database: UPBIT_SPOT/KRW:BINANCE_USD_M/USDT, Filtering 73 klines for 73 unique base_assets took 0.2908937931060791 seconds
2023-11-21 18:48:37,641 - kline_core - INFO - insert_kline_to_db|database: UPBIT_SPOT/KRW:BINANCE_USD_M/USDT, Inserting 73 klines for 73 unique base_assets took 0.1194460391998291 seconds
2023-11-21 18:48:37,641 - kline_core - INFO - insert_kline_to_db|channel_name: INFO_CORE|UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_5T_kline, Inserting 73 klines for 73 unique base_assets took 0.6354479789733887 seconds

resampling ohlc_df(length: 528): 1.0346786975860596

2023-11-21 18:48:38,454 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_1H_kline base_asset is not matched. added: ['ONG'], removed: []

resampling ohlc_df(length: 88): 1.0304713249206543

2023-11-21 18:48:38,599 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_1D_kline base_asset is not matched. added: ['ONG'], removed: []

resampling ohlc_df(length: 146): 0.9574489593505859

2023-11-21 18:48:38,641 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_4H_kline base_asset is not matched. added: ['BAT', 'WAXP'], removed: []
2023-11-21 18:48:38,654 - kline_core - INFO - resampling ohlc_df(length: 803): 0.9256486892700195
2023-11-21 18:48:38,655 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_30T_kline time: 0.0005800724029541016
2023-11-21 18:48:38,656 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_30T_kline time: 0.0003032684326171875
2023-11-21 18:48:38,669 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_30T_kline base_asset is not matched. added: ['BAT', 'WAXP'], removed: []
2023-11-21 18:48:38,684 - kline_core - INFO - resampling ohlc_df(length: 968): 1.0754036903381348
2023-11-21 18:48:38,686 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_30T_kline time: 0.00046825408935546875
2023-11-21 18:48:38,687 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_30T_kline time: 0.0003113746643066406
2023-11-21 18:48:38,688 - kline_core - INFO - insert_kline_to_db|INFO_CORE|UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_1D_kline No klines to be inserted

resampling ohlc_df(length: 73): 0.9299991130828857

2023-11-21 18:48:38,699 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_30T_kline base_asset is not matched. added: ['ONG'], removed: []
2023-11-21 18:48:38,706 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_1D_kline base_asset is not matched. added: ['BAT', 'WAXP'], removed: []

resampling ohlc_df(length: 438): 0.9279091358184814

2023-11-21 18:48:38,776 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_1H_kline base_asset is not matched. added: ['BAT', 'WAXP'], removed: []

resampling ohlc_df(length: 176): 1.1122679710388184

2023-11-21 18:48:38,790 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_4H_kline base_asset is not matched. added: ['ONG'], removed: []
2023-11-21 18:48:38,793 - kline_core - INFO - resampling ohlc_df(length: 1606): 0.9652070999145508
2023-11-21 18:48:38,794 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_15T_kline time: 0.0006082057952880859
2023-11-21 18:48:38,796 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_15T_kline time: 0.0003726482391357422
2023-11-21 18:48:38,810 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_15T_kline base_asset is not matched. added: ['BAT', 'WAXP'], removed: []
2023-11-21 18:48:38,881 - kline_core - INFO - resampling ohlc_df(length: 1936): 1.0982081890106201
2023-11-21 18:48:38,883 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_15T_kline time: 0.00079345703125
2023-11-21 18:48:38,884 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_15T_kline time: 0.0005085468292236328
2023-11-21 18:48:38,901 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_15T_kline base_asset is not matched. added: ['ONG'], removed: []
2023-11-21 18:48:38,992 - kline_core - INFO - resampling ohlc_df(length: 4526): 0.9853858947753906
2023-11-21 18:48:38,994 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_5T_kline time: 0.0011448860168457031
2023-11-21 18:48:38,995 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_5T_kline time: 0.0005435943603515625
2023-11-21 18:48:39,017 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_5T_kline base_asset is not matched. added: ['BAT', 'WAXP'], removed: []
2023-11-21 18:48:39,077 - kline_core - INFO - resampling ohlc_df(length: 5456): 1.1030471324920654
2023-11-21 18:48:39,080 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_5T_kline time: 0.0019533634185791016
2023-11-21 18:48:39,082 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_5T_kline time: 0.0008370876312255859
2023-11-21 18:48:39,109 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_5T_kline base_asset is not matched. added: ['ONG'], removed: []
2023-11-21 18:48:39,201 - kline_core - INFO - insert_kline_to_db|INFO_CORE|UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_1D_kline No klines to be inserted
2023-11-21 18:48:44,670 - kline_core - INFO - resampling ohlc_df(length: 803): 0.8938496112823486
2023-11-21 18:48:44,672 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_30T_kline time: 0.0010297298431396484

resampling ohlc_df(length: 73): 0.8608608245849609

2023-11-21 18:48:44,674 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_30T_kline time: 0.0003936290740966797
2023-11-21 18:48:44,685 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_30T_kline base_asset is not matched. added: ['BAT', 'WAXP'], removed: []
2023-11-21 18:48:44,691 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_1D_kline base_asset is not matched. added: ['BAT', 'WAXP'], removed: []

resampling ohlc_df(length: 146): 1.0005526542663574

2023-11-21 18:48:44,759 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_4H_kline base_asset is not matched. added: ['BAT', 'WAXP'], removed: []

resampling ohlc_df(length: 528): 1.2203290462493896

2023-11-21 18:48:44,794 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_1H_kline base_asset is not matched. added: ['ONG'], removed: []

resampling ohlc_df(length: 88): 1.1024911403656006

2023-11-21 18:48:44,823 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_1D_kline base_asset is not matched. added: ['ONG'], removed: []

resampling ohlc_df(length: 438): 0.9523756504058838

2023-11-21 18:48:44,849 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_1H_kline base_asset is not matched. added: ['BAT', 'WAXP'], removed: []
2023-11-21 18:48:44,877 - kline_core - INFO - insert_kline_to_db|INFO_CORE|UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_1D_kline No klines to be inserted
2023-11-21 18:48:44,901 - kline_core - INFO - resampling ohlc_df(length: 968): 1.096465826034546
2023-11-21 18:48:44,903 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_30T_kline time: 0.0004646778106689453
2023-11-21 18:48:44,904 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_30T_kline time: 0.0003409385681152344
2023-11-21 18:48:44,910 - kline_core - INFO - resampling ohlc_df(length: 1606): 0.9915049076080322
2023-11-21 18:48:44,912 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_15T_kline time: 0.0007350444793701172
2023-11-21 18:48:44,913 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_15T_kline time: 0.00048065185546875
2023-11-21 18:48:44,915 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_30T_kline base_asset is not matched. added: ['ONG'], removed: []
2023-11-21 18:48:44,924 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_15T_kline base_asset is not matched. added: ['BAT', 'WAXP'], removed: []

resampling ohlc_df(length: 176): 1.044173002243042

2023-11-21 18:48:44,951 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_4H_kline base_asset is not matched. added: ['ONG'], removed: []
2023-11-21 18:48:45,136 - kline_core - INFO - resampling ohlc_df(length: 4526): 0.9816412925720215
2023-11-21 18:48:45,138 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_5T_kline time: 0.00128173828125
2023-11-21 18:48:45,140 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_5T_kline time: 0.0006935596466064453
2023-11-21 18:48:45,157 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_5T_kline base_asset is not matched. added: ['BAT', 'WAXP'], removed: []
2023-11-21 18:48:45,161 - kline_core - INFO - insert_kline_to_db|INFO_CORE|UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_1D_kline No klines to be inserted
2023-11-21 18:48:45,173 - kline_core - INFO - resampling ohlc_df(length: 1936): 1.1635117530822754
2023-11-21 18:48:45,175 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_15T_kline time: 0.0007760524749755859
2023-11-21 18:48:45,176 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_15T_kline time: 0.00038051605224609375
2023-11-21 18:48:45,193 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_15T_kline base_asset is not matched. added: ['ONG'], removed: []
2023-11-21 18:48:45,268 - kline_core - INFO - resampling ohlc_df(length: 5456): 1.0280332565307617
2023-11-21 18:48:45,270 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_5T_kline time: 0.0014710426330566406
2023-11-21 18:48:45,272 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_5T_kline time: 0.0011782646179199219
2023-11-21 18:48:45,299 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_5T_kline base_asset is not matched. added: ['ONG'], removed: []

resampling ohlc_df(length: 73): 0.814847469329834

2023-11-21 18:48:50,620 - kline_core - INFO - insert_kline_to_db|INFO_CORE|UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_1D_kline No klines to be inserted
2023-11-21 18:48:50,624 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_1D_kline base_asset is not matched. added: ['BAT', 'WAXP'], removed: []
2023-11-21 18:48:50,670 - kline_core - INFO - resampling ohlc_df(length: 803): 0.8735990524291992
2023-11-21 18:48:50,672 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_30T_kline time: 0.0006127357482910156
2023-11-21 18:48:50,673 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_30T_kline time: 0.00037097930908203125
2023-11-21 18:48:50,688 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_30T_kline base_asset is not matched. added: ['BAT', 'WAXP'], removed: []

resampling ohlc_df(length: 146): 0.85791015625

2023-11-21 18:48:50,731 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_4H_kline base_asset is not matched. added: ['BAT', 'WAXP'], removed: []

resampling ohlc_df(length: 438): 0.8640635013580322

2023-11-21 18:48:50,830 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_1H_kline base_asset is not matched. added: ['BAT', 'WAXP'], removed: []
2023-11-21 18:48:50,878 - kline_core - INFO - resampling ohlc_df(length: 1606): 0.8451709747314453
2023-11-21 18:48:50,880 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_15T_kline time: 0.0005974769592285156
2023-11-21 18:48:50,881 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_15T_kline time: 0.00034046173095703125
2023-11-21 18:48:50,896 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_15T_kline base_asset is not matched. added: ['BAT', 'WAXP'], removed: []

resampling ohlc_df(length: 88): 1.0490765571594238

2023-11-21 18:48:50,994 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_1D_kline base_asset is not matched. added: ['ONG'], removed: []

resampling ohlc_df(length: 176): 1.0006308555603027

2023-11-21 18:48:51,070 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_4H_kline base_asset is not matched. added: ['ONG'], removed: []
2023-11-21 18:48:51,183 - kline_core - INFO - resampling ohlc_df(length: 4526): 0.9069764614105225
2023-11-21 18:48:51,185 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_5T_kline time: 0.001209259033203125
2023-11-21 18:48:51,186 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_5T_kline time: 0.0006802082061767578
2023-11-21 18:48:51,205 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_5T_kline base_asset is not matched. added: ['BAT', 'WAXP'], removed: []
2023-11-21 18:48:51,409 - kline_core - INFO - insert_kline_to_db|INFO_CORE|UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_1D_kline No klines to be inserted
2023-11-21 18:48:51,499 - kline_core - INFO - resampling ohlc_df(length: 5456): 1.078287124633789
2023-11-21 18:48:51,502 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_5T_kline time: 0.0018682479858398438
2023-11-21 18:48:51,504 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_5T_kline time: 0.0013546943664550781
2023-11-21 18:48:51,538 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_5T_kline base_asset is not matched. added: ['ONG'], removed: []

resampling ohlc_df(length: 528): 1.7007651329040527

2023-11-21 18:48:51,610 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_1H_kline base_asset is not matched. added: ['ONG'], removed: []
2023-11-21 18:48:51,689 - kline_core - INFO - resampling ohlc_df(length: 968): 1.6692941188812256
2023-11-21 18:48:51,690 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_30T_kline time: 0.0004458427429199219
2023-11-21 18:48:51,691 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_30T_kline time: 0.00029730796813964844
2023-11-21 18:48:51,704 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_30T_kline base_asset is not matched. added: ['ONG'], removed: []
2023-11-21 18:48:51,826 - kline_core - INFO - resampling ohlc_df(length: 1936): 1.5205786228179932
2023-11-21 18:48:51,828 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_15T_kline time: 0.0006399154663085938
2023-11-21 18:48:51,829 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_15T_kline time: 0.0003457069396972656
2023-11-21 18:48:51,845 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_15T_kline base_asset is not matched. added: ['ONG'], removed: []

resampling ohlc_df(length: 73): 0.8057913780212402

2023-11-21 18:48:56,546 - kline_core - INFO - insert_kline_to_db|INFO_CORE|UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_1D_kline No klines to be inserted
2023-11-21 18:48:56,555 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_1D_kline base_asset is not matched. added: ['BAT', 'WAXP'], removed: []
2023-11-21 18:48:56,655 - kline_core - INFO - resampling ohlc_df(length: 803): 0.8591084480285645
2023-11-21 18:48:56,657 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_30T_kline time: 0.00055694580078125
2023-11-21 18:48:56,658 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_30T_kline time: 0.0005249977111816406
2023-11-21 18:48:56,671 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_30T_kline base_asset is not matched. added: ['BAT', 'WAXP'], removed: []

resampling ohlc_df(length: 146): 0.8402674198150635

2023-11-21 18:48:56,684 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_4H_kline base_asset is not matched. added: ['BAT', 'WAXP'], removed: []

resampling ohlc_df(length: 438): 0.8844845294952393

2023-11-21 18:48:56,840 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_1H_kline base_asset is not matched. added: ['BAT', 'WAXP'], removed: []
2023-11-21 18:48:56,880 - kline_core - INFO - resampling ohlc_df(length: 1606): 0.875246524810791
2023-11-21 18:48:56,881 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_15T_kline time: 0.0007834434509277344
2023-11-21 18:48:56,883 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_15T_kline time: 0.0006721019744873047
2023-11-21 18:48:56,895 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_15T_kline base_asset is not matched. added: ['BAT', 'WAXP'], removed: []

resampling ohlc_df(length: 88): 0.9496188163757324

2023-11-21 18:48:57,069 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_1D_kline base_asset is not matched. added: ['ONG'], removed: []
2023-11-21 18:48:57,248 - kline_core - INFO - resampling ohlc_df(length: 4526): 0.9192085266113281
2023-11-21 18:48:57,250 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_5T_kline time: 0.001672983169555664
2023-11-21 18:48:57,253 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_5T_kline time: 0.0012080669403076172
2023-11-21 18:48:57,277 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_5T_kline base_asset is not matched. added: ['BAT', 'WAXP'], removed: []

resampling ohlc_df(length: 176): 1.1052236557006836

2023-11-21 18:48:57,294 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_4H_kline base_asset is not matched. added: ['ONG'], removed: []
2023-11-21 18:48:57,477 - kline_core - INFO - insert_kline_to_db|INFO_CORE|UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_1D_kline No klines to be inserted
2023-11-21 18:48:57,723 - kline_core - INFO - resampling ohlc_df(length: 5456): 1.0690312385559082
2023-11-21 18:48:57,726 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_5T_kline time: 0.0014073848724365234
2023-11-21 18:48:57,727 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_5T_kline time: 0.0009582042694091797
2023-11-21 18:48:57,753 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_5T_kline base_asset is not matched. added: ['ONG'], removed: []

resampling ohlc_df(length: 528): 1.0423846244812012

2023-11-21 18:48:57,768 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_1H_kline base_asset is not matched. added: ['ONG'], removed: []
2023-11-21 18:48:57,852 - kline_core - INFO - resampling ohlc_df(length: 968): 1.0359022617340088
2023-11-21 18:48:57,854 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_30T_kline time: 0.0007088184356689453
2023-11-21 18:48:57,855 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_30T_kline time: 0.00032520294189453125
2023-11-21 18:48:57,867 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_30T_kline base_asset is not matched. added: ['ONG'], removed: []
2023-11-21 18:48:57,998 - kline_core - INFO - resampling ohlc_df(length: 1936): 1.0435476303100586
2023-11-21 18:48:58,000 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_15T_kline time: 0.0007123947143554688
2023-11-21 18:48:58,001 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_15T_kline time: 0.0003809928894042969
2023-11-21 18:48:58,015 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_15T_kline base_asset is not matched. added: ['ONG'], removed: []

resampling ohlc_df(length: 73): 0.8207705020904541

2023-11-21 18:49:02,492 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_1D_kline base_asset is not matched. added: ['BAT', 'WAXP'], removed: []
2023-11-21 18:49:02,614 - kline_core - INFO - resampling ohlc_df(length: 803): 0.8329708576202393
2023-11-21 18:49:02,616 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_30T_kline time: 0.000568389892578125
2023-11-21 18:49:02,617 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_30T_kline time: 0.0002789497375488281

resampling ohlc_df(length: 146): 0.8309416770935059

2023-11-21 18:49:02,628 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_30T_kline base_asset is not matched. added: ['BAT', 'WAXP'], removed: []
2023-11-21 18:49:02,632 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_4H_kline base_asset is not matched. added: ['BAT', 'WAXP'], removed: []

resampling ohlc_df(length: 438): 0.8160312175750732

2023-11-21 18:49:02,776 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_1H_kline base_asset is not matched. added: ['BAT', 'WAXP'], removed: []
2023-11-21 18:49:02,897 - kline_core - INFO - resampling ohlc_df(length: 1606): 0.895195484161377
2023-11-21 18:49:02,898 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_15T_kline time: 0.0006971359252929688
2023-11-21 18:49:02,899 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_15T_kline time: 0.0003771781921386719
2023-11-21 18:49:02,915 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_15T_kline base_asset is not matched. added: ['BAT', 'WAXP'], removed: []

resampling ohlc_df(length: 88): 0.9743146896362305

2023-11-21 18:49:03,164 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_1D_kline base_asset is not matched. added: ['ONG'], removed: []
2023-11-21 18:49:03,332 - kline_core - INFO - resampling ohlc_df(length: 4528): 0.9380226135253906
2023-11-21 18:49:03,334 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_5T_kline time: 0.0011012554168701172
2023-11-21 18:49:03,335 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_5T_kline time: 0.0005016326904296875
2023-11-21 18:49:03,337 - kline_core - INFO - insert_kline_to_db|database: UPBIT_SPOT/KRW:BINANCE_USD_M/USDT, Filtering 148 klines for 75 unique base_assets took 1.62640380859375 seconds
2023-11-21 18:49:03,337 - kline_core - INFO - insert_kline_to_db|database: UPBIT_SPOT/KRW:BINANCE_USD_M/USDT, Inserting 148 klines for 75 unique base_assets took 0.1533336639404297 seconds
2023-11-21 18:49:03,338 - kline_core - INFO - insert_kline_to_db|channel_name: INFO_CORE|UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_1T_kline, Inserting 148 klines for 75 unique base_assets took 3.129530668258667 seconds

resampling ohlc_df(length: 176): 1.0346927642822266

2023-11-21 18:49:03,447 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_4H_kline base_asset is not matched. added: ['ONG'], removed: []

resampling ohlc_df(length: 528): 1.0492844581604004

2023-11-21 18:49:03,937 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_1H_kline base_asset is not matched. added: ['ONG'], removed: []
2023-11-21 18:49:03,977 - kline_core - INFO - resampling ohlc_df(length: 968): 1.0012342929840088
2023-11-21 18:49:03,979 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_30T_kline time: 0.0005383491516113281
2023-11-21 18:49:03,980 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_30T_kline time: 0.00021386146545410156
2023-11-21 18:49:03,991 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_30T_kline base_asset is not matched. added: ['ONG'], removed: []
2023-11-21 18:49:04,170 - kline_core - INFO - resampling ohlc_df(length: 5457): 1.3003857135772705
2023-11-21 18:49:10,350 - update_dollar - INFO - fetch_dollar|Dollar price (1292.0 KRW) has been updated.
2023-11-21 18:49:04,173 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_5T_kline time: 0.0016474723815917969
2023-11-21 18:49:04,175 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_5T_kline time: 0.0010232925415039062
2023-11-21 18:49:04,200 - kline_core - INFO - resampling ohlc_df(length: 1936): 1.0786917209625244
2023-11-21 18:49:04,201 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_15T_kline time: 0.0005898475646972656
2023-11-21 18:49:04,202 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_15T_kline time: 0.0003669261932373047
2023-11-21 18:49:04,217 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_15T_kline base_asset is not matched. added: ['ONG'], removed: []
2023-11-21 18:49:05,187 - kline_core - INFO - insert_kline_to_db|database: UPBIT_SPOT/KRW:UPBIT_SPOT/BTC, Filtering 97 klines for 97 unique base_assets took 0.9828689098358154 seconds
2023-11-21 18:49:05,188 - kline_core - INFO - insert_kline_to_db|database: UPBIT_SPOT/KRW:UPBIT_SPOT/BTC, Inserting 97 klines for 97 unique base_assets took 0.18432307243347168 seconds
2023-11-21 18:49:05,189 - kline_core - INFO - insert_kline_to_db|channel_name: INFO_CORE|UPBIT_SPOT/KRW:UPBIT_SPOT/BTC_1T_kline, Inserting 97 klines for 97 unique base_assets took 1.829030990600586 seconds
2023-11-21 18:49:06,255 - kline_core - INFO - insert_kline_to_db|database: UPBIT_SPOT/KRW:BYBIT_USD_M/USDT, Filtering 82 klines for 82 unique base_assets took 0.5549912452697754 seconds
2023-11-21 18:49:06,256 - kline_core - INFO - insert_kline_to_db|database: UPBIT_SPOT/KRW:BYBIT_USD_M/USDT, Inserting 82 klines for 82 unique base_assets took 0.14744925498962402 seconds
2023-11-21 18:49:06,256 - kline_core - INFO - insert_kline_to_db|channel_name: INFO_CORE|UPBIT_SPOT/KRW:BYBIT_USD_M/USDT_1T_kline, Inserting 82 klines for 82 unique base_assets took 1.044628620147705 seconds
2023-11-21 18:49:08,583 - kline_core - INFO - resampling ohlc_df(length: 803): 0.8480358123779297
2023-11-21 18:49:08,585 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_30T_kline time: 0.0005130767822265625
2023-11-21 18:49:08,587 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_30T_kline time: 0.00035309791564941406
2023-11-21 18:49:08,599 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_30T_kline base_asset is not matched. added: ['BAT', 'WAXP'], removed: []

resampling ohlc_df(length: 438): 0.874809741973877

2023-11-21 18:49:08,769 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_1H_kline base_asset is not matched. added: ['BAT', 'WAXP'], removed: []

resampling ohlc_df(length: 73): 1.2342760562896729

2023-11-21 18:49:08,841 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_1D_kline base_asset is not matched. added: ['BAT', 'WAXP'], removed: []
2023-11-21 18:49:08,891 - kline_core - INFO - resampling ohlc_df(length: 1608): 0.868920087814331
2023-11-21 18:49:08,892 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_15T_kline time: 0.0006134510040283203
2023-11-21 18:49:08,893 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_15T_kline time: 0.00032639503479003906

resampling ohlc_df(length: 146): 1.1851575374603271

2023-11-21 18:49:08,933 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_4H_kline base_asset is not matched. added: ['BAT', 'WAXP'], removed: []

resampling ohlc_df(length: 88): 0.9098765850067139

2023-11-21 18:49:09,192 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_1D_kline base_asset is not matched. added: ['ONG'], removed: []

resampling ohlc_df(length: 176): 0.974884033203125

2023-11-21 18:49:09,540 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_4H_kline base_asset is not matched. added: ['ONG'], removed: []

resampling ohlc_df(length: 528): 0.9407901763916016

2023-11-21 18:49:10,001 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_1H_kline base_asset is not matched. added: ['ONG'], removed: []
2023-11-21 18:49:10,089 - kline_core - INFO - resampling ohlc_df(length: 968): 0.9928412437438965
2023-11-21 18:49:10,090 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_30T_kline time: 0.00054168701171875
2023-11-21 18:49:10,091 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_30T_kline time: 0.00024247169494628906
2023-11-21 18:49:10,101 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_30T_kline base_asset is not matched. added: ['ONG'], removed: []
2023-11-21 18:49:10,175 - kline_core - INFO - insert_kline_to_db|database: UPBIT_SPOT/KRW:BINANCE_SPOT/USDT, Filtering 177 klines for 89 unique base_assets took 2.070091962814331 seconds
2023-11-21 18:49:10,176 - kline_core - INFO - insert_kline_to_db|database: UPBIT_SPOT/KRW:BINANCE_SPOT/USDT, Inserting 177 klines for 89 unique base_assets took 0.1888742446899414 seconds
2023-11-21 18:49:10,177 - kline_core - INFO - insert_kline_to_db|channel_name: INFO_CORE|UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_1T_kline, Inserting 177 klines for 89 unique base_assets took 3.9043068885803223 seconds
2023-11-21 18:49:10,181 - kline_core - INFO - insert_kline_to_db|INFO_CORE|UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_1D_kline No klines to be inserted
2023-11-21 18:49:10,321 - kline_core - INFO - resampling ohlc_df(length: 1937): 0.994826078414917
2023-11-21 18:49:10,324 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_15T_kline time: 0.0018553733825683594
2023-11-21 18:49:10,325 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_15T_kline time: 0.00039649009704589844
2023-11-21 18:49:10,817 - kline_core - INFO - insert_kline_to_db|INFO_CORE|UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_1D_kline No klines to be inserted
2023-11-21 18:49:13,203 - kline_core - INFO - insert_kline_to_db|INFO_CORE|UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_1D_kline No klines to be inserted
2023-11-21 18:49:13,531 - kline_core - INFO - insert_kline_to_db|INFO_CORE|UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_1D_kline No klines to be inserted
2023-11-21 18:49:14,552 - kline_core - INFO - resampling ohlc_df(length: 805): 0.8446359634399414
2023-11-21 18:49:14,557 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_30T_kline time: 0.0037665367126464844
2023-11-21 18:49:14,560 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_30T_kline time: 0.0006656646728515625

resampling ohlc_df(length: 438): 0.8455615043640137

2023-11-21 18:49:14,734 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_1H_kline base_asset is not matched. added: ['BAT', 'WAXP'], removed: []

resampling ohlc_df(length: 73): 0.8088886737823486

2023-11-21 18:49:14,765 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_1D_kline base_asset is not matched. added: ['BAT', 'WAXP'], removed: []
2023-11-21 18:49:14,883 - kline_core - INFO - insert_kline_to_db|INFO_CORE|UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_1D_kline No klines to be inserted

resampling ohlc_df(length: 146): 0.8746612071990967

2023-11-21 18:49:14,926 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_4H_kline base_asset is not matched. added: ['BAT', 'WAXP'], removed: []

resampling ohlc_df(length: 88): 0.9550955295562744

2023-11-21 18:49:15,260 - kline_core - INFO - insert_kline_to_db|INFO_CORE|UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_1D_kline No klines to be inserted
2023-11-21 18:49:15,269 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_1D_kline base_asset is not matched. added: ['ONG'], removed: []

resampling ohlc_df(length: 176): 0.958524227142334

2023-11-21 18:49:15,617 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_4H_kline base_asset is not matched. added: ['ONG'], removed: []

resampling ohlc_df(length: 528): 0.9753894805908203

2023-11-21 18:49:16,096 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_1H_kline base_asset is not matched. added: ['ONG'], removed: []
2023-11-21 18:49:16,251 - kline_core - INFO - resampling ohlc_df(length: 969): 1.0424001216888428
2023-11-21 18:49:16,252 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_30T_kline time: 0.0004711151123046875
2023-11-21 18:49:16,253 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_30T_kline time: 0.0003185272216796875

resampling ohlc_df(length: 73): 0.8027293682098389

2023-11-21 18:49:20,678 - kline_core - INFO - insert_kline_to_db|INFO_CORE|UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_1D_kline No klines to be inserted
2023-11-21 18:49:20,685 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_1D_kline base_asset is not matched. added: ['BAT', 'WAXP'], removed: []

resampling ohlc_df(length: 440): 0.8601233959197998
resampling ohlc_df(length: 146): 0.811058521270752

2023-11-21 18:49:20,853 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_4H_kline base_asset is not matched. added: ['BAT', 'WAXP'], removed: []

resampling ohlc_df(length: 88): 0.9744000434875488

2023-11-21 18:49:21,354 - kline_core - INFO - insert_kline_to_db|INFO_CORE|UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_1D_kline No klines to be inserted
2023-11-21 18:49:21,363 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_1D_kline base_asset is not matched. added: ['ONG'], removed: []

resampling ohlc_df(length: 176): 0.9879252910614014

2023-11-21 18:49:21,723 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_4H_kline base_asset is not matched. added: ['ONG'], removed: []

resampling ohlc_df(length: 529): 1.0127160549163818
resampling ohlc_df(length: 73): 0.7561354637145996

2023-11-21 18:49:26,552 - kline_core - INFO - insert_kline_to_db|INFO_CORE|UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_1D_kline No klines to be inserted
2023-11-21 18:49:26,556 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_1D_kline base_asset is not matched. added: ['BAT', 'WAXP'], removed: []

resampling ohlc_df(length: 148): 0.8334269523620605
resampling ohlc_df(length: 88): 0.8804898262023926

2023-11-21 18:49:27,356 - kline_core - INFO - insert_kline_to_db|INFO_CORE|UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_1D_kline No klines to be inserted
2023-11-21 18:49:27,362 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_1D_kline base_asset is not matched. added: ['ONG'], removed: []

resampling ohlc_df(length: 177): 1.0567541122436523resampling ohlc_df(length: 75): 0.8059329986572266

2023-11-21 18:49:32,474 - kline_core - INFO - insert_kline_to_db|INFO_CORE|UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_1D_kline No klines to be inserted

resampling ohlc_df(length: 89): 0.9123432636260986

2023-11-21 18:49:33,385 - kline_core - INFO - insert_kline_to_db|INFO_CORE|UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_1D_kline No klines to be inserted
2023-11-21 18:49:42,782 - update_dollar - INFO - fetch_dollar|Dollar price (1292.0 KRW) has been updated.
2023-11-21 18:50:00,952 - kline_core - INFO - resampling ohlc_df(length: 4528): 0.9104766845703125
2023-11-21 18:50:00,954 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_5T_kline time: 0.00115203857421875
2023-11-21 18:50:00,955 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_5T_kline time: 0.0005323886871337891
2023-11-21 18:50:01,103 - kline_core - INFO - resampling ohlc_df(length: 5084): 0.9793355464935303
2023-11-21 18:50:01,105 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BYBIT_USD_M/USDT_5T_kline time: 0.0011951923370361328
2023-11-21 18:50:01,106 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BYBIT_USD_M/USDT_5T_kline time: 0.0004696846008300781
2023-11-21 18:50:01,119 - kline_core - INFO - resampling ohlc_df(length: 5457): 1.0718626976013184
2023-11-21 18:50:01,121 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_5T_kline time: 0.0013937950134277344
2023-11-21 18:50:01,122 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_5T_kline time: 0.0006530284881591797
2023-11-21 18:50:01,136 - kline_core - INFO - resampling ohlc_df(length: 6014): 1.1316502094268799
2023-11-21 18:50:01,139 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:UPBIT_SPOT/BTC_5T_kline time: 0.0013427734375
2023-11-21 18:50:01,140 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:UPBIT_SPOT/BTC_5T_kline time: 0.0007145404815673828
2023-11-21 18:50:02,425 - kline_core - INFO - insert_kline_to_db|database: UPBIT_SPOT/KRW:UPBIT_SPOT/BTC, Filtering 97 klines for 97 unique base_assets took 1.1526718139648438 seconds
2023-11-21 18:50:02,427 - kline_core - INFO - insert_kline_to_db|database: UPBIT_SPOT/KRW:UPBIT_SPOT/BTC, Inserting 97 klines for 97 unique base_assets took 0.1914365291595459 seconds
2023-11-21 18:50:02,427 - kline_core - INFO - insert_kline_to_db|channel_name: INFO_CORE|UPBIT_SPOT/KRW:UPBIT_SPOT/BTC_1T_kline, Inserting 97 klines for 97 unique base_assets took 2.1536757946014404 seconds
2023-11-21 18:50:06,160 - kline_core - INFO - insert_kline_to_db|database: UPBIT_SPOT/KRW:BINANCE_USD_M/USDT, Filtering 75 klines for 75 unique base_assets took 1.950639009475708 seconds
2023-11-21 18:50:06,161 - kline_core - INFO - insert_kline_to_db|database: UPBIT_SPOT/KRW:BINANCE_USD_M/USDT, Inserting 75 klines for 75 unique base_assets took 0.17773795127868652 seconds
2023-11-21 18:50:06,162 - kline_core - INFO - insert_kline_to_db|channel_name: INFO_CORE|UPBIT_SPOT/KRW:BINANCE_USD_M/USDT_1T_kline, Inserting 75 klines for 75 unique base_assets took 3.7183055877685547 seconds
2023-11-21 18:50:07,433 - kline_core - INFO - insert_kline_to_db|database: UPBIT_SPOT/KRW:BYBIT_USD_M/USDT, Filtering 82 klines for 82 unique base_assets took 0.6427023410797119 seconds
2023-11-21 18:50:07,434 - kline_core - INFO - insert_kline_to_db|database: UPBIT_SPOT/KRW:BYBIT_USD_M/USDT, Inserting 82 klines for 82 unique base_assets took 0.1764237880706787 seconds
2023-11-21 18:50:07,434 - kline_core - INFO - insert_kline_to_db|channel_name: INFO_CORE|UPBIT_SPOT/KRW:BYBIT_USD_M/USDT_1T_kline, Inserting 82 klines for 82 unique base_assets took 1.2561333179473877 seconds
2023-11-21 18:50:12,045 - kline_core - INFO - insert_kline_to_db|database: UPBIT_SPOT/KRW:BINANCE_SPOT/USDT, Filtering 89 klines for 89 unique base_assets took 2.4346706867218018 seconds
2023-11-21 18:50:12,046 - kline_core - INFO - insert_kline_to_db|database: UPBIT_SPOT/KRW:BINANCE_SPOT/USDT, Inserting 89 klines for 89 unique base_assets took 0.21344637870788574 seconds
2023-11-21 18:50:12,047 - kline_core - INFO - insert_kline_to_db|channel_name: INFO_CORE|UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_1T_kline, Inserting 89 klines for 89 unique base_assets took 4.593362331390381 seconds
2023-11-21 18:50:13,184 - kline_core - INFO - insert_kline_to_db|channel_name: INFO_CORE|UPBIT_SPOT/KRW:BYBIT_USD_M/USDT_5T_kline, Inserting 82 klines for 82 unique base_assets took 0.39342784881591797 seconds
2023-11-21 18:50:13,183 - kline_core - INFO - insert_kline_to_db|database: UPBIT_SPOT/KRW:BYBIT_USD_M/USDT, Inserting 82 klines for 82 unique base_assets took 0.14106965065002441 seconds
2023-11-21 18:50:13,183 - kline_core - INFO - insert_kline_to_db|database: UPBIT_SPOT/KRW:BYBIT_USD_M/USDT, Filtering 82 klines for 82 unique base_assets took 0.1527552604675293 seconds
2023-11-21 18:50:14,741 - kline_core - INFO - insert_kline_to_db|database: UPBIT_SPOT/KRW:UPBIT_SPOT/BTC, Filtering 97 klines for 97 unique base_assets took 0.31918764114379883 seconds
2023-11-21 18:50:14,742 - kline_core - INFO - insert_kline_to_db|database: UPBIT_SPOT/KRW:UPBIT_SPOT/BTC, Inserting 97 klines for 97 unique base_assets took 0.18628621101379395 seconds
2023-11-21 18:50:14,742 - kline_core - INFO - insert_kline_to_db|channel_name: INFO_CORE|UPBIT_SPOT/KRW:UPBIT_SPOT/BTC_5T_kline, Inserting 97 klines for 97 unique base_assets took 0.7020320892333984 seconds
2023-11-21 18:50:16,070 - update_dollar - INFO - fetch_dollar|Dollar price (1292.0 KRW) has been updated.
2023-11-21 18:50:48,996 - update_dollar - INFO - fetch_dollar|Dollar price (1292.0 KRW) has been updated.

In [4]:
core.enabled_markets_dict

{'UPBIT': {'SPOT': ['KRW', 'BTC'],
  'USD_M': {'PERPETUAL': [], 'FUTURES': []},
  'COIN_M': {'PERPETUAL': [], 'FUTURES': []}},
 'BINANCE': {'SPOT': ['USDT'],
  'USD_M': {'PERPETUAL': ['USDT'], 'FUTURES': []},
  'COIN_M': {'PERPETUAL': [], 'FUTURES': []}},
 'BYBIT': {'SPOT': [],
  'USD_M': {'PERPETUAL': ['USDT'], 'FUTURES': []},
  'COIN_M': {'PERPETUAL': [], 'FUTURES': []}}}

In [9]:
temp = core.exchange_websocket_dict['UPBIT_SPOT'].get_price_df()
temp

,tp,scr,atp24h,h52wp,l52wp,ms,mw,tms_x,cd,tms_y,ap,bp,base_asset,quote_asset
0,2658000.0,0.150716,111759416416.001877,2875000.0,1500000.0,ACTIVE,NONE,1700206271009,KRW-ETH,1700206277787,2.658000e+06,2.655000e+06,ETH,KRW
1,26120.0,0.345755,117925271433.927795,31580.0,18490.0,ACTIVE,NONE,1700206272714,KRW-ETC,1700206277804,2.612000e+04,2.611000e+04,ETC,KRW
2,49.5,0.609756,9758022937.924299,82.6,28.4,ACTIVE,NONE,1700206271010,KRW-XEM,1700206277914,4.950000e+01,4.940000e+01,XEM,KRW
3,359.0,-1.912568,9195553407.814053,465.0,176.0,ACTIVE,NONE,1700206264873,KRW-STEEM,1700206276448,3.590000e+02,3.580000e+02,STEEM,KRW
4,2055.0,-1.201923,50209973061.335503,2495.0,272.0,ACTIVE,NONE,1700206269376,KRW-ARK,1700206276222,2.055000e+03,2.050000e+03,ARK,KRW
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109,303.0,0.0,4393641882.50811,469.0,182.0,ACTIVE,NONE,1700206260164,KRW-ONT,1700206279174,3.030000e+02,3.020000e+02,ONT,KRW
110,11260.0,-2.931034,83759435885.127502,40150.0,2400.0,ACTIVE,NONE,1700206275132,KRW-GAS,1700206279139,1.128000e+04,1.126000e+04,GAS,KRW
111,16.3,-1.212121,7401417910.846171,21.7,8.9,ACTIVE,NONE,1700206260259,KRW-QKC,1700206278539,1.640000e+01,1.630000e+01,QKC,KRW
112,7.77,-0.892857,42893625919.268356,9.8,2.79,ACTIVE,NONE,1700206275125,KRW-MBL,1700206279964,7.770000e+00,7.760000e+00,MBL,KRW
113,0.0118,2.608696,11813163209.306257,0.0259,0.0078,ACTIVE,NONE,1700206260583,KRW-SHIB,1700206279979,1.190000e-02,1.180000e-02,SHIB,KRW

In [24]:
core.enabled_markets_dict

{'UPBIT': {'SPOT': ['KRW', 'BTC'],
  'USD_M': {'PERPETUAL': [], 'FUTURES': []},
  'COIN_M': {'PERPETUAL': [], 'FUTURES': []}},
 'BINANCE': {'SPOT': ['USDT'],
  'USD_M': {'PERPETUAL': ['USDT'], 'FUTURES': []},
  'COIN_M': {'PERPETUAL': [], 'FUTURES': []}},
 'BYBIT': {'SPOT': [],
  'USD_M': {'PERPETUAL': ['USDT'], 'FUTURES': []},
  'COIN_M': {'PERPETUAL': [], 'FUTURES': []}}}

2023-11-17 16:34:38,076 - update_dollar - INFO - fetch_dollar|Dollar price (1299.5 KRW) has been updated.

In [68]:
target_market = 'UPBIT_SPOT'
# def get_symbol_list(core, target_market): # E.g) UPBIT_SPOT, BINANCE_SPOT, BINANCE_USD_M, BINANCE_COIN_M

target_exchange = target_market.split('_')[0]
target_market_type = '_'.join(target_market.split('_')[1:])

comparing_exchanges = core.enabled_markets_dict.keys()
comparison_list = []
total_df = pd.DataFrame()
for exchange in comparing_exchanges:
    for market_type in core.enabled_markets_dict[exchange]:
        if market_type == "SPOT":
            for quote_asset in core.enabled_markets_dict[exchange][market_type]:
                comparison_list.append({"exchange": exchange, "market_type": market_type, "contract_type":None, "quote_asset": quote_asset})
                # TEST
                # print({"exchange": exchange, "market_type": market_type, "contract_type":None, "quote_asset": quote_asset})
        else:
            for contract_type in core.enabled_markets_dict[exchange][market_type]:
                for quote_asset in core.enabled_markets_dict[exchange][market_type][contract_type]:
                    comparison_list.append({"exchange": exchange, "market_type": market_type, "contract_type":contract_type, "quote_asset": quote_asset})

for i, comparison_dict in enumerate(comparison_list):
    if comparison_dict['exchange'] == target_exchange and comparison_dict['market_type'] == target_market_type:
        target_market_dict = comparison_list.pop(i)
        break

# Start compare and concat
target_market_symbols = []
target_market_ticker_df = core.info_dict[f"{target_market_dict['exchange'].lower()}_{target_market_dict['market_type'].lower()}_ticker_df"]
# check if it's spot or not
if target_market_dict['market_type'] != "SPOT":
    target_market_info_df = core.info_dict[f"{target_market_dict['exchange'].lower()}_{target_market_dict['market_type'].lower()}_info_df"][['symbol','perpetual']]
    target_market_ticker_df = target_market_ticker_df.merge(target_market_info_df, on='symbol', how='inner')
    if target_market_dict['contract_type'] == "PERPETUAL":
        target_market_ticker_df = target_market_ticker_df[target_market_ticker_df['perpetual'] == True]
    else: # FUTURES
        target_market_ticker_df = target_market_ticker_df[target_market_ticker_df['perpetual'] == False]
target_market_ticker_df = target_market_ticker_df[target_market_ticker_df['quote_asset']==target_market_dict['quote_asset']][['symbol','lastPrice','atp24h','base_asset','quote_asset']]
for each_comparison_dict in comparison_list:
    each_market_info_df = core.info_dict[f"{each_comparison_dict['exchange'].lower()}_{each_comparison_dict['market_type'].lower()}_info_df"]
    if each_comparison_dict['contract_type'] is None:
        each_market_info_df = each_market_info_df[each_market_info_df['quote_asset']==each_comparison_dict['quote_asset']]
    else: # contract_type is PERPETUAL or FUTURES
        if each_comparison_dict['contract_type'] == "PERPETUAL":
            each_market_info_df = each_market_info_df[(each_market_info_df['quote_asset']==each_comparison_dict['quote_asset'])&(each_market_info_df['perpetual'] == True)]
        else: # FUTURES
            each_market_info_df = each_market_info_df[(each_market_info_df['quote_asset']==each_comparison_dict['quote_asset'])&(each_market_info_df['perpetual'] == False)]
    comparison_market_code = f"{each_comparison_dict['exchange'].lower()}_{each_comparison_dict['market_type'].lower()}"
    new_symbol = f"symbol_{comparison_market_code}"
    new_quote_asset = f"quote_asset_{comparison_market_code}"
    each_market_info_df = each_market_info_df.rename(columns={"symbol":new_symbol, "quote_asset": new_quote_asset})

    merged_df = target_market_ticker_df.merge(each_market_info_df[[new_symbol, "base_asset", new_quote_asset]], on='base_asset', how='inner')
    if (each_comparison_dict['exchange'] == target_market_dict['exchange'] and
        each_comparison_dict['market_type'] == target_market_dict['market_type']):
        target_market_symbols += merged_df[new_symbol].to_list()
    total_df = pd.concat([total_df, merged_df], axis=0, ignore_index=True)
    target_market_symbols += total_df['symbol'].to_list()

target_market_symbols = list(set(target_market_symbols))
total_target_market_ticker_df = core.info_dict[f"{target_market_dict['exchange'].lower()}_{target_market_dict['market_type'].lower()}_ticker_df"]
total_target_market_df = total_target_market_ticker_df[total_target_market_ticker_df['symbol'].isin(target_market_symbols)]
final_symbol_list = total_target_market_df.sort_values('atp24h', ascending=False)['symbol'].to_list()

# total_df.drop_duplicates(['symbol'], inplace=True)
# total_df.sort_values('atp24h', ascending=False)
# total_df.reset_index(drop=True, inplace=True)
# return total_df['symbol'].to_list()
# get_symbol_list(core, 'UPBIT_SPOT')

In [66]:
len(final_symbol_list)

211

2023-11-17 17:15:34,989 - update_dollar - INFO - fetch_dollar|Dollar price (1299.5 KRW) has been updated.
2023-11-17 17:16:07,431 - update_dollar - INFO - fetch_dollar|Dollar price (1299.5 KRW) has been updated.
2023-11-17 17:16:40,288 - update_dollar - INFO - fetch_dollar|Dollar price (1299.5 KRW) has been updated.
2023-11-17 17:17:12,254 - update_dollar - INFO - fetch_dollar|Dollar price (1299.5 KRW) has been updated.
2023-11-17 17:17:43,896 - update_dollar - INFO - fetch_dollar|Dollar price (1299.5 KRW) has been updated.
2023-11-17 17:18:14,781 - update_dollar - INFO - fetch_dollar|Dollar price (1299.5 KRW) has been updated.
2023-11-17 17:18:45,637 - update_dollar - INFO - fetch_dollar|Dollar price (1299.5 KRW) has been updated.
2023-11-17 17:19:18,022 - update_dollar - INFO - fetch_dollar|Dollar price (1299.5 KRW) has been updated.
2023-11-17 17:19:50,673 - update_dollar - INFO - fetch_dollar|Dollar price (1299.5 KRW) has been updated.
2023-11-17 17:20:23,085 - update_dollar - INFO - fetch_dollar|Dollar price (1299.5 KRW) has been updated.
2023-11-17 17:20:55,260 - update_dollar - INFO - fetch_dollar|Dollar price (1299.5 KRW) has been updated.
2023-11-17 17:21:27,432 - update_dollar - INFO - fetch_dollar|Dollar price (1299.5 KRW) has been updated.
2023-11-17 17:21:59,446 - update_dollar - INFO - fetch_dollar|Dollar price (1299.5 KRW) has been updated.
2023-11-17 17:22:31,358 - update_dollar - INFO - fetch_dollar|Dollar price (1299.5 KRW) has been updated.
2023-11-17 17:23:02,211 - update_dollar - INFO - fetch_dollar|Dollar price (1299.5 KRW) has been updated.
2023-11-17 17:23:33,178 - update_dollar - INFO - fetch_dollar|Dollar price (1299.5 KRW) has been updated.
2023-11-17 17:24:05,084 - update_dollar - INFO - fetch_dollar|Dollar price (1299.5 KRW) has been updated.
2023-11-17 17:24:36,781 - update_dollar - INFO - fetch_dollar|Dollar price (1299.5 KRW) has been updated.
2023-11-17 17:25:08,994 - update_dollar - INFO - fetch_dollar|Dollar price (1299.5 KRW) has been updated.
2023-11-17 17:25:41,447 - update_dollar - INFO - fetch_dollar|Dollar price (1299.0 KRW) has been updated.
2023-11-17 17:26:13,700 - update_dollar - INFO - fetch_dollar|Dollar price (1299.0 KRW) has been updated.
2023-11-17 17:26:45,501 - update_dollar - INFO - fetch_dollar|Dollar price (1299.0 KRW) has been updated.
2023-11-17 17:27:16,570 - update_dollar - INFO - fetch_dollar|Dollar price (1299.0 KRW) has been updated.
2023-11-17 17:27:47,417 - update_dollar - INFO - fetch_dollar|Dollar price (1299.0 KRW) has been updated.
2023-11-17 17:28:19,365 - update_dollar - INFO - fetch_dollar|Dollar price (1299.0 KRW) has been updated.
2023-11-17 17:28:51,813 - update_dollar - INFO - fetch_dollar|Dollar price (1299.0 KRW) has been updated.
2023-11-17 17:29:24,211 - update_dollar - INFO - fetch_dollar|Dollar price (1299.0 KRW) has been updated.
2023-11-17 17:29:56,140 - update_dollar - INFO - fetch_dollar|Dollar price (1298.5 KRW) has been updated.
2023-11-17 17:30:28,024 - update_dollar - INFO - fetch_dollar|Dollar price (1298.0 KRW) has been updated.
2023-11-17 17:30:59,712 - update_dollar - INFO - fetch_dollar|Dollar price (1298.0 KRW) has been updated.
2023-11-17 17:31:32,054 - update_dollar - INFO - fetch_dollar|Dollar price (1298.0 KRW) has been updated.
2023-11-17 17:32:02,906 - update_dollar - INFO - fetch_dollar|Dollar price (1298.0 KRW) has been updated.
2023-11-17 17:32:33,762 - update_dollar - INFO - fetch_dollar|Dollar price (1298.0 KRW) has been updated.
2023-11-17 17:33:05,470 - update_dollar - INFO - fetch_dollar|Dollar price (1298.0 KRW) has been updated.
2023-11-17 17:33:37,544 - update_dollar - INFO - fetch_dollar|Dollar price (1298.0 KRW) has been updated.
2023-11-17 17:34:09,346 - update_dollar - INFO - fetch_dollar|Dollar price (1297.5 KRW) has been updated.
2023-11-17 17:34:42,151 - update_dollar - INFO - fetch_dollar|Dollar price (1297.5 KRW) has been updated.
2023-11-17 17:35:15,479 - update_dollar - INFO - fetch_dollar|Dollar price (1297.5 KRW) has been updated.
2023-11-17 17:35:47,972 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:36:19,053 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:36:49,931 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:37:22,049 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:37:55,053 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:38:27,098 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:38:59,961 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:39:32,672 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:40:05,200 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:40:36,798 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:41:07,601 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:41:39,775 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:42:12,813 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:42:44,531 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:43:16,600 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:43:48,577 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:44:20,601 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:44:53,290 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:45:24,206 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:45:54,952 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:46:26,977 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:46:59,060 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:47:31,123 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:48:03,409 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:48:36,069 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:49:07,982 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:49:40,711 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:50:11,744 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:50:42,577 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:51:14,634 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:51:47,325 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:52:20,119 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:52:52,064 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:53:23,689 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:53:56,449 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:54:27,298 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:54:58,103 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:55:30,040 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:56:03,882 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:56:36,353 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:57:08,472 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:57:40,495 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:58:11,966 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:58:44,478 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:59:15,605 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:59:46,448 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 18:00:18,268 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 18:00:50,862 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 18:01:22,725 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 18:01:54,779 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 18:02:26,484 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 18:02:57,820 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 18:03:28,590 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 18:03:59,449 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 18:04:31,504 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 18:05:04,603 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.

In [61]:
target_market_symbols

['BTC-ADA',
 'BTC-ATOM',
 'BTC-CHZ',
 'KRW-STPT',
 'BTC-ELF',
 'KRW-ADA',
 'BTC-UPP',
 'BTC-DOT',
 'KRW-XEC',
 'KRW-IOST',
 'KRW-QTUM',
 'KRW-CBK',
 'KRW-META',
 'BTC-STEEM',
 'BTC-MLK',
 'BTC-WAXP',
 'KRW-SAND',
 'BTC-SXP',
 'KRW-GMT',
 'KRW-SUI',
 'BTC-MOC',
 'BTC-MANA',
 'KRW-MLK',
 'BTC-CBK',
 'BTC-KAVA',
 'KRW-STEEM',
 'KRW-APT',
 'KRW-IQ',
 'KRW-BAT',
 'KRW-ZRX',
 'BTC-BAT',
 'BTC-BLUR',
 'KRW-MOC',
 'BTC-IOST',
 'KRW-GRS',
 'BTC-MTL',
 'BTC-PLA',
 'KRW-MBL',
 'BTC-ARDR',
 'BTC-EOS',
 'BTC-SEI',
 'KRW-LINK',
 'BTC-ARK',
 'BTC-TRX',
 'BTC-SC',
 'BTC-BCH',
 'BTC-SOL',
 'KRW-NEAR',
 'KRW-ATOM',
 'KRW-ZIL',
 'KRW-HIVE',
 'KRW-BTT',
 'BTC-ETH',
 'BTC-XEM',
 'KRW-XEM',
 'KRW-SEI',
 'KRW-STMX',
 'KRW-AHT',
 'KRW-ORBS',
 'KRW-PLA',
 'KRW-ETC',
 'BTC-HUNT',
 'KRW-TRX',
 'KRW-SXP',
 'KRW-ARB',
 'BTC-MVL',
 'BTC-T',
 'KRW-MASK',
 'KRW-AXS',
 'KRW-WAVES',
 'BTC-STX',
 'KRW-HUNT',
 'KRW-ONT',
 'KRW-BTG',
 'BTC-MATIC',
 'BTC-SBD',
 'BTC-HPO',
 'BTC-JST',
 'BTC-IMX',
 'KRW-SHIB',
 'KRW-DOGE',
 'KRW-EGLD',
 'BTC-GLM',
 'KRW-ARDR',
 'KRW-CHZ',
 'KRW-MATIC',
 'BTC-SAND',
 'BTC-APT',
 'BTC-SNT',
 'BTC-GRT',
 'KRW-JST',
 'KRW-PUNDIX',
 'KRW-SBD',
 'KRW-IMX',
 'BTC-DOGE',
 'KRW-1INCH',
 'KRW-HPO',
 'KRW-BSV',
 'BTC-FCT2',
 'KRW-SSX',
 'BTC-HIFI',
 'KRW-QKC',
 'BTC-BORA',
 'KRW-DKA',
 'KRW-CRO',
 'KRW-STORJ',
 'BTC-POLYX',
 'BTC-AERGO',
 'BTC-SUI',
 'KRW-TON',
 'BTC-TON',
 'KRW-STX',
 'BTC-AVAX',
 'KRW-TFUEL',
 'KRW-UPP',
 'BTC-VET',
 'BTC-AXS',
 'BTC-MINA',
 'KRW-THETA',
 'KRW-EOS',
 'BTC-BSV',
 'BTC-1INCH',
 'KRW-POWR',
 'KRW-GAS',
 'BTC-XLM',
 'KRW-SC',
 'KRW-MED',
 'KRW-WAXP',
 'KRW-LOOM',
 'BTC-META',
 'BTC-AAVE',
 'KRW-LSK',
 'KRW-STRK',
 'KRW-FCT2',
 'BTC-IQ',
 'BTC-ALGO',
 'KRW-MANA',
 'KRW-XRP',
 'BTC-POWR',
 'BTC-XTZ',
 'KRW-CELO',
 'KRW-DOT',
 'KRW-ONG',
 'BTC-CRO',
 'KRW-XTZ',
 'KRW-AERGO',
 'KRW-GRT',
 'BTC-SSX',
 'KRW-NEO',
 'BTC-PUNDIX',
 'BTC-ANKR',
 'KRW-STRAX',
 'KRW-HIFI',
 'BTC-GMT',
 'KRW-BCH',
 'BTC-ZIL',
 'BTC-DKA',
 'BTC-LINK',
 'KRW-KAVA',
 'BTC-ARB',
 'KRW-VET',
 'BTC-CELO',
 'BTC-ZRX',
 'KRW-ELF',
 'KRW-MTL',
 'KRW-AQT',
 'KRW-HBAR',
 'KRW-FLOW',
 'KRW-BORA',
 'BTC-STMX',
 'BTC-XRP',
 'BTC-QTUM',
 'KRW-BTC',
 'BTC-AQT',
 'BTC-WAVES',
 'KRW-MINA',
 'BTC-NEAR',
 'BTC-STPT',
 'BTC-MED',
 'KRW-ANKR',
 'BTC-ETC',
 'BTC-LOOM',
 'KRW-ARK',
 'KRW-SNT',
 'BTC-LSK',
 'KRW-AAVE',
 'KRW-AVAX',
 'BTC-AHT',
 'BTC-MASK',
 'BTC-FLOW',
 'KRW-POLYX',
 'BTC-STRAX',
 'KRW-CVC',
 'BTC-STORJ',
 'BTC-GRS',
 'KRW-SOL',
 'KRW-IOTA',
 'BTC-EGLD',
 'KRW-ETH',
 'KRW-XLM',
 'KRW-T',
 'KRW-ALGO',
 'BTC-ORBS',
 'BTC-CVC',
 'BTC-HIVE',
 'KRW-MVL',
 'KRW-BLUR',
 'KRW-GLM',
 'KRW-ICX',
 'BTC-STRK',
 'KRW-KNC']

2023-11-17 17:09:11,836 - update_dollar - INFO - fetch_dollar|Dollar price (1300.0 KRW) has been updated.

In [60]:
len(final_symbol_list)

114

In [56]:
same_market_symbols

['BTC-ETH',
 'BTC-MTL',
 'BTC-XRP',
 'BTC-ETC',
 'BTC-SNT',
 'BTC-WAVES',
 'BTC-XEM',
 'BTC-QTUM',
 'BTC-LSK',
 'BTC-STEEM',
 'BTC-XLM',
 'BTC-ARDR',
 'BTC-ARK',
 'BTC-STORJ',
 'BTC-GRS',
 'BTC-ADA',
 'BTC-SBD',
 'BTC-POWR',
 'BTC-EOS',
 'BTC-TRX',
 'BTC-SC',
 'BTC-ZIL',
 'BTC-POLYX',
 'BTC-ZRX',
 'BTC-LOOM',
 'BTC-BCH',
 'BTC-BAT',
 'BTC-IOST',
 'BTC-CVC',
 'BTC-IQ',
 'BTC-HIFI',
 'BTC-UPP',
 'BTC-ELF',
 'BTC-BSV',
 'BTC-MOC',
 'BTC-MANA',
 'BTC-ANKR',
 'BTC-AERGO',
 'BTC-ATOM',
 'BTC-WAXP',
 'BTC-MED',
 'BTC-MLK',
 'BTC-STPT',
 'BTC-ORBS',
 'BTC-VET',
 'BTC-CHZ',
 'BTC-STMX',
 'BTC-DKA',
 'BTC-HIVE',
 'BTC-KAVA',
 'BTC-AHT',
 'BTC-LINK',
 'BTC-XTZ',
 'BTC-BORA',
 'BTC-JST',
 'BTC-CRO',
 'BTC-TON',
 'BTC-SXP',
 'BTC-HUNT',
 'BTC-PLA',
 'BTC-DOT',
 'BTC-MVL',
 'BTC-STRAX',
 'BTC-AQT',
 'BTC-GLM',
 'BTC-SSX',
 'BTC-META',
 'BTC-FCT2',
 'BTC-CBK',
 'BTC-SAND',
 'BTC-HPO',
 'BTC-DOGE',
 'BTC-STRK',
 'BTC-PUNDIX',
 'BTC-FLOW',
 'BTC-AXS',
 'BTC-STX',
 'BTC-SOL',
 'BTC-MATIC',
 'BTC-AAVE',
 'BTC-1INCH',
 'BTC-ALGO',
 'BTC-NEAR',
 'BTC-AVAX',
 'BTC-T',
 'BTC-CELO',
 'BTC-GMT',
 'BTC-APT',
 'BTC-MASK',
 'BTC-ARB',
 'BTC-EGLD',
 'BTC-SUI',
 'BTC-GRT',
 'BTC-BLUR',
 'BTC-IMX',
 'BTC-SEI',
 'BTC-MINA']

2023-11-17 17:03:22,015 - update_dollar - INFO - fetch_dollar|Dollar price (1300.5 KRW) has been updated.
2023-11-17 17:03:54,014 - update_dollar - INFO - fetch_dollar|Dollar price (1300.5 KRW) has been updated.

In [57]:
total_df

,symbol,lastPrice,atp24h,base_asset,quote_asset,symbol_upbit_spot,quote_asset_upbit_spot,symbol_binance_spot,quote_asset_binance_spot,symbol_binance_usd_m,quote_asset_binance_usd_m,symbol_bybit_usd_m,quote_asset_bybit_usd_m
0,KRW-ETH,2.659000e+06,1.115199e+11,ETH,KRW,BTC-ETH,BTC,NaN,NaN,NaN,NaN,NaN,NaN
1,KRW-MTL,2.305000e+03,1.273609e+10,MTL,KRW,BTC-MTL,BTC,NaN,NaN,NaN,NaN,NaN,NaN
2,KRW-XRP,8.310000e+02,2.498419e+11,XRP,KRW,BTC-XRP,BTC,NaN,NaN,NaN,NaN,NaN,NaN
3,KRW-ETC,2.612000e+04,1.171078e+11,ETC,KRW,BTC-ETC,BTC,NaN,NaN,NaN,NaN,NaN,NaN
4,KRW-SNT,5.810000e+01,8.296213e+09,SNT,KRW,BTC-SNT,BTC,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
109,KRW-TFUEL,6.070000e+01,3.289010e+09,TFUEL,KRW,NaN,NaN,TFUELUSDT,USDT,NaN,NaN,NaN,NaN
110,KRW-MBL,7.760000e+00,3.568509e+10,MBL,KRW,NaN,NaN,MBLUSDT,USDT,NaN,NaN,NaN,NaN
111,KRW-HBAR,8.790000e+01,3.778188e+10,HBAR,KRW,NaN,NaN,HBARUSDT,USDT,NaN,NaN,NaN,NaN
112,KRW-XEC,4.050000e-02,9.703034e+09,XEC,KRW,NaN,NaN,XECUSDT,USDT,NaN,NaN,NaN,NaN
113,KRW-SHIB,1.170000e-02,1.123301e+10,SHIB,KRW,NaN,NaN,SHIBUSDT,USDT,NaN,NaN,NaN,NaN

2023-11-17 17:04:24,964 - update_dollar - INFO - fetch_dollar|Dollar price (1300.5 KRW) has been updated.

In [34]:
temp = core.get_symbol_list("BINANCE_SPOT")
temp

['BTCUSDT',
 'ETHUSDT',
 'NEOUSDT',
 'QTUMUSDT',
 'ADAUSDT',
 'XRPUSDT',
 'EOSUSDT',
 'IOTAUSDT',
 'XLMUSDT',
 'ONTUSDT',
 'TRXUSDT',
 'ETCUSDT',
 'ICXUSDT',
 'VETUSDT',
 'LINKUSDT',
 'WAVESUSDT',
 'BTTUSDT',
 'ONGUSDT',
 'ZILUSDT',
 'ZRXUSDT',
 'BATUSDT',
 'IOSTUSDT',
 'THETAUSDT',
 'MATICUSDT',
 'ATOMUSDT',
 'TFUELUSDT',
 'ALGOUSDT',
 'DOGEUSDT',
 'ANKRUSDT',
 'MTLUSDT',
 'CVCUSDT',
 'CHZUSDT',
 'XTZUSDT',
 'HBARUSDT',
 'STXUSDT',
 'KAVAUSDT',
 'BCHUSDT',
 'LSKUSDT',
 'MBLUSDT',
 'STPTUSDT',
 'SOLUSDT',
 'HIVEUSDT',
 'ARDRUSDT',
 'STMXUSDT',
 'KNCUSDT',
 'SCUSDT',
 'SXPUSDT',
 'STORJUSDT',
 'MANAUSDT',
 'JSTUSDT',
 'SANDUSDT',
 'DOTUSDT',
 'EGLDUSDT',
 'AVAXUSDT',
 'AAVEUSDT',
 'NEARUSDT',
 'AXSUSDT',
 'STRAXUSDT',
 'XEMUSDT',
 'GRTUSDT',
 '1INCHUSDT',
 'CELOUSDT',
 'PUNDIXUSDT',
 'BTGUSDT',
 'SHIBUSDT',
 'MASKUSDT',
 'FLOWUSDT',
 'MINAUSDT',
 'WAXPUSDT',
 'XECUSDT',
 'ELFUSDT',
 'POWRUSDT',
 'PLAUSDT',
 'IMXUSDT',
 'TUSDT',
 'GMTUSDT',
 'STEEMUSDT',
 'POLYXUSDT',
 'APTUSDT',
 'HIFIUSDT',
 'GASUSDT',
 'GLMUSDT',
 'QKCUSDT',
 'ARBUSDT',
 'LOOMUSDT',
 'SUIUSDT',
 'AERGOUSDT',
 'SNTUSDT',
 'SEIUSDT',
 'ARKUSDT',
 'IQUSDT',
 'TUSDUSDT',
 'ENJUSDT',
 'DENTUSDT',
 'RVNUSDT',
 'NKNUSDT',
 'ARPAUSDT',
 'IOTXUSDT',
 'RLCUSDT',
 'OGNUSDT',
 'BNTUSDT',
 'CTSIUSDT',
 'CHRUSDT',
 'LRCUSDT',
 'COMPUSDT',
 'SNXUSDT',
 'DGBUSDT',
 'MKRUSDT',
 'DAIUSDT',
 'CRVUSDT',
 'OCEANUSDT',
 'NMRUSDT',
 'RSRUSDT',
 'UNIUSDT',
 'OXTUSDT',
 'SUNUSDT',
 'FILUSDT',
 'INJUSDT',
 'AUDIOUSDT',
 'DNTUSDT',
 'JUVUSDT',
 'PSGUSDT',
 'ATMUSDT',
 'ACMUSDT',
 'BARUSDT',
 'LPTUSDT',
 'GTCUSDT',
 'RAYUSDT',
 'FORUSDT',
 'USDPUSDT',
 'YGGUSDT',
 'AGLDUSDT',
 'RADUSDT',
 'AUCTIONUSDT',
 'CITYUSDT',
 'ENSUSDT',
 'RNDRUSDT',
 'GLMRUSDT',
 'API3USDT',
 'ASTRUSDT',
 'APEUSDT',
 'REIUSDT',
 'GALUSDT',
 'STGUSDT',
 'MAGICUSDT',
 'PROMUSDT',
 'CYBERUSDT',
 'BNBUSDT',
 'LTCUSDT',
 'USDCUSDT',
 'HOTUSDT',
 'FETUSDT',
 'XMRUSDT',
 'ZECUSDT',
 'CELRUSDT',
 'DASHUSDT',
 'OMGUSDT',
 'ONEUSDT',
 'FTMUSDT',
 'DUSKUSDT',
 'COCOSUSDT',
 'TOMOUSDT',
 'KEYUSDT',
 'BANDUSDT',
 'RENUSDT',
 'FTTUSDT',
 'BTSUSDT',
 'COTIUSDT',
 'MDTUSDT',
 'ZENUSDT',
 'YFIUSDT',
 'BALUSDT',
 'BLZUSDT',
 'SRMUSDT',
 'ANTUSDT',
 'TRBUSDT',
 'SUSHIUSDT',
 'KSMUSDT',
 'RUNEUSDT',
 'UMAUSDT',
 'BELUSDT',
 'HNTUSDT',
 'FLMUSDT',
 'XVSUSDT',
 'ALPHAUSDT',
 'CTKUSDT',
 'UNFIUSDT',
 'ROSEUSDT',
 'SKLUSDT',
 'REEFUSDT',
 'RIFUSDT',
 'TRUUSDT',
 'CKBUSDT',
 'TWTUSDT',
 'LITUSDT',
 'SFPUSDT',
 'CAKEUSDT',
 'BADGERUSDT',
 'ALICEUSDT',
 'LINAUSDT',
 'PERPUSDT',
 'CFXUSDT',
 'TLMUSDT',
 'BAKEUSDT',
 'SLPUSDT',
 'ICPUSDT',
 'ARUSDT',
 'XVGUSDT',
 'ATAUSDT',
 'KLAYUSDT',
 'BONDUSDT',
 'C98USDT',
 'QNTUSDT',
 'DYDXUSDT',
 'IDEXUSDT',
 'GALAUSDT',
 'ILVUSDT',
 'FRONTUSDT',
 'DARUSDT',
 'BNXUSDT',
 'JASMYUSDT',
 'BICOUSDT',
 'FXSUSDT',
 'HIGHUSDT',
 'CVXUSDT',
 'PEOPLEUSDT',
 'SPELLUSDT',
 'JOEUSDT',
 'ACHUSDT',
 'WOOUSDT',
 'LDOUSDT',
 'OPUSDT',
 'LEVERUSDT',
 'GMXUSDT',
 'HFTUSDT',
 'PHBUSDT',
 'HOOKUSDT',
 'AGIXUSDT',
 'SSVUSDT',
 'LQTYUSDT',
 'AMBUSDT',
 'IDUSDT',
 'RDNTUSDT',
 'EDUUSDT',
 'COMBOUSDT',
 'MAVUSDT',
 'PENDLEUSDT',
 'ARKMUSDT',
 'WLDUSDT',
 'NTRNUSDT',
 'TIAUSDT',
 'MEMEUSDT',
 'ORDIUSDT',
 'BUSDUSDT',
 'BEAMUSDT',
 'PAXGUSDT',
 'YFIIUSDT',
 'AKROUSDT',
 'OGUSDT',
 'DODOUSDT',
 'FORTHUSDT',
 'ALPACAUSDT',
 'REQUSDT',
 'VGXUSDT',
 'SCRTUSDT',
 'XNOUSDT',
 'KDAUSDT',
 'BSWUSDT',
 'MULTIUSDT',
 'RPLUSDT',
 'GFTUSDT']

2023-11-17 16:40:29,872 - update_dollar - INFO - fetch_dollar|Dollar price (1299.5 KRW) has been updated.
2023-11-17 16:41:01,912 - update_dollar - INFO - fetch_dollar|Dollar price (1299.5 KRW) has been updated.
2023-11-17 16:41:33,641 - update_dollar - INFO - fetch_dollar|Dollar price (1299.5 KRW) has been updated.

In [18]:
[x for x in temp if 'BTC' in x]

['KRW-BTC']

2023-11-17 16:33:04,138 - update_dollar - INFO - fetch_dollar|Dollar price (1299.5 KRW) has been updated.
2023-11-17 16:33:34,901 - update_dollar - INFO - fetch_dollar|Dollar price (1299.5 KRW) has been updated.

In [5]:
core.get_premium_df('UPBIT_SPOT/BTC', "BINANCE_USD_M/USDT")

resampling ohlc_df(length: 82): 0.8031275272369385

2023-11-17 16:28:10,402 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_4H_kline base_asset is not matched. added: ['ANKR', 'CVC', 'ELF', 'HIVE', 'IQ', 'PUNDIX', 'SC'], removed: []
2023-11-17 16:28:10,612 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_1H_kline base_asset is not matched. added: ['ANKR', 'CVC', 'ELF', 'HIVE', 'IQ', 'PUNDIX', 'SC'], removed: []
2023-11-17 16:28:10,755 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_15T_kline time: 0.00013875961303710938
2023-11-17 16:28:10,754 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_15T_kline time: 0.0003762245178222656

resampling ohlc_df(length: 162): 0.7972066402435303

2023-11-17 16:28:10,753 - kline_core - INFO - resampling ohlc_df(length: 329): 1.2126274108886719
2023-11-17 16:28:10,932 - kline_core - INFO - resampling ohlc_df(length: 162): 1.3442575931549072
2023-11-17 16:28:10,933 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_30T_kline time: 0.0003600120544433594
2023-11-17 16:28:10,933 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_30T_kline time: 0.00011563301086425781
2023-11-17 16:28:10,941 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_30T_kline base_asset is not matched. added: ['ANKR', 'CVC', 'ELF', 'HIVE', 'IQ', 'PUNDIX', 'SC'], removed: []
2023-11-17 16:28:12,670 - kline_core - ERROR - ohlc_1T_loader|target_market_code:UPBIT_SPOT/KRW, origin_market_code:UPBIT_SPOT/BTC, Error in ohlc_1T_loader: Traceback (most recent call last):
  File "/home/kp_info_loader/kline_generator/kline_core.py", line 159, in ohlc_1T_loader
    ohlc_df = self.generate_ohlc_df(appended_premium_df)
  File "/home/kp_info_loader/kline_generator/kline_core.py", line 108, in generate_ohlc_df
    ohlc_df['dollar'] = df['dollar'].iloc[-1]
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1103, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1656, in _getitem_axis
    self._validate_integer(key, axis)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1589, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds

 appended_premium_df:Empty DataFrame
Columns: [tp_premium, LS_premium, SL_premium, LS_SL_spread, base_asset, quote_asset, tp, ap, bp, scr, atp24h, converted_tp, converted_ap, converted_bp, dollar, datetime_now]
Index: [], premium_df:Empty DataFrame
Columns: [tp_premium, LS_premium, SL_premium, LS_SL_spread, base_asset, quote_asset, tp, ap, bp, scr, atp24h, converted_tp, converted_ap, converted_bp, dollar, datetime_now]
Index: []

resampling ohlc_df(length: 82): 1.034785509109497

2023-11-17 16:28:13,011 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_1D_kline base_asset is not matched. added: ['ANKR', 'CVC', 'ELF', 'HIVE', 'IQ', 'PUNDIX', 'SC'], removed: []
2023-11-17 16:28:15,785 - kline_core - ERROR - ohlc_1T_loader|target_market_code:UPBIT_SPOT/KRW, origin_market_code:UPBIT_SPOT/BTC, Error in ohlc_1T_loader: Traceback (most recent call last):
  File "/home/kp_info_loader/kline_generator/kline_core.py", line 159, in ohlc_1T_loader
    ohlc_df = self.generate_ohlc_df(appended_premium_df)
  File "/home/kp_info_loader/kline_generator/kline_core.py", line 108, in generate_ohlc_df
    ohlc_df['dollar'] = df['dollar'].iloc[-1]
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1103, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1656, in _getitem_axis
    self._validate_integer(key, axis)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1589, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds

 appended_premium_df:Empty DataFrame
Columns: [tp_premium, LS_premium, SL_premium, LS_SL_spread, base_asset, quote_asset, tp, ap, bp, scr, atp24h, converted_tp, converted_ap, converted_bp, dollar, datetime_now]
Index: [], premium_df:Empty DataFrame
Columns: [tp_premium, LS_premium, SL_premium, LS_SL_spread, base_asset, quote_asset, tp, ap, bp, scr, atp24h, converted_tp, converted_ap, converted_bp, dollar, datetime_now]
Index: []

2023-11-17 16:28:16,176 - update_dollar - INFO - fetch_dollar|Dollar price (1299.5 KRW) has been updated.
2023-11-17 16:28:27,743 - kline_core - INFO - insert_kline_to_db|INFO_CORE|UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_1H_kline No klines to be inserted
2023-11-17 16:28:27,937 - kline_core - INFO - insert_kline_to_db|INFO_CORE|UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_4H_kline No klines to be inserted
2023-11-17 16:28:28,287 - kline_core - INFO - insert_kline_to_db|INFO_CORE|UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_1D_kline No klines to be inserted

resampling ohlc_df(length: 82): 0.8510136604309082

2023-11-17 16:28:16,368 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_4H_kline base_asset is not matched. added: ['ANKR', 'CVC', 'ELF', 'HIVE', 'IQ', 'PUNDIX', 'SC'], removed: []

resampling ohlc_df(length: 162): 0.832120418548584

2023-11-17 16:28:16,560 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_1H_kline base_asset is not matched. added: ['ANKR', 'CVC', 'ELF', 'HIVE', 'IQ', 'PUNDIX', 'SC'], removed: []
2023-11-17 16:28:17,004 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_30T_kline time: 0.0001392364501953125
2023-11-17 16:28:17,004 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_30T_kline time: 0.0003650188446044922
2023-11-17 16:28:17,002 - kline_core - INFO - resampling ohlc_df(length: 169): 0.9555423259735107
2023-11-17 16:28:18,903 - kline_core - ERROR - ohlc_1T_loader|target_market_code:UPBIT_SPOT/KRW, origin_market_code:UPBIT_SPOT/BTC, Error in ohlc_1T_loader: Traceback (most recent call last):
  File "/home/kp_info_loader/kline_generator/kline_core.py", line 159, in ohlc_1T_loader
    ohlc_df = self.generate_ohlc_df(appended_premium_df)
  File "/home/kp_info_loader/kline_generator/kline_core.py", line 108, in generate_ohlc_df
    ohlc_df['dollar'] = df['dollar'].iloc[-1]
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1103, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1656, in _getitem_axis
    self._validate_integer(key, axis)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1589, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds

 appended_premium_df:Empty DataFrame
Columns: [tp_premium, LS_premium, SL_premium, LS_SL_spread, base_asset, quote_asset, tp, ap, bp, scr, atp24h, converted_tp, converted_ap, converted_bp, dollar, datetime_now]
Index: [], premium_df:Empty DataFrame
Columns: [tp_premium, LS_premium, SL_premium, LS_SL_spread, base_asset, quote_asset, tp, ap, bp, scr, atp24h, converted_tp, converted_ap, converted_bp, dollar, datetime_now]
Index: []
2023-11-17 16:28:18,960 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_1D_kline base_asset is not matched. added: ['ANKR', 'CVC', 'ELF', 'HIVE', 'IQ', 'PUNDIX', 'SC'], removed: []

resampling ohlc_df(length: 82): 0.8375968933105469

2023-11-17 16:28:22,018 - kline_core - ERROR - ohlc_1T_loader|target_market_code:UPBIT_SPOT/KRW, origin_market_code:UPBIT_SPOT/BTC, Error in ohlc_1T_loader: Traceback (most recent call last):
  File "/home/kp_info_loader/kline_generator/kline_core.py", line 159, in ohlc_1T_loader
    ohlc_df = self.generate_ohlc_df(appended_premium_df)
  File "/home/kp_info_loader/kline_generator/kline_core.py", line 108, in generate_ohlc_df
    ohlc_df['dollar'] = df['dollar'].iloc[-1]
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1103, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1656, in _getitem_axis
    self._validate_integer(key, axis)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1589, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds

 appended_premium_df:Empty DataFrame
Columns: [tp_premium, LS_premium, SL_premium, LS_SL_spread, base_asset, quote_asset, tp, ap, bp, scr, atp24h, converted_tp, converted_ap, converted_bp, dollar, datetime_now]
Index: [], premium_df:Empty DataFrame
Columns: [tp_premium, LS_premium, SL_premium, LS_SL_spread, base_asset, quote_asset, tp, ap, bp, scr, atp24h, converted_tp, converted_ap, converted_bp, dollar, datetime_now]
Index: []

resampling ohlc_df(length: 82): 0.8253812789916992

2023-11-17 16:28:22,311 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_4H_kline base_asset is not matched. added: ['ANKR', 'CVC', 'ELF', 'HIVE', 'IQ', 'PUNDIX', 'SC'], removed: []

resampling ohlc_df(length: 169): 0.877469539642334
resampling ohlc_df(length: 82): 0.8109667301177979

2023-11-17 16:28:24,887 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_1D_kline base_asset is not matched. added: ['ANKR', 'CVC', 'ELF', 'HIVE', 'IQ', 'PUNDIX', 'SC'], removed: []
2023-11-17 16:28:25,121 - kline_core - ERROR - ohlc_1T_loader|target_market_code:UPBIT_SPOT/KRW, origin_market_code:UPBIT_SPOT/BTC, Error in ohlc_1T_loader: Traceback (most recent call last):
  File "/home/kp_info_loader/kline_generator/kline_core.py", line 159, in ohlc_1T_loader
    ohlc_df = self.generate_ohlc_df(appended_premium_df)
  File "/home/kp_info_loader/kline_generator/kline_core.py", line 108, in generate_ohlc_df
    ohlc_df['dollar'] = df['dollar'].iloc[-1]
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1103, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1656, in _getitem_axis
    self._validate_integer(key, axis)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1589, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds

 appended_premium_df:Empty DataFrame
Columns: [tp_premium, LS_premium, SL_premium, LS_SL_spread, base_asset, quote_asset, tp, ap, bp, scr, atp24h, converted_tp, converted_ap, converted_bp, dollar, datetime_now]
Index: [], premium_df:Empty DataFrame
Columns: [tp_premium, LS_premium, SL_premium, LS_SL_spread, base_asset, quote_asset, tp, ap, bp, scr, atp24h, converted_tp, converted_ap, converted_bp, dollar, datetime_now]
Index: []
2023-11-17 16:28:28,236 - kline_core - ERROR - ohlc_1T_loader|target_market_code:UPBIT_SPOT/KRW, origin_market_code:UPBIT_SPOT/BTC, Error in ohlc_1T_loader: Traceback (most recent call last):
  File "/home/kp_info_loader/kline_generator/kline_core.py", line 159, in ohlc_1T_loader
    ohlc_df = self.generate_ohlc_df(appended_premium_df)
  File "/home/kp_info_loader/kline_generator/kline_core.py", line 108, in generate_ohlc_df
    ohlc_df['dollar'] = df['dollar'].iloc[-1]
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1103, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1656, in _getitem_axis
    self._validate_integer(key, axis)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1589, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds

 appended_premium_df:Empty DataFrame
Columns: [tp_premium, LS_premium, SL_premium, LS_SL_spread, base_asset, quote_asset, tp, ap, bp, scr, atp24h, converted_tp, converted_ap, converted_bp, dollar, datetime_now]
Index: [], premium_df:Empty DataFrame
Columns: [tp_premium, LS_premium, SL_premium, LS_SL_spread, base_asset, quote_asset, tp, ap, bp, scr, atp24h, converted_tp, converted_ap, converted_bp, dollar, datetime_now]
Index: []

resampling ohlc_df(length: 89): 0.8227534294128418
resampling ohlc_df(length: 89): 0.871284008026123

2023-11-17 16:28:31,345 - kline_core - ERROR - ohlc_1T_loader|target_market_code:UPBIT_SPOT/KRW, origin_market_code:UPBIT_SPOT/BTC, Error in ohlc_1T_loader: Traceback (most recent call last):
  File "/home/kp_info_loader/kline_generator/kline_core.py", line 159, in ohlc_1T_loader
    ohlc_df = self.generate_ohlc_df(appended_premium_df)
  File "/home/kp_info_loader/kline_generator/kline_core.py", line 108, in generate_ohlc_df
    ohlc_df['dollar'] = df['dollar'].iloc[-1]
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1103, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1656, in _getitem_axis
    self._validate_integer(key, axis)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1589, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds

 appended_premium_df:Empty DataFrame
Columns: [tp_premium, LS_premium, SL_premium, LS_SL_spread, base_asset, quote_asset, tp, ap, bp, scr, atp24h, converted_tp, converted_ap, converted_bp, dollar, datetime_now]
Index: [], premium_df:Empty DataFrame
Columns: [tp_premium, LS_premium, SL_premium, LS_SL_spread, base_asset, quote_asset, tp, ap, bp, scr, atp24h, converted_tp, converted_ap, converted_bp, dollar, datetime_now]
Index: []
2023-11-17 16:28:34,458 - kline_core - ERROR - ohlc_1T_loader|target_market_code:UPBIT_SPOT/KRW, origin_market_code:UPBIT_SPOT/BTC, Error in ohlc_1T_loader: Traceback (most recent call last):
  File "/home/kp_info_loader/kline_generator/kline_core.py", line 159, in ohlc_1T_loader
    ohlc_df = self.generate_ohlc_df(appended_premium_df)
  File "/home/kp_info_loader/kline_generator/kline_core.py", line 108, in generate_ohlc_df
    ohlc_df['dollar'] = df['dollar'].iloc[-1]
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1103, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1656, in _getitem_axis
    self._validate_integer(key, axis)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1589, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds

 appended_premium_df:Empty DataFrame
Columns: [tp_premium, LS_premium, SL_premium, LS_SL_spread, base_asset, quote_asset, tp, ap, bp, scr, atp24h, converted_tp, converted_ap, converted_bp, dollar, datetime_now]
Index: [], premium_df:Empty DataFrame
Columns: [tp_premium, LS_premium, SL_premium, LS_SL_spread, base_asset, quote_asset, tp, ap, bp, scr, atp24h, converted_tp, converted_ap, converted_bp, dollar, datetime_now]
Index: []
2023-11-17 16:28:37,578 - kline_core - ERROR - ohlc_1T_loader|target_market_code:UPBIT_SPOT/KRW, origin_market_code:UPBIT_SPOT/BTC, Error in ohlc_1T_loader: Traceback (most recent call last):
  File "/home/kp_info_loader/kline_generator/kline_core.py", line 159, in ohlc_1T_loader
    ohlc_df = self.generate_ohlc_df(appended_premium_df)
  File "/home/kp_info_loader/kline_generator/kline_core.py", line 108, in generate_ohlc_df
    ohlc_df['dollar'] = df['dollar'].iloc[-1]
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1103, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1656, in _getitem_axis
    self._validate_integer(key, axis)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1589, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds

 appended_premium_df:Empty DataFrame
Columns: [tp_premium, LS_premium, SL_premium, LS_SL_spread, base_asset, quote_asset, tp, ap, bp, scr, atp24h, converted_tp, converted_ap, converted_bp, dollar, datetime_now]
Index: [], premium_df:Empty DataFrame
Columns: [tp_premium, LS_premium, SL_premium, LS_SL_spread, base_asset, quote_asset, tp, ap, bp, scr, atp24h, converted_tp, converted_ap, converted_bp, dollar, datetime_now]
Index: []
2023-11-17 16:28:40,683 - kline_core - ERROR - ohlc_1T_loader|target_market_code:UPBIT_SPOT/KRW, origin_market_code:UPBIT_SPOT/BTC, Error in ohlc_1T_loader: Traceback (most recent call last):
  File "/home/kp_info_loader/kline_generator/kline_core.py", line 159, in ohlc_1T_loader
    ohlc_df = self.generate_ohlc_df(appended_premium_df)
  File "/home/kp_info_loader/kline_generator/kline_core.py", line 108, in generate_ohlc_df
    ohlc_df['dollar'] = df['dollar'].iloc[-1]
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1103, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1656, in _getitem_axis
    self._validate_integer(key, axis)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1589, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds

 appended_premium_df:Empty DataFrame
Columns: [tp_premium, LS_premium, SL_premium, LS_SL_spread, base_asset, quote_asset, tp, ap, bp, scr, atp24h, converted_tp, converted_ap, converted_bp, dollar, datetime_now]
Index: [], premium_df:Empty DataFrame
Columns: [tp_premium, LS_premium, SL_premium, LS_SL_spread, base_asset, quote_asset, tp, ap, bp, scr, atp24h, converted_tp, converted_ap, converted_bp, dollar, datetime_now]
Index: []

In [ ]:
target_market_code = "UPBIT_SPOT/KRW"
origin_market_code = "BINANCE_USD_M/USDT"
core.get_premium_df(target_market_code, origin_market_code)

In [ ]:
origin_market = "UPBIT_SPOT"
target_market = "BINANCE_SPOT"

origin_market_spot_info_df = core.info_dict['binance_spot_info_df']
origin_quote_asset = 'BTC'
target_quote_asset = 'USDT'

if origin_quote_asset == "USD":
    origin_quote_asset = "USDT"
if target_quote_asset == "USD":
    target_quote_asset = "USDT"
if origin_quote_asset == target_quote_asset:
    # return 1
    print(1) # TEST
# origin_market_spot_info_df = self.info_dict[f"{origin_market.lower().split('_')[0]}_spot_ticker_df"]
origin_market_spot_info_df = core.info_dict[f"{origin_market.lower().split('_')[0]}_spot_ticker_df"] # TEST
# First try to find the rate from the info_dict

def convert_between_coins(origin_market_spot_info_df, origin_quote_asset, target_quote_asset):
    df = origin_market_spot_info_df[(origin_market_spot_info_df['base_asset']==origin_quote_asset)&(origin_market_spot_info_df['quote_asset']==target_quote_asset)]
    reverse_df = origin_market_spot_info_df[(origin_market_spot_info_df['quote_asset']==origin_quote_asset)&(origin_market_spot_info_df['base_asset']==target_quote_asset)]
    if len(df) == 1:
        convert_rate = df['lastPrice'].values[0]
    elif len(reverse_df) == 1:
        convert_rate = 1 / reverse_df['lastPrice'].values[0]
    else:
        convert_rate = None
    return convert_rate
convert_rate = convert_between_coins(origin_market_spot_info_df, origin_quote_asset, target_quote_asset)
if convert_rate is None: # not between coins
    # print("1st convert_rate is None, Not between coins")
    if target_quote_asset == "KRW" and origin_quote_asset == "USDT":
        # convert_rate = self.get_dollar_dict()['price']
        convert_rate = core.get_dollar_dict()['price'] # TEST
    elif target_quote_asset == "USDT" and origin_quote_asset == "KRW":
        # convert_rate = 1 / self.get_dollar_dict()['price']
        convert_rate = 1 / core.get_dollar_dict()['price'] # TEST
    elif target_quote_asset == "KRW":
        # convert_rate = convert_between_coins(origin_market_spot_info_df, origin_quote_asset, "USDT") * self.get_dollar_dict()['price']
        convert_rate = convert_between_coins(origin_market_spot_info_df, origin_quote_asset, "USDT") * core.get_dollar_dict()['price'] # TEST
    elif origin_quote_asset == "KRW":
        # temp_convert_rate = self.convert_asset_rate(target_market, target_quote_asset, origin_market, origin_quote_asset)
        temp_convert_rate = core.convert_asset_rate(target_market, target_quote_asset, origin_market, origin_quote_asset) # TEST
        if temp_convert_rate is not None:
            convert_rate = 1 / temp_convert_rate
        else:
            title = f"target_market: {target_market}, target_quote_asset: {target_quote_asset}, origin_market:{origin_market}, origin_quote_asset: {origin_quote_asset}"
            raise Exception(f"Cannot find the convert rate for {title}")
    else:
        # temp_convert_rate = self.convert_asset_rate(target_market, target_quote_asset, origin_market, "USDT")
        temp_convert_rate = core.convert_asset_rate(target_market, target_quote_asset, origin_market, origin_quote_asset) # TEST
        if temp_convert_rate is not None:
            convert_rate = 1 / temp_convert_rate
            # return convert_rate
            print(convert_rate)
        else:
            pass
        title = f"target_market: {target_market}, target_quote_asset: {target_quote_asset}, origin_market:{origin_market}, origin_quote_asset: {origin_quote_asset}"
        raise Exception(f"Cannot find the convert rate for {title}")
# return convert_rate
print(convert_rate) # TEST

In [ ]:
origin_market_spot_info_df.columns

In [ ]:
origin_market_spot_info_df[['market','base_asset','quote_asset']]#[(origin_market_spot_info_df['base_asset']==origin_quote_asset)&(origin_market_spot_info_df['quote_asset']==target_quote_asset)]

In [ ]:
temp_convert_rate

In [ ]:
def convert_asset_rate(self, origin_market, origin_quote_asset, target_market, target_quote_asset):
    if origin_quote_asset == "USD":
        origin_quote_asset = "USDT"
    if target_quote_asset == "USD":
        target_quote_asset = "USDT"
    if origin_quote_asset == target_quote_asset:
        return 1
    origin_market_spot_info_df = self.info_dict[f"{origin_market.lower().split('_')[0]}_spot_ticker_df"]
    # First try to find the rate from the info_dict

    def convert_between_coins(origin_market_spot_info_df, origin_quote_asset, target_quote_asset):
        df = origin_market_spot_info_df[(origin_market_spot_info_df['base_asset']==origin_quote_asset)&(origin_market_spot_info_df['quote_asset']==target_quote_asset)]
        reverse_df = origin_market_spot_info_df[(origin_market_spot_info_df['quote_asset']==origin_quote_asset)&(origin_market_spot_info_df['base_asset']==target_quote_asset)]
        if len(df) == 1:
            convert_rate = df['lastPrice'].values[0]
        elif len(reverse_df) == 1:
            convert_rate = 1 / reverse_df['lastPrice'].values[0]
        else:
            convert_rate = None
        return convert_rate
    convert_rate = convert_between_coins(origin_market_spot_info_df, origin_quote_asset, target_quote_asset)
    if convert_rate is None: # not between coins
        # print("1st convert_rate is None, Not between coins")
        if target_quote_asset == "KRW" and origin_quote_asset == "USDT":
            convert_rate = self.get_dollar_dict()['price']
        elif target_quote_asset == "USDT" and origin_quote_asset == "KRW":
            convert_rate = 1 / self.get_dollar_dict()['price']
        elif target_quote_asset == "KRW":
            convert_rate = convert_between_coins(origin_market_spot_info_df, origin_quote_asset, "USDT") * self.get_dollar_dict()['price']
        elif origin_quote_asset == "KRW":
            temp_convert_rate = self.convert_asset_rate(target_market, target_quote_asset, origin_market, origin_quote_asset)
            if temp_convert_rate is not None:
                convert_rate = 1 / temp_convert_rate
            else:
                title = f"target_market: {target_market}, target_quote_asset: {target_quote_asset}, origin_market:{origin_market}, origin_quote_asset: {origin_quote_asset}"
                raise Exception(f"Cannot find the convert rate for {title}")
        else:
            title = f"target_market: {target_market}, target_quote_asset: {target_quote_asset}, origin_market:{origin_market}, origin_quote_asset: {origin_quote_asset}"
            raise Exception(f"Cannot find the convert rate for {title}")
    return convert_rate

In [ ]:
core.get_market_code_list()

In [ ]:
origin_exchange_code = 'BINANCE_SPOT/BTC'
target_exchange_code = 'UPBIT_SPOT/KRW'

core.get_premium_df(origin_exchange_code, target_exchange_code)

In [ ]:
core.exchange_websocket_dict['UPBIT_SPOT'].check_status(print_result=True)

In [ ]:
core.exchange_websocket_dict['BINANCE_SPOT'].check_status(print_result=True)

In [ ]:
core.exchange_websocket_dict['BINANCE_USD_M'].get_price_df()

In [ ]:
temp = core.exchange_websocket_dict['BINANCE_USD_M'].get_price_df()
temp[temp['base_asset']=='STX']

In [ ]:
temp = core.exchange_websocket_dict['UPBIT_SPOT'].get_price_df()
temp[temp['base_asset']=='STX']

In [ ]:
core.info_dict['binance_spot_ticker_df']['symbol']

In [ ]:
len(core.get_binance_spot_symbol_list())

In [ ]:
core.info_dict['upbit_spot_ticker_df']

In [ ]:
def convert_asset_rate(origin_market, origin_quote_asset, target_market, target_quote_asset):
    if origin_quote_asset == "USD":
        origin_quote_asset = "USDT"
    if target_quote_asset == "USD":
        target_quote_asset = "USDT"
    if origin_quote_asset == target_quote_asset:
        return 1
    origin_market_spot_info_df = core.info_dict[f"{origin_market.lower().split('_')[0]}_spot_ticker_df"]
    # First try to find the rate from the info_dict

    def convert_between_coins(origin_market_spot_info_df, origin_quote_asset, target_quote_asset):
        df = origin_market_spot_info_df[(origin_market_spot_info_df['base_asset']==origin_quote_asset)&(origin_market_spot_info_df['quote_asset']==target_quote_asset)]
        reverse_df = origin_market_spot_info_df[(origin_market_spot_info_df['quote_asset']==origin_quote_asset)&(origin_market_spot_info_df['base_asset']==target_quote_asset)]
        if len(df) == 1:
            convert_rate = df['lastPrice'].values[0]
        elif len(reverse_df) == 1:
            convert_rate = 1 / reverse_df['lastPrice'].values[0]
        else:
            convert_rate = None
        return convert_rate
    convert_rate = convert_between_coins(origin_market_spot_info_df, origin_quote_asset, target_quote_asset)
    if convert_rate is None: # not between coins
        # print("1st convert_rate is None, Not between coins")
        if target_quote_asset == "KRW" and origin_quote_asset == "USDT":
            convert_rate = core.update_dollar_return_dict['price']
        elif target_quote_asset == "USDT" and origin_quote_asset == "KRW":
            convert_rate = 1 / core.update_dollar_return_dict['price']
        elif target_quote_asset == "KRW":
            convert_rate = convert_between_coins(origin_market_spot_info_df, origin_quote_asset, "USDT") * core.update_dollar_return_dict['price']
        elif origin_quote_asset == "KRW":
            temp_convert_rate = convert_asset_rate(target_market, target_quote_asset, origin_market, origin_quote_asset)
            if temp_convert_rate is not None:
                convert_rate = 1 / temp_convert_rate
            else:
                title = f"target_quote_asset: {target_quote_asset}, origin_quote_asset: {origin_quote_asset}"
                raise Exception(f"Cannot find the convert rate for {title}")
        else:
            title = f"target_quote_asset: {target_quote_asset}, origin_quote_asset: {origin_quote_asset}"
            raise Exception(f"Cannot find the convert rate for {title}")
    return convert_rate

In [ ]:
exchange_origin = 'BINANCE_USD_M/USDT'
exchange_target = 'UPBIT_SPOT/BTC'
def get_premium_df(self, target_exchange_code, origin_exchange_code):
    # POSSIBLE quote_assets: USDT, BUSD, BTC, KRW
    origin_market = exchange_origin.split('/')[0]
    quote_asset_one = exchange_origin.split('/')[1]
    target_market = exchange_target.split('/')[0]
    quote_asset_two = exchange_target.split('/')[1]

    origin_market_df = self.exchange_websocket_dict[origin_market].get_price_df()
    origin_market_df = origin_market_df[origin_market_df['quote_asset'] == quote_asset_one]
    target_market_df = self.exchange_websocket_dict[target_market].get_price_df()
    target_market_df = target_market_df[target_market_df['quote_asset'] == quote_asset_two]

    shared_bass_asset_list = list(set(origin_market_df['base_asset'].values).intersection(set(target_market_df['base_asset'].values)))
    origin_market_df = origin_market_df[origin_market_df['base_asset'].isin(shared_bass_asset_list)].sort_values('base_asset').reset_index(drop=True)
    target_market_df = target_market_df[target_market_df['base_asset'].isin(shared_bass_asset_list)].sort_values('base_asset').reset_index(drop=True)

    convert_rate = convert_asset_rate(origin_market, quote_asset_one, target_market, quote_asset_two)
    origin_market_df[['converted_tp','converted_ap','converted_bp']] = origin_market_df[['tp','ap','bp']] * convert_rate
    # target_market_df[['converted_tp','converted_ap','converted_bp']] = target_market_df[['tp','ap','bp']]

    # divide by target_market_df[['tp','ap','bp']]
    premium_df = pd.DataFrame((target_market_df[['tp','ap','bp']].values - origin_market_df[['converted_tp','converted_bp','converted_ap']].values)/
                            origin_market_df[['converted_tp','converted_bp','converted_ap']].values, columns=['tp_premium','LS_premium','SL_premium'])
    premium_df['LS_SL_spread'] = premium_df['LS_premium'] - premium_df['SL_premium']
    premium_df[['base_asset','quote_asset','tp','ap','bp','atp24h']] = target_market_df[['base_asset','quote_asset','tp','ap','bp','atp24h']]
    premium_df[['converted_tp','converted_ap','converted_bp']] = origin_market_df[['converted_tp','converted_ap', 'converted_bp']]
    premium_df.loc[:, ['tp_premium','LS_premium','SL_premium','LS_SL_spread']] = premium_df[['tp_premium','LS_premium','SL_premium','LS_SL_spread']] * 100
    return premium_df

In [ ]:
# POSSIBLE quote_assets: USDT, BUSD, BTC, KRW

exchange_origin = 'BINANCE_USD_M/USDT'
exchange_target = 'UPBIT_SPOT/BTC'

origin_market = exchange_origin.split('/')[0]
quote_asset_one = exchange_origin.split('/')[1]
target_market = exchange_target.split('/')[0]
quote_asset_two = exchange_target.split('/')[1]


origin_market_df = core.exchange_websocket_dict[origin_market].get_price_df()
origin_market_df = origin_market_df[origin_market_df['quote_asset'] == quote_asset_one]
target_market_df = core.exchange_websocket_dict[target_market].get_price_df()
target_market_df = target_market_df[target_market_df['quote_asset'] == quote_asset_two]

shared_bass_asset_list = list(set(origin_market_df['base_asset'].values).intersection(set(target_market_df['base_asset'].values)))
origin_market_df = origin_market_df[origin_market_df['base_asset'].isin(shared_bass_asset_list)].sort_values('base_asset').reset_index(drop=True)
# origin_market_df = origin_market_df[origin_market_df['base_asset'].isin(shared_bass_asset_list)].set_index('base_asset')
target_market_df = target_market_df[target_market_df['base_asset'].isin(shared_bass_asset_list)].sort_values('base_asset').reset_index(drop=True)
# target_market_df = target_market_df[target_market_df['base_asset'].isin(shared_bass_asset_list)].set_index('base_asset')

convert_rate = convert_asset_rate(origin_market, quote_asset_one, target_market, quote_asset_two)

origin_market_df[['converted_tp','converted_ap','converted_bp']] = origin_market_df[['tp','ap','bp']] * convert_rate
# target_market_df[['converted_tp','converted_ap','converted_bp']] = target_market_df[['tp','ap','bp']]

# divide by target_market_df[['tp','ap','bp']]
premium_df = pd.DataFrame((target_market_df[['tp','ap','bp']].values - origin_market_df[['converted_tp','converted_bp','converted_ap']].values)/
                          origin_market_df[['converted_tp','converted_bp','converted_ap']].values, columns=['tp_premium','LS_premium','SL_premium'])
premium_df['LS_SL_spread'] = premium_df['LS_premium'] - premium_df['SL_premium']
premium_df[['base_asset','quote_asset','tp','ap','bp','atp24h']] = target_market_df[['base_asset','quote_asset','tp','ap','bp','atp24h']]
premium_df[['converted_tp','converted_ap','converted_bp']] = origin_market_df[['converted_tp','converted_ap', 'converted_bp']]
premium_df.loc[:, ['tp_premium','LS_premium','SL_premium','LS_SL_spread']] = premium_df[['tp_premium','LS_premium','SL_premium','LS_SL_spread']] * 100
premium_df.sort_values('atp24h', ascending=False).reset_index(drop=True).head(10)

In [ ]:
origin_market_df = core.exchange_websocket_dict[origin_market].get_price_df()
origin_market_df = origin_market_df[origin_market_df['quote_asset'] == quote_asset_one]
target_market_df = core.exchange_websocket_dict[target_market].get_price_df()
target_market_df = target_market_df[target_market_df['quote_asset'] == quote_asset_two]

In [ ]:
origin_market_df

In [ ]:
core.exchange_websocket_dict[target_market].get_price_df()

In [ ]:
target_market_df.head()[['base_asset','tp','ap','bp']]

In [ ]:
origin_market_df.head()[['base_asset','tp','ap','bp']]

In [ ]:
origin_market_df.head()

In [ ]:
convert_asset_rate(origin_market="BINANCE_SPOT", origin_quote_asset='BUSD', target_market="UPBIT_SPOT", target_quote_asset='KRW')

In [ ]:
core.update_dollar_return_dict['price']

In [ ]:
upbit_ticker_df = pd.DataFrame(dict(core.exchange_websocket_dict['UPBIT'].upbit_ticker_dict)).T.reset_index()[['index','tp','scr','atp24h','h52wp','l52wp','ms','mw','tms']]
upbit_orderbook_df = pd.DataFrame(dict(core.exchange_websocket_dict['UPBIT'].upbit_orderbook_dict)).T.reset_index(drop=True)[['cd','tms','obu']]
upbit_orderbook_df['ap'] = upbit_orderbook_df['obu'].apply(lambda x: x[0]['ap'])
upbit_orderbook_df['bp'] = upbit_orderbook_df['obu'].apply(lambda x: x[0]['bp'])
upbit_orderbook_df.drop('obu', axis=1, inplace=True)
upbit_merged_df = pd.merge(upbit_ticker_df, upbit_orderbook_df, left_on='index', right_on='cd', how='inner')
upbit_merged_df['base_asset'] = upbit_merged_df['index'].apply(lambda x: x.split('-')[1])
upbit_merged_df['quote_asset'] = upbit_merged_df['index'].apply(lambda x: x.split('-')[0])
upbit_merged_df.drop('index', axis=1, inplace=True)
upbit_merged_df.loc[:, ['scr','atp24h','h52wp','l52wp','ap','bp']] = upbit_merged_df.loc[:, ['scr','atp24h','h52wp','l52wp','ap','bp']].astype(float)
upbit_merged_df.loc[:, 'scr'] = upbit_merged_df['scr'] * 100
upbit_merged_df.head()

In [ ]:
upbit_merged_df.head()

In [ ]:
core.info_dict['binance_spot_info_df'][['symbol','baseAsset','quoteAsset']].head()

In [ ]:
binance_ticker_df = pd.DataFrame(dict(core.exchange_websocket_dict['BINANCE_SPOT'].ticker_dict)).T.reset_index(drop=True)[['s','P','c','v','q']]
binance_ticker_df.rename(columns={"q": "atp24h", 'P': 'scr', 'c': 'tp'}, inplace=True)
binance_bookticker_df = pd.DataFrame(dict(core.exchange_websocket_dict['BINANCE_SPOT'].bookticker_dict)).T.reset_index(drop=True)[['s','b','a']]
binance_bookticker_df.rename(columns={"b": "bp", "a": "ap"}, inplace=True)
binance_merged_df = pd.merge(binance_ticker_df, binance_bookticker_df, on='s', how='inner')
binance_merged_df.loc[:, ['scr','tp','atp24h','ap','bp']] = binance_merged_df[['scr','tp','atp24h','ap','bp']].astype(float)
binance_merged_df = binance_merged_df.merge(core.info_dict['binance_spot_info_df'][['symbol','baseAsset','quoteAsset']], left_on='s', right_on='symbol', how='inner')
binance_merged_df.drop(['symbol', 's'], axis=1, inplace=True)
binance_merged_df.rename(columns={'baseAsset':"base_asset", 'quoteAsset':"quote_asset"}, inplace=True)
binance_merged_df

In [ ]:
binance_merged_df['quote_asset'].unique()

In [ ]:
binance_ticker_df = pd.DataFrame(dict(core.exchange_websocket_dict['BINANCE_USD_M'].ticker_dict)).T.reset_index(drop=True)[['s','P','c','v','q']]
binance_ticker_df.rename(columns={"q": "atp24h", 'P': 'scr', 'c': 'tp'}, inplace=True)
binance_bookticker_df = pd.DataFrame(dict(core.exchange_websocket_dict['BINANCE_USD_M'].bookticker_dict)).T.reset_index(drop=True)[['s','b','a']]
binance_bookticker_df.rename(columns={"b": "bp", "a": "ap"}, inplace=True)
binance_merged_df = pd.merge(binance_ticker_df, binance_bookticker_df, on='s', how='inner')
binance_merged_df.loc[:, ['scr','tp','atp24h','ap','bp']] = binance_merged_df[['scr','tp','atp24h','ap','bp']].astype(float)
binance_merged_df = binance_merged_df.merge(core.info_dict['binance_usdm_info_df'][['symbol','baseAsset','quoteAsset']], left_on='s', right_on='symbol', how='inner')
binance_merged_df.drop(['symbol', 's'], axis=1, inplace=True)
binance_merged_df.rename(columns={'baseAsset':"base_asset", 'quoteAsset':"quote_asset"}, inplace=True)
binance_merged_df

In [ ]:
binance_ticker_df = pd.DataFrame(dict(core.exchange_websocket_dict['BINANCE_COIN_M'].ticker_dict)).T.reset_index(drop=True)[['s','P','c','v','q']]
binance_ticker_df.rename(columns={"q": "atp24h", 'P': 'scr', 'c': 'tp'}, inplace=True)
binance_bookticker_df = pd.DataFrame(dict(core.exchange_websocket_dict['BINANCE_COIN_M'].bookticker_dict)).T.reset_index(drop=True)[['s','b','a']]
binance_bookticker_df.rename(columns={"b": "bp", "a": "ap"}, inplace=True)
binance_merged_df = pd.merge(binance_ticker_df, binance_bookticker_df, on='s', how='inner')
binance_merged_df.loc[:, ['scr','tp','atp24h','ap','bp']] = binance_merged_df[['scr','tp','atp24h','ap','bp']].astype(float)
binance_merged_df = binance_merged_df.merge(core.info_dict['binance_coinm_info_df'][['symbol','baseAsset','quoteAsset']], left_on='s', right_on='symbol', how='inner')
binance_merged_df.drop(['symbol', 's'], axis=1, inplace=True)
binance_merged_df.rename(columns={'baseAsset':"base_asset", 'quoteAsset':"quote_asset"}, inplace=True)
binance_merged_df