In [2]:
import os
import json
import sys
import argparse
import datetime
import pandas as pd
from kp_info_loader_core import InitCore
# from exchange_plugin.common_info import InitCommonInfo
# from monitor_engine.kimp_core_monitor import InitKimpCoreMonitor
# from etc.db_handler.create_schema_tables import InitDBClient
# from trigger_engine.snatcher import InitSnatcher
from etc.register_monitor_msg import RegisterMonitorMsg
from etc.redis_connector.redis_connector import InitRedis
import _pickle as pickle

# for jupyter notebook
import nest_asyncio
nest_asyncio.apply()

In [2]:
redis_cli = InitRedis()

In [ ]:
temp = pickle.loads(redis_cli.get_data('INFO_CORE|UPBIT_SPOT/KRW:BITHUMB_SPOT/KRW_1T_now'))
tempexit

In [2]:
logging_dir = "/home/kp_info_loader/"
with open("/home/kp_info_loader/kp_info_loader_config.json") as f:
    config = json.load(f)
proc_n = 3
# node = config['node']
node = 'kp_info_loader'
monitor_bot_name = config['monitor_setting']['monitor_bot']
monitor_bot_token = config['telegram_bot_setting'][monitor_bot_name]
monitor_bot_api_url = config['monitor_setting']['monitor_bot_api_url']
admin_id = config['telegram_admin_id']['charlie1155']
register_monitor_msg = RegisterMonitorMsg(monitor_bot_token, monitor_bot_api_url, admin_id, logging_dir)
# Read api keys
exchange_api_key_dict = config['exchange_api_key']
# Exchange market settings
enabled_market_klines = config['node_settings'][node]['enabled_market_klines']

# db dict
db_dict = config['database_setting'][config['node_settings'][node]['db_settings']]

my_okx_demo_api_key = "bbb8a09a-6ea2-4686-add5-1095c918b7f4"
my_okx_demo_secret_key = "FBEAD86057449BAEC3FFA8A80CE76E4F"
my_okx_demo_passphrase = "121431Rn!!"

In [3]:
core = InitCore(logging_dir, proc_n, node, admin_id, register_monitor_msg, exchange_api_key_dict, enabled_market_klines, db_dict)

2023-11-17 16:29:47,939 - kp_info_loader - INFO - InitCore|InitCore initiated with proc_n=3
2023-11-17 16:29:48,107 - okx_plug - INFO - okx_plug_logger started.
2023-11-17 16:29:48,393 - upbit_plug - INFO - upbit_plug_logger started.
2023-11-17 16:29:48,506 - binance_plug - INFO - binance_plug_logger started.
2023-11-17 16:29:48,507 - bithumb_plug - INFO - bithumb_plug_logger started.
2023-11-17 16:29:48,508 - bybit_plug - INFO - bybit_plug_logger started.
2023-11-17 16:29:48,510 - kp_info_loader - INFO - InitCore|update_upbit_spot_info_df thread has started.
2023-11-17 16:29:48,512 - kp_info_loader - INFO - InitCore|update_upbit_spot_ticker_df thread has started.
2023-11-17 16:29:48,515 - kp_info_loader - INFO - InitCore|update_binance_spot_ticker_df thread has started.
2023-11-17 16:29:48,519 - kp_info_loader - INFO - InitCore|update_binance_spot_info_df thread has started.
2023-11-17 16:29:48,521 - kp_info_loader - INFO - InitCore|update_binance_usd_m_ticker_df thread has started.
2023-11-17 16:29:48,524 - kp_info_loader - INFO - InitCore|update_binance_usd_m_info_df thread has started.
2023-11-17 16:29:48,526 - kp_info_loader - INFO - InitCore|update_binance_coin_m_ticker_df thread has started.
2023-11-17 16:29:48,529 - kp_info_loader - INFO - InitCore|update_binance_coin_m_info_df thread has started.
2023-11-17 16:29:48,532 - kp_info_loader - INFO - InitCore|update_okx_spot_ticker_df thread has started.
2023-11-17 16:29:48,534 - kp_info_loader - INFO - InitCore|update_okx_spot_info_df thread has started.
2023-11-17 16:29:48,535 - kp_info_loader - INFO - InitCore|update_okx_usd_m_ticker_df thread has started.
2023-11-17 16:29:48,537 - kp_info_loader - INFO - InitCore|update_okx_usd_m_info_df thread has started.
2023-11-17 16:29:48,539 - kp_info_loader - INFO - InitCore|update_okx_coin_m_ticker_df thread has started.
2023-11-17 16:29:48,541 - kp_info_loader - INFO - InitCore|update_okx_coin_m_info_df thread has started.
2023-11-17 16:29:48,550 - kp_info_loader - INFO - InitCore|update_bithumb_spot_info_df thread has started.
2023-11-17 16:29:48,558 - kp_info_loader - INFO - InitCore|update_bithumb_spot_ticker_df thread has started.
2023-11-17 16:29:48,566 - kp_info_loader - INFO - InitCore|update_bybit_spot_info_df thread has started.
2023-11-17 16:29:48,569 - kp_info_loader - INFO - InitCore|update_bybit_spot_ticker_df thread has started.
2023-11-17 16:29:48,571 - kp_info_loader - INFO - InitCore|update_bybit_usd_m_info_df thread has started.
2023-11-17 16:29:48,573 - kp_info_loader - INFO - InitCore|update_bybit_usd_m_ticker_df thread has started.
2023-11-17 16:29:48,575 - kp_info_loader - INFO - InitCore|update_bybit_coin_m_info_df thread has started.
2023-11-17 16:29:48,577 - kp_info_loader - INFO - InitCore|update_bybit_coin_m_ticker_df thread has started.
2023-11-17 16:29:48,579 - kp_info_loader - INFO - InitCore|Waiting for all info to be updated.
2023-11-17 16:29:49,369 - bybit_plug - INFO - self.info_dict is None or self.info_dict.get('bybit_coin_m_info_df') is None, Fetched from API
2023-11-17 16:29:50,602 - kp_info_loader - INFO - InitCore|Waiting for all info to be updated.
2023-11-17 16:29:50,668 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_usd_m_info_df') is None, Fetched from API
2023-11-17 16:29:51,022 - bybit_plug - INFO - self.info_dict is None or self.info_dict.get('bybit_spot_info_df') is None, Fetched from API
2023-11-17 16:29:51,282 - bybit_plug - INFO - self.info_dict is None or self.info_dict.get('bybit_usd_m_info_df') is None, Fetched from API
2023-11-17 16:29:51,303 - update_dollar - INFO - fetch_dollar|Dollar price (1299.5 KRW) has been updated.
2023-11-17 16:29:52,632 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-11-17 16:29:52,657 - kp_info_loader - INFO - InitCore|Waiting for all info to be updated.
2023-11-17 16:29:52,706 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_ticker_df') is None, Fetched from API
2023-11-17 16:29:54,693 - kp_info_loader - INFO - InitCore|All info df has been updated.
2023-11-17 16:29:54,785 - bybit_usd_m_websocket - INFO - 1th Bybit ticker websocket does not exist. starting..
2023-11-17 16:29:54,786 - bybit_usd_m_websocket - INFO - [BYBIT USD_M]started monitor_shared_symbol_change..
2023-11-17 16:29:54,787 - bybit_usd_m_websocket - INFO - [BYBIT USD_M]started monitor_websocket_last_update..
2023-11-17 16:29:54,788 - bybit_usd_m_websocket - INFO - bybit_ticker_websocket|1th bybit_ticker_proc started.
2023-11-17 16:29:54,849 - binance_spot_websocket - INFO - [BINANCE SPOT]1th_bookticker_proc is not in self.websocket_proc_dict. starting..
2023-11-17 16:29:54,850 - binance_spot_websocket - INFO - [BINANCE SPOT]started monitor_shared_symbol_change..
2023-11-17 16:29:54,851 - binance_spot_websocket - INFO - started monitor_websocket_last_update..
2023-11-17 16:29:54,862 - binance_spot_websocket - INFO - [BINANCE SPOT]started 1th_bookticker_proc websocket proc..
2023-11-17 16:29:54,912 - binance_usd_m_websocket - INFO - [BINANCE USD_M]1th_bookticker_proc is not in self.websocket_proc_dict. starting..
2023-11-17 16:29:54,913 - binance_usd_m_websocket - INFO - [BINANCE USD_M]started monitor_shared_symbol_change..
2023-11-17 16:29:54,914 - binance_usd_m_websocket - INFO - started monitor_websocket_last_update..
2023-11-17 16:29:54,924 - binance_usd_m_websocket - INFO - [BINANCE USD_M]started 1th_bookticker_proc websocket proc..
2023-11-17 16:29:55,015 - upbit_websocket - INFO - 1th Upbit ticker websocket does not exist. starting..
2023-11-17 16:29:55,016 - kp_info_loader - INFO - InitCore|exchange_websocket_dict, dict_keys(['BYBIT_USD_M', 'BINANCE_SPOT', 'BINANCE_USD_M', 'UPBIT_SPOT']) has been initiated.
2023-11-17 16:29:55,015 - upbit_websocket - INFO - [UPBIT SPOT]started monitor_shared_symbol_change..
2023-11-17 16:29:55,016 - upbit_websocket - INFO - [UPBIT SPOT]started monitor_websocket_last_update..
2023-11-17 16:29:55,017 - upbit_websocket - INFO - upbit_orderbook_ticker_websocket|1th upbit_ticker_proc started.
2023-11-17 16:29:55,091 - upbit_websocket - INFO - upbit_websocket|upbit_websocket started
2023-11-17 16:29:55,305 - bybit_usd_m_websocket - INFO - 1th Bybit orderbook websocket does not exist. starting..
2023-11-17 16:29:55,305 - bybit_usd_m_websocket - INFO - bybit_orderbook_websocket|1th bybit_orderbook_proc started.
2023-11-17 16:29:55,371 - binance_spot_websocket - INFO - [BINANCE SPOT]2th_bookticker_proc is not in self.websocket_proc_dict. starting..
2023-11-17 16:29:55,381 - binance_spot_websocket - INFO - [BINANCE SPOT]started 2th_bookticker_proc websocket proc..
2023-11-17 16:29:55,425 - binance_usd_m_websocket - INFO - [BINANCE USD_M]2th_bookticker_proc is not in self.websocket_proc_dict. starting..
2023-11-17 16:29:55,432 - binance_usd_m_websocket - INFO - [BINANCE USD_M]started 2th_bookticker_proc websocket proc..
2023-11-17 16:29:55,554 - upbit_websocket - INFO - 1th Upbit orderbook websocket does not exist. starting..
2023-11-17 16:29:55,556 - upbit_websocket - INFO - upbit_orderbook_ticker_websocket|1th upbit_orderbook_proc started.
2023-11-17 16:29:55,600 - upbit_websocket - INFO - upbit_websocket|upbit_websocket started
2023-11-17 16:29:55,814 - bybit_usd_m_websocket - INFO - 2th Bybit ticker websocket does not exist. starting..
2023-11-17 16:29:55,816 - bybit_usd_m_websocket - INFO - bybit_ticker_websocket|2th bybit_ticker_proc started.
2023-11-17 16:29:55,884 - binance_spot_websocket - INFO - [BINANCE SPOT]3th_bookticker_proc is not in self.websocket_proc_dict. starting..
2023-11-17 16:29:55,894 - binance_spot_websocket - INFO - [BINANCE SPOT]started 3th_bookticker_proc websocket proc..
2023-11-17 16:29:55,935 - binance_usd_m_websocket - INFO - [BINANCE USD_M]3th_bookticker_proc is not in self.websocket_proc_dict. starting..
2023-11-17 16:29:55,942 - binance_usd_m_websocket - INFO - [BINANCE USD_M]started 3th_bookticker_proc websocket proc..
2023-11-17 16:29:56,063 - upbit_websocket - INFO - 2th Upbit ticker websocket does not exist. starting..
2023-11-17 16:29:56,064 - upbit_websocket - INFO - upbit_orderbook_ticker_websocket|2th upbit_ticker_proc started.
2023-11-17 16:29:56,109 - upbit_websocket - INFO - upbit_websocket|upbit_websocket started
2023-11-17 16:29:56,328 - bybit_usd_m_websocket - INFO - 2th Bybit orderbook websocket does not exist. starting..
2023-11-17 16:29:56,329 - bybit_usd_m_websocket - INFO - bybit_orderbook_websocket|2th bybit_orderbook_proc started.
2023-11-17 16:29:56,396 - binance_spot_websocket - INFO - [BINANCE SPOT]4th_bookticker_proc is not in self.websocket_proc_dict. starting..
2023-11-17 16:29:56,410 - binance_spot_websocket - INFO - [BINANCE SPOT]started 4th_bookticker_proc websocket proc..
2023-11-17 16:29:56,445 - binance_usd_m_websocket - INFO - [BINANCE USD_M]4th_bookticker_proc is not in self.websocket_proc_dict. starting..
2023-11-17 16:29:56,456 - binance_usd_m_websocket - INFO - [BINANCE USD_M]started 4th_bookticker_proc websocket proc..
2023-11-17 16:29:56,573 - upbit_websocket - INFO - 2th Upbit orderbook websocket does not exist. starting..
2023-11-17 16:29:56,574 - upbit_websocket - INFO - upbit_orderbook_ticker_websocket|2th upbit_orderbook_proc started.
2023-11-17 16:29:56,620 - upbit_websocket - INFO - upbit_websocket|upbit_websocket started
2023-11-17 16:29:56,841 - bybit_usd_m_websocket - INFO - 3th Bybit ticker websocket does not exist. starting..
2023-11-17 16:29:56,842 - bybit_usd_m_websocket - INFO - bybit_ticker_websocket|3th bybit_ticker_proc started.
2023-11-17 16:29:56,912 - binance_spot_websocket - INFO - [BINANCE SPOT]5th_bookticker_proc is not in self.websocket_proc_dict. starting..
2023-11-17 16:29:56,925 - binance_spot_websocket - INFO - [BINANCE SPOT]started 5th_bookticker_proc websocket proc..
2023-11-17 16:29:56,958 - binance_usd_m_websocket - INFO - [BINANCE USD_M]5th_bookticker_proc is not in self.websocket_proc_dict. starting..
2023-11-17 16:29:56,968 - binance_usd_m_websocket - INFO - [BINANCE USD_M]started 5th_bookticker_proc websocket proc..
2023-11-17 16:29:57,086 - upbit_websocket - INFO - 3th Upbit ticker websocket does not exist. starting..
2023-11-17 16:29:57,087 - upbit_websocket - INFO - upbit_orderbook_ticker_websocket|3th upbit_ticker_proc started.
2023-11-17 16:29:57,133 - upbit_websocket - INFO - upbit_websocket|upbit_websocket started
2023-11-17 16:29:57,354 - bybit_usd_m_websocket - INFO - 3th Bybit orderbook websocket does not exist. starting..
2023-11-17 16:29:57,356 - bybit_usd_m_websocket - INFO - bybit_orderbook_websocket|3th bybit_orderbook_proc started.
2023-11-17 16:29:57,428 - binance_spot_websocket - INFO - [BINANCE SPOT]6th_bookticker_proc is not in self.websocket_proc_dict. starting..
2023-11-17 16:29:57,440 - binance_spot_websocket - INFO - [BINANCE SPOT]started 6th_bookticker_proc websocket proc..
2023-11-17 16:29:57,469 - binance_usd_m_websocket - INFO - [BINANCE USD_M]6th_bookticker_proc is not in self.websocket_proc_dict. starting..
2023-11-17 16:29:57,478 - binance_usd_m_websocket - INFO - [BINANCE USD_M]started 6th_bookticker_proc websocket proc..
2023-11-17 16:29:57,596 - upbit_websocket - INFO - 3th Upbit orderbook websocket does not exist. starting..
2023-11-17 16:29:57,597 - upbit_websocket - INFO - upbit_orderbook_ticker_websocket|3th upbit_orderbook_proc started.
2023-11-17 16:29:57,644 - upbit_websocket - INFO - upbit_websocket|upbit_websocket started
2023-11-17 16:29:57,942 - binance_spot_websocket - INFO - [BINANCE SPOT]ticker_proc is not in self.websocket_proc_dict. starting..
2023-11-17 16:29:57,952 - binance_spot_websocket - INFO - [BINANCE SPOT]started ticker_proc websocket proc..
2023-11-17 16:29:57,980 - binance_usd_m_websocket - INFO - [BINANCE USD_M]ticker_proc is not in self.websocket_proc_dict. starting..
2023-11-17 16:29:57,990 - binance_usd_m_websocket - INFO - [BINANCE USD_M]started ticker_proc websocket proc..
2023-11-17 16:29:57,991 - binance_usd_m_websocket - INFO - [BINANCE USD_M]liquidation_proc is not in self.websocket_proc_dict. starting..
2023-11-17 16:29:57,999 - binance_usd_m_websocket - INFO - [BINANCE USD_M]started liquidation_proc websocket proc..
2023-11-17 16:29:58,005 - binance_usd_m_websocket - INFO - started liquidation_websocket for USD_M..
2023-11-17 16:30:05,025 - kp_info_loader - INFO - update_fundingrate|BINANCE update_fundingrate thread has started.
2023-11-17 16:30:05,027 - kp_info_loader - INFO - update_fundingrate|OKX update_fundingrate thread has started.
2023-11-17 16:30:05,030 - kp_info_loader - INFO - update_fundingrate|BYBIT update_fundingrate thread has started.
2023-11-17 16:30:05,031 - kp_info_loader - INFO - update_wallet_status|UPBIT update_wallet_status thread has started.
2023-11-17 16:30:05,034 - kp_info_loader - INFO - update_wallet_status|BINANCE update_wallet_status thread has started.
2023-11-17 16:30:05,035 - kp_info_loader - INFO - update_wallet_status|OKX update_wallet_status thread has started.
2023-11-17 16:30:05,036 - kp_info_loader - INFO - update_wallet_status|BITHUMB update_wallet_status thread has started.
2023-11-17 16:30:05,036 - kp_info_loader - INFO - update_wallet_status|BYBIT update_wallet_status thread has started.

In [4]:
core.enabled_markets_dict

{'UPBIT': {'SPOT': ['KRW', 'BTC'],
  'USD_M': {'PERPETUAL': [], 'FUTURES': []},
  'COIN_M': {'PERPETUAL': [], 'FUTURES': []}},
 'BINANCE': {'SPOT': ['USDT'],
  'USD_M': {'PERPETUAL': ['USDT'], 'FUTURES': []},
  'COIN_M': {'PERPETUAL': [], 'FUTURES': []}},
 'BYBIT': {'SPOT': [],
  'USD_M': {'PERPETUAL': ['USDT'], 'FUTURES': []},
  'COIN_M': {'PERPETUAL': [], 'FUTURES': []}}}

In [9]:
temp = core.exchange_websocket_dict['UPBIT_SPOT'].get_price_df()
temp

,tp,scr,atp24h,h52wp,l52wp,ms,mw,tms_x,cd,tms_y,ap,bp,base_asset,quote_asset
0,2658000.0,0.150716,111759416416.001877,2875000.0,1500000.0,ACTIVE,NONE,1700206271009,KRW-ETH,1700206277787,2.658000e+06,2.655000e+06,ETH,KRW
1,26120.0,0.345755,117925271433.927795,31580.0,18490.0,ACTIVE,NONE,1700206272714,KRW-ETC,1700206277804,2.612000e+04,2.611000e+04,ETC,KRW
2,49.5,0.609756,9758022937.924299,82.6,28.4,ACTIVE,NONE,1700206271010,KRW-XEM,1700206277914,4.950000e+01,4.940000e+01,XEM,KRW
3,359.0,-1.912568,9195553407.814053,465.0,176.0,ACTIVE,NONE,1700206264873,KRW-STEEM,1700206276448,3.590000e+02,3.580000e+02,STEEM,KRW
4,2055.0,-1.201923,50209973061.335503,2495.0,272.0,ACTIVE,NONE,1700206269376,KRW-ARK,1700206276222,2.055000e+03,2.050000e+03,ARK,KRW
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109,303.0,0.0,4393641882.50811,469.0,182.0,ACTIVE,NONE,1700206260164,KRW-ONT,1700206279174,3.030000e+02,3.020000e+02,ONT,KRW
110,11260.0,-2.931034,83759435885.127502,40150.0,2400.0,ACTIVE,NONE,1700206275132,KRW-GAS,1700206279139,1.128000e+04,1.126000e+04,GAS,KRW
111,16.3,-1.212121,7401417910.846171,21.7,8.9,ACTIVE,NONE,1700206260259,KRW-QKC,1700206278539,1.640000e+01,1.630000e+01,QKC,KRW
112,7.77,-0.892857,42893625919.268356,9.8,2.79,ACTIVE,NONE,1700206275125,KRW-MBL,1700206279964,7.770000e+00,7.760000e+00,MBL,KRW
113,0.0118,2.608696,11813163209.306257,0.0259,0.0078,ACTIVE,NONE,1700206260583,KRW-SHIB,1700206279979,1.190000e-02,1.180000e-02,SHIB,KRW

In [24]:
core.enabled_markets_dict

{'UPBIT': {'SPOT': ['KRW', 'BTC'],
  'USD_M': {'PERPETUAL': [], 'FUTURES': []},
  'COIN_M': {'PERPETUAL': [], 'FUTURES': []}},
 'BINANCE': {'SPOT': ['USDT'],
  'USD_M': {'PERPETUAL': ['USDT'], 'FUTURES': []},
  'COIN_M': {'PERPETUAL': [], 'FUTURES': []}},
 'BYBIT': {'SPOT': [],
  'USD_M': {'PERPETUAL': ['USDT'], 'FUTURES': []},
  'COIN_M': {'PERPETUAL': [], 'FUTURES': []}}}

2023-11-17 16:34:38,076 - update_dollar - INFO - fetch_dollar|Dollar price (1299.5 KRW) has been updated.

In [68]:
target_market = 'UPBIT_SPOT'
# def get_symbol_list(core, target_market): # E.g) UPBIT_SPOT, BINANCE_SPOT, BINANCE_USD_M, BINANCE_COIN_M

target_exchange = target_market.split('_')[0]
target_market_type = '_'.join(target_market.split('_')[1:])

comparing_exchanges = core.enabled_markets_dict.keys()
comparison_list = []
total_df = pd.DataFrame()
for exchange in comparing_exchanges:
    for market_type in core.enabled_markets_dict[exchange]:
        if market_type == "SPOT":
            for quote_asset in core.enabled_markets_dict[exchange][market_type]:
                comparison_list.append({"exchange": exchange, "market_type": market_type, "contract_type":None, "quote_asset": quote_asset})
                # TEST
                # print({"exchange": exchange, "market_type": market_type, "contract_type":None, "quote_asset": quote_asset})
        else:
            for contract_type in core.enabled_markets_dict[exchange][market_type]:
                for quote_asset in core.enabled_markets_dict[exchange][market_type][contract_type]:
                    comparison_list.append({"exchange": exchange, "market_type": market_type, "contract_type":contract_type, "quote_asset": quote_asset})

for i, comparison_dict in enumerate(comparison_list):
    if comparison_dict['exchange'] == target_exchange and comparison_dict['market_type'] == target_market_type:
        target_market_dict = comparison_list.pop(i)
        break

# Start compare and concat
target_market_symbols = []
target_market_ticker_df = core.info_dict[f"{target_market_dict['exchange'].lower()}_{target_market_dict['market_type'].lower()}_ticker_df"]
# check if it's spot or not
if target_market_dict['market_type'] != "SPOT":
    target_market_info_df = core.info_dict[f"{target_market_dict['exchange'].lower()}_{target_market_dict['market_type'].lower()}_info_df"][['symbol','perpetual']]
    target_market_ticker_df = target_market_ticker_df.merge(target_market_info_df, on='symbol', how='inner')
    if target_market_dict['contract_type'] == "PERPETUAL":
        target_market_ticker_df = target_market_ticker_df[target_market_ticker_df['perpetual'] == True]
    else: # FUTURES
        target_market_ticker_df = target_market_ticker_df[target_market_ticker_df['perpetual'] == False]
target_market_ticker_df = target_market_ticker_df[target_market_ticker_df['quote_asset']==target_market_dict['quote_asset']][['symbol','lastPrice','atp24h','base_asset','quote_asset']]
for each_comparison_dict in comparison_list:
    each_market_info_df = core.info_dict[f"{each_comparison_dict['exchange'].lower()}_{each_comparison_dict['market_type'].lower()}_info_df"]
    if each_comparison_dict['contract_type'] is None:
        each_market_info_df = each_market_info_df[each_market_info_df['quote_asset']==each_comparison_dict['quote_asset']]
    else: # contract_type is PERPETUAL or FUTURES
        if each_comparison_dict['contract_type'] == "PERPETUAL":
            each_market_info_df = each_market_info_df[(each_market_info_df['quote_asset']==each_comparison_dict['quote_asset'])&(each_market_info_df['perpetual'] == True)]
        else: # FUTURES
            each_market_info_df = each_market_info_df[(each_market_info_df['quote_asset']==each_comparison_dict['quote_asset'])&(each_market_info_df['perpetual'] == False)]
    comparison_market_code = f"{each_comparison_dict['exchange'].lower()}_{each_comparison_dict['market_type'].lower()}"
    new_symbol = f"symbol_{comparison_market_code}"
    new_quote_asset = f"quote_asset_{comparison_market_code}"
    each_market_info_df = each_market_info_df.rename(columns={"symbol":new_symbol, "quote_asset": new_quote_asset})

    merged_df = target_market_ticker_df.merge(each_market_info_df[[new_symbol, "base_asset", new_quote_asset]], on='base_asset', how='inner')
    if (each_comparison_dict['exchange'] == target_market_dict['exchange'] and
        each_comparison_dict['market_type'] == target_market_dict['market_type']):
        target_market_symbols += merged_df[new_symbol].to_list()
    total_df = pd.concat([total_df, merged_df], axis=0, ignore_index=True)
    target_market_symbols += total_df['symbol'].to_list()

target_market_symbols = list(set(target_market_symbols))
total_target_market_ticker_df = core.info_dict[f"{target_market_dict['exchange'].lower()}_{target_market_dict['market_type'].lower()}_ticker_df"]
total_target_market_df = total_target_market_ticker_df[total_target_market_ticker_df['symbol'].isin(target_market_symbols)]
final_symbol_list = total_target_market_df.sort_values('atp24h', ascending=False)['symbol'].to_list()

# total_df.drop_duplicates(['symbol'], inplace=True)
# total_df.sort_values('atp24h', ascending=False)
# total_df.reset_index(drop=True, inplace=True)
# return total_df['symbol'].to_list()
# get_symbol_list(core, 'UPBIT_SPOT')

In [66]:
len(final_symbol_list)

211

2023-11-17 17:15:34,989 - update_dollar - INFO - fetch_dollar|Dollar price (1299.5 KRW) has been updated.
2023-11-17 17:16:07,431 - update_dollar - INFO - fetch_dollar|Dollar price (1299.5 KRW) has been updated.
2023-11-17 17:16:40,288 - update_dollar - INFO - fetch_dollar|Dollar price (1299.5 KRW) has been updated.
2023-11-17 17:17:12,254 - update_dollar - INFO - fetch_dollar|Dollar price (1299.5 KRW) has been updated.
2023-11-17 17:17:43,896 - update_dollar - INFO - fetch_dollar|Dollar price (1299.5 KRW) has been updated.
2023-11-17 17:18:14,781 - update_dollar - INFO - fetch_dollar|Dollar price (1299.5 KRW) has been updated.
2023-11-17 17:18:45,637 - update_dollar - INFO - fetch_dollar|Dollar price (1299.5 KRW) has been updated.
2023-11-17 17:19:18,022 - update_dollar - INFO - fetch_dollar|Dollar price (1299.5 KRW) has been updated.
2023-11-17 17:19:50,673 - update_dollar - INFO - fetch_dollar|Dollar price (1299.5 KRW) has been updated.
2023-11-17 17:20:23,085 - update_dollar - INFO - fetch_dollar|Dollar price (1299.5 KRW) has been updated.
2023-11-17 17:20:55,260 - update_dollar - INFO - fetch_dollar|Dollar price (1299.5 KRW) has been updated.
2023-11-17 17:21:27,432 - update_dollar - INFO - fetch_dollar|Dollar price (1299.5 KRW) has been updated.
2023-11-17 17:21:59,446 - update_dollar - INFO - fetch_dollar|Dollar price (1299.5 KRW) has been updated.
2023-11-17 17:22:31,358 - update_dollar - INFO - fetch_dollar|Dollar price (1299.5 KRW) has been updated.
2023-11-17 17:23:02,211 - update_dollar - INFO - fetch_dollar|Dollar price (1299.5 KRW) has been updated.
2023-11-17 17:23:33,178 - update_dollar - INFO - fetch_dollar|Dollar price (1299.5 KRW) has been updated.
2023-11-17 17:24:05,084 - update_dollar - INFO - fetch_dollar|Dollar price (1299.5 KRW) has been updated.
2023-11-17 17:24:36,781 - update_dollar - INFO - fetch_dollar|Dollar price (1299.5 KRW) has been updated.
2023-11-17 17:25:08,994 - update_dollar - INFO - fetch_dollar|Dollar price (1299.5 KRW) has been updated.
2023-11-17 17:25:41,447 - update_dollar - INFO - fetch_dollar|Dollar price (1299.0 KRW) has been updated.
2023-11-17 17:26:13,700 - update_dollar - INFO - fetch_dollar|Dollar price (1299.0 KRW) has been updated.
2023-11-17 17:26:45,501 - update_dollar - INFO - fetch_dollar|Dollar price (1299.0 KRW) has been updated.
2023-11-17 17:27:16,570 - update_dollar - INFO - fetch_dollar|Dollar price (1299.0 KRW) has been updated.
2023-11-17 17:27:47,417 - update_dollar - INFO - fetch_dollar|Dollar price (1299.0 KRW) has been updated.
2023-11-17 17:28:19,365 - update_dollar - INFO - fetch_dollar|Dollar price (1299.0 KRW) has been updated.
2023-11-17 17:28:51,813 - update_dollar - INFO - fetch_dollar|Dollar price (1299.0 KRW) has been updated.
2023-11-17 17:29:24,211 - update_dollar - INFO - fetch_dollar|Dollar price (1299.0 KRW) has been updated.
2023-11-17 17:29:56,140 - update_dollar - INFO - fetch_dollar|Dollar price (1298.5 KRW) has been updated.
2023-11-17 17:30:28,024 - update_dollar - INFO - fetch_dollar|Dollar price (1298.0 KRW) has been updated.
2023-11-17 17:30:59,712 - update_dollar - INFO - fetch_dollar|Dollar price (1298.0 KRW) has been updated.
2023-11-17 17:31:32,054 - update_dollar - INFO - fetch_dollar|Dollar price (1298.0 KRW) has been updated.
2023-11-17 17:32:02,906 - update_dollar - INFO - fetch_dollar|Dollar price (1298.0 KRW) has been updated.
2023-11-17 17:32:33,762 - update_dollar - INFO - fetch_dollar|Dollar price (1298.0 KRW) has been updated.
2023-11-17 17:33:05,470 - update_dollar - INFO - fetch_dollar|Dollar price (1298.0 KRW) has been updated.
2023-11-17 17:33:37,544 - update_dollar - INFO - fetch_dollar|Dollar price (1298.0 KRW) has been updated.
2023-11-17 17:34:09,346 - update_dollar - INFO - fetch_dollar|Dollar price (1297.5 KRW) has been updated.
2023-11-17 17:34:42,151 - update_dollar - INFO - fetch_dollar|Dollar price (1297.5 KRW) has been updated.
2023-11-17 17:35:15,479 - update_dollar - INFO - fetch_dollar|Dollar price (1297.5 KRW) has been updated.
2023-11-17 17:35:47,972 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:36:19,053 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:36:49,931 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:37:22,049 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:37:55,053 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:38:27,098 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:38:59,961 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:39:32,672 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:40:05,200 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:40:36,798 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:41:07,601 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:41:39,775 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:42:12,813 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:42:44,531 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:43:16,600 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:43:48,577 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:44:20,601 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:44:53,290 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:45:24,206 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:45:54,952 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:46:26,977 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:46:59,060 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:47:31,123 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:48:03,409 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:48:36,069 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:49:07,982 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:49:40,711 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:50:11,744 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:50:42,577 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:51:14,634 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:51:47,325 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:52:20,119 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:52:52,064 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:53:23,689 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:53:56,449 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:54:27,298 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:54:58,103 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:55:30,040 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:56:03,882 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:56:36,353 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:57:08,472 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:57:40,495 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:58:11,966 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:58:44,478 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:59:15,605 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 17:59:46,448 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 18:00:18,268 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 18:00:50,862 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 18:01:22,725 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 18:01:54,779 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 18:02:26,484 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 18:02:57,820 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 18:03:28,590 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 18:03:59,449 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 18:04:31,504 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.
2023-11-17 18:05:04,603 - update_dollar - INFO - fetch_dollar|Dollar price (1297.0 KRW) has been updated.

In [61]:
target_market_symbols

['BTC-ADA',
 'BTC-ATOM',
 'BTC-CHZ',
 'KRW-STPT',
 'BTC-ELF',
 'KRW-ADA',
 'BTC-UPP',
 'BTC-DOT',
 'KRW-XEC',
 'KRW-IOST',
 'KRW-QTUM',
 'KRW-CBK',
 'KRW-META',
 'BTC-STEEM',
 'BTC-MLK',
 'BTC-WAXP',
 'KRW-SAND',
 'BTC-SXP',
 'KRW-GMT',
 'KRW-SUI',
 'BTC-MOC',
 'BTC-MANA',
 'KRW-MLK',
 'BTC-CBK',
 'BTC-KAVA',
 'KRW-STEEM',
 'KRW-APT',
 'KRW-IQ',
 'KRW-BAT',
 'KRW-ZRX',
 'BTC-BAT',
 'BTC-BLUR',
 'KRW-MOC',
 'BTC-IOST',
 'KRW-GRS',
 'BTC-MTL',
 'BTC-PLA',
 'KRW-MBL',
 'BTC-ARDR',
 'BTC-EOS',
 'BTC-SEI',
 'KRW-LINK',
 'BTC-ARK',
 'BTC-TRX',
 'BTC-SC',
 'BTC-BCH',
 'BTC-SOL',
 'KRW-NEAR',
 'KRW-ATOM',
 'KRW-ZIL',
 'KRW-HIVE',
 'KRW-BTT',
 'BTC-ETH',
 'BTC-XEM',
 'KRW-XEM',
 'KRW-SEI',
 'KRW-STMX',
 'KRW-AHT',
 'KRW-ORBS',
 'KRW-PLA',
 'KRW-ETC',
 'BTC-HUNT',
 'KRW-TRX',
 'KRW-SXP',
 'KRW-ARB',
 'BTC-MVL',
 'BTC-T',
 'KRW-MASK',
 'KRW-AXS',
 'KRW-WAVES',
 'BTC-STX',
 'KRW-HUNT',
 'KRW-ONT',
 'KRW-BTG',
 'BTC-MATIC',
 'BTC-SBD',
 'BTC-HPO',
 'BTC-JST',
 'BTC-IMX',
 'KRW-SHIB',
 'KRW-DOGE',
 'KRW-EGLD',
 'BTC-GLM',
 'KRW-ARDR',
 'KRW-CHZ',
 'KRW-MATIC',
 'BTC-SAND',
 'BTC-APT',
 'BTC-SNT',
 'BTC-GRT',
 'KRW-JST',
 'KRW-PUNDIX',
 'KRW-SBD',
 'KRW-IMX',
 'BTC-DOGE',
 'KRW-1INCH',
 'KRW-HPO',
 'KRW-BSV',
 'BTC-FCT2',
 'KRW-SSX',
 'BTC-HIFI',
 'KRW-QKC',
 'BTC-BORA',
 'KRW-DKA',
 'KRW-CRO',
 'KRW-STORJ',
 'BTC-POLYX',
 'BTC-AERGO',
 'BTC-SUI',
 'KRW-TON',
 'BTC-TON',
 'KRW-STX',
 'BTC-AVAX',
 'KRW-TFUEL',
 'KRW-UPP',
 'BTC-VET',
 'BTC-AXS',
 'BTC-MINA',
 'KRW-THETA',
 'KRW-EOS',
 'BTC-BSV',
 'BTC-1INCH',
 'KRW-POWR',
 'KRW-GAS',
 'BTC-XLM',
 'KRW-SC',
 'KRW-MED',
 'KRW-WAXP',
 'KRW-LOOM',
 'BTC-META',
 'BTC-AAVE',
 'KRW-LSK',
 'KRW-STRK',
 'KRW-FCT2',
 'BTC-IQ',
 'BTC-ALGO',
 'KRW-MANA',
 'KRW-XRP',
 'BTC-POWR',
 'BTC-XTZ',
 'KRW-CELO',
 'KRW-DOT',
 'KRW-ONG',
 'BTC-CRO',
 'KRW-XTZ',
 'KRW-AERGO',
 'KRW-GRT',
 'BTC-SSX',
 'KRW-NEO',
 'BTC-PUNDIX',
 'BTC-ANKR',
 'KRW-STRAX',
 'KRW-HIFI',
 'BTC-GMT',
 'KRW-BCH',
 'BTC-ZIL',
 'BTC-DKA',
 'BTC-LINK',
 'KRW-KAVA',
 'BTC-ARB',
 'KRW-VET',
 'BTC-CELO',
 'BTC-ZRX',
 'KRW-ELF',
 'KRW-MTL',
 'KRW-AQT',
 'KRW-HBAR',
 'KRW-FLOW',
 'KRW-BORA',
 'BTC-STMX',
 'BTC-XRP',
 'BTC-QTUM',
 'KRW-BTC',
 'BTC-AQT',
 'BTC-WAVES',
 'KRW-MINA',
 'BTC-NEAR',
 'BTC-STPT',
 'BTC-MED',
 'KRW-ANKR',
 'BTC-ETC',
 'BTC-LOOM',
 'KRW-ARK',
 'KRW-SNT',
 'BTC-LSK',
 'KRW-AAVE',
 'KRW-AVAX',
 'BTC-AHT',
 'BTC-MASK',
 'BTC-FLOW',
 'KRW-POLYX',
 'BTC-STRAX',
 'KRW-CVC',
 'BTC-STORJ',
 'BTC-GRS',
 'KRW-SOL',
 'KRW-IOTA',
 'BTC-EGLD',
 'KRW-ETH',
 'KRW-XLM',
 'KRW-T',
 'KRW-ALGO',
 'BTC-ORBS',
 'BTC-CVC',
 'BTC-HIVE',
 'KRW-MVL',
 'KRW-BLUR',
 'KRW-GLM',
 'KRW-ICX',
 'BTC-STRK',
 'KRW-KNC']

2023-11-17 17:09:11,836 - update_dollar - INFO - fetch_dollar|Dollar price (1300.0 KRW) has been updated.

In [60]:
len(final_symbol_list)

114

In [56]:
same_market_symbols

['BTC-ETH',
 'BTC-MTL',
 'BTC-XRP',
 'BTC-ETC',
 'BTC-SNT',
 'BTC-WAVES',
 'BTC-XEM',
 'BTC-QTUM',
 'BTC-LSK',
 'BTC-STEEM',
 'BTC-XLM',
 'BTC-ARDR',
 'BTC-ARK',
 'BTC-STORJ',
 'BTC-GRS',
 'BTC-ADA',
 'BTC-SBD',
 'BTC-POWR',
 'BTC-EOS',
 'BTC-TRX',
 'BTC-SC',
 'BTC-ZIL',
 'BTC-POLYX',
 'BTC-ZRX',
 'BTC-LOOM',
 'BTC-BCH',
 'BTC-BAT',
 'BTC-IOST',
 'BTC-CVC',
 'BTC-IQ',
 'BTC-HIFI',
 'BTC-UPP',
 'BTC-ELF',
 'BTC-BSV',
 'BTC-MOC',
 'BTC-MANA',
 'BTC-ANKR',
 'BTC-AERGO',
 'BTC-ATOM',
 'BTC-WAXP',
 'BTC-MED',
 'BTC-MLK',
 'BTC-STPT',
 'BTC-ORBS',
 'BTC-VET',
 'BTC-CHZ',
 'BTC-STMX',
 'BTC-DKA',
 'BTC-HIVE',
 'BTC-KAVA',
 'BTC-AHT',
 'BTC-LINK',
 'BTC-XTZ',
 'BTC-BORA',
 'BTC-JST',
 'BTC-CRO',
 'BTC-TON',
 'BTC-SXP',
 'BTC-HUNT',
 'BTC-PLA',
 'BTC-DOT',
 'BTC-MVL',
 'BTC-STRAX',
 'BTC-AQT',
 'BTC-GLM',
 'BTC-SSX',
 'BTC-META',
 'BTC-FCT2',
 'BTC-CBK',
 'BTC-SAND',
 'BTC-HPO',
 'BTC-DOGE',
 'BTC-STRK',
 'BTC-PUNDIX',
 'BTC-FLOW',
 'BTC-AXS',
 'BTC-STX',
 'BTC-SOL',
 'BTC-MATIC',
 'BTC-AAVE',
 'BTC-1INCH',
 'BTC-ALGO',
 'BTC-NEAR',
 'BTC-AVAX',
 'BTC-T',
 'BTC-CELO',
 'BTC-GMT',
 'BTC-APT',
 'BTC-MASK',
 'BTC-ARB',
 'BTC-EGLD',
 'BTC-SUI',
 'BTC-GRT',
 'BTC-BLUR',
 'BTC-IMX',
 'BTC-SEI',
 'BTC-MINA']

2023-11-17 17:03:22,015 - update_dollar - INFO - fetch_dollar|Dollar price (1300.5 KRW) has been updated.
2023-11-17 17:03:54,014 - update_dollar - INFO - fetch_dollar|Dollar price (1300.5 KRW) has been updated.

In [57]:
total_df

,symbol,lastPrice,atp24h,base_asset,quote_asset,symbol_upbit_spot,quote_asset_upbit_spot,symbol_binance_spot,quote_asset_binance_spot,symbol_binance_usd_m,quote_asset_binance_usd_m,symbol_bybit_usd_m,quote_asset_bybit_usd_m
0,KRW-ETH,2.659000e+06,1.115199e+11,ETH,KRW,BTC-ETH,BTC,NaN,NaN,NaN,NaN,NaN,NaN
1,KRW-MTL,2.305000e+03,1.273609e+10,MTL,KRW,BTC-MTL,BTC,NaN,NaN,NaN,NaN,NaN,NaN
2,KRW-XRP,8.310000e+02,2.498419e+11,XRP,KRW,BTC-XRP,BTC,NaN,NaN,NaN,NaN,NaN,NaN
3,KRW-ETC,2.612000e+04,1.171078e+11,ETC,KRW,BTC-ETC,BTC,NaN,NaN,NaN,NaN,NaN,NaN
4,KRW-SNT,5.810000e+01,8.296213e+09,SNT,KRW,BTC-SNT,BTC,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
109,KRW-TFUEL,6.070000e+01,3.289010e+09,TFUEL,KRW,NaN,NaN,TFUELUSDT,USDT,NaN,NaN,NaN,NaN
110,KRW-MBL,7.760000e+00,3.568509e+10,MBL,KRW,NaN,NaN,MBLUSDT,USDT,NaN,NaN,NaN,NaN
111,KRW-HBAR,8.790000e+01,3.778188e+10,HBAR,KRW,NaN,NaN,HBARUSDT,USDT,NaN,NaN,NaN,NaN
112,KRW-XEC,4.050000e-02,9.703034e+09,XEC,KRW,NaN,NaN,XECUSDT,USDT,NaN,NaN,NaN,NaN
113,KRW-SHIB,1.170000e-02,1.123301e+10,SHIB,KRW,NaN,NaN,SHIBUSDT,USDT,NaN,NaN,NaN,NaN

2023-11-17 17:04:24,964 - update_dollar - INFO - fetch_dollar|Dollar price (1300.5 KRW) has been updated.

In [34]:
temp = core.get_symbol_list("BINANCE_SPOT")
temp

['BTCUSDT',
 'ETHUSDT',
 'NEOUSDT',
 'QTUMUSDT',
 'ADAUSDT',
 'XRPUSDT',
 'EOSUSDT',
 'IOTAUSDT',
 'XLMUSDT',
 'ONTUSDT',
 'TRXUSDT',
 'ETCUSDT',
 'ICXUSDT',
 'VETUSDT',
 'LINKUSDT',
 'WAVESUSDT',
 'BTTUSDT',
 'ONGUSDT',
 'ZILUSDT',
 'ZRXUSDT',
 'BATUSDT',
 'IOSTUSDT',
 'THETAUSDT',
 'MATICUSDT',
 'ATOMUSDT',
 'TFUELUSDT',
 'ALGOUSDT',
 'DOGEUSDT',
 'ANKRUSDT',
 'MTLUSDT',
 'CVCUSDT',
 'CHZUSDT',
 'XTZUSDT',
 'HBARUSDT',
 'STXUSDT',
 'KAVAUSDT',
 'BCHUSDT',
 'LSKUSDT',
 'MBLUSDT',
 'STPTUSDT',
 'SOLUSDT',
 'HIVEUSDT',
 'ARDRUSDT',
 'STMXUSDT',
 'KNCUSDT',
 'SCUSDT',
 'SXPUSDT',
 'STORJUSDT',
 'MANAUSDT',
 'JSTUSDT',
 'SANDUSDT',
 'DOTUSDT',
 'EGLDUSDT',
 'AVAXUSDT',
 'AAVEUSDT',
 'NEARUSDT',
 'AXSUSDT',
 'STRAXUSDT',
 'XEMUSDT',
 'GRTUSDT',
 '1INCHUSDT',
 'CELOUSDT',
 'PUNDIXUSDT',
 'BTGUSDT',
 'SHIBUSDT',
 'MASKUSDT',
 'FLOWUSDT',
 'MINAUSDT',
 'WAXPUSDT',
 'XECUSDT',
 'ELFUSDT',
 'POWRUSDT',
 'PLAUSDT',
 'IMXUSDT',
 'TUSDT',
 'GMTUSDT',
 'STEEMUSDT',
 'POLYXUSDT',
 'APTUSDT',
 'HIFIUSDT',
 'GASUSDT',
 'GLMUSDT',
 'QKCUSDT',
 'ARBUSDT',
 'LOOMUSDT',
 'SUIUSDT',
 'AERGOUSDT',
 'SNTUSDT',
 'SEIUSDT',
 'ARKUSDT',
 'IQUSDT',
 'TUSDUSDT',
 'ENJUSDT',
 'DENTUSDT',
 'RVNUSDT',
 'NKNUSDT',
 'ARPAUSDT',
 'IOTXUSDT',
 'RLCUSDT',
 'OGNUSDT',
 'BNTUSDT',
 'CTSIUSDT',
 'CHRUSDT',
 'LRCUSDT',
 'COMPUSDT',
 'SNXUSDT',
 'DGBUSDT',
 'MKRUSDT',
 'DAIUSDT',
 'CRVUSDT',
 'OCEANUSDT',
 'NMRUSDT',
 'RSRUSDT',
 'UNIUSDT',
 'OXTUSDT',
 'SUNUSDT',
 'FILUSDT',
 'INJUSDT',
 'AUDIOUSDT',
 'DNTUSDT',
 'JUVUSDT',
 'PSGUSDT',
 'ATMUSDT',
 'ACMUSDT',
 'BARUSDT',
 'LPTUSDT',
 'GTCUSDT',
 'RAYUSDT',
 'FORUSDT',
 'USDPUSDT',
 'YGGUSDT',
 'AGLDUSDT',
 'RADUSDT',
 'AUCTIONUSDT',
 'CITYUSDT',
 'ENSUSDT',
 'RNDRUSDT',
 'GLMRUSDT',
 'API3USDT',
 'ASTRUSDT',
 'APEUSDT',
 'REIUSDT',
 'GALUSDT',
 'STGUSDT',
 'MAGICUSDT',
 'PROMUSDT',
 'CYBERUSDT',
 'BNBUSDT',
 'LTCUSDT',
 'USDCUSDT',
 'HOTUSDT',
 'FETUSDT',
 'XMRUSDT',
 'ZECUSDT',
 'CELRUSDT',
 'DASHUSDT',
 'OMGUSDT',
 'ONEUSDT',
 'FTMUSDT',
 'DUSKUSDT',
 'COCOSUSDT',
 'TOMOUSDT',
 'KEYUSDT',
 'BANDUSDT',
 'RENUSDT',
 'FTTUSDT',
 'BTSUSDT',
 'COTIUSDT',
 'MDTUSDT',
 'ZENUSDT',
 'YFIUSDT',
 'BALUSDT',
 'BLZUSDT',
 'SRMUSDT',
 'ANTUSDT',
 'TRBUSDT',
 'SUSHIUSDT',
 'KSMUSDT',
 'RUNEUSDT',
 'UMAUSDT',
 'BELUSDT',
 'HNTUSDT',
 'FLMUSDT',
 'XVSUSDT',
 'ALPHAUSDT',
 'CTKUSDT',
 'UNFIUSDT',
 'ROSEUSDT',
 'SKLUSDT',
 'REEFUSDT',
 'RIFUSDT',
 'TRUUSDT',
 'CKBUSDT',
 'TWTUSDT',
 'LITUSDT',
 'SFPUSDT',
 'CAKEUSDT',
 'BADGERUSDT',
 'ALICEUSDT',
 'LINAUSDT',
 'PERPUSDT',
 'CFXUSDT',
 'TLMUSDT',
 'BAKEUSDT',
 'SLPUSDT',
 'ICPUSDT',
 'ARUSDT',
 'XVGUSDT',
 'ATAUSDT',
 'KLAYUSDT',
 'BONDUSDT',
 'C98USDT',
 'QNTUSDT',
 'DYDXUSDT',
 'IDEXUSDT',
 'GALAUSDT',
 'ILVUSDT',
 'FRONTUSDT',
 'DARUSDT',
 'BNXUSDT',
 'JASMYUSDT',
 'BICOUSDT',
 'FXSUSDT',
 'HIGHUSDT',
 'CVXUSDT',
 'PEOPLEUSDT',
 'SPELLUSDT',
 'JOEUSDT',
 'ACHUSDT',
 'WOOUSDT',
 'LDOUSDT',
 'OPUSDT',
 'LEVERUSDT',
 'GMXUSDT',
 'HFTUSDT',
 'PHBUSDT',
 'HOOKUSDT',
 'AGIXUSDT',
 'SSVUSDT',
 'LQTYUSDT',
 'AMBUSDT',
 'IDUSDT',
 'RDNTUSDT',
 'EDUUSDT',
 'COMBOUSDT',
 'MAVUSDT',
 'PENDLEUSDT',
 'ARKMUSDT',
 'WLDUSDT',
 'NTRNUSDT',
 'TIAUSDT',
 'MEMEUSDT',
 'ORDIUSDT',
 'BUSDUSDT',
 'BEAMUSDT',
 'PAXGUSDT',
 'YFIIUSDT',
 'AKROUSDT',
 'OGUSDT',
 'DODOUSDT',
 'FORTHUSDT',
 'ALPACAUSDT',
 'REQUSDT',
 'VGXUSDT',
 'SCRTUSDT',
 'XNOUSDT',
 'KDAUSDT',
 'BSWUSDT',
 'MULTIUSDT',
 'RPLUSDT',
 'GFTUSDT']

2023-11-17 16:40:29,872 - update_dollar - INFO - fetch_dollar|Dollar price (1299.5 KRW) has been updated.
2023-11-17 16:41:01,912 - update_dollar - INFO - fetch_dollar|Dollar price (1299.5 KRW) has been updated.
2023-11-17 16:41:33,641 - update_dollar - INFO - fetch_dollar|Dollar price (1299.5 KRW) has been updated.

In [18]:
[x for x in temp if 'BTC' in x]

['KRW-BTC']

2023-11-17 16:33:04,138 - update_dollar - INFO - fetch_dollar|Dollar price (1299.5 KRW) has been updated.
2023-11-17 16:33:34,901 - update_dollar - INFO - fetch_dollar|Dollar price (1299.5 KRW) has been updated.

In [5]:
core.get_premium_df('UPBIT_SPOT/BTC', "BINANCE_USD_M/USDT")

resampling ohlc_df(length: 82): 0.8031275272369385

2023-11-17 16:28:10,402 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_4H_kline base_asset is not matched. added: ['ANKR', 'CVC', 'ELF', 'HIVE', 'IQ', 'PUNDIX', 'SC'], removed: []
2023-11-17 16:28:10,612 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_1H_kline base_asset is not matched. added: ['ANKR', 'CVC', 'ELF', 'HIVE', 'IQ', 'PUNDIX', 'SC'], removed: []
2023-11-17 16:28:10,755 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_15T_kline time: 0.00013875961303710938
2023-11-17 16:28:10,754 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_15T_kline time: 0.0003762245178222656

resampling ohlc_df(length: 162): 0.7972066402435303

2023-11-17 16:28:10,753 - kline_core - INFO - resampling ohlc_df(length: 329): 1.2126274108886719
2023-11-17 16:28:10,932 - kline_core - INFO - resampling ohlc_df(length: 162): 1.3442575931549072
2023-11-17 16:28:10,933 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_30T_kline time: 0.0003600120544433594
2023-11-17 16:28:10,933 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_30T_kline time: 0.00011563301086425781
2023-11-17 16:28:10,941 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_30T_kline base_asset is not matched. added: ['ANKR', 'CVC', 'ELF', 'HIVE', 'IQ', 'PUNDIX', 'SC'], removed: []
2023-11-17 16:28:12,670 - kline_core - ERROR - ohlc_1T_loader|target_market_code:UPBIT_SPOT/KRW, origin_market_code:UPBIT_SPOT/BTC, Error in ohlc_1T_loader: Traceback (most recent call last):
  File "/home/kp_info_loader/kline_generator/kline_core.py", line 159, in ohlc_1T_loader
    ohlc_df = self.generate_ohlc_df(appended_premium_df)
  File "/home/kp_info_loader/kline_generator/kline_core.py", line 108, in generate_ohlc_df
    ohlc_df['dollar'] = df['dollar'].iloc[-1]
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1103, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1656, in _getitem_axis
    self._validate_integer(key, axis)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1589, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds

 appended_premium_df:Empty DataFrame
Columns: [tp_premium, LS_premium, SL_premium, LS_SL_spread, base_asset, quote_asset, tp, ap, bp, scr, atp24h, converted_tp, converted_ap, converted_bp, dollar, datetime_now]
Index: [], premium_df:Empty DataFrame
Columns: [tp_premium, LS_premium, SL_premium, LS_SL_spread, base_asset, quote_asset, tp, ap, bp, scr, atp24h, converted_tp, converted_ap, converted_bp, dollar, datetime_now]
Index: []

resampling ohlc_df(length: 82): 1.034785509109497

2023-11-17 16:28:13,011 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_1D_kline base_asset is not matched. added: ['ANKR', 'CVC', 'ELF', 'HIVE', 'IQ', 'PUNDIX', 'SC'], removed: []
2023-11-17 16:28:15,785 - kline_core - ERROR - ohlc_1T_loader|target_market_code:UPBIT_SPOT/KRW, origin_market_code:UPBIT_SPOT/BTC, Error in ohlc_1T_loader: Traceback (most recent call last):
  File "/home/kp_info_loader/kline_generator/kline_core.py", line 159, in ohlc_1T_loader
    ohlc_df = self.generate_ohlc_df(appended_premium_df)
  File "/home/kp_info_loader/kline_generator/kline_core.py", line 108, in generate_ohlc_df
    ohlc_df['dollar'] = df['dollar'].iloc[-1]
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1103, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1656, in _getitem_axis
    self._validate_integer(key, axis)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1589, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds

 appended_premium_df:Empty DataFrame
Columns: [tp_premium, LS_premium, SL_premium, LS_SL_spread, base_asset, quote_asset, tp, ap, bp, scr, atp24h, converted_tp, converted_ap, converted_bp, dollar, datetime_now]
Index: [], premium_df:Empty DataFrame
Columns: [tp_premium, LS_premium, SL_premium, LS_SL_spread, base_asset, quote_asset, tp, ap, bp, scr, atp24h, converted_tp, converted_ap, converted_bp, dollar, datetime_now]
Index: []

2023-11-17 16:28:16,176 - update_dollar - INFO - fetch_dollar|Dollar price (1299.5 KRW) has been updated.
2023-11-17 16:28:27,743 - kline_core - INFO - insert_kline_to_db|INFO_CORE|UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_1H_kline No klines to be inserted
2023-11-17 16:28:27,937 - kline_core - INFO - insert_kline_to_db|INFO_CORE|UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_4H_kline No klines to be inserted
2023-11-17 16:28:28,287 - kline_core - INFO - insert_kline_to_db|INFO_CORE|UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_1D_kline No klines to be inserted

resampling ohlc_df(length: 82): 0.8510136604309082

2023-11-17 16:28:16,368 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_4H_kline base_asset is not matched. added: ['ANKR', 'CVC', 'ELF', 'HIVE', 'IQ', 'PUNDIX', 'SC'], removed: []

resampling ohlc_df(length: 162): 0.832120418548584

2023-11-17 16:28:16,560 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_1H_kline base_asset is not matched. added: ['ANKR', 'CVC', 'ELF', 'HIVE', 'IQ', 'PUNDIX', 'SC'], removed: []
2023-11-17 16:28:17,004 - kline_core - INFO - redis publishing UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_30T_kline time: 0.0001392364501953125
2023-11-17 16:28:17,004 - kline_core - INFO - redis saving UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_30T_kline time: 0.0003650188446044922
2023-11-17 16:28:17,002 - kline_core - INFO - resampling ohlc_df(length: 169): 0.9555423259735107
2023-11-17 16:28:18,903 - kline_core - ERROR - ohlc_1T_loader|target_market_code:UPBIT_SPOT/KRW, origin_market_code:UPBIT_SPOT/BTC, Error in ohlc_1T_loader: Traceback (most recent call last):
  File "/home/kp_info_loader/kline_generator/kline_core.py", line 159, in ohlc_1T_loader
    ohlc_df = self.generate_ohlc_df(appended_premium_df)
  File "/home/kp_info_loader/kline_generator/kline_core.py", line 108, in generate_ohlc_df
    ohlc_df['dollar'] = df['dollar'].iloc[-1]
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1103, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1656, in _getitem_axis
    self._validate_integer(key, axis)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1589, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds

 appended_premium_df:Empty DataFrame
Columns: [tp_premium, LS_premium, SL_premium, LS_SL_spread, base_asset, quote_asset, tp, ap, bp, scr, atp24h, converted_tp, converted_ap, converted_bp, dollar, datetime_now]
Index: [], premium_df:Empty DataFrame
Columns: [tp_premium, LS_premium, SL_premium, LS_SL_spread, base_asset, quote_asset, tp, ap, bp, scr, atp24h, converted_tp, converted_ap, converted_bp, dollar, datetime_now]
Index: []
2023-11-17 16:28:18,960 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_1D_kline base_asset is not matched. added: ['ANKR', 'CVC', 'ELF', 'HIVE', 'IQ', 'PUNDIX', 'SC'], removed: []

resampling ohlc_df(length: 82): 0.8375968933105469

2023-11-17 16:28:22,018 - kline_core - ERROR - ohlc_1T_loader|target_market_code:UPBIT_SPOT/KRW, origin_market_code:UPBIT_SPOT/BTC, Error in ohlc_1T_loader: Traceback (most recent call last):
  File "/home/kp_info_loader/kline_generator/kline_core.py", line 159, in ohlc_1T_loader
    ohlc_df = self.generate_ohlc_df(appended_premium_df)
  File "/home/kp_info_loader/kline_generator/kline_core.py", line 108, in generate_ohlc_df
    ohlc_df['dollar'] = df['dollar'].iloc[-1]
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1103, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1656, in _getitem_axis
    self._validate_integer(key, axis)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1589, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds

 appended_premium_df:Empty DataFrame
Columns: [tp_premium, LS_premium, SL_premium, LS_SL_spread, base_asset, quote_asset, tp, ap, bp, scr, atp24h, converted_tp, converted_ap, converted_bp, dollar, datetime_now]
Index: [], premium_df:Empty DataFrame
Columns: [tp_premium, LS_premium, SL_premium, LS_SL_spread, base_asset, quote_asset, tp, ap, bp, scr, atp24h, converted_tp, converted_ap, converted_bp, dollar, datetime_now]
Index: []

resampling ohlc_df(length: 82): 0.8253812789916992

2023-11-17 16:28:22,311 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_4H_kline base_asset is not matched. added: ['ANKR', 'CVC', 'ELF', 'HIVE', 'IQ', 'PUNDIX', 'SC'], removed: []

resampling ohlc_df(length: 169): 0.877469539642334
resampling ohlc_df(length: 82): 0.8109667301177979

2023-11-17 16:28:24,887 - kline_core - INFO - UPBIT_SPOT/KRW:BINANCE_SPOT/USDT_1D_kline base_asset is not matched. added: ['ANKR', 'CVC', 'ELF', 'HIVE', 'IQ', 'PUNDIX', 'SC'], removed: []
2023-11-17 16:28:25,121 - kline_core - ERROR - ohlc_1T_loader|target_market_code:UPBIT_SPOT/KRW, origin_market_code:UPBIT_SPOT/BTC, Error in ohlc_1T_loader: Traceback (most recent call last):
  File "/home/kp_info_loader/kline_generator/kline_core.py", line 159, in ohlc_1T_loader
    ohlc_df = self.generate_ohlc_df(appended_premium_df)
  File "/home/kp_info_loader/kline_generator/kline_core.py", line 108, in generate_ohlc_df
    ohlc_df['dollar'] = df['dollar'].iloc[-1]
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1103, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1656, in _getitem_axis
    self._validate_integer(key, axis)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1589, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds

 appended_premium_df:Empty DataFrame
Columns: [tp_premium, LS_premium, SL_premium, LS_SL_spread, base_asset, quote_asset, tp, ap, bp, scr, atp24h, converted_tp, converted_ap, converted_bp, dollar, datetime_now]
Index: [], premium_df:Empty DataFrame
Columns: [tp_premium, LS_premium, SL_premium, LS_SL_spread, base_asset, quote_asset, tp, ap, bp, scr, atp24h, converted_tp, converted_ap, converted_bp, dollar, datetime_now]
Index: []
2023-11-17 16:28:28,236 - kline_core - ERROR - ohlc_1T_loader|target_market_code:UPBIT_SPOT/KRW, origin_market_code:UPBIT_SPOT/BTC, Error in ohlc_1T_loader: Traceback (most recent call last):
  File "/home/kp_info_loader/kline_generator/kline_core.py", line 159, in ohlc_1T_loader
    ohlc_df = self.generate_ohlc_df(appended_premium_df)
  File "/home/kp_info_loader/kline_generator/kline_core.py", line 108, in generate_ohlc_df
    ohlc_df['dollar'] = df['dollar'].iloc[-1]
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1103, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1656, in _getitem_axis
    self._validate_integer(key, axis)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1589, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds

 appended_premium_df:Empty DataFrame
Columns: [tp_premium, LS_premium, SL_premium, LS_SL_spread, base_asset, quote_asset, tp, ap, bp, scr, atp24h, converted_tp, converted_ap, converted_bp, dollar, datetime_now]
Index: [], premium_df:Empty DataFrame
Columns: [tp_premium, LS_premium, SL_premium, LS_SL_spread, base_asset, quote_asset, tp, ap, bp, scr, atp24h, converted_tp, converted_ap, converted_bp, dollar, datetime_now]
Index: []

resampling ohlc_df(length: 89): 0.8227534294128418
resampling ohlc_df(length: 89): 0.871284008026123

2023-11-17 16:28:31,345 - kline_core - ERROR - ohlc_1T_loader|target_market_code:UPBIT_SPOT/KRW, origin_market_code:UPBIT_SPOT/BTC, Error in ohlc_1T_loader: Traceback (most recent call last):
  File "/home/kp_info_loader/kline_generator/kline_core.py", line 159, in ohlc_1T_loader
    ohlc_df = self.generate_ohlc_df(appended_premium_df)
  File "/home/kp_info_loader/kline_generator/kline_core.py", line 108, in generate_ohlc_df
    ohlc_df['dollar'] = df['dollar'].iloc[-1]
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1103, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1656, in _getitem_axis
    self._validate_integer(key, axis)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1589, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds

 appended_premium_df:Empty DataFrame
Columns: [tp_premium, LS_premium, SL_premium, LS_SL_spread, base_asset, quote_asset, tp, ap, bp, scr, atp24h, converted_tp, converted_ap, converted_bp, dollar, datetime_now]
Index: [], premium_df:Empty DataFrame
Columns: [tp_premium, LS_premium, SL_premium, LS_SL_spread, base_asset, quote_asset, tp, ap, bp, scr, atp24h, converted_tp, converted_ap, converted_bp, dollar, datetime_now]
Index: []
2023-11-17 16:28:34,458 - kline_core - ERROR - ohlc_1T_loader|target_market_code:UPBIT_SPOT/KRW, origin_market_code:UPBIT_SPOT/BTC, Error in ohlc_1T_loader: Traceback (most recent call last):
  File "/home/kp_info_loader/kline_generator/kline_core.py", line 159, in ohlc_1T_loader
    ohlc_df = self.generate_ohlc_df(appended_premium_df)
  File "/home/kp_info_loader/kline_generator/kline_core.py", line 108, in generate_ohlc_df
    ohlc_df['dollar'] = df['dollar'].iloc[-1]
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1103, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1656, in _getitem_axis
    self._validate_integer(key, axis)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1589, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds

 appended_premium_df:Empty DataFrame
Columns: [tp_premium, LS_premium, SL_premium, LS_SL_spread, base_asset, quote_asset, tp, ap, bp, scr, atp24h, converted_tp, converted_ap, converted_bp, dollar, datetime_now]
Index: [], premium_df:Empty DataFrame
Columns: [tp_premium, LS_premium, SL_premium, LS_SL_spread, base_asset, quote_asset, tp, ap, bp, scr, atp24h, converted_tp, converted_ap, converted_bp, dollar, datetime_now]
Index: []
2023-11-17 16:28:37,578 - kline_core - ERROR - ohlc_1T_loader|target_market_code:UPBIT_SPOT/KRW, origin_market_code:UPBIT_SPOT/BTC, Error in ohlc_1T_loader: Traceback (most recent call last):
  File "/home/kp_info_loader/kline_generator/kline_core.py", line 159, in ohlc_1T_loader
    ohlc_df = self.generate_ohlc_df(appended_premium_df)
  File "/home/kp_info_loader/kline_generator/kline_core.py", line 108, in generate_ohlc_df
    ohlc_df['dollar'] = df['dollar'].iloc[-1]
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1103, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1656, in _getitem_axis
    self._validate_integer(key, axis)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1589, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds

 appended_premium_df:Empty DataFrame
Columns: [tp_premium, LS_premium, SL_premium, LS_SL_spread, base_asset, quote_asset, tp, ap, bp, scr, atp24h, converted_tp, converted_ap, converted_bp, dollar, datetime_now]
Index: [], premium_df:Empty DataFrame
Columns: [tp_premium, LS_premium, SL_premium, LS_SL_spread, base_asset, quote_asset, tp, ap, bp, scr, atp24h, converted_tp, converted_ap, converted_bp, dollar, datetime_now]
Index: []
2023-11-17 16:28:40,683 - kline_core - ERROR - ohlc_1T_loader|target_market_code:UPBIT_SPOT/KRW, origin_market_code:UPBIT_SPOT/BTC, Error in ohlc_1T_loader: Traceback (most recent call last):
  File "/home/kp_info_loader/kline_generator/kline_core.py", line 159, in ohlc_1T_loader
    ohlc_df = self.generate_ohlc_df(appended_premium_df)
  File "/home/kp_info_loader/kline_generator/kline_core.py", line 108, in generate_ohlc_df
    ohlc_df['dollar'] = df['dollar'].iloc[-1]
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1103, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1656, in _getitem_axis
    self._validate_integer(key, axis)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1589, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds

 appended_premium_df:Empty DataFrame
Columns: [tp_premium, LS_premium, SL_premium, LS_SL_spread, base_asset, quote_asset, tp, ap, bp, scr, atp24h, converted_tp, converted_ap, converted_bp, dollar, datetime_now]
Index: [], premium_df:Empty DataFrame
Columns: [tp_premium, LS_premium, SL_premium, LS_SL_spread, base_asset, quote_asset, tp, ap, bp, scr, atp24h, converted_tp, converted_ap, converted_bp, dollar, datetime_now]
Index: []

In [ ]:
target_market_code = "UPBIT_SPOT/KRW"
origin_market_code = "BINANCE_USD_M/USDT"
core.get_premium_df(target_market_code, origin_market_code)

In [ ]:
origin_market = "UPBIT_SPOT"
target_market = "BINANCE_SPOT"

origin_market_spot_info_df = core.info_dict['binance_spot_info_df']
origin_quote_asset = 'BTC'
target_quote_asset = 'USDT'

if origin_quote_asset == "USD":
    origin_quote_asset = "USDT"
if target_quote_asset == "USD":
    target_quote_asset = "USDT"
if origin_quote_asset == target_quote_asset:
    # return 1
    print(1) # TEST
# origin_market_spot_info_df = self.info_dict[f"{origin_market.lower().split('_')[0]}_spot_ticker_df"]
origin_market_spot_info_df = core.info_dict[f"{origin_market.lower().split('_')[0]}_spot_ticker_df"] # TEST
# First try to find the rate from the info_dict

def convert_between_coins(origin_market_spot_info_df, origin_quote_asset, target_quote_asset):
    df = origin_market_spot_info_df[(origin_market_spot_info_df['base_asset']==origin_quote_asset)&(origin_market_spot_info_df['quote_asset']==target_quote_asset)]
    reverse_df = origin_market_spot_info_df[(origin_market_spot_info_df['quote_asset']==origin_quote_asset)&(origin_market_spot_info_df['base_asset']==target_quote_asset)]
    if len(df) == 1:
        convert_rate = df['lastPrice'].values[0]
    elif len(reverse_df) == 1:
        convert_rate = 1 / reverse_df['lastPrice'].values[0]
    else:
        convert_rate = None
    return convert_rate
convert_rate = convert_between_coins(origin_market_spot_info_df, origin_quote_asset, target_quote_asset)
if convert_rate is None: # not between coins
    # print("1st convert_rate is None, Not between coins")
    if target_quote_asset == "KRW" and origin_quote_asset == "USDT":
        # convert_rate = self.get_dollar_dict()['price']
        convert_rate = core.get_dollar_dict()['price'] # TEST
    elif target_quote_asset == "USDT" and origin_quote_asset == "KRW":
        # convert_rate = 1 / self.get_dollar_dict()['price']
        convert_rate = 1 / core.get_dollar_dict()['price'] # TEST
    elif target_quote_asset == "KRW":
        # convert_rate = convert_between_coins(origin_market_spot_info_df, origin_quote_asset, "USDT") * self.get_dollar_dict()['price']
        convert_rate = convert_between_coins(origin_market_spot_info_df, origin_quote_asset, "USDT") * core.get_dollar_dict()['price'] # TEST
    elif origin_quote_asset == "KRW":
        # temp_convert_rate = self.convert_asset_rate(target_market, target_quote_asset, origin_market, origin_quote_asset)
        temp_convert_rate = core.convert_asset_rate(target_market, target_quote_asset, origin_market, origin_quote_asset) # TEST
        if temp_convert_rate is not None:
            convert_rate = 1 / temp_convert_rate
        else:
            title = f"target_market: {target_market}, target_quote_asset: {target_quote_asset}, origin_market:{origin_market}, origin_quote_asset: {origin_quote_asset}"
            raise Exception(f"Cannot find the convert rate for {title}")
    else:
        # temp_convert_rate = self.convert_asset_rate(target_market, target_quote_asset, origin_market, "USDT")
        temp_convert_rate = core.convert_asset_rate(target_market, target_quote_asset, origin_market, origin_quote_asset) # TEST
        if temp_convert_rate is not None:
            convert_rate = 1 / temp_convert_rate
            # return convert_rate
            print(convert_rate)
        else:
            pass
        title = f"target_market: {target_market}, target_quote_asset: {target_quote_asset}, origin_market:{origin_market}, origin_quote_asset: {origin_quote_asset}"
        raise Exception(f"Cannot find the convert rate for {title}")
# return convert_rate
print(convert_rate) # TEST

In [ ]:
origin_market_spot_info_df.columns

In [ ]:
origin_market_spot_info_df[['market','base_asset','quote_asset']]#[(origin_market_spot_info_df['base_asset']==origin_quote_asset)&(origin_market_spot_info_df['quote_asset']==target_quote_asset)]

In [ ]:
temp_convert_rate

In [ ]:
def convert_asset_rate(self, origin_market, origin_quote_asset, target_market, target_quote_asset):
    if origin_quote_asset == "USD":
        origin_quote_asset = "USDT"
    if target_quote_asset == "USD":
        target_quote_asset = "USDT"
    if origin_quote_asset == target_quote_asset:
        return 1
    origin_market_spot_info_df = self.info_dict[f"{origin_market.lower().split('_')[0]}_spot_ticker_df"]
    # First try to find the rate from the info_dict

    def convert_between_coins(origin_market_spot_info_df, origin_quote_asset, target_quote_asset):
        df = origin_market_spot_info_df[(origin_market_spot_info_df['base_asset']==origin_quote_asset)&(origin_market_spot_info_df['quote_asset']==target_quote_asset)]
        reverse_df = origin_market_spot_info_df[(origin_market_spot_info_df['quote_asset']==origin_quote_asset)&(origin_market_spot_info_df['base_asset']==target_quote_asset)]
        if len(df) == 1:
            convert_rate = df['lastPrice'].values[0]
        elif len(reverse_df) == 1:
            convert_rate = 1 / reverse_df['lastPrice'].values[0]
        else:
            convert_rate = None
        return convert_rate
    convert_rate = convert_between_coins(origin_market_spot_info_df, origin_quote_asset, target_quote_asset)
    if convert_rate is None: # not between coins
        # print("1st convert_rate is None, Not between coins")
        if target_quote_asset == "KRW" and origin_quote_asset == "USDT":
            convert_rate = self.get_dollar_dict()['price']
        elif target_quote_asset == "USDT" and origin_quote_asset == "KRW":
            convert_rate = 1 / self.get_dollar_dict()['price']
        elif target_quote_asset == "KRW":
            convert_rate = convert_between_coins(origin_market_spot_info_df, origin_quote_asset, "USDT") * self.get_dollar_dict()['price']
        elif origin_quote_asset == "KRW":
            temp_convert_rate = self.convert_asset_rate(target_market, target_quote_asset, origin_market, origin_quote_asset)
            if temp_convert_rate is not None:
                convert_rate = 1 / temp_convert_rate
            else:
                title = f"target_market: {target_market}, target_quote_asset: {target_quote_asset}, origin_market:{origin_market}, origin_quote_asset: {origin_quote_asset}"
                raise Exception(f"Cannot find the convert rate for {title}")
        else:
            title = f"target_market: {target_market}, target_quote_asset: {target_quote_asset}, origin_market:{origin_market}, origin_quote_asset: {origin_quote_asset}"
            raise Exception(f"Cannot find the convert rate for {title}")
    return convert_rate

In [ ]:
core.get_market_code_list()

In [ ]:
origin_exchange_code = 'BINANCE_SPOT/BTC'
target_exchange_code = 'UPBIT_SPOT/KRW'

core.get_premium_df(origin_exchange_code, target_exchange_code)

In [ ]:
core.exchange_websocket_dict['UPBIT_SPOT'].check_status(print_result=True)

In [ ]:
core.exchange_websocket_dict['BINANCE_SPOT'].check_status(print_result=True)

In [ ]:
core.exchange_websocket_dict['BINANCE_USD_M'].get_price_df()

In [ ]:
temp = core.exchange_websocket_dict['BINANCE_USD_M'].get_price_df()
temp[temp['base_asset']=='STX']

In [ ]:
temp = core.exchange_websocket_dict['UPBIT_SPOT'].get_price_df()
temp[temp['base_asset']=='STX']

In [ ]:
core.info_dict['binance_spot_ticker_df']['symbol']

In [ ]:
len(core.get_binance_spot_symbol_list())

In [ ]:
core.info_dict['upbit_spot_ticker_df']

In [ ]:
def convert_asset_rate(origin_market, origin_quote_asset, target_market, target_quote_asset):
    if origin_quote_asset == "USD":
        origin_quote_asset = "USDT"
    if target_quote_asset == "USD":
        target_quote_asset = "USDT"
    if origin_quote_asset == target_quote_asset:
        return 1
    origin_market_spot_info_df = core.info_dict[f"{origin_market.lower().split('_')[0]}_spot_ticker_df"]
    # First try to find the rate from the info_dict

    def convert_between_coins(origin_market_spot_info_df, origin_quote_asset, target_quote_asset):
        df = origin_market_spot_info_df[(origin_market_spot_info_df['base_asset']==origin_quote_asset)&(origin_market_spot_info_df['quote_asset']==target_quote_asset)]
        reverse_df = origin_market_spot_info_df[(origin_market_spot_info_df['quote_asset']==origin_quote_asset)&(origin_market_spot_info_df['base_asset']==target_quote_asset)]
        if len(df) == 1:
            convert_rate = df['lastPrice'].values[0]
        elif len(reverse_df) == 1:
            convert_rate = 1 / reverse_df['lastPrice'].values[0]
        else:
            convert_rate = None
        return convert_rate
    convert_rate = convert_between_coins(origin_market_spot_info_df, origin_quote_asset, target_quote_asset)
    if convert_rate is None: # not between coins
        # print("1st convert_rate is None, Not between coins")
        if target_quote_asset == "KRW" and origin_quote_asset == "USDT":
            convert_rate = core.update_dollar_return_dict['price']
        elif target_quote_asset == "USDT" and origin_quote_asset == "KRW":
            convert_rate = 1 / core.update_dollar_return_dict['price']
        elif target_quote_asset == "KRW":
            convert_rate = convert_between_coins(origin_market_spot_info_df, origin_quote_asset, "USDT") * core.update_dollar_return_dict['price']
        elif origin_quote_asset == "KRW":
            temp_convert_rate = convert_asset_rate(target_market, target_quote_asset, origin_market, origin_quote_asset)
            if temp_convert_rate is not None:
                convert_rate = 1 / temp_convert_rate
            else:
                title = f"target_quote_asset: {target_quote_asset}, origin_quote_asset: {origin_quote_asset}"
                raise Exception(f"Cannot find the convert rate for {title}")
        else:
            title = f"target_quote_asset: {target_quote_asset}, origin_quote_asset: {origin_quote_asset}"
            raise Exception(f"Cannot find the convert rate for {title}")
    return convert_rate

In [ ]:
exchange_origin = 'BINANCE_USD_M/USDT'
exchange_target = 'UPBIT_SPOT/BTC'
def get_premium_df(self, target_exchange_code, origin_exchange_code):
    # POSSIBLE quote_assets: USDT, BUSD, BTC, KRW
    origin_market = exchange_origin.split('/')[0]
    quote_asset_one = exchange_origin.split('/')[1]
    target_market = exchange_target.split('/')[0]
    quote_asset_two = exchange_target.split('/')[1]

    origin_market_df = self.exchange_websocket_dict[origin_market].get_price_df()
    origin_market_df = origin_market_df[origin_market_df['quote_asset'] == quote_asset_one]
    target_market_df = self.exchange_websocket_dict[target_market].get_price_df()
    target_market_df = target_market_df[target_market_df['quote_asset'] == quote_asset_two]

    shared_bass_asset_list = list(set(origin_market_df['base_asset'].values).intersection(set(target_market_df['base_asset'].values)))
    origin_market_df = origin_market_df[origin_market_df['base_asset'].isin(shared_bass_asset_list)].sort_values('base_asset').reset_index(drop=True)
    target_market_df = target_market_df[target_market_df['base_asset'].isin(shared_bass_asset_list)].sort_values('base_asset').reset_index(drop=True)

    convert_rate = convert_asset_rate(origin_market, quote_asset_one, target_market, quote_asset_two)
    origin_market_df[['converted_tp','converted_ap','converted_bp']] = origin_market_df[['tp','ap','bp']] * convert_rate
    # target_market_df[['converted_tp','converted_ap','converted_bp']] = target_market_df[['tp','ap','bp']]

    # divide by target_market_df[['tp','ap','bp']]
    premium_df = pd.DataFrame((target_market_df[['tp','ap','bp']].values - origin_market_df[['converted_tp','converted_bp','converted_ap']].values)/
                            origin_market_df[['converted_tp','converted_bp','converted_ap']].values, columns=['tp_premium','LS_premium','SL_premium'])
    premium_df['LS_SL_spread'] = premium_df['LS_premium'] - premium_df['SL_premium']
    premium_df[['base_asset','quote_asset','tp','ap','bp','atp24h']] = target_market_df[['base_asset','quote_asset','tp','ap','bp','atp24h']]
    premium_df[['converted_tp','converted_ap','converted_bp']] = origin_market_df[['converted_tp','converted_ap', 'converted_bp']]
    premium_df.loc[:, ['tp_premium','LS_premium','SL_premium','LS_SL_spread']] = premium_df[['tp_premium','LS_premium','SL_premium','LS_SL_spread']] * 100
    return premium_df

In [ ]:
# POSSIBLE quote_assets: USDT, BUSD, BTC, KRW

exchange_origin = 'BINANCE_USD_M/USDT'
exchange_target = 'UPBIT_SPOT/BTC'

origin_market = exchange_origin.split('/')[0]
quote_asset_one = exchange_origin.split('/')[1]
target_market = exchange_target.split('/')[0]
quote_asset_two = exchange_target.split('/')[1]


origin_market_df = core.exchange_websocket_dict[origin_market].get_price_df()
origin_market_df = origin_market_df[origin_market_df['quote_asset'] == quote_asset_one]
target_market_df = core.exchange_websocket_dict[target_market].get_price_df()
target_market_df = target_market_df[target_market_df['quote_asset'] == quote_asset_two]

shared_bass_asset_list = list(set(origin_market_df['base_asset'].values).intersection(set(target_market_df['base_asset'].values)))
origin_market_df = origin_market_df[origin_market_df['base_asset'].isin(shared_bass_asset_list)].sort_values('base_asset').reset_index(drop=True)
# origin_market_df = origin_market_df[origin_market_df['base_asset'].isin(shared_bass_asset_list)].set_index('base_asset')
target_market_df = target_market_df[target_market_df['base_asset'].isin(shared_bass_asset_list)].sort_values('base_asset').reset_index(drop=True)
# target_market_df = target_market_df[target_market_df['base_asset'].isin(shared_bass_asset_list)].set_index('base_asset')

convert_rate = convert_asset_rate(origin_market, quote_asset_one, target_market, quote_asset_two)

origin_market_df[['converted_tp','converted_ap','converted_bp']] = origin_market_df[['tp','ap','bp']] * convert_rate
# target_market_df[['converted_tp','converted_ap','converted_bp']] = target_market_df[['tp','ap','bp']]

# divide by target_market_df[['tp','ap','bp']]
premium_df = pd.DataFrame((target_market_df[['tp','ap','bp']].values - origin_market_df[['converted_tp','converted_bp','converted_ap']].values)/
                          origin_market_df[['converted_tp','converted_bp','converted_ap']].values, columns=['tp_premium','LS_premium','SL_premium'])
premium_df['LS_SL_spread'] = premium_df['LS_premium'] - premium_df['SL_premium']
premium_df[['base_asset','quote_asset','tp','ap','bp','atp24h']] = target_market_df[['base_asset','quote_asset','tp','ap','bp','atp24h']]
premium_df[['converted_tp','converted_ap','converted_bp']] = origin_market_df[['converted_tp','converted_ap', 'converted_bp']]
premium_df.loc[:, ['tp_premium','LS_premium','SL_premium','LS_SL_spread']] = premium_df[['tp_premium','LS_premium','SL_premium','LS_SL_spread']] * 100
premium_df.sort_values('atp24h', ascending=False).reset_index(drop=True).head(10)

In [ ]:
origin_market_df = core.exchange_websocket_dict[origin_market].get_price_df()
origin_market_df = origin_market_df[origin_market_df['quote_asset'] == quote_asset_one]
target_market_df = core.exchange_websocket_dict[target_market].get_price_df()
target_market_df = target_market_df[target_market_df['quote_asset'] == quote_asset_two]

In [ ]:
origin_market_df

In [ ]:
core.exchange_websocket_dict[target_market].get_price_df()

In [ ]:
target_market_df.head()[['base_asset','tp','ap','bp']]

In [ ]:
origin_market_df.head()[['base_asset','tp','ap','bp']]

In [ ]:
origin_market_df.head()

In [ ]:
convert_asset_rate(origin_market="BINANCE_SPOT", origin_quote_asset='BUSD', target_market="UPBIT_SPOT", target_quote_asset='KRW')

In [ ]:
core.update_dollar_return_dict['price']

In [ ]:
upbit_ticker_df = pd.DataFrame(dict(core.exchange_websocket_dict['UPBIT'].upbit_ticker_dict)).T.reset_index()[['index','tp','scr','atp24h','h52wp','l52wp','ms','mw','tms']]
upbit_orderbook_df = pd.DataFrame(dict(core.exchange_websocket_dict['UPBIT'].upbit_orderbook_dict)).T.reset_index(drop=True)[['cd','tms','obu']]
upbit_orderbook_df['ap'] = upbit_orderbook_df['obu'].apply(lambda x: x[0]['ap'])
upbit_orderbook_df['bp'] = upbit_orderbook_df['obu'].apply(lambda x: x[0]['bp'])
upbit_orderbook_df.drop('obu', axis=1, inplace=True)
upbit_merged_df = pd.merge(upbit_ticker_df, upbit_orderbook_df, left_on='index', right_on='cd', how='inner')
upbit_merged_df['base_asset'] = upbit_merged_df['index'].apply(lambda x: x.split('-')[1])
upbit_merged_df['quote_asset'] = upbit_merged_df['index'].apply(lambda x: x.split('-')[0])
upbit_merged_df.drop('index', axis=1, inplace=True)
upbit_merged_df.loc[:, ['scr','atp24h','h52wp','l52wp','ap','bp']] = upbit_merged_df.loc[:, ['scr','atp24h','h52wp','l52wp','ap','bp']].astype(float)
upbit_merged_df.loc[:, 'scr'] = upbit_merged_df['scr'] * 100
upbit_merged_df.head()

In [ ]:
upbit_merged_df.head()

In [ ]:
core.info_dict['binance_spot_info_df'][['symbol','baseAsset','quoteAsset']].head()

In [ ]:
binance_ticker_df = pd.DataFrame(dict(core.exchange_websocket_dict['BINANCE_SPOT'].ticker_dict)).T.reset_index(drop=True)[['s','P','c','v','q']]
binance_ticker_df.rename(columns={"q": "atp24h", 'P': 'scr', 'c': 'tp'}, inplace=True)
binance_bookticker_df = pd.DataFrame(dict(core.exchange_websocket_dict['BINANCE_SPOT'].bookticker_dict)).T.reset_index(drop=True)[['s','b','a']]
binance_bookticker_df.rename(columns={"b": "bp", "a": "ap"}, inplace=True)
binance_merged_df = pd.merge(binance_ticker_df, binance_bookticker_df, on='s', how='inner')
binance_merged_df.loc[:, ['scr','tp','atp24h','ap','bp']] = binance_merged_df[['scr','tp','atp24h','ap','bp']].astype(float)
binance_merged_df = binance_merged_df.merge(core.info_dict['binance_spot_info_df'][['symbol','baseAsset','quoteAsset']], left_on='s', right_on='symbol', how='inner')
binance_merged_df.drop(['symbol', 's'], axis=1, inplace=True)
binance_merged_df.rename(columns={'baseAsset':"base_asset", 'quoteAsset':"quote_asset"}, inplace=True)
binance_merged_df

In [ ]:
binance_merged_df['quote_asset'].unique()

In [ ]:
binance_ticker_df = pd.DataFrame(dict(core.exchange_websocket_dict['BINANCE_USD_M'].ticker_dict)).T.reset_index(drop=True)[['s','P','c','v','q']]
binance_ticker_df.rename(columns={"q": "atp24h", 'P': 'scr', 'c': 'tp'}, inplace=True)
binance_bookticker_df = pd.DataFrame(dict(core.exchange_websocket_dict['BINANCE_USD_M'].bookticker_dict)).T.reset_index(drop=True)[['s','b','a']]
binance_bookticker_df.rename(columns={"b": "bp", "a": "ap"}, inplace=True)
binance_merged_df = pd.merge(binance_ticker_df, binance_bookticker_df, on='s', how='inner')
binance_merged_df.loc[:, ['scr','tp','atp24h','ap','bp']] = binance_merged_df[['scr','tp','atp24h','ap','bp']].astype(float)
binance_merged_df = binance_merged_df.merge(core.info_dict['binance_usdm_info_df'][['symbol','baseAsset','quoteAsset']], left_on='s', right_on='symbol', how='inner')
binance_merged_df.drop(['symbol', 's'], axis=1, inplace=True)
binance_merged_df.rename(columns={'baseAsset':"base_asset", 'quoteAsset':"quote_asset"}, inplace=True)
binance_merged_df

In [ ]:
binance_ticker_df = pd.DataFrame(dict(core.exchange_websocket_dict['BINANCE_COIN_M'].ticker_dict)).T.reset_index(drop=True)[['s','P','c','v','q']]
binance_ticker_df.rename(columns={"q": "atp24h", 'P': 'scr', 'c': 'tp'}, inplace=True)
binance_bookticker_df = pd.DataFrame(dict(core.exchange_websocket_dict['BINANCE_COIN_M'].bookticker_dict)).T.reset_index(drop=True)[['s','b','a']]
binance_bookticker_df.rename(columns={"b": "bp", "a": "ap"}, inplace=True)
binance_merged_df = pd.merge(binance_ticker_df, binance_bookticker_df, on='s', how='inner')
binance_merged_df.loc[:, ['scr','tp','atp24h','ap','bp']] = binance_merged_df[['scr','tp','atp24h','ap','bp']].astype(float)
binance_merged_df = binance_merged_df.merge(core.info_dict['binance_coinm_info_df'][['symbol','baseAsset','quoteAsset']], left_on='s', right_on='symbol', how='inner')
binance_merged_df.drop(['symbol', 's'], axis=1, inplace=True)
binance_merged_df.rename(columns={'baseAsset':"base_asset", 'quoteAsset':"quote_asset"}, inplace=True)
binance_merged_df