In [3]:
import datetime
import pandas as pd
import requests
import os
import sys
from msg_api import MsgApi

In [4]:
message_api = MsgApi(prod=False)

# acw_api.create_message(telegram_chat_id=1390695186, title="test_from_core3_trade_core", origin="test", type="info", content="test", remark="test", code=None, sent=False, send_times=1, send_term=1)
message_api.get_message()

/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py:1095: InsecureRequestWarning: Unverified HTTPS request is being made to host 'acw-dev.orbitholdings.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

,id,datetime,telegram_bot_username,telegram_chat_id,title,content,remarks,origin,type,code,sent,send_times,send_term
0,1,2023-12-26T13:05:12+0000,test_acw_bot,1722781031,Test,Test from acw-dev,None,insomia,info,None,True,1,1
1,2,2024-01-08T09:20:58+0000,test_acw_bot,1722781031,ngroktest,Test from terminal,None,terminal,info,None,True,1,1
2,3,2024-01-09T09:05:21+0000,arbicrypto_dev_bot,1722781031,ngroktest,Test from terminal,None,terminal,info,None,True,1,1
3,4,2024-01-09T09:05:21+0000,arbicrypto_dev_bot,1390695186,ngroktest,Test from terminal,None,terminal,info,None,True,1,1
4,5,2024-01-09T09:05:21+0000,arbicrypto_dev_bot,1731633310,ngroktest,Test from terminal,None,terminal,info,None,True,1,1
5,6,2024-01-09T09:13:40+0000,arbicrypto_dev_bot,1722781031,ngroktest,Test2 from terminal,None,terminal,info,None,True,1,1
6,7,2024-01-09T09:13:40+0000,arbicrypto_dev_bot,1390695186,ngroktest,Test2 from terminal,None,terminal,info,None,True,1,1
7,8,2024-01-09T09:13:40+0000,arbicrypto_dev_bot,1731633310,ngroktest,Test2 from terminal,None,terminal,info,None,True,1,1
8,9,2024-01-09T09:16:21+0000,arbicrypto_dev_bot,1722781031,ngroktest,Test2 from terminal,None,terminal,info,None,True,3,10
9,10,2024-01-09T09:16:21+0000,arbicrypto_dev_bot,1390695186,ngroktest,Test2 from terminal,None,terminal,info,None,True,3,10
10,11,2024-01-09T09:16:21+0000,arbicrypto_dev_bot,1731633310,ngroktest,Test2 from terminal,None,terminal,info,None,True,3,10
11,12,2024-01-09T09:17:49+0000,arbicrypto_dev_bot,1722781031,ngroktest,Test 5 times every 5 seconds,None,terminal,info,None,True,5,5
12,13,2024-01-09T09:17:49+0000,arbicrypto_dev_bot,1390695186,ngroktest,Test 5 times every 5 seconds,None,terminal,info,None,True,5,5
13,14,2024-01-09T09:17:49+0000,arbicrypto_dev_bot,1731633310,ngroktest,Test 5 times every 5 seconds,None,terminal,info,None,True,5,5
14,17,2024-01-18T13:52:42+0000,arbicrypto_dev_bot,1390695186,프리미엄 하향돌파,"BTC KRW 2.4110263472477538 2.4110263472477538,...",None,trade_core1,info,None,False,1,1

In [5]:
message_api.delete_message(17)
message_api.get_message()

/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py:1095: InsecureRequestWarning: Unverified HTTPS request is being made to host 'acw-dev.orbitholdings.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py:1095: InsecureRequestWarning: Unverified HTTPS request is being made to host 'acw-dev.orbitholdings.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

,id,datetime,telegram_bot_username,telegram_chat_id,title,content,remarks,origin,type,code,sent,send_times,send_term
0,1,2023-12-26T13:05:12+0000,test_acw_bot,1722781031,Test,Test from acw-dev,None,insomia,info,None,True,1,1
1,2,2024-01-08T09:20:58+0000,test_acw_bot,1722781031,ngroktest,Test from terminal,None,terminal,info,None,True,1,1
2,3,2024-01-09T09:05:21+0000,arbicrypto_dev_bot,1722781031,ngroktest,Test from terminal,None,terminal,info,None,True,1,1
3,4,2024-01-09T09:05:21+0000,arbicrypto_dev_bot,1390695186,ngroktest,Test from terminal,None,terminal,info,None,True,1,1
4,5,2024-01-09T09:05:21+0000,arbicrypto_dev_bot,1731633310,ngroktest,Test from terminal,None,terminal,info,None,True,1,1
5,6,2024-01-09T09:13:40+0000,arbicrypto_dev_bot,1722781031,ngroktest,Test2 from terminal,None,terminal,info,None,True,1,1
6,7,2024-01-09T09:13:40+0000,arbicrypto_dev_bot,1390695186,ngroktest,Test2 from terminal,None,terminal,info,None,True,1,1
7,8,2024-01-09T09:13:40+0000,arbicrypto_dev_bot,1731633310,ngroktest,Test2 from terminal,None,terminal,info,None,True,1,1
8,9,2024-01-09T09:16:21+0000,arbicrypto_dev_bot,1722781031,ngroktest,Test2 from terminal,None,terminal,info,None,True,3,10
9,10,2024-01-09T09:16:21+0000,arbicrypto_dev_bot,1390695186,ngroktest,Test2 from terminal,None,terminal,info,None,True,3,10
10,11,2024-01-09T09:16:21+0000,arbicrypto_dev_bot,1731633310,ngroktest,Test2 from terminal,None,terminal,info,None,True,3,10
11,12,2024-01-09T09:17:49+0000,arbicrypto_dev_bot,1722781031,ngroktest,Test 5 times every 5 seconds,None,terminal,info,None,True,5,5
12,13,2024-01-09T09:17:49+0000,arbicrypto_dev_bot,1390695186,ngroktest,Test 5 times every 5 seconds,None,terminal,info,None,True,5,5
13,14,2024-01-09T09:17:49+0000,arbicrypto_dev_bot,1731633310,ngroktest,Test 5 times every 5 seconds,None,terminal,info,None,True,5,5

In [3]:
message_api.get_message()

/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py:1095: InsecureRequestWarning: Unverified HTTPS request is being made to host 'acw-dev.orbitholdings.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

,id,datetime,telegram_bot_username,telegram_chat_id,title,content,remarks,origin,type,code,sent,send_times,send_term
0,1,2023-12-26T13:05:12+0000,test_acw_bot,1722781031,Test,Test from acw-dev,None,insomia,info,None,True,1,1
1,2,2024-01-08T09:20:58+0000,test_acw_bot,1722781031,ngroktest,Test from terminal,None,terminal,info,None,True,1,1
2,3,2024-01-09T09:05:21+0000,arbicrypto_dev_bot,1722781031,ngroktest,Test from terminal,None,terminal,info,None,True,1,1
3,4,2024-01-09T09:05:21+0000,arbicrypto_dev_bot,1390695186,ngroktest,Test from terminal,None,terminal,info,None,True,1,1
4,5,2024-01-09T09:05:21+0000,arbicrypto_dev_bot,1731633310,ngroktest,Test from terminal,None,terminal,info,None,True,1,1
5,6,2024-01-09T09:13:40+0000,arbicrypto_dev_bot,1722781031,ngroktest,Test2 from terminal,None,terminal,info,None,True,1,1
6,7,2024-01-09T09:13:40+0000,arbicrypto_dev_bot,1390695186,ngroktest,Test2 from terminal,None,terminal,info,None,True,1,1
7,8,2024-01-09T09:13:40+0000,arbicrypto_dev_bot,1731633310,ngroktest,Test2 from terminal,None,terminal,info,None,True,1,1
8,9,2024-01-09T09:16:21+0000,arbicrypto_dev_bot,1722781031,ngroktest,Test2 from terminal,None,terminal,info,None,True,3,10
9,10,2024-01-09T09:16:21+0000,arbicrypto_dev_bot,1390695186,ngroktest,Test2 from terminal,None,terminal,info,None,True,3,10
10,11,2024-01-09T09:16:21+0000,arbicrypto_dev_bot,1731633310,ngroktest,Test2 from terminal,None,terminal,info,None,True,3,10
11,12,2024-01-09T09:17:49+0000,arbicrypto_dev_bot,1722781031,ngroktest,Test 5 times every 5 seconds,None,terminal,info,None,True,5,5
12,13,2024-01-09T09:17:49+0000,arbicrypto_dev_bot,1390695186,ngroktest,Test 5 times every 5 seconds,None,terminal,info,None,True,5,5
13,14,2024-01-09T09:17:49+0000,arbicrypto_dev_bot,1731633310,ngroktest,Test 5 times every 5 seconds,None,terminal,info,None,True,5,5

In [4]:
message_api.delete_message(16)

/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py:1095: InsecureRequestWarning: Unverified HTTPS request is being made to host 'acw-dev.orbitholdings.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Exception: Error: 404
{"detail":"Not found."}