In [1]:
import os
import sys
import traceback
from io import BytesIO
from io import TextIOWrapper, BytesIO
import datetime
import time
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import matplotlib.ticker as mtick
from sklearn import linear_model
# library for candlestick
import mplfinance as mpf

# Skip any overhead related to the GUI backends.
import matplotlib
matplotlib.use('Agg')

# upper_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
upper_dir = '/home/trade_core/'
sys.path.append(upper_dir)
from etc.db_handler.postgres_client import InitDBClient
from loggers.logger import KimpBotLogger

In [2]:
# TEST
import json
from etc.db_handler.mongodb_client import InitDBClient as InitMongoDBClient
config_dir = "/home/trade_core/trade_core_config.json"
with open(config_dir) as f:
    config = json.load(f)
    
node = config['node']
mongo_db_dict = config['database_setting'][config['node_settings'][node]['mongo_db_settings']]
mongo_db_client = InitMongoDBClient(**mongo_db_dict)
conn = mongo_db_client.get_conn()

In [3]:
collection = conn['UPBIT_SPOT__KRW-BINANCE_USD_M__USDT']['BTC_1H']

In [4]:
temp_df = pd.DataFrame(collection.find({}).sort('_id', -1).limit(200))

In [5]:
temp_df.fillna(method='ffill')

,_id,base_asset,datetime_now,tp_open,tp_high,tp_low,tp_close,LS_open,LS_high,LS_low,...,SL_high,SL_low,SL_close,dollar,count,closed,tp,scr,atp24h,converted_tp
0,6614f580def4968d716fcd26,BTC,2024-04-09 06:00:00,4.990514,5.464679,4.904058,5.110492,4.990662,5.466917,4.919481,...,5.459459,4.901230,5.106574,1355.0,2,True,100364000.0,-1.701257,6.239355e+11,95522064.00
1,6614e770def4968d716fccd5,BTC,2024-04-09 05:00:00,5.110284,5.253429,4.953334,4.990514,5.138245,5.268493,4.950683,...,5.254747,4.945997,4.989476,1354.9,2,True,100879000.0,-1.196854,6.385490e+11,95974243.50
2,6614d960def4968d716fcc84,BTC,2024-04-09 04:00:00,5.059143,5.332844,5.001291,5.110284,5.069488,5.347823,5.020765,...,5.305721,4.999070,5.110137,1355.1,2,True,101156000.0,-0.925554,6.216148e+11,96347751.94
3,6614cb50def4968d716fcc33,BTC,2024-04-09 03:00:00,5.029349,5.216026,4.747819,5.073903,5.029349,5.216026,4.761978,...,5.200227,4.747819,5.073903,1355.0,2,True,101499000.0,-0.589612,6.179005e+11,96564290.49
4,6614bd40def4968d716fcbe2,BTC,2024-04-09 02:00:00,5.133440,5.232701,4.816748,5.029349,5.133587,5.239353,4.819533,...,5.224696,4.814536,5.028170,1355.1,2,True,101569000.0,-0.521053,6.097991e+11,96664345.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,65e65271d6e58a00e2f8c6cc,BTC,2024-03-04 21:00:00,5.072772,5.457942,4.912812,5.194028,5.065944,5.483470,4.936303,...,5.456390,4.885266,5.193093,1333.0,2,True,94940000.0,7.908436,1.130239e+12,90507866.90
196,65e64460d6e58a00e2f8c67a,BTC,2024-03-04 20:00:00,4.657428,5.201464,4.587932,5.072772,4.650787,5.218973,4.611715,...,5.176391,4.572444,4.928839,1333.0,2,True,94456000.0,7.358323,1.103477e+12,89793119.90
197,65e63650d6e58a00e2f8c628,BTC,2024-03-04 19:00:00,4.608191,4.995554,4.564483,4.657428,4.615878,5.037435,4.560142,...,5.035673,4.548385,4.647192,1333.0,2,True,94250000.0,7.124184,1.075954e+12,89811088.40
198,65e62841d6e58a00e2f8c5d6,BTC,2024-03-04 18:00:00,5.037199,5.332145,4.608191,4.608191,5.037355,5.362992,4.608819,...,5.313313,4.605282,4.605282,1333.0,2,True,93993000.0,6.832079,1.049087e+12,89810156.70
199,65e61a31d6e58a00e2f8c584,BTC,2024-03-04 17:00:00,4.603032,5.094887,4.210151,5.039443,4.601933,5.107702,4.211541,...,5.045031,4.157937,4.872708,1333.0,2,True,92859000.0,5.543179,1.034266e+12,88768383.00

In [112]:
temp_df

,_id,base_asset,datetime_now,tp_open,tp_high,tp_low,tp_close,LS_open,LS_high,LS_low,...,SL_high,SL_low,SL_close,dollar,count,closed,tp,scr,atp24h,converted_tp
0,6614cb50def4968d716fcc33,BTC,2024-04-09 03:00:00,5.029349,5.216026,4.747819,5.073903,5.029349,5.216026,4.761978,...,5.200227,4.747819,5.073903,1355.0,2,True,101499000.0,-0.589612,6.179005e+11,96564290.49
1,6614bd40def4968d716fcbe2,BTC,2024-04-09 02:00:00,5.133440,5.232701,4.816748,5.029349,5.133587,5.239353,4.819533,...,5.224696,4.814536,5.028170,1355.1,2,True,101569000.0,-0.521053,6.097991e+11,96664345.00
2,6614af30def4968d716fcb91,BTC,2024-04-09 01:00:00,5.075561,5.344368,4.904567,5.137862,5.102580,5.433658,4.915949,...,5.408876,4.903521,5.115842,1354.5,2,True,101800000.0,-0.294806,6.071148e+11,96925289.13
3,6614a120def4968d716fcb40,BTC,2024-04-09 00:00:00,5.201766,5.461831,5.056759,5.075561,5.201912,5.469778,5.063103,...,5.457263,5.056759,5.084863,1353.8,2,True,101560000.0,-0.529867,6.013274e+11,96596980.20
4,66149310def4968d716fcaef,BTC,2024-04-08 23:00:00,4.873763,5.293704,4.742837,5.201766,4.860217,5.299435,4.777414,...,5.286342,4.746558,5.149217,1354.0,2,True,101667000.0,-0.425069,5.816810e+11,96756086.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,65e62841d6e58a00e2f8c5d6,BTC,2024-03-04 18:00:00,5.037199,5.332145,4.608191,4.608191,5.037355,5.362992,4.608819,...,5.313313,4.605282,4.605282,1333.0,2,True,93993000.0,6.832079,1.049087e+12,89810156.70
196,65e61a31d6e58a00e2f8c584,BTC,2024-03-04 17:00:00,4.603032,5.094887,4.210151,5.039443,4.601933,5.107702,4.211541,...,5.045031,4.157937,4.872708,1333.0,2,True,92859000.0,5.543179,1.034266e+12,88768383.00
197,65e60c21d6e58a00e2f8c532,BTC,2024-03-04 16:00:00,4.567622,4.998101,4.425171,4.605073,4.565648,5.004908,4.194216,...,4.951765,4.192930,4.598521,1333.0,2,True,93580000.0,6.362665,1.008607e+12,89097006.90
198,65e5fe11d6e58a00e2f8c4e0,BTC,2024-03-04 15:00:00,4.622701,4.787520,4.241769,4.567622,4.633630,4.848651,4.216002,...,4.839555,4.189150,4.556168,1333.0,2,True,92750000.0,5.419290,9.574565e+11,88666827.70
199,65e5f001d6e58a00e2f8c48e,BTC,2024-03-04 14:00:00,5.046175,5.398893,4.193552,4.622701,5.046336,5.439838,4.195104,...,5.386376,4.180191,4.632338,1333.0,2,True,92563000.0,5.206747,9.161594e+11,88523878.30

In [8]:
test_market_code_combination_name = 'UPBIT_SPOT/KRW:BINANCE_USD_M/USDT'
test_market_code_combination_name.replace('/', '__').replace(':', '-')

'UPBIT_SPOT__KRW-BINANCE_USD_M__USDT'

In [38]:
class InitDataProcessor:
    def __init__(self, logging_dir, mongo_db_client):
        self.data_process_logger = KimpBotLogger("data_process_logger", logging_dir).logger
        self.mongo_db_client = mongo_db_client
        self.mongo_db_conn = self.mongo_db_client.get_conn()

    def get_pboundary(self, market_code_combination, base_asset, usdt_conversion, interval, kline_num, percent_gap, draw_plot=False, return_dict=None):
        converted_market_code_combination = market_code_combination.replace('/', '__').replace(':', '-')
        try:
            if draw_plot:
                plt.clf()
                fig = plt.figure(figsize=(14,8))
                ax = plt.gca()
                ax.grid(True)
            
            # Load kimp_kline from DB
            # db_start = time.time()                                                      #test
            collection = self.mongo_db_conn[f"{converted_market_code_combination}"][f'{base_asset}_{interval}'].find({}).sort('_id', -1).limit(kline_num)
            fetched_df = pd.DataFrame(collection)
            # print(f"db fetch time: {time.time() - db_start}")                           #test
            premium_df = pd.DataFrame(fetched_df).drop('_id', axis=1).sort_values('datetime_now').reset_index(drop=True).drop_duplicates()
            # check whether 'tp_close' column is full of NaN or null values
            if premium_df['tp_close'].isnull().all():
                premium_df.loc[:, 'tp_close'] = (premium_df['LS_close'] + premium_df['SL_close']) / 2
            premium_df = premium_df.fillna(method='ffill')
            if usdt_conversion:
                y_value = (1+premium_df['tp_close']/100) * premium_df['dollar']
                y_enter_value = (1+premium_df['LS_close']/100) * premium_df['dollar']
                y_exit_value = (1+premium_df['SL_close']/100) * premium_df['dollar']
            else:
                y_value = premium_df['tp_close']
                y_enter_value = premium_df['LS_close']
                y_exit_value = premium_df['SL_close']

            if draw_plot:
                ax.plot(premium_df['datetime_now'], y_value, marker='.', alpha=0.85, label=f'{base_asset}|{converted_market_code_combination}')
                # ax.plot(premium_df['datetime_now'], y_enter_value, marker='.', alpha=0.85, label=f'{base_asset}|{converted_market_code_combination} LS')
                # ax.plot(premium_df['datetime_now'], y_exit_value, marker='.', alpha=0.85, label=f'{base_asset}|{converted_market_code_combination} SL')
                # mpf.plot(pd.DataFrame(columns=['Open','High','Low','Close'], data=premium_df.loc[:, 'tp_open':'tp_close'].to_numpy(), index=premium_df['datetime_now'].values),type='candle', figsize=(14,10), ylabel='', ax=ax)

            timedel = premium_df['datetime_now'].iloc[-1] - premium_df['datetime_now'].iloc[-2]
            
            if draw_plot:
                ax.set_xlim(premium_df['datetime_now'].iloc[0], premium_df['datetime_now'].iloc[-1]+(timedel * 20))
                if usdt_conversion == False:
                    ax.yaxis.set_major_formatter(mtick.PercentFormatter())
                ax.tick_params(labelsize=14)
                ax.tick_params(labelsize=14)
                ax.set_ylabel('Kimchi Premium', fontsize=20)
                ax.legend(prop={'size':20})
                
            # Regression Line
            clf = linear_model.LinearRegression()
            x_axis = np.array(list(range(len(y_value)))).reshape(-1,1)
            clf.fit(x_axis, y_value)
            prediction = clf.predict(x_axis)
            
            if draw_plot:
                ax.plot(premium_df['datetime_now'], prediction, color='green', alpha=0.65, linestyle='--')
                
            # extrapolate number
            extra_interval_num = 3
            linear_pred = clf.predict((x_axis[-1]+extra_interval_num).reshape(-1,1))
            if usdt_conversion == True:
                lower_bound = linear_pred-(0.5*percent_gap*0.01*linear_pred)
                upper_bound = linear_pred+(0.5*percent_gap*0.01*linear_pred)
            else:
                lower_bound = linear_pred-(0.5*percent_gap)
                upper_bound = linear_pred+(0.5*percent_gap)

            if 'T' in interval:
                extra_interval_min = int(interval.replace('T', ''))
            elif 'H' in interval:
                extra_interval_min = 60 * int(interval.replace('H', ''))
            elif 'D' in interval:
                extra_interval_min = 60 * 24 * int(interval.replace('D', ''))
            else:
                # raise error
                raise ValueError(f"Invalid interval: {interval}")
            
            lower_bound = round(float(lower_bound[0]), 3)
            upper_bound = round(float(upper_bound[0]), 3)
            
            if draw_plot:
                ax.plot((premium_df['datetime_now'].iloc[-1] + datetime.timedelta(minutes=extra_interval_min*extra_interval_num)), lower_bound, 'X', color='r', markersize = 20)
                ax.plot((premium_df['datetime_now'].iloc[-1] + datetime.timedelta(minutes=extra_interval_min*extra_interval_num)), upper_bound, 'X', color='r', markersize = 20)

            if draw_plot:
                buf = BytesIO()
                fig.savefig(buf, format='png', dpi=75, bbox_inches='tight')
                # test save as image
                plt.savefig(f"/home/trade_core/data_process/{base_asset}_plot.png", format='png', dpi=75, bbox_inches='tight')
                # plt.show()               # test
                plt.close(fig)
            else:
                buf = None
                
            output_dict = {
                "buf": buf,
                "regression_line": {"x": list(premium_df['datetime_now'].dt.strftime('%Y-%m-%d %H:%M:%S').values), "y": list(prediction)},
                "predicted_points": {"x": [x.strftime('%Y-%m-%d %H:%M:%S') for x in list(2*[premium_df['datetime_now'].iloc[-1] + datetime.timedelta(minutes=extra_interval_min*extra_interval_num)])], "y":[lower_bound, upper_bound]}
            }
            if return_dict is not None:
                return_dict['return'] = output_dict
            return output_dict
        except Exception:
            self.data_process_logger.error(f"get_pboundary|{converted_market_code_combination}|{base_asset}|{interval}|{traceback.format_exc()}")

In [39]:
data_processor = InitDataProcessor(None, mongo_db_client)
output = data_processor.get_pboundary(test_market_code_combination_name, 'DOGE', True, '1T', 200, 1, True, None)

In [40]:
output

{'buf': <_io.BytesIO at 0x7f2df366d090>,
 'regression_line': {'x': ['2024-04-09 05:08:00',
   '2024-04-09 05:09:00',
   '2024-04-09 05:10:00',
   '2024-04-09 05:11:00',
   '2024-04-09 05:12:00',
   '2024-04-09 05:13:00',
   '2024-04-09 05:14:00',
   '2024-04-09 05:15:00',
   '2024-04-09 05:16:00',
   '2024-04-09 05:17:00',
   '2024-04-09 05:18:00',
   '2024-04-09 05:19:00',
   '2024-04-09 05:20:00',
   '2024-04-09 05:21:00',
   '2024-04-09 05:22:00',
   '2024-04-09 05:23:00',
   '2024-04-09 05:24:00',
   '2024-04-09 05:25:00',
   '2024-04-09 05:26:00',
   '2024-04-09 05:27:00',
   '2024-04-09 05:28:00',
   '2024-04-09 05:29:00',
   '2024-04-09 05:30:00',
   '2024-04-09 05:31:00',
   '2024-04-09 05:32:00',
   '2024-04-09 05:33:00',
   '2024-04-09 05:34:00',
   '2024-04-09 05:35:00',
   '2024-04-09 05:36:00',
   '2024-04-09 05:37:00',
   '2024-04-09 05:38:00',
   '2024-04-09 05:39:00',
   '2024-04-09 05:40:00',
   '2024-04-09 05:41:00',
   '2024-04-09 05:42:00',
   '2024-04-09 05:43:00',
   '2024-04-09 05:44:00',
   '2024-04-09 05:45:00',
   '2024-04-09 05:46:00',
   '2024-04-09 05:47:00',
   '2024-04-09 05:48:00',
   '2024-04-09 05:49:00',
   '2024-04-09 05:50:00',
   '2024-04-09 05:51:00',
   '2024-04-09 05:52:00',
   '2024-04-09 05:53:00',
   '2024-04-09 05:54:00',
   '2024-04-09 05:55:00',
   '2024-04-09 05:56:00',
   '2024-04-09 05:57:00',
   '2024-04-09 05:58:00',
   '2024-04-09 05:59:00',
   '2024-04-09 06:00:00',
   '2024-04-09 06:01:00',
   '2024-04-09 06:02:00',
   '2024-04-09 06:03:00',
   '2024-04-09 06:04:00',
   '2024-04-09 06:05:00',
   '2024-04-09 06:06:00',
   '2024-04-09 06:07:00',
   '2024-04-09 06:08:00',
   '2024-04-09 06:09:00',
   '2024-04-09 06:10:00',
   '2024-04-09 06:11:00',
   '2024-04-09 06:12:00',
   '2024-04-09 06:13:00',
   '2024-04-09 06:14:00',
   '2024-04-09 06:15:00',
   '2024-04-09 06:16:00',
   '2024-04-09 06:17:00',
   '2024-04-09 06:18:00',
   '2024-04-09 06:19:00',
   '2024-04-09 06:20:00',
   '2024-04-09 06:21:00',
   '2024-04-09 06:22:00',
   '2024-04-09 06:23:00',
   '2024-04-09 06:24:00',
   '2024-04-09 06:25:00',
   '2024-04-09 06:26:00',
   '2024-04-09 06:27:00',
   '2024-04-09 06:28:00',
   '2024-04-09 06:29:00',
   '2024-04-09 06:30:00',
   '2024-04-09 06:31:00',
   '2024-04-09 06:32:00',
   '2024-04-09 06:33:00',
   '2024-04-09 06:34:00',
   '2024-04-09 06:35:00',
   '2024-04-09 06:36:00',
   '2024-04-09 06:37:00',
   '2024-04-09 06:38:00',
   '2024-04-09 06:39:00',
   '2024-04-09 06:40:00',
   '2024-04-09 06:41:00',
   '2024-04-09 06:42:00',
   '2024-04-09 06:43:00',
   '2024-04-09 06:44:00',
   '2024-04-09 06:45:00',
   '2024-04-09 06:46:00',
   '2024-04-09 06:47:00',
   '2024-04-09 06:48:00',
   '2024-04-09 06:49:00',
   '2024-04-09 06:50:00',
   '2024-04-09 06:51:00',
   '2024-04-09 06:52:00',
   '2024-04-09 06:53:00',
   '2024-04-09 06:54:00',
   '2024-04-09 06:55:00',
   '2024-04-09 06:56:00',
   '2024-04-09 06:57:00',
   '2024-04-09 06:58:00',
   '2024-04-09 06:59:00',
   '2024-04-09 07:00:00',
   '2024-04-09 07:01:00',
   '2024-04-09 07:02:00',
   '2024-04-09 07:03:00',
   '2024-04-09 07:04:00',
   '2024-04-09 07:05:00',
   '2024-04-09 07:06:00',
   '2024-04-09 07:07:00',
   '2024-04-09 07:08:00',
   '2024-04-09 07:09:00',
   '2024-04-09 07:10:00',
   '2024-04-09 07:11:00',
   '2024-04-09 07:12:00',
   '2024-04-09 07:13:00',
   '2024-04-09 07:14:00',
   '2024-04-09 07:15:00',
   '2024-04-09 07:16:00',
   '2024-04-09 07:17:00',
   '2024-04-09 07:18:00',
   '2024-04-09 07:19:00',
   '2024-04-09 07:20:00',
   '2024-04-09 07:21:00',
   '2024-04-09 07:22:00',
   '2024-04-09 07:23:00',
   '2024-04-09 07:24:00',
   '2024-04-09 07:25:00',
   '2024-04-09 07:26:00',
   '2024-04-09 07:27:00',
   '2024-04-09 07:28:00',
   '2024-04-09 07:29:00',
   '2024-04-09 07:30:00',
   '2024-04-09 07:31:00',
   '2024-04-09 07:32:00',
   '2024-04-09 07:33:00',
   '2024-04-09 07:34:00',
   '2024-04-09 07:35:00',
   '2024-04-09 07:36:00',
   '2024-04-09 07:37:00',
   '2024-04-09 07:38:00',
   '2024-04-09 07:39:00',
   '2024-04-09 07:40:00',
   '2024-04-09 07:41:00',
   '2024-04-09 07:42:00',
   '2024-04-09 07:43:00',
   '2024-04-09 07:44:00',
   '2024-04-09 07:45:00',
   '2024-04-09 07:46:00',
   '2024-04-09 07:47:00',
   '2024-04-09 07:48:00',
   '2024-04-09 07:49:00',
   '2024-04-09 07:50:00',
   '2024-04-09 07:51:00',
   '2024-04-09 07:52:00',
   '2024-04-09 07:53:00',
   '2024-04-09 07:54:00',
   '2024-04-09 07:55:00',
   '2024-04-09 07:56:00',
   '2024-04-09 07:57:00',
   '2024-04-09 07:58:00',
   '2024-04-09 07:59:00',
   '2024-04-09 08:00:00',
   '2024-04-09 08:01:00',
   '2024-04-09 08:02:00',
   '2024-04-09 08:03:00',
   '2024-04-09 08:04:00',
   '2024-04-09 08:05:00',
   '2024-04-09 08:06:00',
   '2024-04-09 08:07:00',
   '2024-04-09 08:08:00',
   '2024-04-09 08:09:00',
   '2024-04-09 08:10:00',
   '2024-04-09 08:11:00',
   '2024-04-09 08:12:00',
   '2024-04-09 08:13:00',
   '2024-04-09 08:14:00',
   '2024-04-09 08:15:00',
   '2024-04-09 08:16:00',
   '2024-04-09 08:17:00',
   '2024-04-09 08:18:00',
   '2024-04-09 08:19:00',
   '2024-04-09 08:20:00',
   '2024-04-09 08:21:00',
   '2024-04-09 08:22:00',
   '2024-04-09 08:23:00',
   '2024-04-09 08:24:00',
   '2024-04-09 08:25:00',
   '2024-04-09 08:26:00',
   '2024-04-09 08:27:00'],
  'y': [1423.4373280434827,
   1423.444361221779,
   1423.4513944000755,
   1423.4584275783718,
   1423.465460756668,
   1423.4724939349646,
   1423.479527113261,
   1423.4865602915572,
   1423.4935934698537,
   1423.50062664815,
   1423.5076598264463,
   1423.5146930047426,
   1423.5217261830392,
   1423.5287593613355,
   1423.5357925396318,
   1423.5428257179283,
   1423.5498588962246,
   1423.5568920745209,
   1423.5639252528174,
   1423.5709584311137,
   1423.57799160941,
   1423.5850247877065,
   1423.5920579660028,
   1423.599091144299,
   1423.6061243225956,
   1423.613157500892,
   1423.6201906791882,
   1423.6272238574845,
   1423.634257035781,
   1423.6412902140773,
   1423.6483233923736,
   1423.6553565706702,
   1423.6623897489665,
   1423.6694229272628,
   1423.6764561055593,
   1423.6834892838556,
   1423.6905224621519,
   1423.6975556404484,
   1423.7045888187447,
   1423.711621997041,
   1423.7186551753375,
   1423.7256883536338,
   1423.73272153193,
   1423.7397547102266,
   1423.746787888523,
   1423.7538210668192,
   1423.7608542451155,
   1423.767887423412,
   1423.7749206017083,
   1423.7819537800046,
   1423.7889869583012,
   1423.7960201365975,
   1423.8030533148938,
   1423.8100864931903,
   1423.8171196714866,
   1423.8241528497829,
   1423.8311860280794,
   1423.8382192063757,
   1423.845252384672,
   1423.8522855629685,
   1423.8593187412648,
   1423.866351919561,
   1423.8733850978576,
   1423.880418276154,
   1423.8874514544502,
   1423.8944846327465,
   1423.901517811043,
   1423.9085509893393,
   1423.9155841676356,
   1423.9226173459322,
   1423.9296505242285,
   1423.9366837025248,
   1423.9437168808213,
   1423.9507500591176,
   1423.9577832374139,
   1423.9648164157104,
   1423.9718495940067,
   1423.978882772303,
   1423.9859159505995,
   1423.9929491288958,
   1423.999982307192,
   1424.0070154854884,
   1424.014048663785,
   1424.0210818420812,
   1424.0281150203775,
   1424.035148198674,
   1424.0421813769703,
   1424.0492145552666,
   1424.0562477335632,
   1424.0632809118595,
   1424.0703140901558,
   1424.0773472684523,
   1424.0843804467486,
   1424.0914136250449,
   1424.0984468033414,
   1424.1054799816377,
   1424.112513159934,
   1424.1195463382305,
   1424.1265795165268,
   1424.1336126948231,
   1424.1406458731194,
   1424.147679051416,
   1424.1547122297122,
   1424.1617454080085,
   1424.168778586305,
   1424.1758117646013,
   1424.1828449428976,
   1424.1898781211942,
   1424.1969112994905,
   1424.2039444777868,
   1424.2109776560833,
   1424.2180108343796,
   1424.2250440126759,
   1424.2320771909724,
   1424.2391103692687,
   1424.246143547565,
   1424.2531767258615,
   1424.2602099041578,
   1424.2672430824541,
   1424.2742762607504,
   1424.281309439047,
   1424.2883426173432,
   1424.2953757956395,
   1424.302408973936,
   1424.3094421522324,
   1424.3164753305286,
   1424.3235085088252,
   1424.3305416871215,
   1424.3375748654178,
   1424.3446080437143,
   1424.3516412220106,
   1424.3586744003069,
   1424.3657075786034,
   1424.3727407568997,
   1424.379773935196,
   1424.3868071134923,
   1424.3938402917888,
   1424.4008734700851,
   1424.4079066483814,
   1424.414939826678,
   1424.4219730049742,
   1424.4290061832705,
   1424.436039361567,
   1424.4430725398634,
   1424.4501057181596,
   1424.4571388964562,
   1424.4641720747525,
   1424.4712052530488,
   1424.4782384313453,
   1424.4852716096416,
   1424.4923047879379,
   1424.4993379662344,
   1424.5063711445307,
   1424.513404322827,
   1424.5204375011233,
   1424.5274706794198,
   1424.5345038577161,
   1424.5415370360124,
   1424.548570214309,
   1424.5556033926052,
   1424.5626365709015,
   1424.569669749198,
   1424.5767029274944,
   1424.5837361057906,
   1424.5907692840872,
   1424.5978024623835,
   1424.6048356406798,
   1424.6118688189763,
   1424.6189019972726,
   1424.6259351755689,
   1424.6329683538652,
   1424.6400015321617,
   1424.647034710458,
   1424.6540678887543,
   1424.6611010670508,
   1424.6681342453471,
   1424.6751674236434,
   1424.68220060194,
   1424.6892337802362,
   1424.6962669585325,
   1424.703300136829,
   1424.7103333151254,
   1424.7173664934217,
   1424.7243996717182,
   1424.7314328500145,
   1424.7384660283108,
   1424.7454992066073,
   1424.7525323849036,
   1424.7595655631999,
   1424.7665987414962,
   1424.7736319197927,
   1424.780665098089,
   1424.7876982763853,
   1424.7947314546818,
   1424.8017646329781,
   1424.8087978112744,
   1424.815830989571,
   1424.8228641678672,
   1424.8298973461635,
   1424.83693052446]},
 'predicted_points': {'x': ['2024-04-09 08:30:00', '2024-04-09 08:30:00'],
  'y': [1417.734, 1431.982]}}

In [37]:
[x.strftime('%Y-%m-%d %H:%M:%S') for x in output['predicted_points']['x']]

['2024-04-09 08:29:00', '2024-04-09 08:29:00']