In [1]:
from okx_plug import InitOkxAdaptor
from upbit_plug import InitUpbitAdaptor
from binance_plug import InitBinanceAdaptor
from bithumb_plug import InitBithumbAdaptor
from bybit_plug import InitBybitAdaptor
import pandas as pd
import json
import time
import datetime
from threading import Thread
import numpy as np

import sys,os
sys.path.append("/home/info_core")
from etc.db_handler.mongodb_client import InitDBClient

In [2]:
info_dict = {}
info_thread_dict = {}

okx_adaptor = InitOkxAdaptor("fcb66a6e-0443-4743-8d9b-61caf7eab662", "0029E09874B38F5AC7E68E9DFC348667", "121431Rn!!")
upbit_adaptor = InitUpbitAdaptor("x2AKLfsRtAgRxFjQ7p9TZTAg6E1SveoqfNfD8MK8", "svEran52QdsUyJdxAPYoTgFT2MXsHc5ZiKsKPxTL", info_dict, None)
binance_adaptor = InitBinanceAdaptor("4PFfYsObYyUaMlk7m6tT9qIl8X8P3WCUsyu1lEyZ4h50VfTMPIQCNdL9eOJCl3Lb", "011Z1W9p4425AZgtCNbs5L1d77ehZFNmBIwT0pz1SJGP7EiOlPILfWBglbVsxMcK", info_dict, None)
bithumb_adaptor = InitBithumbAdaptor()
bybit_adaptor = InitBybitAdaptor("S3YKBbD0kz1WwcfqZD", "390M6dKJ9J0uEK7vXYAl3qxVCh944tRrzHah")

# UPBIT SPOT (KRW, BTC Market)
# UPBIT wallet status
# BINANCE SPOT, USD-M Futures, COIN-M Futures
data_name_list = [
        "upbit_spot_info_df",
        "upbit_spot_ticker_df",
        # "upbit_wallet_status_df",
        "binance_spot_ticker_df",
        "binance_spot_info_df",
        "binance_usd_m_ticker_df",
        "binance_usd_m_info_df",
        "binance_coin_m_ticker_df",
        "binance_coin_m_info_df",
        "okx_spot_ticker_df",
        "okx_spot_info_df",
        "okx_usd_m_ticker_df",
        "okx_usd_m_info_df",
        "okx_coin_m_ticker_df",
        "okx_coin_m_info_df",
        "bithumb_spot_info_df",
        "bithumb_spot_ticker_df",
        # "bithumb_wallet_status_df",
        "bybit_spot_info_df",
        "bybit_spot_ticker_df",
        "bybit_usd_m_info_df",
        "bybit_usd_m_ticker_df",
        "bybit_coin_m_info_df",
        "bybit_coin_m_ticker_df"
    ]

def update_exchange_info_as_df(data_name, loop_time_secs=15):
    if data_name == "upbit_spot_ticker_df":
        info_dict[data_name] = upbit_adaptor.spot_all_tickers()
    elif data_name == "upbit_wallet_status_df":
        info_dict[data_name] = upbit_adaptor.wallet_status()
    elif data_name == "upbit_spot_info_df":
        info_dict[data_name] = upbit_adaptor.spot_exchange_info()
    elif data_name == "binance_spot_ticker_df":
        info_dict[data_name] = binance_adaptor.spot_all_tickers()
    elif data_name == "binance_spot_info_df":
        info_dict[data_name] = binance_adaptor.spot_exchange_info()
    elif data_name == "binance_usd_m_ticker_df":
        info_dict[data_name] = binance_adaptor.usd_m_all_tickers()
    elif data_name == "binance_usd_m_info_df":
        info_dict[data_name] = binance_adaptor.usd_m_exchange_info()
    elif data_name == "binance_coin_m_ticker_df":
        info_dict[data_name] = binance_adaptor.coin_m_all_tickers()
    elif data_name == "binance_coin_m_info_df":
        info_dict[data_name] = binance_adaptor.coin_m_exchange_info()
    elif data_name == "okx_spot_ticker_df":
        info_dict[data_name] = okx_adaptor.spot_all_tickers()
    elif data_name == "okx_spot_info_df":
        info_dict[data_name] = okx_adaptor.spot_exchange_info()
    elif data_name == "okx_usd_m_ticker_df":
        info_dict[data_name] = okx_adaptor.usd_m_all_tickers()
    elif data_name == "okx_usd_m_info_df":
        info_dict[data_name] = okx_adaptor.usd_m_exchange_info()
    elif data_name == "okx_coin_m_ticker_df":
        info_dict[data_name] = okx_adaptor.coin_m_all_tickers()
    elif data_name == "okx_coin_m_info_df":
        info_dict[data_name] = okx_adaptor.coin_m_exchange_info()
    elif data_name == "bithumb_spot_info_df":
        info_dict[data_name] = bithumb_adaptor.spot_exchange_info()
    elif data_name == "bithumb_spot_ticker_df":
        info_dict[data_name] = bithumb_adaptor.spot_all_tickers()
    elif data_name == "bithumb_wallet_status_df":
        info_dict[data_name] = bithumb_adaptor.wallet_status()
    elif data_name == "bybit_spot_info_df":
        info_dict[data_name] = bybit_adaptor.spot_exchange_info()
    elif data_name == "bybit_spot_ticker_df":
        info_dict[data_name] = bybit_adaptor.spot_all_tickers()
    elif data_name == "bybit_usd_m_info_df":
        info_dict[data_name] = bybit_adaptor.usd_m_exchange_info()
    elif data_name == "bybit_usd_m_ticker_df":
        info_dict[data_name] = bybit_adaptor.usd_m_all_tickers()
    elif data_name == "bybit_coin_m_info_df":
        info_dict[data_name] = bybit_adaptor.coin_m_exchange_info()
    elif data_name == "bybit_coin_m_ticker_df":
        info_dict[data_name] = bybit_adaptor.coin_m_all_tickers()
    else:
        print(f"update_exchange_info_as_df|name:{data_name} is not valid.")

for data_name in data_name_list:
    info_thread_dict[f"update_{data_name}"] = Thread(target=update_exchange_info_as_df, args=(data_name,), daemon=True)
    info_thread_dict[f"update_{data_name}"].start()
    print(f"InitCore|update_{data_name} thread has started.")

2023-12-11 10:05:04,108 - okx_plug - INFO - okx_plug_logger started.
2023-12-11 10:05:04,555 - upbit_plug - INFO - upbit_plug_logger started.
2023-12-11 10:05:04,829 - binance_plug - INFO - binance_plug_logger started.
2023-12-11 10:05:04,830 - bithumb_plug - INFO - bithumb_plug_logger started.
2023-12-11 10:05:04,831 - bybit_plug - INFO - bybit_plug_logger started.

InitCore|update_upbit_spot_info_df thread has started.
InitCore|update_upbit_spot_ticker_df thread has started.
InitCore|update_binance_spot_ticker_df thread has started.
InitCore|update_binance_spot_info_df thread has started.
InitCore|update_binance_usd_m_ticker_df thread has started.
InitCore|update_binance_usd_m_info_df thread has started.
InitCore|update_binance_coin_m_ticker_df thread has started.
InitCore|update_binance_coin_m_info_df thread has started.
InitCore|update_okx_spot_ticker_df thread has started.
InitCore|update_okx_spot_info_df thread has started.
InitCore|update_okx_usd_m_ticker_df thread has started.
InitCore|update_okx_usd_m_info_df thread has started.
InitCore|update_okx_coin_m_ticker_df thread has started.
InitCore|update_okx_coin_m_info_df thread has started.
InitCore|update_bithumb_spot_info_df thread has started.
InitCore|update_bithumb_spot_ticker_df thread has started.
InitCore|update_bybit_spot_info_df thread has started.
InitCore|update_bybit_spot_ticker_df thread has started.
InitCore|update_bybit_usd_m_info_df thread has started.
InitCore|update_bybit_usd_m_ticker_df thread has started.
InitCore|update_bybit_coin_m_info_df thread has started.
InitCore|update_bybit_coin_m_ticker_df thread has started.

2023-12-11 10:05:05,663 - bybit_plug - INFO - self.info_dict is None or self.info_dict.get('bybit_coin_m_info_df') is None, Fetched from API
2023-12-11 10:05:06,455 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_usd_m_info_df') is None, Fetched from API
2023-12-11 10:05:06,980 - bybit_plug - INFO - self.info_dict is None or self.info_dict.get('bybit_spot_info_df') is None, Fetched from API
2023-12-11 10:05:07,218 - bybit_plug - INFO - self.info_dict is None or self.info_dict.get('bybit_usd_m_info_df') is None, Fetched from API
2023-12-11 10:05:07,599 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_ticker_df') is None, Fetched from API

In [9]:
exchange_name = "bybit"
exchange_adaptor = bybit_adaptor
db_client = InitDBClient(host="221.148.128.212", port=27017, user="acw", passwd="o,hOL6M11zg,")
mongo_conn = db_client.get_conn()

exchange_name = exchange_name.upper()
# self.logger.info(f"update_wallet_status|{exchange_name} update_wallet_status thread has started.") # TEST
error_count = 0
# while True:
#     try:
# Check whether the market is in maintenance or not
# server_check = False
# registered_server_check_list = [x.decode('utf-8') for x in self.redis_client_db0.redis_conn.keys() if 'INFO_CORE|SERVER_CHECK' in x.decode('utf-8')]
# for each_market_server_check in registered_server_check_list:
#     market_name = each_market_server_check.replace('INFO_CORE|SERVER_CHECK|', '')
#     if 'SPOT' in market_name and exchange_name in market_name:
#         server_check_dict = self.redis_client_db0.get_dict(each_market_server_check)
#         server_check_start_timestamp_utc = server_check_dict['start']
#         server_check_end_timestamp_utc = server_check_dict['end']
#         now_timestamp_utc = datetime.datetime.utcnow().timestamp()
#         if server_check_start_timestamp_utc <= now_timestamp_utc <= server_check_end_timestamp_utc:
#             server_check = True
#             break
# if server_check is True:
#     # TEST
#     self.logger.info(f"update_wallet_status|name:{exchange_name} has been skipped due to server check.")
#     time.sleep(loop_time_secs)
#     continue

read_time = 0
write_time = 0
calculate_time = 0
api_time = 0

start = time.time()
# mongo_db_conn = self.mongo_conn # TEST
mongo_db_conn = mongo_conn
# First fetch from the mongodb
# fetch from mongodb
read_time_start = time.time()
mongo_db = mongo_db_conn["wallet_status"]
collection = mongo_db[f"{exchange_name}"]
# get all the data
data = collection.find({})
# convert to dataframe
df = pd.DataFrame(data)
read_time += time.time() - read_time_start
api_start = time.time()
wallet_status_df = exchange_adaptor.wallet_status().drop_duplicates()
api_time += time.time() - api_start
wallet_status_df['datetime_now'] = datetime.datetime.utcnow()
if len(df) == 0:
    # Store
    wallet_status_dict = wallet_status_df.to_dict('records')
    collection.insert_many(wallet_status_dict)
    # self.logger.info(f"Collection empty. Inserting {exchange_name}'s wallet_status to mongodb") # TEST
    print(f"Collection empty. Inserting {exchange_name}'s wallet_status to mongodb") # TEST
else:
    for row_tup in wallet_status_df.iterrows():
        row = row_tup[1]
        # if the asset with the network_type already exist in the db, update it otherwise insert it.
        write_time_start = time.time()
        if len(df[(df['asset']==row['asset'])&(df['network_type']==row['network_type'])]) == 1:
            collection.update_one({'asset':row['asset'], 'network_type':row['network_type']}, {'$set':{k: row[k] for k in row.keys() if k not in ['asset','network_type']}})
        else:
            collection.insert_one(row.to_dict())
        write_time += time.time() - write_time_start
# mongo_db_conn.close()
error_count = 0
# self.logger.info(f"update_wallet_status|{exchange_name} update_wallet_status took {time.time()-start} secs, read_time: {read_time}, write_time: {write_time}, calculate_time: {calculate_time}, api_time: {api_time}") # TEST
print(f"update_wallet_status|{exchange_name} update_wallet_status took {time.time()-start} secs, read_time: {read_time}, write_time: {write_time}, calculate_time: {calculate_time}, api_time: {api_time}") # TEST
    # except Exception as e:
    #     error_count += 1
    #     if error_count >= 10:
    #         content = f"update_wallet_status|Exception occured in {exchange_name}'s update_wallet_status! Error: {e}, {traceback.format_exc()}"
    #         # self.logger.error(content) # TEST
    #         # self.register_monitor_msg.register(self.admin_id, self.node, 'error', f"Error occured in {exchange_name} update_wallet_status.", content=content, code=None, sent_switch=0, send_counts=1, remark=None) # TEST
    #         print(content) # TEST
    # time.sleep(loop_time_secs)

update_wallet_status|BYBIT update_wallet_status took 0.745166540145874 secs, read_time: 0.020118236541748047, write_time: 0.44819164276123047, calculate_time: 0, api_time: 0.2478468418121338

In [10]:
temp = mongo_conn['wallet_status']['BYBIT'].find({})

In [11]:
fetched_bybit_wallet_status_df = pd.DataFrame(temp)
fetched_bybit_wallet_status_df

,_id,asset,remainAmount,chainType,confirmation,withdrawFee,depositMin,withdrawMin,network_type,deposit,withdraw,minAccuracy,withdrawPercentageFee,datetime_now
0,6576df03d466081f5217330e,AGLD,256400,ERC20,6,3,0,3,ETH,True,True,8,0,2023-12-11 10:06:00.780
1,6576df03d466081f5217330f,AGLA,12500000,ERC20,6,50,0,50,ETH,True,True,8,0,2023-12-11 10:06:00.780
2,6576df03d466081f52173310,AGLA,12500000,SOL,200,10,0,10,SOL,True,False,8,0,2023-12-11 10:06:00.780
3,6576df03d466081f52173311,DFI,200000,ERC20,6,12,0,12,ETH,True,True,8,0,2023-12-11 10:06:00.780
4,6576df03d466081f52173312,DFL,16000000,SOL,200,80,0,80,SOL,False,False,8,0,2023-12-11 10:06:00.780
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
483,6576df03d466081f521734f1,BAR,100000,Chiliz Legacy Chain,12,0,0,1,CHZ,True,True,0,0,2023-12-11 10:06:00.780
484,6576df03d466081f521734f2,BAT,2061000,ERC20,6,15,0,15,ETH,True,True,8,0,2023-12-11 10:06:00.780
485,6576df03d466081f521734f3,TEL,103000000,ERC20,6,2404,0,4808,ETH,True,True,2,0,2023-12-11 10:06:00.780
486,6576df03d466081f521734f4,MOVR,10000,MOVR,30,0.003,0,0.003,MOVR,True,True,8,0,2023-12-11 10:06:00.780
487,6576df03d466081f521734f5,5IRE,50000000,ERC20,6,10,0,10,ETH,True,True,8,0,2023-12-11 10:06:00.780

In [29]:
bybit_wallet_status_df = exchange_adaptor.wallet_status()
bybit_wallet_status_df.drop_duplicates()

,asset,remainAmount,chainType,confirmation,withdrawFee,depositMin,withdrawMin,network_type,deposit,withdraw,minAccuracy,withdrawPercentageFee
0,AGLD,256400,ERC20,6,3,0,3,ETH,True,True,8,0
1,AGLA,12500000,ERC20,6,50,0,50,ETH,True,True,8,0
2,AGLA,12500000,SOL,200,10,0,10,SOL,True,False,8,0
5,DFI,200000,ERC20,6,12,0,12,ETH,True,True,8,0
6,DFL,16000000,SOL,200,80,0,80,SOL,False,False,8,0
...,...,...,...,...,...,...,...,...,...,...,...,...
981,BAR,100000,Chiliz Legacy Chain,12,0,0,1,CHZ,True,True,0,0
982,BAT,2061000,ERC20,6,15,0,15,ETH,True,True,8,0
983,TEL,103000000,ERC20,6,2404,0,4808,ETH,True,True,2,0
984,MOVR,10000,MOVR,30,0.003,0,0.003,MOVR,True,True,8,0
985,5IRE,50000000,ERC20,6,10,0,10,ETH,True,True,8,0

In [28]:
bybit_wallet_status_df[(bybit_wallet_status_df['asset']=='AGLD')&(bybit_wallet_status_df['chainType']=='ERC20')]

,asset,remainAmount,chainType,confirmation,withdrawFee,depositMin,withdrawMin,network_type,deposit,withdraw,minAccuracy,withdrawPercentageFee
0,AGLD,256400,ERC20,6,3,0,3,ETH,True,True,8,0